### ISSUE TITLE
Prepares_statements can not be automatically created with an already existed name?

### ISSUE THREAD

**Issue by RuiWang-vmw** [pgbouncer/pgbouncer#1008]
I have looked into the doc of max_prepared_statements, but I have some questions on the new feature. 
 If the first client sends the prepared statement to the server, will all the other clients on the server automatically create the prepared_statements with the existed name like "PGBOUNCER_123" when the clients receive the execute requests related to the prepared statements? 

**experiment**
I have written a script about this question

```
import psycopg

conn1=psycopg.connect("port= 6432 dbname=postgres user=gpadmin")
conn2=psycopg.connect("port= 6432 dbname=postgres user=gpadmin")

cur1=conn1.cursor()
cur2=conn2.cursor()

cur1.execute("deallocate all")
cur2.execute("deallocate all")

#create prepared statements on cur1
prepared_query="select %s"
cur1.execute(prepared_query, params = (1,), prepare = True)
cur1.execute(prepared_query, params = (1,))

#execute directly on cursor2 with the prepared statement
cur2.execute(prepared_query, params = (2,))

#print the prepared statements that cursor1 and cursor2 have
print("cursor1 created prepared statements, cursor2 executed without creating prepared statements, but executed it")
cur1.execute("select * from pg_prepared_statements;")
result=cur1.fetchall()
print("cur1 prepared statement is ", result)
cur2.execute("select * from pg_prepared_statements;")
result=cur2.fetchall()
print("cur2 prepared statement is ", result)

#now create the prepared statement on cursor2
cur2.execute(prepared_query, params = (2,), prepare = True)

print("cursor2 created the prepared statement now")
cur1.execute("select * from pg_prepared_statements;")
result=cur1.fetchall()
print("cur1 prepared statement is ", result)
cur2.execute("select * from pg_prepared_statements;")
result=cur2.fetchall()
print("cur2 prepared statement is ", result)

print("deallocate all on the cursor1")
cur1.execute("deallocate all")

cur1.execute("select * from pg_prepared_statements;")
result=cur1.fetchall()
print("cur1 prepared statement is ", result)
cur2.execute("select * from pg_prepared_statements;")
result=cur2.fetchall()
print("cur2 prepared statement is ", result)

conn1.commit()
conn2.commit()
```

the result is 
```
cursor1 created prepared statements, cursor2 executed without creating prepared statements, but executed it
cur1 prepared statement is  [('PGBOUNCER_30', 'select $1', datetime.datetime(2024, 1, 14, 10, 25, 50, 323305, tzinfo=backports.zoneinfo.ZoneInfo(key='Asia/Shanghai')), ['smallint'], ['smallint'], False, 0, 2)]
cur2 prepared statement is  []
cursor2 created the prepared statement now
cur1 prepared statement is  [('PGBOUNCER_30', 'select $1', datetime.datetime(2024, 1, 14, 10, 25, 50, 323305, tzinfo=backports.zoneinfo.ZoneInfo(key='Asia/Shanghai')), ['smallint'], ['smallint'], False, 0, 2)]
cur2 prepared statement is  [('PGBOUNCER_30', 'select $1', datetime.datetime(2024, 1, 14, 10, 25, 50, 326126, tzinfo=backports.zoneinfo.ZoneInfo(key='Asia/Shanghai')), ['smallint'], ['smallint'], False, 0, 1)]
deallocate all on the cursor1
cur1 prepared statement is  []
cur2 prepared statement is  [('PGBOUNCER_30', 'select $1', datetime.datetime(2024, 1, 14, 10, 25, 50, 326126, tzinfo=backports.zoneinfo.ZoneInfo(key='Asia/Shanghai')), ['smallint'], ['smallint'], False, 0, 1)]
```

**expectation**
1. I read the documentation and I thought the expectation should be for the first time, cursor2 calling `cur2.execute(prepared_query, params = (2,))`, should be the first time that cursor2 creating prepared_statement with the name PGBOUNCER_XX automatically,.
2. When the prepared statements on the both two clients are created, and I run deallocate all on the first client, the second prepared statements with the same name should be deallocated, too?

**behavior that I experimented**
1. The behavior is that the `cur2.execute(prepared_query, params = (2,))` does not throw an error but no PGBOUNCER_XX is created. I debugged in the PostgreSQL Code, I find each time when the cursor2 runs `execute(prepared_query, params=(2,))`, the `CreateCachedPlan` is called, with an unnamed prepared statements, unless the cursor2 calls `cur2.execute(prepared_query, params = (2,), prepare = True)`, that means, when the cursor2 didn't create the prepared_statement and runs the execute(prepared_query, params=(2,)), the memory will be palloced on the cache to build the prepared cache plan again and again and again. 
2. When I deallocate all on the first client, the second still has the prepared statements left.

**questions**
1. Does the expectation make sense?  Is it a bug, or I misunderstood the feature?

the pgbouncer.ini is
```
[databases]
postgres = host=127.0.0.1 port=5010 dbname=postgres

[pgbouncer]
listen_addr = 127.0.0.1
auth_type = trust
auth_file = auth_file.conf
logfile = pgbouncer1.log
pidfile = pgbouncer1.pid
so_reuseport = 1
server_round_robin = 1
max_prepared_statements=20
admin_users=gpadmin
pool_mode=transaction
```

**Comment by RuiWang-vmw** [comment]
OK, I got it, thanks for your answer to my questions. At least I know my test results meet the expectation. But how to understand the " It rewrites each command that uses a prepared statement to use the matching internal name (e.g. PGBOUNCER_123) before forwarding that command to the server. More importantly, if the prepared statement that the client wants to use is not prepared on the server yet, it automatically prepares that statement before forwarding the command that the client sent." in the documentation. 
This really confuses me. And I think this statement means that if the cursor1 creates the prepared statements with the name PGBOUNCER_30, and cursor2 will create the same prepared statements automatically, when cursor2 has the requirements to utilize that?

**Comment by JelteF** [comment]
This part of the docs is meant to suggest that internal statement names are shared if the query string is the same:

> PgBouncer internally examines all the queries that are sent as a prepared statement by clients and gives each unique query string an internal name with the format PGBOUNCER_{unique_id}. 

I can understand the docs on this are not entirely clear though. Suggestions for improvements are always very welcome. Does this make it clearer:

> PgBouncer internally examines all the queries that are sent as a prepared statement by clients and gives each unique query string an internal name with the format PGBOUNCER_{unique_id}. Prepared statements are only prepared using this name on the corresponding PostgreSQL server. PgBouncer keeps track of the name that the client gave to each prepared statement **in a hashmap**. **And using that hashmap** it then replaces the prepared statement name the client uses with the internal prepared statement name (e.g. PGBOUNCER_123), before forwarding a prepared statement command from the client to the server. More importantly, if the prepared statement that the client wants to use is not prepared on the assigned server yet, it automatically prepares that statement using the internal name before forwarding the command that the client sent.

**Comment by RuiWang-vmw** [comment]
> Question: Is this with pgbouncer code from the master branch? Because DEALLOCATE ALL support is not released yet, it's only available on master.
Not from the main branch, from pgbouncer 1.21.0


> PgBouncer internally examines all the queries that are sent as a prepared statement by clients and gives each unique query string an internal name with the format PGBOUNCER_{unique_id}. Prepared statements are only prepared using this name on the corresponding PostgreSQL server. PgBouncer keeps track of the name that the client gave to each prepared statement in a hashmap. And using that hashmap it then replaces the prepared statement name the client uses with the internal prepared statement name (e.g. PGBOUNCER_123), before forwarding a prepared statement command from the client to the server. More importantly, if the prepared statement that the client wants to use is not prepared on the assigned server yet, it automatically prepares that statement using the internal name before forwarding the command that the client sent.

Maybe I misunderstood the "automatically prepares the statement" before. I thought it was to create the prepared statements on the server, but it actually just prepares on the client side. So, I think both the original and the above docs are OK. As long as one can understand the "prepare the statement" clearly
