### ISSUE TITLE
Release for 1.22.0 does not contain pgbouncer-1.22.0.tar.gz

### ISSUE THREAD

**Issue by tanelso2** [pgbouncer/pgbouncer#1027]
I have a script that builds pgbouncer by pulling down the tarball from the release.

With the most recent release of pgbouncer, the release does not have the same files as previous releases and breaks my script.

Is this intended? Should I be using the unnamed tarball included in the release instead?

**Comment by JelteF** [comment]
I guess you meant the Github release page? Sorry about that, attached the binaries now. The official place for the sources downloads is here btw (it contains the sha hashes): https://www.pgbouncer.org/downloads/

**Comment by tanelso2** [comment]
I did mean the Github release page. Thank you, and I'll look into grabbing the source from the official spot
