### ISSUE TITLE
Difficult to diagnose TLS error

### ISSUE THREAD

**Issue by squaretrade-jal** [pgbouncer/pgbouncer#1033]
We are having a TLS issue in our production pgbouncer cluster and are having difficulty troubleshooting it. 

 We have a two-node active/backup 1.21 setup running on Ubuntu 20.04. It serves hundreds of clients for access to less than 100 DBs across multiple Postgres servers, and generally sees 900-1000 connections/minute. Occasionally, we are seeing an error, below. When this occurs, pgbouncer drops all client connections, which is disruptive. 

 2024-02-25 05:33:59.017 PST [27014] WARNING TLS handshake error: handshake failed: Success 

Because the warning doesn't indicate which connection caused it, we can't tell which client is involved. Turning debug logging up to 2 overwhelmed the machine. We built an experimental replacement configured with a RAM disk, but debug logging consumes almost 1G/minute, so we can't run it continuously and are trying to guess when it might occur in hopes of capturing more detail. I'm not even sure that will provide anything useful; most of what it seems to log is timing. This machine is running libgnutls 3.8.3 - I built the latest release of the library in case there was a bug fix. 

So far we have been unable to reproduce the issue in a less critical/lower volume environment.  A big part of the problem for us is that this only manifests in production; we can't stop the world and investigate, can't be invasive if it risks disruptions, and have to respect the usual controls for prod changes. 

 If we could identify the client, we could figure this out, but from the docs cannot see configuration options that might supply hints. 

Has anyone seen this? Can anyone think of a way to gather more info on what's going on?

**Comment by JelteF** [comment]
I'd expect such a failure to also show up on the client side, i.e. if the handshake of a client fails then the client would throw an error.

I do agree that not showing the server/client involved in the failure in the log is quite annoying.  A PR to fix that is definitely welcome.

**Comment by JelteF** [comment]
Closing this because the issue is stale
