### ISSUE TITLE
Improvements to tls setup documentation would be nice

### ISSUE THREAD

**Issue by dr-kd** [pgbouncer/pgbouncer#1035]
Yesterday I was spending some time on configuring a new pgbouncer to use an existing certificate to provide an environment configured for `client_tls_sslmode=require`.  It took me a lot of digging around to try to discover the correct certificate formats, finally discovering that our existing .pem files were perfectly ok for the certificate and key.  It would be good if the valid types of formats were documented in pgbouncer.  I would provide a patch, but I do not know the completely accurate answer.

**Comment by JelteF** [comment]
Honestly I don't know the completely accurate answer too. I do think it makes sense to at least mention that pem files work, since that is probably what most people have anyway. Could you provide a patch explaining that?

**Comment by dr-kd** [comment]
I think a very short patch would be adequate:

```
diff --git a/doc/config.md b/doc/config.md
index c7f8ff3..20012fb 100644
--- a/doc/config.md
+++ b/doc/config.md
@@ -757,6 +757,7 @@ TLS mode to use for connections from clients.  TLS connections
 are disabled by default.  When enabled, `client_tls_key_file`
 and `client_tls_cert_file` must be also configured to set up
 the key and certificate PgBouncer uses to accept client connections.
+The most common certificate file format usable by PgBouner is pem.
 
 disable
 :   Plain TCP.  If client requests TLS, it's ignored.  Default.
```

The other thing that would be neat, is that if pgbouncer accepted concatenated pem files with certificate and key in the same file then certificates would be interchangeable with haproxy - excepting any file permission issues that is, but that would be a separate issue, and perhaps not quite worth it.

**Comment by JelteF** [comment]
> I think a very short patch would be adequate:
> 
> ```
> diff --git a/doc/config.md b/doc/config.md
> index c7f8ff3..20012fb 100644
> --- a/doc/config.md
> +++ b/doc/config.md
> @@ -757,6 +757,7 @@ TLS mode to use for connections from clients.  TLS connections
>  are disabled by default.  When enabled, `client_tls_key_file`
>  and `client_tls_cert_file` must be also configured to set up
>  the key and certificate PgBouncer uses to accept client connections.
> +The most common certificate file format usable by PgBouner is pem.
>  
>  disable
>  :   Plain TCP.  If client requests TLS, it's ignored.  Default.
> ```

Looks good, if you make it a PR I'll merge it.

> The other thing that would be neat, is that if pgbouncer accepted concatenated pem files with certificate and key in the same file then certificates would be interchangeable with haproxy - excepting any file permission issues that is, but that would be a separate issue, and perhaps not quite worth it.

Interesting, I've never heard of that being a thing before. To me key and cert files have always been different files.

**Comment by dr-kd** [comment]
done, thanks!
