### ISSUE TITLE
Issue with interaction between CloudSQL Proxy (GCP) and PgBouncer

### ISSUE THREAD

**Issue by adriangb** [pgbouncer/pgbouncer#1053]
I tried using [CloudSQL Proxy](https://github.com/GoogleCloudPlatform/cloud-sql-proxy) in conjunction with PgBouncer w/ transaction pooling and am running into some strange performance issues that I can't explain.

I tested:
1. CloudSQL Proxy directly -> fine
2. PgBouncer connected to a different Postgres database -> fine
3. PgBouncer connected to CloudSQL Proxy -> bad

So each seems to work fine in isolation but not when combined.
I'm not sure if I'm doing something wrong or if it's a bug in one of the two but I put together an MRE and am filing this as a bug report in hopes of getting some clarity. Sorry if this is a mistake on my end.

The MRE is here: https://github.com/adriangb/pgbouncer-cloudsqlproxy-bug

**Comment by enocom** [comment]
FYI https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/2201.

I think this is a configuration issue and not a bug.

**Comment by eulerto** [comment]
Unless you can show that the extra time is spent on PgBouncer side, there is no bug here. I advise you to check hardware resources too.
