### ISSUE TITLE
auth_query example in SQL instead of plpgsql

### ISSUE THREAD

**Issue by anayrat** [pgbouncer/pgbouncer#1055]
Hello,

I wonder why the example of auth_query is in plpgsql instead of simple SQL?

```
CREATE OR REPLACE FUNCTION pgbouncer.user_lookup(in i_username text, out uname text, out phash text)
RETURNS record AS $$
BEGIN
    SELECT usename, passwd FROM pg_catalog.pg_shadow
    WHERE usename = i_username INTO uname, phash;
    RETURN;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
```

vs

```
CREATE OR REPLACE FUNCTION pgbouncer.user_lookup(in i_username text, out uname text, out phash text)
AS $$

    SELECT usename, passwd FROM pg_catalog.pg_shadow
    WHERE usename = i_username;

$$ LANGUAGE SQL SECURITY DEFINER;
```

SQL function should be cheaper ?

I can provide a PR to change that.

Regards,

**Comment by JelteF** [comment]
Yeah, sounds totally reasonable. If you provide a PR I'll merge it.

**Comment by anayrat** [comment]
Oh, I tested both solutions, and plpgsql is faster! I perform a simple test thanks to pgbench with  `--connect`:

* SQL function : 9000tps
* plpgsql : 12600

I suppose, with plpgsql function, the plan is cached :) 
So, we should keep plpgsql

**Comment by JelteF** [comment]
Alright, that's quite surprising but sounds fine to me. Closing this issue then.
