### ISSUE TITLE
Request: Creating unique pools based upon the value of user-specified startup options (e.g. search_path)

### ISSUE THREAD

**Issue by polobo** [pgbouncer/pgbouncer#107]
With bash I define a function that wraps psql thusly:
`psql "service=$SERVICE options='-c search_path=$SCHEMAS'"`

Ignoring the search_path parameter doesn't help since I indeed want its value to take effect.

What I think would work is for the configuration of a given database to specify something like:
`key_startup_parameters=search_path`
and for a new pool to be created that would be dedicated to each search_path value seen.  Additional settings could be added to control these specialized pools compared to the main settings which would apply when the startup parameter is not present (i.e., the default pool).

This negates any need for pgbouncer to parse SQL while avoiding the explosion of roles and/or explicit database configurations with default search_paths.  The former being verboten to the project and the latter likely being tedious to setup and maintain for the user.

The repeated use of the same search_path within a script is quite common and being able to leverage the session startup parameter facility that PostgreSQL provides allows for easy centralization of its specification at the point of command issuance instead of sprinkling `SET search_path` throughout ones scripts or creating dedicated roles onto which a default can be set.  It would be nice to be able to leverage that feature even if one chooses to use pgbouncer.

**Comment by markokr** [comment]
This looks like bad idea.

- The whole idea of "getopt" args in startup packet is ugly historical accident, not a practice to encourage.
- Allowing parallel pools will erode the control that pool_size has over db load.
- And such apps are clearly written without any consideration of pooling, so they are not pgbouncer target audience...

**Comment by polobo** [comment]
On Tuesday, February 2, 2016, Marko Kreen <notifications@github.com> wrote:

> This looks like bad idea.
>
>    - The whole idea of "getopt" args in startup packet is ugly historical
>    accident, not a practice to encourage.
>
>  It hasn't been deprecated and does provide a nice way to setup
localized defaults.

>
>    - Allowing parallel pools will erode the control that pool_size has
>    over db load.
>
> Fair enough but in the usage I'm dealing with pool size considerations
just don't matter.  In most cases a single connection is all that is
needed.  Just something that will persist between command line invocations
of psql.

>
>    - And such apps are clearly written without any consideration of
>    pooling, so they are not pgbouncer target audience...
>
> You can choose to not devote time to minority use cases but that in itself
doesn't make it a bad idea.

David J.

**Comment by markokr** [comment]
"deprecated" as in "not supported by any middleware".  If you care only about connecting directly to postgres, no problem.

And it's bad idea in the sense of "is it worth additional complexity in pgbouncer".  And "should there be more apps that use that feature".

It would be clearly useful for you and perhaps few other people, I'm not disagreeing with that,
but it does not belong to pgbouncer.
