### ISSUE TITLE
Unsuported startup parameter default_transaction_isolation

### ISSUE THREAD

**Issue by wszychta** [pgbouncer/pgbouncer#1074]
Hello,

I'm trying to use pgbouncer with tool called [teleport](https://goteleport.com). Unfortunatelly when I'm trying to access database via pgbounder I'm gettting this error: 
```
server error (FATAL: unsupported startup parameter: default_transaction_isolation (SQLSTATE 08P01))
```
When I did the same thing without pgbouncer, then I was able to access my database cluster.
We are using pgbouncer in version `1.22.1`, so this is not a problem with a version.

Is this possible to add support for this startup parameter or make a workarund until it will be supported by pgbouncer?

**Comment by JelteF** [comment]
you can set it in `ignore_startup_parameters` to ignore this parameter, but if the tool requires the value to be correct you should set it some other way. e.g. by setting it by default for the user on the postgres server that this tool is connecting as.
