### ISSUE TITLE
Establishing more client connections than max_client_conn rejects all connections

### ISSUE THREAD

**Issue by Avinodh** [pgbouncer/pgbouncer#1086]
Pgbouncer Version: `v1.17`

`pgbouncer.ini` : 

```
[databases]
    storagegopg_1 = host=<rds-endpoint> port=5432 dbname=storagegopg pool_size=100 pool_mode=transaction

[pgbouncer]
listen_addr=0.0.0.0
pidfile=/home/pgbouncer/pid
ignore_startup_parameters=extra_float_digits
unix_socket_dir=/tmp
auth_type=md5
auth_file=/home/pgbouncer/userlist.ini
pool_mode=transaction
server_round_robin=1
server_check_query=select 1
dns_max_ttl=2
dns_nxdomain_ttl=2
default_pool_size=70
stats_users=stats
admin_users=admin
log_connections=1
log_disconnections=1
listen_port=5432
max_client_conn=400
min_pool_size=20
pkt_buf=4096
reserve_pool_size=10
reserve_pool_timeout=0
server_lifetime=300
server_reset_query=
tcp_keepalive=1
tcp_keepidle=30
tcp_keepintvl=10
tcp_keepcnt=3
tcp_user_timeout=60000
```

Specifically, `max_client_conn = 400` and we are using `transaction` pooling mode.

**Experiment 1:**
1. At the start of the experiment:
`SHOW POOLS;`
<img width="1507" alt="image" src="https://github.com/pgbouncer/pgbouncer/assets/5704154/c67e8822-ea52-40d6-ae6c-4a32204a7295">

`SHOW LISTS;`
<img width="299" alt="image" src="https://github.com/pgbouncer/pgbouncer/assets/5704154/0360fc4c-2fbd-4a1a-b989-e17ab254ccb5">

2. Running `pgbench` from a different host than the Pgbouncer host with `500` concurrent clients:
`script.sql`:
```
SELECT pg_sleep(1);
```

```
pgbench -U storagegopg_1 -c 500 -j 1 -T 30 -n -h <pgbouncer-endpoint> storagegopg_1 -f script.sql 
connection to database "storagegopg_1" failed:
FATAL:  no more connections allowed (max_client_conn)
transaction type: script.sql
scaling factor: 1
query mode: simple
number of clients: 500
number of threads: 1
duration: 30 s
number of transactions actually processed: 0
```

3. After `pgbench` is run:
`SHOW POOLS;`
<img width="1369" alt="image" src="https://github.com/pgbouncer/pgbouncer/assets/5704154/21129f5d-cfe3-434a-939e-8657730ba66e">

after `server_check_delay = 30s (default)`:
<img width="1395" alt="image" src="https://github.com/pgbouncer/pgbouncer/assets/5704154/985089cd-3b4e-4e4e-a348-6e29cd7c3bee">

`SHOW LISTS;`
<img width="299" alt="image" src="https://github.com/pgbouncer/pgbouncer/assets/5704154/043622ab-4ffb-4e8f-b916-95ce2a20516c">

4. Results:
We see that the `pgbench` command fails immediately because Pgbouncer rejects all connections. Moreover, we see that the connection pools are still effectively empty, ie, there only seem to be 1-2 allocated server connections. Looking at the Pgbouncer logs during this window, we see a large number of login attempts, followed by `pooler error: no more connections allowed (max_client_conn)` and then `closing because: client close request (age=0s)` :
```
. . .
login attempt: db=storagegopg_1 user=storagegopg_1 tls=no
. . .
pooler error: no more connections allowed (max_client_conn)
. . .
closing because: client close request (age=0s)
```
<img width="1426" alt="image" src="https://github.com/pgbouncer/pgbouncer/assets/5704154/6788d319-7000-4ec9-997a-0d7a24f3c6bc">

This seems concerning because when there is a large load spike, this behavior implies that Pgbouncer will reject most, if not all, client connections as opposed to accepting up to `max_client_conn` client connections. 

The check for accepting clients is done [here](https://github.com/pgbouncer/pgbouncer/blob/817c20a97e27bb3958a348f5bd9d39688a60e7c0/src/client.c#L886C1-L891C3):

```
if (get_active_client_count() > cf_max_client_conn) {
		if (strcmp(dbname, "pgbouncer") != 0) {
			disconnect_client(client, true, "no more connections allowed (max_client_conn)");
			return false;
		}
	}
```
[get_active_client_count()](https://github.com/pgbouncer/pgbouncer/blob/817c20a97e27bb3958a348f5bd9d39688a60e7c0/src/objects.c#L93):
```
/* fast way to get number of active clients */
int get_active_client_count(void)
{
	return slab_active_count(client_cache);
}
```
`slab_active_count` [maps](https://github.com/pgbouncer/pgbouncer/blob/817c20a97e27bb3958a348f5bd9d39688a60e7c0/src/admin.c#L573) to the `used_clients` list reported by `SHOW LISTS;` in the above experiment, which seemed to be ~`2` right after pgbench was run, but this could just be due to not being collected in real-time. 

Can you please help advise on whether this is "by design", or a race-condition due to scheduling with how the `client_cache` active objects are allocated/checked?

**Comment by Avinodh** [comment]
I am trying to repro this issue because a while ago, my service encountered a huge traffic spike, which resulted in Pgbouncer's `sv_active` and `sv_idle` dropping to 0, resulting in the same `no more connections allowed (max_client_conn)` and  `closing because: client close request (age=0s)` logs. This also resulted in a complete drop in Database Connections on the actual Postgres Database itself from the pgbouncer.

In this case, `max_client_conn = 4096`, which is much less than the number of clients connecting as shown below.

This was only mitigated when I added new Pgbouncer instances to the fleet.

`Total client connections = cl_active + cl_waiting`"
<img width="1602" alt="image" src="https://github.com/pgbouncer/pgbouncer/assets/5704154/5463932c-36dc-4960-84d3-f4c4ca8f203c">

`sv_active` and `sv_idle` metrics:
<img width="1710" alt="image" src="https://github.com/pgbouncer/pgbouncer/assets/5704154/bdb65dd7-54eb-4e31-bf97-ef39828b6f90">

My theory is that based on the above issue above:
1.  A huge number of continued client connections to the pgbouncer > `max_client_conn` resulted in all the clients being rejected by the pgbouncer based on the experiment above
2. The existing Pgbouncer `sv_active` connections drops to 0 (presumably due to older transactions completing) and so do the `sv_idle` transaction, likely due to them exceeding`server_lifetime = 3600s` and being closed
3. No new server connections are allocated in the Pgbouncer because all client connections are actively being rejected due to the issue noted above, which effectively prevents any new workloads from running

**Comment by Avinodh** [comment]
cc. @petere / @JelteF for advise on this

**Comment by JelteF** [comment]
How are you gathering these metrics? Is it through PgBouncer? i.e. maybe it's missing the metrics because it cannot connect anymore, instead of these metrics actually being 0.

**Comment by Avinodh** [comment]
@JelteF  - The metrics are exported by `pgbouncer-exporter` (https://github.com/prometheus-community/pgbouncer_exporter) which connects to the Pgbouncer admin database and gathers statistics from `SHOW POOLS;`, `SHOW LISTS;` etc.

**Comment by Avinodh** [comment]
@JelteF  - Since this is only connecting to the admin database, I don't think there should be issues here gathering metrics.

**Comment by eulerto** [comment]
pgbench fails if it cannot open all required connections. See

https://github.com/postgres/postgres/blob/master/src/bin/pgbench/pgbench.c#L7442-L7451

I expect that PgBouncer opens connections up to the `max_client_conn` limit (like in this example that I have `max_client_conn = 1`).

```
2024-06-27 10:15:17.394 -03 [132763] LOG C-0x55f4d686da10: euler/euler@unix(133320):6432 login attempt: db=euler user=euler tls=no
2024-06-27 10:15:17.397 -03 [132763] LOG C-0x55f4d686da10: euler/euler@unix(133320):6432 closing because: client close request (age=0s)
2024-06-27 10:15:17.397 -03 [132763] LOG C-0x55f4d686da10: euler/euler@unix(133320):6432 login attempt: db=euler user=euler tls=no
2024-06-27 10:15:17.397 -03 [132763] LOG C-0x55f4d686dcc0: (nodb)/(nouser)@unix(133320):6432 closing because: no more connections allowed (max_client_conn) (age=0s)
2024-06-27 10:15:17.397 -03 [132763] WARNING C-0x55f4d686dcc0: (nodb)/(nouser)@unix(133320):6432 pooler error: no more connections allowed (max_client_conn)
2024-06-27 10:15:17.398 -03 [132763] LOG C-0x55f4d686da10: euler/euler@unix(133320):6432 closing because: client unexpected eof (age=0s)
```

If your application terminates if it cannot connect to PgBouncer, you should (a) fix the PgBouncer configuration (`max_client_conn`) or (b) change the application design (no hard failure if the database connection failed).

**Comment by Avinodh** [comment]
Thanks @eulerto  - will continue investigating why the actual application (not pgbench) then encountered such an issue.
