### ISSUE TITLE
is verbose=1 required for stats logging?

### ISSUE THREAD

**Issue by jjb** [pgbouncer/pgbouncer#1088]
this (simplified) config does not do the minutely stats logging

```ini
[pgbouncer]
logfile = /dev/stdout
```

if i add `verbose = 1`, it does

is that expected? if so, i can modify the docs

thanks!

**Comment by jjb** [comment]
although, looks like verbose 1 is way more verbose than anyone would want in prod, so there doesn't seem to be a way to log just stats in prod

**Comment by eulerto** [comment]
What do you want to accomplish? How are you starting the service? By default, `verbose = 0` even though the statistic messages are printed to `stderr` (`-q` disallows any messages to `stderr`). See the following code in libusual:

https://github.com/libusual/libusual/blob/826fbb40325c56ea59f67ca6b2841b68760e1c0f/usual/logging.c#L206-L234

**Comment by jjb** [comment]
hm okay, so you're saying stats go to stderr regardless of the verbose setting? maybe stderr in my environment isn't making it to my logs, something like that. will look into it. thanks.
