### ISSUE TITLE
PGBOUNCER "server conn crashed?" Error

### ISSUE THREAD

**Issue by abdullahergin** [pgbouncer/pgbouncer#1092]
Pgbouncer returns this error frequently on many of my database connections. I can't figure out what exactly is causing this error.

`2024-06-12 13:02:23.005 +03 [2865569] LOG C-0x56059d2f0410: db_name/user_name@IP_Adrr:64507 closing because: server conn crashed? (age=151s)`
`2024-06-12 13:02:23.005 +03 [2865569] WARNING C-0x56059d2f0410: db_name/user_name@IP_Adrr:64507 pooler error: server conn crashed?`
`2024-06-12 13:04:41.649 +03 [2865569] LOG S-0x56059d2e5e30: db_name/user_name@IP_Adrr:5438 closing because: server conn crashed? (age=9s)`
`2024-06-12 13:04:41.649 +03 [2865569] LOG C-0x56059d2e9900: db_name/user_name@IP_Adrr:12012 closing because: server conn crashed? (age=176s)`
`2024-06-12 13:04:41.649 +03 [2865569] WARNING C-0x56059d2e9900: db_name/user_name@IP_Adrr:12012 pooler error: server conn crashed?`
`2024-06-12 13:06:11.077 +03 [2865569] LOG S-0x56059d2e0480: db_name/user_name@IP_Adrr:5438 closing because: server conn crashed? (age=53s)`
`2024-06-12 13:06:11.077 +03 [2865569] LOG C-0x56059d2f50a0: db_name/user_name@IP_Adrr:11403 closing because: server conn crashed? (age=91s)`
`2024-06-12 13:06:11.077 +03 [2865569] WARNING C-0x56059d2f50a0: db_name/user_name@IP_Adrr:11403 pooler error: server conn crashed?`
`2024-06-12 13:24:14.772 +03 [2865569] LOG S-0x56059d2ffb40: db_name/user_name@IP_Adrr:5433 closing because: server conn crashed? (age=1s)`
`2024-06-12 13:24:14.772 +03 [2865569] LOG C-0x56059d30e110: db_name/user_name@IP_Adrr:27698 closing because: server conn crashed? (age=18s)`
`2024-06-12 13:24:14.772 +03 [2865569] WARNING C-0x56059d30e110: db_name/user_name@IP_Adrr:27698 pooler error: server conn crashed?`

I couldn't find a clear configuration parameter for this particular error. What is the solution to this error?

Postgresql Version: 13.3

Pgbouncer Version: 1.15

Thanks.

**Comment by JelteF** [comment]
Are there crashes in the postgresql logs? Also PgBouncer 1.15 is pretty old, so I'd recommend upgrading. PG13.3 is also missing a bunch of bugfix releases, so that could also definitely be related.

**Comment by abdullahergin** [comment]
When I filter my database clusters according to the time of the error logs of pgbouncer, I saw that it prints the same log every time: " invalid frontend message type", "invalid message format"

Detailed Information;
`pgbouncer;
	2024-06-12 17:57:16.850 +03 [3082827] LOG S-0x5614e6fb7f70: dbname/username@Ip_Adrr:5438 closing because: server conn crashed? (age=0s)
	2024-06-12 17:57:16.850 +03 [3082827] LOG C-0x7f43e43ac9f0: dbname/username@Ip_Adrr:58547 closing because: server conn crashed? (age=54s)
	2024-06-12 17:57:16.850 +03 [3082827] WARNING C-0x7f43e43ac9f0: dbname/username@Ip_Adrr:58547 pooler error: server conn crashed?
	2024-06-12 17:57:16.857 +03 [3082827] LOG S-0x5614e6fb4230: dbname/username@Ip_Adrr:5438 closing because: server conn crashed? (age=7s)
	2024-06-12 17:57:16.857 +03 [3082827] LOG C-0x5614e6ff4810: dbname/username@Ip_Adrr:34049 closing because: server conn crashed? (age=0s)
	2024-06-12 17:57:16.857 +03 [3082827] WARNING C-0x5614e6ff4810: dbname/username@Ip_Adrr:34049 pooler error: server conn crashed?`
	
And when I checked the logs of my database cluster at 17:57:16;
`postgres;
	time=2024-06-12 17:57:16 +03,pid=3094030 db=dbname,usr=username,client=Ip_Adrr FATAL:  invalid frontend message type 54
	time=2024-06-12 17:57:16 +03,pid=3094044 db=dbname,usr=username,client=Ip_Adrr ERROR:  invalid message format
	time=2024-06-12 17:57:16 +03,pid=3094044 db=dbname,usr=username,client=Ip_Adrr FATAL:  invalid frontend message type 50`

Thanks.

**Comment by JelteF** [comment]
Sounds like updating PgBouncer to the latest version might help with that.

**Comment by abdullahergin** [comment]
The error occurs when the value of the `pool_mode` parameter is `transaction.` When I change it to session, the problem disappears. But this time, after a certain period of time, my databases give `Connection attempt timed` out error when trying to connect with pgbouncer. 
Pgbouncer version: 1.20.1
Postgres version: 13.3

**Comment by JelteF** [comment]
Can you share your full configuration?

**Comment by abdullahergin** [comment]
Sorry, I should have communicated earlier
Conf;
**pgbouncer;**
```
max_client_conn = 4096
default_pool_size = 100
min_pool_size = 0
reserve_pool_size = 0
reserve_pool_timeout = 5
max_db_connections = 0
max_user_connections = 0

Timeouts
server_lifetime = 3600
server_idle_timeout = 600
server_connect_timeout = 30
server_login_retry = 5
query_timeout = 0
query_wait_timeout = 60
client_idle_timeout = 300
client_login_timeout = 150
idle_transaction_timeout = 120
```

**Postgres;**
```
max_connections = 4096
shared_buffers = 512MB
max_prepared_transactions = 4096  **We use prepared_transaction**
work_mem = 64MB
maintenance_work_mem = 32MB
max_wal_size = 1GB
min_wal_size = 80MB
```

**Comment by abdullahergin** [comment]
what I forgot to add;
pool_mode = transaction
server_reset_query = DISCARD ALL
server_check_query = select 1
server_check_delay = 3

**Comment by JelteF** [comment]
I expect it's related to one of these settings:
```
server_reset_query = DISCARD ALL
server_check_query = select 1
server_check_delay = 3
```

**Comment by abdullahergin** [comment]
Do you have an alternative suggestion?
Thanks.

**Comment by JelteF** [comment]
I would try removing `server_reset_query = DISCARD ALL` to see if that resolves your problem.

**Comment by JelteF** [comment]
If it does fix the problem then it's somehow a bug in the `server_reset_query` logic of PgBouncer. It would be helpful if you could provide logs with `verbose=2` of the error.

**Comment by abdullahergin** [comment]
So I need to` DEALLOCATE ALL` the value of the parameter?
like `server_reset_query = DEALLOCATE ALL`

**Comment by abdullahergin** [comment]
I also see my transactions in DISCARD ALL for a long day, I have the connection and idle timeouts. I don't sure why this transaction keeps going instead of killing automatically;
![image](https://github.com/pgbouncer/pgbouncer/assets/123872870/5a5964f1-b37d-46d6-aeb7-334304b3a029)

**Comment by JelteF** [comment]
Why do use use `server_reset_query` in the first place? If it's because of prepared statements it's probably better to upgrade to PgBouncer 1.22.1 and set `max_prepared_statements=100`.

**Comment by abdullahergin** [comment]
The value of the server_reset_query parameter is DISCARD ALL by default. I honestly did not know that there was any parameter in pgbouncer for prepared transactions and I was managing only with the max_prepared_transactions parameter on the postgres side. I will try to do max_prepared_statements and version update process as soon as possible and inform you.

If it doesn't work, I guess I'll have to remove the first parameter you mentioned "server_reset_query = DISCARD ALL", but I don't quite understand how to remove this parameter. Are you talking about deleting the parameter completely from the config file?

Thank you very much for your support

**Comment by JelteF** [comment]
ah sorry, I didn't realize you didn't set `server_reset_query_always=1`. So in your case the `server_reset_query` is should be unused if you use transaction pooling.

**Comment by JelteF** [comment]
Also, prepared transactions and prepared statements are two very different things (even though they both have similar names).

**Comment by JelteF** [comment]
Also, it's worth trying 1.22.1 instead of 1.20.1, there have been some bugfixes since than that might fix this too.
