### ISSUE TITLE
Different problems in parse_ident_line (hba.c)

### ISSUE THREAD

**Issue by dmitry-lipetsk** [pgbouncer/pgbouncer#1100]
Hello,

I found that parse_ident_line (hba.c) does not check strdup results and may exit by error without cleanup.

https://github.com/pgbouncer/pgbouncer/blob/5e01e56328201ce8272e4421b550874162508a70/src/hba.c#L569

Here it does not check map_name_copy:
https://github.com/pgbouncer/pgbouncer/blob/5e01e56328201ce8272e4421b550874162508a70/src/hba.c#L595-L597

Here it does not check mapping->system_user_name:
https://github.com/pgbouncer/pgbouncer/blob/5e01e56328201ce8272e4421b550874162508a70/src/hba.c#L604-L606

Here it does not check mapping->postgres_user_name:
https://github.com/pgbouncer/pgbouncer/blob/5e01e56328201ce8272e4421b550874162508a70/src/hba.c#L615-L617

Here it exits by error without releasing an allocated 'mapping':
https://github.com/pgbouncer/pgbouncer/blob/5e01e56328201ce8272e4421b550874162508a70/src/hba.c#L631-L636

Section 'failed' must free map_name_copy, too:
https://github.com/pgbouncer/pgbouncer/blob/5e01e56328201ce8272e4421b550874162508a70/src/hba.c#L646-L650

**Comment by eulerto** [comment]
@emelsimsek it seems you forgot to edit the commit message saying that the PR #1101 closes this issue.

@dmitry-lipetsk some of your contributions already have a patch so there is no need to create an issue and after that a PR, you can create only the PR. If you are fixing an issue that was reported some time ago, you should say so using a [GH keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
