### ISSUE TITLE
PgCredentials objects are freed incorrectly [through user_cache, not credentials_cache]

### ISSUE THREAD

**Issue by dmitry-lipetsk** [pgbouncer/pgbouncer#1104]
Hello,

kill_databases uses slab_free(user_cache, db->forced_user_credentials):
https://github.com/pgbouncer/pgbouncer/blob/bc6bf4fdd0777f283fa9357e999765abf0f2f587/src/janitor.c#L846-L847

but force_user_credentials uses slab_alloc(credentials_cache):
https://github.com/pgbouncer/pgbouncer/blob/bc6bf4fdd0777f283fa9357e999765abf0f2f587/src/objects.c#L596

Is it ok?

**Comment by dmitry-lipetsk** [comment]
Hello,

As I understand it is not OK.

A similar problem exists in credentials_node_release

https://github.com/pgbouncer/pgbouncer/blob/bc6bf4fdd0777f283fa9357e999765abf0f2f587/src/objects.c#L138-L142

This function is used to free db->user_tree:
https://github.com/pgbouncer/pgbouncer/blob/bc6bf4fdd0777f283fa9357e999765abf0f2f587/src/janitor.c#L861

db->user_tree is filed in add_dynamic_credentials:
https://github.com/pgbouncer/pgbouncer/blob/bc6bf4fdd0777f283fa9357e999765abf0f2f587/src/objects.c#L543-L554

So credentials_node_release must use:
`slab_free(credentials_cache, user);`

credentials_node_release is used only for PgDatabase::user_tree.

It seems to me, it is the last point where PgCredentials is freed incorrectly.

**Comment by dmitry-lipetsk** [comment]
This issue leads to the following crash within pgbouncer:

![image](https://github.com/pgbouncer/pgbouncer/assets/4594554/dd90dbd7-9b73-41f9-a3ce-3ce113a00369)

**Comment by eulerto** [comment]
PR was merged.
