### ISSUE TITLE
pgbouncer and patroni haproxy-based leader/replica: how to load balance?

### ISSUE THREAD

**Issue by VinnyVicious** [pgbouncer/pgbouncer#1130]
Is it possible to use pgbouncer with patroni's haproxy load balancer? Meaning: can pgbouncer dynamically elect port 5000 or port 5001 depending if the query is a SELECT or a write?

Consider the following cluster architecture:

![image](https://github.com/user-attachments/assets/00492cd8-5f8f-435f-8ac3-e3ad2cf3f46e)

HAProxy does the following:

```
listen primary
    bind *:5000
    option httpchk /primary 
    http-check expect status 200
    default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
    server node1 node1:5432 maxconn 100 check port 8008
    server node2 node2:5432 maxconn 100 check port 8008
    server node3 node3:5432 maxconn 100 check port 8008

listen standbys
    balance roundrobin
    bind *:5001
    option httpchk /replica 
    http-check expect status 200
    default-server inter 3s fall 3 rise 2 on-marked-down shutdown-sessions
    server node1 node1:5432 maxconn 100 check port 8008
    server node2 node2:5432 maxconn 100 check port 8008
    server node3 node3:5432 maxconn 100 check port 8008
```

So, if a postgres instance is primary, 5000. If not, if it is a replica, answer on 5001. Do I need a pool for reads and a pool for writes? 

Right now I have this:

```
[databases]
# Define connection pools for your databases
master_db = host=localhost port=5000 dbname=mydatabase user=myuser password=mypassword
slave_db1 = host=localhost port=5001 dbname=mydatabase user=myuser password=mypassword
slave_db2 = host=localhost port=5001 dbname=mydatabase user=myuser password=mypassword

[pgbouncer]
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /var/run/pgbouncer/pgbouncer.pid
listen_addr = *
listen_port = 6432
auth_type = any

pool_mode = transaction
max_client_conn = 100
default_pool_size = 20
reserve_pool_size = 5
reserve_pool_timeout = 5

log_connections = 1
log_disconnections = 1
log_pooler_errors = 1

server_round_robin = 1

server_idle_timeout = 600
server_lifetime = 3600
server_connect_timeout = 15
server_login_retry = 15
client_login_timeout = 60
query_timeout = 0
```

**Comment by eulerto** [comment]
No. PgBouncer is just a connection pooler. It does not parse the query to figure out if it is a read or write query. If you want to use PgBouncer in your solution, the application should have this knowledge (read/write query) and use different pools. Another option is to use something that reports to HA Proxy what its current role (primary or standby) is such as the [bgw_replstatus](https://github.com/mhagander/bgw_replstatus) extension.

**Comment by VinnyVicious** [comment]
So, the correct way is to maintain 2 different pools on pgbouncer? I still want to use pgbouncer, but don't want it to confuse between read and write pools. How can I assure it is going to separate them?

**Comment by AndrewJackson2020** [comment]
So pgbouncer has no way of separating read only and write only traffic (no easy task in postgres because of volatile functions). You need to do this yourself at the application/user layer. Basically ur application should be smart enough to know to send read only traffic to the read pool and write traffic to the write pool. The underlying database of the read pool can even be a read only replica which assures that it will not accept and write traffic.
