### ISSUE TITLE
server_idle_timeout

### ISSUE THREAD

**Issue by dafrpappe** [pgbouncer/pgbouncer#114]
Do you think server_idle_timeout = 60 is a small time? I have 100 DBs and once in awhile I get and error "pgbouncer cannot connect to server". The server_life_time is set to 3600. However, when I set server_idle_timeout to 600, it works fine. The reason I set this parameter to 60 is I can have control the database connection to 300, if not it goes up between 700 to 800 connections.
Any thoughts

**Comment by markokr** [comment]
Why it cannot connect to server?  Could it be you are running into postgres' max_connections?

**Comment by dafrpappe** [comment]
There are 28 Ruby application nodes that points to pgbouncer. Each node has  the db_pool set  to 35. Each app node can go up to  80 threads.
In pgbouncer, 
In postgres, there is one database with 100 schemas and the max_connection is set to 1500, but it never goes up to 1000. In pgbouncer it is set  [database] dbname1 =  search_path to schemaXX,    max_client_conn = 60000, default_pool_size = 1500, min_pool_size = 1, server_lifetime = 600, server_idle_timeout = 60, idle_transaction_timeout = 310,client_idle_timeout = 300.
If  I set server_lifetime to 60, the number of connections goes down to 300 but the error "pgbouncer cannot connect to server" starts showing up ( one or two daily). If server_lifetime is set to 600(default value) the number of connections goes up between 700 to 800 (This number is too high).

**Comment by markokr** [comment]
What is the pool_mode?

Does postgres server has anything in log why the connection failed?

Note that this exact error comes from "fast-fail" path, where the pool is empty and last connection failed.  Bouncer will immedietely close client then.  So the question is: why did the actual connection attempt fail?  Please look into logs.

**Comment by dafrpappe** [comment]
We are using transaction mode.
No, that is why to me is it strange because this connection error is not showing in the postgres log. Apparently, postgres never knew about these requests, and that is why is not showing in the logs. This only happens when  server_idle_timeout  is set to  60. However, when server_idle_timeout  is set to 600 (default), there are no pgbouncer errors.
Is there a way to keep low connections in the postgres server?  Will help if default_pool_size set to 300? If pgbouncer multiplex 300 connections, the perfomance won't be affected even though each database (schema) pool goes up to 500 connections? 
 By the way, the pgbouncer  version is 1.5.4-7..

**Comment by markokr** [comment]
1.5.4 is pretty old, and has remote crash bug.  Also 1.6 has:

  * Disable server_idle_timeout when server count gets below min_pool (#60)
    (Marko Kreen)

which could be related - you mhavay e bad relationship with idle pools, min_pool_size and server_lifetime.

If you have many users who come and go, you might be better off with disabling min_pool_size.

In any case, please test with newer pgbouncer, and please test if min_pool_size=0 helps.
