### ISSUE TITLE
Inconsistent Error Message

### ISSUE THREAD

**Issue by AndrewJackson2020** [pgbouncer/pgbouncer#1149]
I am seeing an inconsistent error message when trying to log in as a user with nologin. basically the below test case failed on the last pytest.raises below. Would expect the error message to show 'is not permitted to login' as it does after the first attempt to login. Is this intended behavior?

It looks like the reason for this behaviour is the if statement `if (!pool->last_login_failed)` in the function test_fast_fail. Simply returning true  and skipping the subsequent application logic does not cause any other test failures and fixes the below test case. Not sure if there is some untested behavior that the rest of this function is needed for though.

```python
def test_message(bouncer, pg):
  test_user = "maxedout"
  test_database = "p0a"
  # Connect to database as User, creates existing pool
  conn_1 = bouncer.conn(user=test_user, dbname=test_database)

  # Change user to nologin
  pg.sql(f"ALTER USER {test_user} WITH NOLOGIN;")

  # Kill process on postgres
  terminate_string = f"""
  SELECT pg_terminate_backend(pid)
  FROM pg_stat_activity
  WHERE
    pid <> pg_backend_pid()
    AND usename = '{test_user}'
  """
  pg.sql(terminate_string)

  # login, check error message
  with pytest.raises(psycopg.OperationalError, match=r"is not permitted to log in"):
    bouncer.test(user=test_user, dbname=test_database)

  # login again, check error message
  # TODO This assert fails, No longer raises 'is not permitted to log in', why?
  with pytest.raises(psycopg.OperationalError, match=r"is not permitted to log in"):
    bouncer.test(user=test_user, dbname=test_database)
```

**Comment by JelteF** [comment]
I agree that this is a bug. A PR to fix this would definitely be appreciated.
