### ISSUE TITLE
Too many open files for pgbouncer

### ISSUE THREAD

**Issue by transcendx** [pgbouncer/pgbouncer#115]
I have ~20 postgres databases with hundreds of users + cronjobs, which uses these databases, therefore I get the limit of files - from pgbouncer log:
<pre>
2016-03-03 10:47:36.624 53297 WARNING sbuf_connect failed: Too many open files
2016-03-03 10:47:41.035 53297 ERROR accept() failed: Too many open files
</pre>
I use debian wheezy. in /etc/init.d/pgbouncer I added line *ulimit -n 32768*
<pre>
case "$1" in
  start)
    # Check if we are still disabled in /etc/default/pgbouncer
    [ "${START:-}" = "0" ] && exit 0
    log_daemon_msg "Starting PgBouncer" $NAME
    test -d $PIDDIR || install -d -o postgres -g postgres -m 2775 $PIDDIR
    ulimit -n 32768
    $SSD --start --chuid $RUNASUSER --oknodo -- $OPTS 2> /dev/null
    log_end_msg $?
    ;;

$ ps -e | fgrep pgbouncer
54021 ?        00:00:06 pgbouncer

$ fgrep files /proc/54021/limits
Max open files            32768                 32768                 files
</pre>
But when I need to reload config when adding new user or database:
<pre>
postgres@pgbouncer:/$ /usr/sbin/pgbouncer -R -d /etc/pgbouncer/pgbouncer.ini
Max open files again is 1024.
Max open files            1024                 4096                 files
</pre>
1. Is it possible to set ulimit parameter unchangable?
2. How to reload config with this parameter without restarting service which drops all connections.

**Comment by markokr** [comment]
when doing manual exec:

$ ulimit ...; /usr/sbin/pgbouncer -R -d ...

to test whether init.d change works:

$ /etc/init.d/pgbouncer stop
$ /etc/init.d/pgbouncer start

when adding new user or database, SIGHUP should be enough, no need for re-exec

**Comment by transcendx** [comment]
thanks for replay. I will try this!
I have one more question, because pgbouncer somehow did reload on his own.
Is this possible or some of the functionality of pgbouncer, when it gets
some state and reloads its configuration?

2016-03-03 15:26 GMT+02:00 Marko Kreen <notifications@github.com>:

**Comment by markokr** [comment]
it does not reload on it's own.  you need to send SIGHUP or say "RELOAD:" on console
