### ISSUE TITLE
Dereference of the pointer before checking against NULL

### ISSUE THREAD

**Issue by ProjectMutilation** [pgbouncer/pgbouncer#1158]
src/sbuf.c - sbuf_process_pending()
```
	IOBuf *io = sbuf->io;

	bool full = iobuf_amount_recv(io) <= 0; // io was dereferenced by call of  iobuf_amount_recv()
...
	if (sbuf->sock && io && sbuf->wait_type == W_RECV) { / /check of the pointer "io"
```
It may be worth adding an assert or it is possible that checking the pointer is unnecessary

**Comment by JelteF** [comment]
`allocate_iobuf` is called all the way at the entry point of all these sbuf functions, at the top of `sbuf_main_loop`. I don't really think there's a benefit in continously checking something that can be assumed to be true like this (even with only an assert).
