### ISSUE TITLE
undefined reference to `tls_backend_version'

### ISSUE THREAD

**Issue by jsvisa** [pgbouncer/pgbouncer#116]
@markokr I'm sorry, but I can't compile 1.7.2, because of 

```bash
undefined reference to `tls_backend_version'
```

And I can't find the declaration in libssl, could you show what I'm missing.

**Comment by markokr** [comment]
Cannot reproduce.  Are you using official tarball?

**Comment by jsvisa** [comment]
@markokr I'm using this project's clone, error msg is below:

```bash
.objs/pgbouncer/src/main.o: In function `main':
/root/pgbouncer/src/main.c:917: undefined reference to `tls_backend_version'
collect2: error: ld returned 1 exit status
make: *** [pgbouncer] Error 1
```
[main.c:L917](https://github.com/pgbouncer/pgbouncer/blob/master/src%2Fmain.c#L917-L919)

**Comment by markokr** [comment]
Ok, that explains it - you have older checkout of libusual under lib/.  Either fetch it separately or use --recurse-submodules when fetching/pulling pgbouncer repo.
