### ISSUE TITLE
Auth_type = md5 is not working 

### ISSUE THREAD

**Issue by adnanhamdussalam** [pgbouncer/pgbouncer#1160]
HI,
When I set auth_type = md5 the session is not established and when I use trust the session getting establish:
pgbouncer -V
      PgBouncer 1.23.1
      libevent 2.1.12-stable
      adns: c-ares 1.19.1
      tls: OpenSSL 3.0.7 1 Nov 2022
      systemd: yes

my pgbouncer.ini setting:
[databases]
ctafiniti = host=10.114.16.33 port=5432 dbname=ctdb

[users]
[pgbouncer]
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /var/run/pgbouncer/pgbouncer.pid
listen_addr = 10.114.16.33
listen_port = 6432
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
admin_users = postgres
stats_users = stats, postgres
pool_mode = session
max_client_conn = 100
default_pool_size = 20
min_pool_size = 1
#server_round_robin = 1
log_connections = 1
verbose = 3

Log when connection established:

Sep 04 12:51:03 testbed04 pgbouncer[88405]: new fd from accept=11
Sep 04 12:51:03 testbed04 pgbouncer[88405]: resync(11): done=0, parse=0, recv=0
Sep 04 12:51:03 testbed04 pgbouncer[88405]: sbuf_process_pending: start
Sep 04 12:51:03 testbed04 pgbouncer[88405]: sbuf_process_pending: loop 1
Sep 04 12:51:03 testbed04 pgbouncer[88405]: C-0x56439540b440: (nodb)/(nouser)@10.114.16.50:37052 read pkt='!' len=8
Sep 04 12:51:03 testbed04 pgbouncer[88405]: C-0x56439540b440: (nodb)/(nouser)@10.114.16.50:37052 C: req SSL
Sep 04 12:51:03 testbed04 pgbouncer[88405]: C-0x56439540b440: (nodb)/(nouser)@10.114.16.50:37052 P: nak
Sep 04 12:51:03 testbed04 pgbouncer[88405]: sbuf_process_pending: loop 2
Sep 04 12:51:03 testbed04 pgbouncer[88405]: sbuf_process_pending: done looping
Sep 04 12:51:03 testbed04 pgbouncer[88405]: sbuf_send_pending_iobuf
Sep 04 12:51:03 testbed04 pgbouncer[88405]: sbuf_process_pending: end
Sep 04 12:51:03 testbed04 pgbouncer[88405]: resync(11): done=8, parse=8, recv=8
Sep 04 12:51:03 testbed04 pgbouncer[88405]: C-0x56439540b440: (nodb)/(nouser)@10.114.16.50:37052 P: got connection: 10.114.16.50:37052 -> 10.114.16.33:6432
Sep 04 12:51:03 testbed04 pgbouncer[88405]: safe_accept(9) = Resource temporarily unavailable
Sep 04 12:51:03 testbed04 pgbouncer[88405]: resync(11): done=0, parse=0, recv=0
Sep 04 12:51:03 testbed04 pgbouncer[88405]: sbuf_process_pending: start
Sep 04 12:51:03 testbed04 pgbouncer[88405]: sbuf_process_pending: loop 1
Sep 04 12:51:03 testbed04 pgbouncer[88405]: C-0x56439540b440: (nodb)/(nouser)@10.114.16.50:37052 read pkt='!' len=85
Sep 04 12:51:03 testbed04 pgbouncer[88405]: C-0x56439540b440: (nodb)/(nouser)@10.114.16.50:37052 got var: user=postgres
Sep 04 12:51:03 testbed04 pgbouncer[88405]: C-0x56439540b440: (nodb)/(nouser)@10.114.16.50:37052 got var: database=ctafiniti
Sep 04 12:51:03 testbed04 pgbouncer[88405]: C-0x56439540b440: (nodb)/(nouser)@10.114.16.50:37052 using application_name: psql
Sep 04 12:51:03 testbed04 pgbouncer[88405]: C-0x56439540b440: (nodb)/(nouser)@10.114.16.50:37052 got var: client_encoding=UTF8
Sep 04 12:51:03 testbed04 pgbouncer[88405]: C-0x56439540b440: ctdb/postgres@10.114.16.50:37052 login attempt: db=ctafiniti user=postgres tls=no replication=no
Sep 04 12:51:03 testbed04 pgbouncer[88405]: C-0x56439540b440: ctdb/postgres@10.114.16.50:37052 P: welcome_client
Sep 04 12:51:03 testbed04 pgbouncer[88405]: C-0x56439540b440: ctdb/postgres@10.114.16.50:37052 logged in
Sep 04 12:51:03 testbed04 pgbouncer[88405]: sbuf_process_pending: loop 2
Sep 04 12:51:03 testbed04 pgbouncer[88405]: sbuf_process_pending: done looping
Sep 04 12:51:03 testbed04 pgbouncer[88405]: sbuf_send_pending_iobuf
Sep 04 12:51:03 testbed04 pgbouncer[88405]: sbuf_process_pending: end
Sep 04 12:51:03 testbed04 pgbouncer[88405]: resync(11): done=85, parse=85, recv=85

Log when connection does not establish:

Sep 04 12:52:57 testbed04 pgbouncer[88599]: sbuf_process_pending: end
Sep 04 12:52:57 testbed04 pgbouncer[88599]: resync(11): done=8, parse=8, recv=8
Sep 04 12:52:57 testbed04 pgbouncer[88599]: C-0x55bf137d4440: (nodb)/(nouser)@10.114.16.50:42324 P: got connection: 10.114.16.50:42324 -> 10.114.16.33:6432
Sep 04 12:52:57 testbed04 pgbouncer[88599]: safe_accept(9) = Resource temporarily unavailable
Sep 04 12:52:57 testbed04 pgbouncer[88599]: resync(11): done=0, parse=0, recv=0
Sep 04 12:52:57 testbed04 pgbouncer[88599]: sbuf_process_pending: start
Sep 04 12:52:57 testbed04 pgbouncer[88599]: sbuf_process_pending: loop 1
Sep 04 12:52:57 testbed04 pgbouncer[88599]: C-0x55bf137d4440: (nodb)/(nouser)@10.114.16.50:42324 read pkt='!' len=85
Sep 04 12:52:57 testbed04 pgbouncer[88599]: C-0x55bf137d4440: (nodb)/(nouser)@10.114.16.50:42324 got var: user=postgres
Sep 04 12:52:57 testbed04 pgbouncer[88599]: C-0x55bf137d4440: (nodb)/(nouser)@10.114.16.50:42324 got var: database=ctafiniti
Sep 04 12:52:57 testbed04 pgbouncer[88599]: C-0x55bf137d4440: (nodb)/(nouser)@10.114.16.50:42324 using application_name: psql
Sep 04 12:52:57 testbed04 pgbouncer[88599]: C-0x55bf137d4440: (nodb)/(nouser)@10.114.16.50:42324 got var: client_encoding=UTF8
Sep 04 12:52:57 testbed04 pgbouncer[88599]: C-0x55bf137d4440: ctdb/postgres@10.114.16.50:42324 login attempt: db=ctafiniti user=postgres tls=no replication=no
Sep 04 12:52:57 testbed04 pgbouncer[88599]: C-0x55bf137d4440: ctdb/postgres@10.114.16.50:42324 Auth request sent successfully
Sep 04 12:52:57 testbed04 pgbouncer[88599]: sbuf_process_pending: loop 2
Sep 04 12:52:57 testbed04 pgbouncer[88599]: sbuf_process_pending: done looping
Sep 04 12:52:57 testbed04 pgbouncer[88599]: sbuf_send_pending_iobuf
Sep 04 12:52:57 testbed04 pgbouncer[88599]: sbuf_process_pending: end
Sep 04 12:52:57 testbed04 pgbouncer[88599]: resync(11): done=85, parse=85, recv=85
Sep 04 12:52:57 testbed04 pgbouncer[88599]: resync(11): done=0, parse=0, recv=0

**Comment by AndrewJackson2020** [comment]
I'm not 100% sure what issue you are seeing. Can you post the error that you are seeing from the database client? (psql, psycopg, or the like)

**Comment by adnanhamdussalam** [comment]
I am using haproxy and in haproxy I have mentioned the pgbouncer port 6432 to connect the standby database (.33) and I also having another standby db (.34) against port 5432 and set to connect as roundrobin.
When connecting to  database using below query it always connects with (.34) as it is set as roundrobin so should it first connect with (.33) and then (.34) and so on but my connection is always established at .34 but when I change the auth_type to trust I am able to connect with .33.

psql -h 10.114.16.50 -p 5001  -U postgres -d ctdb

Any idea ?
Below is the haproxy.cfg file setting:


global
    log /dev/log    local0
    log /dev/log    local1 notice
    #chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # Default SSL material locations
   # ca-base /etc/ssl/certs
   # crt-base /etc/ssl/private

    # Default ciphers to use on SSL-enabled listening sockets.
    # For more information, see ciphers(1SSL). This list is from:
    # https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers/
    #ssl-default-bind-ciphers PROFILE=SYSTEM
    #ssl-default-bind-options no-sslv3

defaults
    log     global
    option  dontlognull
    timeout connect 500000ms
    timeout client  50m  # 10 minutes
    timeout server  50m  # 10 minutes
    # timeout client-fin 10s
    # timeout server-fin 10s
# Stats configuration
listen stats
    # Set mode to HTTP
    mode http
    # Bind to port 8080
    bind *:8080
    # Enable stats
    stats enable
    # Stats URI
    stats uri /

# Frontend for write operations on port 5000
frontend postgresql_write
    bind 10.114.16.50:5000
    mode tcp
    option tcplog

# Route all traffic to the write backend
    default_backend write_backend

# Frontend for read operations on port 5001
frontend postgresql_read
    bind 10.114.16.50:5001
    mode tcp
    option tcplog

    # Route all traffic to the read backend
    default_backend read_backend

# Backend for write operations (primary node)
backend write_backend
    mode tcp
    option tcp-check
    default-server inter 3s fall 3 rise 2
    server primary_node 10.114.16.28:5432 check
# Backend for read operations (secondary nodes)
backend read_backend
    mode tcp
    option tcp-check
    balance roundrobin
    default-server inter 3s fall 3 rise 2
    server secondary_node1 10.114.16.33:6432 check
    server secondary_node2 10.114.16.34:5432 check

**Comment by adnanhamdussalam** [comment]
Hi ,

Any idea I have also try with older version of pgbouncer but still facing the same issue psql gets connect without any error but it always connects with .34 but not connecting with .33

**Comment by AndrewJackson2020** [comment]
Tbh this sounds like an haproxy issue and I am not an expert with that software.

**Comment by adnanhamdussalam** [comment]
Thank you for the update.
Then why it connects when I change the auth_type to trust and  pgbouncer if the issue is at haproxy then why it is connecting when I change the auth type to trust in pgbouncer.ini and in the log you can also see the welcome_client message 

PFA the log of pgbouncer after changing the auth type trust 

Sep 05 06:57:38 testbed04 pgbouncer[122354]: safe_accept(9) = 12 (10.114.16.50:43018)
Sep 05 06:57:38 testbed04 pgbouncer[122354]: new fd from accept=12
Sep 05 06:57:38 testbed04 pgbouncer[122354]: resync(12): done=0, parse=0, recv=0
Sep 05 06:57:38 testbed04 pgbouncer[122354]: safe_recv(12, 4096) = 8
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: start
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 1
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: (nodb)/(nouser)@10.114.16.50:43018 read pkt='!' len=8
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: (nodb)/(nouser)@10.114.16.50:43018 C: req SSL
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: (nodb)/(nouser)@10.114.16.50:43018 P: nak
Sep 05 06:57:38 testbed04 pgbouncer[122354]: safe_send(12, 1) = 1
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 2
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: done looping
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_send_pending_iobuf
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: end
Sep 05 06:57:38 testbed04 pgbouncer[122354]: resync(12): done=8, parse=8, recv=8
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: (nodb)/(nouser)@10.114.16.50:43018 P: got connection: 10.114.16.50:43018 -> 10.114.16.33:6432
Sep 05 06:57:38 testbed04 pgbouncer[122354]: safe_accept(9) = Resource temporarily unavailable
Sep 05 06:57:38 testbed04 pgbouncer[122354]: resync(12): done=0, parse=0, recv=0
Sep 05 06:57:38 testbed04 pgbouncer[122354]: safe_recv(12, 4096) = 85
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: start
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 1
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: (nodb)/(nouser)@10.114.16.50:43018 read pkt='!' len=85
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: (nodb)/(nouser)@10.114.16.50:43018 got var: user=postgres
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: (nodb)/(nouser)@10.114.16.50:43018 got var: database=ctafiniti
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: (nodb)/(nouser)@10.114.16.50:43018 using application_name: psql
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: (nodb)/(nouser)@10.114.16.50:43018 got var: client_encoding=UTF8
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: ctafiniti/postgres@10.114.16.50:43018 login attempt: db=ctafiniti user=postgres tls=no
Sep 05 06:57:38 testbed04 pgbouncer[122354]: finish_client_login: no welcome message, pause
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: ctafiniti/postgres@10.114.16.50:43018 pause_client
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@(bad-af):0 inet socket: 10.114.16.33
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 launching new connection to server
Sep 05 06:57:38 testbed04 pgbouncer[122354]: connect(13, 10.114.16.33:5432) = Operation now in progress
Sep 05 06:57:38 testbed04 pgbouncer[122354]: launch_new_connection: already progress
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: connect ok
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 new connection to server (from 10.114.16.33:38478)
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 P: SSL request
Sep 05 06:57:38 testbed04 pgbouncer[122354]: safe_send(13, 8) = 8
Sep 05 06:57:38 testbed04 pgbouncer[122354]: launch_new_connection: already progress
Sep 05 06:57:38 testbed04 pgbouncer[122354]: resync(13): done=0, parse=0, recv=0
Sep 05 06:57:38 testbed04 pgbouncer[122354]: safe_recv(13, 4096) = 1
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: start
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 1
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 launching tls
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 2
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: done looping
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_send_pending_iobuf
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: end
Sep 05 06:57:38 testbed04 pgbouncer[122354]: resync(13): done=1, parse=1, recv=1
Sep 05 06:57:38 testbed04 pgbouncer[122354]: tls_handshake: err=-2
Sep 05 06:57:38 testbed04 pgbouncer[122354]: launch_new_connection: already progress
Sep 05 06:57:38 testbed04 pgbouncer[122354]: tls_handshake: err=-2
Sep 05 06:57:38 testbed04 pgbouncer[122354]: launch_new_connection: already progress
Sep 05 06:57:38 testbed04 pgbouncer[122354]: tls_handshake: err=0
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 SSL established: TLSv1.3/TLS_AES_256_GCM_SHA384/ECDH=prime256v1
Sep 05 06:57:38 testbed04 pgbouncer[122354]: pktbuf_dynamic(512): 0x55f092a9db10
Sep 05 06:57:38 testbed04 pgbouncer[122354]: tls_write: req=42 out=42
Sep 05 06:57:38 testbed04 pgbouncer[122354]: resync(13): done=0, parse=0, recv=0
Sep 05 06:57:38 testbed04 pgbouncer[122354]: tls_read: req=4096 out=-2
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: start
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 1
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: done looping
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_send_pending_iobuf
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: end
Sep 05 06:57:38 testbed04 pgbouncer[122354]: resync(13): done=0, parse=0, recv=0
Sep 05 06:57:38 testbed04 pgbouncer[122354]: launch_new_connection: already progress
Sep 05 06:57:38 testbed04 pgbouncer[122354]: resync(13): done=0, parse=0, recv=0
Sep 05 06:57:38 testbed04 pgbouncer[122354]: tls_read: req=4096 out=452
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: start
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 1
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='R', len=9
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 calling login_answer
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: auth ok
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 2
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=31
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: TimeZone = America/New_York
Sep 05 06:57:38 testbed04 pgbouncer[122354]: pktbuf_dynamic(128): 0x55f092ab40e0
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 3
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=28
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: IntervalStyle = postgres
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 4
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=33
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: search_path = "$user", public
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 5
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=21
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: is_superuser = on
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 6
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=23
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: application_name =
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 7
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=39
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: default_transaction_read_only = off
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 8
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=27
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: scram_iterations = 4096
Sep 05 06:57:38 testbed04 pgbouncer[122354]: make_room(0x55f092ab40e0, 5): realloc newlen=256
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 9
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=24
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: DateStyle = ISO, MDY
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 10
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=36
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: standard_conforming_strings = on
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 11
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=36
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: session_authorization = postgres
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 12
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=26
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: client_encoding = UTF8
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 13
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=25
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: server_version = 16.4
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 14
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=26
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: server_encoding = UTF8
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 15
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=23
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: in_hot_standby = on
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 16
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='S', len=26
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 S: param: integer_datetimes = on
Sep 05 06:57:38 testbed04 pgbouncer[122354]: make_room(0x55f092ab40e0, 18): realloc newlen=512
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 17
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='K', len=13
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 18
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 read pkt='Z', len=6
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 server login ok, start accepting queries
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@10.114.16.33:5432 release_server: new state=12
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: ctafiniti/postgres@10.114.16.50:43018 activate_client
Sep 05 06:57:38 testbed04 pgbouncer[122354]: resync(12): done=0, parse=0, recv=85
Sep 05 06:57:38 testbed04 pgbouncer[122354]: safe_recv(12, 4011) = Resource temporarily unavailable
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: start
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 1
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: ctafiniti/postgres@10.114.16.50:43018 read pkt='!' len=85
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: ctafiniti/postgres@10.114.16.50:43018 P: welcome_client
Sep 05 06:57:38 testbed04 pgbouncer[122354]: safe_send(12, 456) = 456
Sep 05 06:57:38 testbed04 pgbouncer[122354]: C-0x55f092a36ef0: ctafiniti/postgres@10.114.16.50:43018 logged in
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 2
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: done looping
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_send_pending_iobuf
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: end
Sep 05 06:57:38 testbed04 pgbouncer[122354]: resync(12): done=85, parse=85, recv=85
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: loop 19
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: done looping
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_send_pending_iobuf
Sep 05 06:57:38 testbed04 pgbouncer[122354]: sbuf_process_pending: end
Sep 05 06:57:38 testbed04 pgbouncer[122354]: resync(13): done=452, parse=452, recv=452

**Comment by adnanhamdussalam** [comment]
Sep 05 06:57:38 testbed04 pgbouncer[122354]: S-0x55f092a3f5a0: ctafiniti/postgres@(bad-af):0 inet socket: 10.114.16.33
Any idea what (bad-af) menas ?

**Comment by AndrewJackson2020** [comment]
I see what ur saying. If I have time today I will try to recreate this on my local machine.

**Comment by adnanhamdussalam** [comment]
Did you get the time to recreate on your local machine ?

I have also try with auth_type = hba but same issue but  only when I use auth_type = trust I am available to connect with both standby database in a round robin fashion.

**Comment by eulerto** [comment]
@adnanhamdussalam check your HA Proxy logs. Maybe the .33 is not healthy. I mean it didn't pass the check. I also think you can use [option pgsql-check](https://www.haproxy.com/documentation/haproxy-configuration-tutorials/service-reliability/health-checks/#postgresql-health-checks) instead of `option tcp-check`.

I don't think there is a PgBouncer issue per your log messages.

**Comment by eulerto** [comment]
Silence here. Closing.
