### ISSUE TITLE
Cert auth not working

### ISSUE THREAD

**Issue by BabaTataKaka** [pgbouncer/pgbouncer#1161]
Hi there,

I'm trying to implement zero-trust auth for our postgres cluster. I'm using the pgbouncer pg_hba.conf and pg_ident.conf files to do so. However , I' m getting the following error why I try to connect using psql:

`psql: error: connection to server at "pg-1.ll" (xxx.xxx.xxx.xxx), port 6432 failed: FATAL:  server login failed: wrong password typepsql: error: connection to server at "pg-1.ll" (xxx.xxx.xxx.xxx), port 6432 failed: FATAL:  server login failed: wrong password type`

Here is the psql command:

` psql "port=6432 host=pg-1.ll user=keycloak dbname=keycloak sslcert=/opt/keycloak/certs/tls.crt sslkey=/opt/keycloak/certs/pkc8.key sslrootcert=/etc/ssl/certs/ca-certificates.crt sslmode=require"
`

Please note that the same psql command above is working when I try to connect directly to postgres(no pgbouncer) and the the postgresl pg_hba.conf and pg_ident.conf files are configured identically compared to the pbouncer one.

**Pgbouncer.ini**
```
[databases]

postgres = host=/var/run/postgresql port=5432 dbname=postgres



* = host=/var/run/postgresql port=5432



[pgbouncer]

logfile = /var/log/pgbouncer/pgbouncer.log

pidfile = /run/pgbouncer/pgbouncer.pid

listen_addr = 0.0.0.0

listen_port = 6432

unix_socket_dir = /var/run/pgbouncer

auth_hba_file = /etc/pgbouncer/pg_hba.conf

auth_ident_file = /etc/pgbouncer/pg_ident.conf

#auth_type = scram-sha-256

auth_type = hba

auth_user = pgbouncer

auth_dbname = postgres

auth_query = SELECT usename, passwd FROM user_search($1)

admin_users = postgres

stats_users = postgres

ignore_startup_parameters = extra_float_digits,geqo,search_path



pool_mode = session

server_reset_query = DISCARD ALL

max_client_conn = 10000

default_pool_size = 20

query_wait_timeout = 120

reserve_pool_size = 1

reserve_pool_timeout = 1

max_db_connections = 1000

pkt_buf = 8192

listen_backlog = 4096

max_prepared_statements = 1024

so_reuseport = 1

log_connections = 0

log_disconnections = 0

client_tls_sslmode = verify-full

client_tls_key_file = /etc/postgresql/certs/tls.key

#client_tls_key_file = /etc/postgresql/certs/pkc8.key

client_tls_cert_file = /etc/postgresql/certs/tls.crt

client_tls_ca_file = /etc/ssl/certs/ca-certificates.crt

# Documentation https://pgbouncer.github.io/config.html


```

**pgbouncer pg_hba.conf**

```
# TYPE      DATABASE                 USER                     ADDRESS                  METHOD

  hostssl   keycloak                 keycloak                 xxx.xxx.xxx.xxx/32     cert map=keycloak

  hostssl   keycloak                 keycloak                 xxx.xxx.xxx.xxx/32     cert map=keycloak

```

**pgbouncer  pg_ident.conf**

```
keycloak      keycloak-1.ll   keycloak

keycloak      keycloak-2.ll   keycloak
```

**Postgres log**

`2024-09-05 14:49:09 UTC [461639-1] [local] [unknown]@[unknown] LOG:  connection received: host=[local]`

For some reason my pgboucner.log file is in /var/log/postgresql insteand of
/var/log/pgbouncer as specified in the pbouncer.ini. In any cases, there is no relevant logs to see in the pgbouncer.log.

**Comment by JelteF** [comment]
The error suggests that pgbouncer is not allowed to log in to postgres i.e. the client to pgbouncer auth works but the pgbouncer to postgres auth doesn't.

From your description this seems to make sense, because pgbouncer is not configured to provide a certificate to postgres and postgres only allows certificate auth. 

You either need to tell pgbouncer to use a certificate using `server_tls_key_file` and related options, or you need to allow pgbouncer to authenticate some other way to postgres. e.g. using `trust` auth on UNIX sockets.

Note: Pgbouncer cannot simply reuse the cert+key that the client used to authenticate to pgbouncer (unless you give it filesystem access using `server_tls_key_file`), because TLS is designed in a way such that the server (PgBounncer) has no access to the client (psql) its key.

**Comment by BabaTataKaka** [comment]
> Reference in new issu

Ok, but in my case, postgres is already configure to accept pgbouncer connection(trust). That mean it should authenticate to pgbouncer using the provided cert and then pgbouncer should connect to postgres locally using the unix socket(trust) right?

**Comment by BabaTataKaka** [comment]
> The error suggests that pgbouncer is not allowed to log in to postgres i.e. the client to pgbouncer auth works but the pgbouncer to postgres auth doesn't.
> 
> From your description this seems to make sense, because pgbouncer is not configured to provide a certificate to postgres and postgres only allows certificate auth.
> 
> You either need to tell pgbouncer to use a certificate using `server_tls_key_file` and related options, or you need to allow pgbouncer to authenticate some other way to postgres. e.g. using `trust` auth on UNIX sockets.
> 
> Note: Pgbouncer cannot simply reuse the cert+key that the client used to authenticate to pgbouncer (unless you give it filesystem access using `server_tls_key_file`), because TLS is designed in a way such that the server (PgBounncer) has no access to the client (psql) its key.

Ok, but in my case, postgres is already configure to accept pgbouncer connection(trust). That mean it should authenticate to pgbouncer using the provided cert and then pgbouncer should connect to postgres locally using the unix socket(trust) right?

**Comment by BabaTataKaka** [comment]
Ok, i forgot to turn on the log_connections flag. Now I'm getting the following error in the pgbouncer logs:

```
2024-09-05 18:34:57.869 UTC [525780] LOG C-0x563313797910: keycloak/keycloak@xxx.xxx.xxx.xxx:52208 login attempt: db=keycloak user=keycloak tls=TLSv1.3/TLS_AES_256_GCM_SHA384 replication=no

2024-09-05 18:34:57.869 UTC [525780] LOG S-0x5633137bc648: keycloak/keycloak@unix:5432 new connection to server

2024-09-05 18:34:57.871 UTC [525780] ERROR S-0x5633137bc648: keycloak/keycloak@unix:5432 cannot do SCRAM authentication: password is SCRAM secret but client authentication did not provide SCRAM keys

2024-09-05 18:34:57.871 UTC [525780] WARNING C-0x563313797910: keycloak/keycloak@xxx.xxx.xxx.xxx:52208 pooler error: server login failed: wrong password type
```

**Comment by JelteF** [comment]
Pgbouncer is trying to log in as the keycloack user. Which means it doesn't hit this hba rule in postgres its pg_hba.conf, because the user is not pgbouncer:
```
  local     all                      pgbouncer                                         trust
```
So instead this rule is hit:
```
  local     all                      all                                               scram-sha-256
```

You probably just want to remove both and add a rule like this instead:
```
  local     all                      all                                         trust
```

**Comment by BabaTataKaka** [comment]
> Pgbouncer is trying to log in as the keycloack user. Which means it doesn't hit this hba rule in postgres its pg_hba.conf, because the user is not pgbouncer:
> 
> ```
>   local     all                      pgbouncer                                         trust
> ```
> 
> So instead this rule is hit:
> 
> ```
>   local     all                      all                                               scram-sha-256
> ```
> 
> You probably just want to remove both and add a rule like this instead:
> 
> ```
>   local     all                      all                                         trust
> ```

Its working! I always been under the impression that pgbouncer would connect to postgres using pgbouncer user(on behalf of keycloak) and not as the keycloak user. Thanks a lot for your help!

**Comment by BabaTataKaka** [comment]
> Pgbouncer is trying to log in as the keycloack user. Which means it doesn't hit this hba rule in postgres its pg_hba.conf, because the user is not pgbouncer:
> 
> ```
>   local     all                      pgbouncer                                         trust
> ```
> 
> So instead this rule is hit:
> 
> ```
>   local     all                      all                                               scram-sha-256
> ```
> 
> You probably just want to remove both and add a rule like this instead:
> 
> ```
>   local     all                      all                                         trust
> ```

I have a question, do you know if the ip of the client using a certficate to authenciate must absolutely match the IP in the pgbouncer pg_hba file? We are using HAproxy alb (between the client and pgbouncer) in ssl pass-through mode so the actual connection(IP) is coming from the alb and not the client. The client point to the alb url then the alb re-route to pgbouncer. I know its using the CN from the certicate to map to the correct user(pg_ident).  I would think the incoming IP  shouldn't  matter because the authentication is made with the certificate?
