### ISSUE TITLE
logical replication and auth_query issues

### ISSUE THREAD

**Issue by dbarrosop** [pgbouncer/pgbouncer#1164]
Hello,
I saw that recently support for logical replication was added to 1.23.0 and I was trying to test it but I am having some issues with it. I have the following pgbouncer configuration:

```
[pgbouncer]
listen_addr               = 0.0.0.0
listen_port               = 5432
unix_socket_dir           = /tmp
user                      = postgres
auth_file                 = /etc/pgbouncer/users.txt
auth_type                 = md5
auth_user                 = pgbouncer
auth_query                = SELECT uname,phash FROM pgbouncer.user_lookup($1)
default_pool_size         = 20
pool_mode                 = session
max_client_conn           = 4000
server_idle_timeout       = 600
ignore_startup_parameters = extra_float_digits
admin_users               = pgbouncer_admin
client_tls_sslmode        = allow
client_tls_key_file       = /etc/pgbouncer-certs/client/tls.key
client_tls_cert_file      = /etc/pgbouncer-certs/client/tls.crt

[databases]
dbname = host=hostname port=5432 dbname=dbname pool_size=10
```

When I try to connect to the database with the string:

```
postgres://username:password@hostname:5432/dbname?replication=database
```

I get the error (on the database side):

```
2024-09-12 08:38:43.147 GMT [124] FATAL:  permission denied to start WAL sender
2024-09-12 08:38:43.147 GMT [124] DETAIL:  Only roles with the REPLICATION attribute may start a WAL sender process.
```

I suspect it is because of the `auth_query` is trying to connect with the pgbouncer user to the database while forwarding the `replication=database` parameter.

If I add REPLICATION permissions to pgbouncer then I get the error that extended queries are not supported in replication connections:

```
2024-09-12 08:22:13.670 GMT [159] ERROR:  extended query protocol not supported in a replication connection
```

Do you know if/how this is supposed to work?

Thanks for the awesome work!

**Comment by dbarrosop** [comment]
I did a few more tests and I can confirm the issue is with `auth_query`. I basically tested without it by setting the user/password in the database entry and then I could connect with `?replication=database` with no problem. I tried setting `ignore_startup_parameters = replication` but that didn't do the trick. Is this expected? Is there any workaround? Thanks!

**Comment by JelteF** [comment]
Ugh... That's indeed a bug... I think fixing it might not be too difficult though. I'll take a stab at doing so soonish.

The only workaround that I can think of is adding the password of the user that needs to do logical replication to the `auth_file`, so that the `auth_query` does not need to be sent for this user.

**Comment by dbarrosop** [comment]
I have been following your PR, if there is anything I can do to help with it let me know. Thanks again for the awesome work :)

**Comment by d3qtian** [comment]
Hi @JelteF 
Thank you for addressing this issue and providing a fix! We are currently in urgent need of this functionality for our project. Could you kindly let us know when this fix will be released in the next version of pgbouncer? Your update will help us plan accordingly.

Thanks again for the great work and support!
