### ISSUE TITLE
WARNING hba line 81: unsupported method: buf=ident

### ISSUE THREAD

**Issue by grayhemp** [pgbouncer/pgbouncer#117]
Ubuntu 14.04
PgBouncer 1.7.2

I have an `ident` auth method entry in my pg_hba.conf file

```
host    all             all             127.0.0.1/32            ident
```

and it looks like pgbouncer doesn't support it

```
pgbouncer -u postgres -d /etc/pgbouncer/pgbouncer.ini
2016-03-04 12:53:10.887 82103 WARNING hba line 81: unsupported method: buf=ident
```

that is a little bit confusing.

It is for a purpose or a bug?

**Comment by markokr** [comment]
Yeah, 'ident' is not supported.  Perhaps you want 'peer' method?

**Comment by grayhemp** [comment]
I see. Thank you.

Are there any plans to add it?

On Sat, Mar 5, 2016 at 4:30 AM, Marko Kreen <notifications@github.com>
wrote:

> Yeah, 'ident' is not supported. Perhaps you want 'peer' method?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pgbouncer/pgbouncer/issues/117#issuecomment-192634657>
> .
>



-- 
Kind regards,
Sergey Konoplev
PostgreSQL Consultant and DBA

http://www.linkedin.com/in/grayhemp
https://github.com/grayhemp
+1 (415) 867-9984, +7 (499) 346-7196, +7 (988) 888-1979
gray.ru@gmail.com

**Comment by markokr** [comment]
No.  Is anyone actually using it?  I mean network ident (RFC1413).

If you actually need it and post a patch I don't mind adding it.

My only requirement is that it must not be alias for "peer" auth on unix sockets.   It Postgres bug that it allows such confusion.

**Comment by grayhemp** [comment]
I agree, ident is something that should probably be avoided. I have a bunch
of prehistoric pg deployments, without peer support, which I'm slowly
migrating to the new version, so I thought about a temporary workaround. If
ident is not planned then I don't want anyone to waste time on it, I'll
work it around with md5 + pgpass.

Thank you for your help.
