### ISSUE TITLE
could not read pidfile while running in daemon mode.

### ISSUE THREAD

**Issue by Monk-Liu** [pgbouncer/pgbouncer#1174]
I have set pidfile in config.ini in order to run in daemon mode.
```
pidfile = /var/run/pgbouncer/pgbouncer.pid
```
However, when I start pgbouncer, it raise an error.
```
# pgbouncer -v /etc/pgbouncer/pgbouncer.ini
2024-09-25 18:18:12.897 CST [14956] FATAL could not read pidfile '/var/run/pgbouncer/pgbouncer.pid': No such file or directory
```
 the error is raised from "src/main.c:722".

It seems that we can't just create an empty pgbouncer.pid file, instead, we should add one number to the pidfile.  But why? Shouldn't the code handle the situation that the pidfile is empty when we first start pgbouncer?

**Comment by petere** [comment]
The error handling in the code is sloppy. It should not treat a return of 0 from `read()` as a system call error, but handle it separately.

One of the purposes of a PID file is to protect against multiple instances interfering with each other. So being restrictive about how faulty PID files are treated seems sound to me.

**Comment by Monk-Liu** [comment]
get it, thanks Petere!

**Comment by JelteF** [comment]
I'll re-open this, as we should handle the error better. But manually creating pidfiles yourself is definetly not something that's recommended.
