### ISSUE TITLE
Building 1.23.1 --with-cares still looks for libevent

### ISSUE THREAD

**Issue by jardayn** [pgbouncer/pgbouncer#1175]
How to reproduce:

Fresh ubuntu system  
Install c-ares
Try installing PGB with `./configure --with-cares`

enjoy the error.

Ain't critical, but still a bug.

**Comment by eulerto** [comment]
It works for me. You didn't show the error. You didn't show your exact Ubuntu version.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
$ ./pgbouncer -V
PgBouncer 1.23.1
libevent 2.1.12-stable
adns: c-ares 1.27.0
tls: OpenSSL 3.0.13 30 Jan 2024
$ dpkg -l | grep ares
ii  libc-ares-dev:amd64                  1.27.0-1.0ubuntu1                       amd64        asynchronous name resolver - development files
ii  libcares2:amd64                      1.27.0-1.0ubuntu1                       amd64        asynchronous name resolver
```

**Comment by JelteF** [comment]
Even when building with c-ares support, it's expected that pgbouncer still needs/links to libevent. It won't be used for the DNS queries, but it will be used for the main eventloop that pgbouncer uses.

So, losing this since it's expected.
