### ISSUE TITLE
SHUTDOWN WAIT_FOR_SERVERS Best Practice Usage

### ISSUE THREAD

**Issue by akiffeyzioglu** [pgbouncer/pgbouncer#1185]
What's the best practices SHUTDOWN WAIT_FOR_SERVERS usage on Kubernetes pod? How can i use this and close database connections gracefully.

**Comment by eulerto** [comment]
AFAICS the [description](https://www.pgbouncer.org/usage.html) is accurate. Isn't the documentation clear enough? Are you observing any issues with this command?

**Comment by JelteF** [comment]
Generally you want to use `WAIT_FOR_CLIENTS` for graceful failover. And indeed a description of how to do that is in the docs: https://www.pgbouncer.org/usage.html#shutdown-wait_for_clients

**Comment by atmosx** [comment]
According to the documentation, there’s no functional difference between using `SHUTDOWN WAIT_FOR_CLIENTS` and the `SIGTERM` signal, which Kubernetes sends by default to a pod that is scheduled for removal. The only remaining step is to set `terminationGracePeriodSeconds: 305`, assuming the default `server_idle_timeout` (5 minutes) is being used.
