### ISSUE TITLE
Release tag with a weird suffix

### ISSUE THREAD

**Issue by sxd** [pgbouncer/pgbouncer#1194]
Hello!

In our project https://github.com/cloudnative-pg/pgbouncer-containers/ we just go an issue https://github.com/cloudnative-pg/pgbouncer-containers/issues/52 of the update workflow not working, this was due to being disable (shame on GitHub) but after we enable it, turns out that we're not picking up the right release tag because for some reason the tag is "1.23.1-fixed", why is like that? We would love to have some standard on the tags and releases so we can look for them and avoid this kind of issues in the future, it's there any standard applied here for the release tag? 

Regards!

**Comment by sxd** [comment]
So GitHub is not the source of true for the PgBouncer? sounds like that!
On the other hand, so the downloads page has any kind of feed that we can read/parse by an automated process so we can retrieve and update our dependencies ? Since we can't trust on GitHub will be awesome to have a way to retrieve the proper tags and build the versions and updates in the future :D

**Comment by JelteF** [comment]
Another way to get the latest release is going to: https://github.com/pgbouncer/pgbouncer/releases/latest

**Comment by sxd** [comment]
Yeah we know that, well you can read here https://github.com/cloudnative-pg/pgbouncer-containers/blob/main/.github/workflows/update.yml#L22 what we use the GitHub API for that, the problem is that we double check is a semantic version, in the tag to pull the code and compile (waiting for packages on distributions is a real pain in the ass) so we can know that we'r;e pulling a release version and so

**Comment by petere** [comment]
> The reason why the tag was named `1.23.1-fixed` is because something went wrong during the `1.23.1` release. And we had pushed thus pushed a tag on the wrong commit. Changing already tags after pushing is a big no-no on git repos. I think we probably should have removed the old tag, but we didn't do that and doing that now seems a bit late. Especially since all that is wrong about that tag is that the version is incorrectly reported, on `SHOW VERSION` etc.

Maybe we learn a lesson here and in the future we just make it a 1.23.2 release instead.

**Comment by JelteF** [comment]
> Maybe we learn a lesson here and in the future we just make it a 1.23.2 release instead.

Sounds reasonable. Let's do that. I updated the release wiki with a note about this.
