### ISSUE TITLE
PGbouncer 1.23.0 doesn't create unix sockets on HUP 

### ISSUE THREAD

**Issue by jardayn** [pgbouncer/pgbouncer#1207]
You have to restart PGB for it to create sockets.

Replication: 
1: add a pgbouncer systemd file
```
[Service]
Type=simple
User=ubuntu
ExecStart=/usr/local/bin/pgbouncer /pgbconf/pgbouncer.ini
ExecReload=/bin/kill -HUP $MAINPID
KillSignal=SIGINT
Restart=always
RestartSec=2s
LimitNOFILE=20000
```

2 `systemctl daemon-reload`  

3 Start PGB without  `unix_socket_dir=` in the .ini file  
4 add `unix_socket_dir=/tmp` to the ini file  
5: `systemctl reload pgbouncer` (or `kill -s HUP $PID` 
6: Check /tmp with `ls -ltrha`. There's no PGB socket  
7: `systemctl restart pgbouncer`  
8: Now there's a socket in /tmp 

Version:
```
PgBouncer 1.23.0
libevent 2.1.12-stable
adns: c-ares 1.33.1
tls: OpenSSL 3.0.2 15 Mar 2022
systemd: yes
```

**Comment by eulerto** [comment]
That's expected. The parameter `unix_socket_dir` is CF_NO_RELOAD which means it does not change on reload.

https://github.com/pgbouncer/pgbouncer/blob/544542b6a17314d8cc9bc8bb9903b9e022f424ae/src/main.c#L335-L339

**Comment by jardayn** [comment]
> That's expected. The parameter `unix_socket_dir` is CF_NO_RELOAD which means it does not change on reload.
> 
> https://github.com/pgbouncer/pgbouncer/blob/544542b6a17314d8cc9bc8bb9903b9e022f424ae/src/main.c#L335-L339

Huh. Okay, it wasn't mentioned in the docs. Will work around it. 

Any way for me to make it create the sockets without dropping existing connections/queries?

**Comment by eulerto** [comment]
AFAICS there is no workaround. You should restart the service.

**Comment by jardayn** [comment]
> AFAICS there is no workaround. You should restart the service.

Gotcha. Thank you very much.
