### ISSUE TITLE
Report backend id to the client application (e.g. for prepared statements)

### ISSUE THREAD

**Issue by vlsi** [pgbouncer/pgbouncer#126]
Current pgbouncer recommendation is "you must discard prepared statements".
That is bad from performance point of view.

What if pgbouncer reported `pgbouncer_backend_id` (or however you name it) to the client application via some fake `ParameterStatus` v3 protocol message?

That would enable proper prepared statement usage if client considers that `pgbouncer_backend_id` as a part of statement cache key. E.g. having per `pgbouncer_backend_id` statement cache might be one of the workable solutions.

I think pgjdbc (as well as other clients) can be tought to have per-`pgbouncer_backend_id` cache.
I bet that is easier than adoption of some newer frontend-backend protocol and/or adoption of newer PG version.

As far as I can see `ParameterStatus(pgbouncer_backend_id)` would support:
- Plain prepared statements with no need to `discard all`. The protocol would still be plain v3.
- All PG versions would be supported just fine.
- Failover/reconnect. pgbouncer would need to generate new `pgbouncer_backend_id`, so client (e.g. pgjdbc) would just create a new cache.

The open questions are:
1) "how client would know when to drop the cache". For instance, if a particular connection gets dropped, then there still might be a statement cache at the client side. I'm not sure if we want to have "pgbouncer_backend_id_terminated" kind of messages to each and every client connection.

2) How client should communicate to pgbouncer that the client does support per-`pgbouncer_backend_id` prepared statement cache.
For instance, client can send a specific query during a connection "startup", so pgbouncer can detect dumb clients and `discard all` for them, yet skip that `discard all` for smart clients.

3) What are the triggers for the backend id to change. For instance: what if pgbouncer sends a query to backend and it fails somehow. Does pgbouncer try to use alternative backend? That might fail since another backend might have completely irrelevant set of prepared statements.
It might require adding "the backend just died, please retry your query against new pgbouncer_backend_id" kind of pgbouncer->client kind of message.

See the discussion here: http://www.postgresql.org/message-id/CAB=Je-Es0uZtogqNBQHqsQ0OB_8A_1Lymvc7UgeUPxzzX-sYNQ@mail.gmail.com

**Comment by markokr** [comment]
All this does not work as app cannot predict on what backend query ends up running.

And there is already enough info in protocol for pgbouncer to implement plan name remapping, transparently to all apps.  (Assuming they use protocol-level plans, not SQL plans with PREPARE <foo>)

So this is the project to spent time on, no need to invent workarounds.
