### ISSUE TITLE
Be able to set auth_query database as parameter

### ISSUE THREAD

**Issue by luisbosque** [pgbouncer/pgbouncer#128]
Hi guys,

I'm having a problem with auth_user and auth_query in a environment where there are several databases.

The problem is that the client always tries to run the auth_query with the auth_user in the databases that the client is trying to connect.

https://github.com/pgbouncer/pgbouncer/blob/410617df1e218b4a934b9353e2198bd91f0feac6/src/client.c#L87

I can see two problems with this.
The first one is that this forces to authorize the user in auth_user to connect to any database in the postgresql cluster (at least in the cases where you are defining the database \* in pgbouncer).

The second is that, in a environment where there are several databases in the postgresql cluster and clients connections can go to any of these databases, the auth_user:client_database connection won't be reused. It would be useful for the cases when the auth_query must be run within the client databases (the user and password is stored in every individual database) but, if not it will cause having duplicated connections to postgresql cluster, since this auth query will respect the server_idle_timeout.

So, for example if I have 100 databases but I extract the user/password from pg_shadow I will have 100 extra connections persisted for the duration of server_idle_timeout that I don't need. Because of this I need to keep this in mind in order to configure the max connections of the postgresql cluster and the memory usage.

I have two suggestions:
- Don't persist auth connections for the server_idle_timeout duration
- Be able to set something like auth_database that overrides the client database

Please, let me know if this makes sense to you or maybe I'm missing some important context information.

Cheers

**Comment by mpalmer** [comment]
You may wish to take a look at #315.

**Comment by eulerto** [comment]
It was implemented in #764 .
