### ISSUE TITLE
 pgbouncer cannot connect to server

### ISSUE THREAD

**Issue by aek** [pgbouncer/pgbouncer#139]
Hi @all
I have an issue with pgbouncer and I think that maybe someone else have the knowledge of how to solve it.
I'm creating databases using pgbouncer by connecting to the postgres database and running create database sql queries automatically of course, not manual, but when I try to connect to the new created database pgbouncer says that cannot connect to the server
I'm closing cursors and everything, the database is there but pgbouncer seems to not know about that. How could I solve it without directly connecting to postgres?

My pgbouncer setup is with fallback connect string
- = host=localhost port=5431
  and transaction pooling

**Comment by markokr** [comment]
Works here.  pgbouncer does not do stuff like "select * from pg_databases", so local config problem?

look at pgbouncer and postges logs to see problem.  and is the port 5431 correct?

**Comment by aek** [comment]
Hi @markokr mark
I still have the issue and my config is the same of pgbouncer default and the port 5431 is setted on postgres config so pgbouncer could use the 5432

**Comment by markokr** [comment]
Ok.  I tried the fallback-db config, create and connect.  And it worked.  So there is something different in your system that makes it fail.  What is it?

**Comment by sfilargi** [comment]
```
I am seeing the same behavior. My code like this:

def db_connect():
    return psycopg2.connect(
        host=pg_host,
        port=pg_port,
        dbname=pg_db, 
        user=pg_user,
        password=pg_pass)


def create_db():
    db = psycopg2.connect(
        host=pg_host,
        port=pg_port,
        dbname='postgres', 
        user=pg_user,
        password=pg_pass)
    db.set_isolation_level(0)
    cur = db.cursor()
    cur.execute('''
        CREATE DATABASE %s
        ''' % (pg_db,))

    db.commit()

    db = db_connect()
```

The second connect fails with: `unix(30884):6432 closing because: pgbouncer cannot connect to server (age=0)`.

I cannot even connect with 'psql --port=6432 newdb" immediately. After a couple of times, it works.

**Comment by sfilargi** [comment]
I am seeing the same behavior. Easily reproducible:

```
$ psql --port 6432 testdb; createdb --port 6432 testdb; psql --port 6432 testdb
psql: ERROR:  database "testdb" does not exist
psql: ERROR:  pgbouncer cannot connect to server
```

**Comment by aek** [comment]
Completing the @sfilargi test I add some wait and reply commands to test when it will be available the db to be used through pgbouncer that it took around 18s to be accesible
```cmd
postgres@aek:~$ psql --port 6432 -U odoo testdb; createdb --port 6432 -U odoo testdb; sleep 3s; psql --port 6432 -U odoo testdb; sleep 3s; psql --port 6432 -U odoo testdb; sleep 3s; psql --port 6432 -U odoo testdb; sleep 3s; psql --port 6432 -U odoo testdb; sleep 3s; psql --port 6432 -U odoo testdb; sleep 3s; psql --port 6432 -U odoo testdb; sleep 3s; psql --port 6432 -U odoo testdb; sleep 3s; psql --port 6432 -U odoo testdb; sleep 3s; psql --port 6432 -U odoo testdb; sleep 3s; psql --port 6432 -U odoo testdb; sleep 3s; psql --port 6432 -U odoo testdb
psql: ERROR:  database "testdb" does not exist
psql: ERROR:  pgbouncer cannot connect to server
psql: ERROR:  pgbouncer cannot connect to server
psql: ERROR:  pgbouncer cannot connect to server
psql: ERROR:  pgbouncer cannot connect to server
psql: ERROR:  pgbouncer cannot connect to server
psql (9.5.6)
Type "help" for help.

```
I also solve it by pre-creating dbs from templates and use it like it will be already available on pgbouncer, also I have that solution for performance matters but I still have some on demand user named dbs that it will broken by this issue. I think that I will need to put some wait and try cicle.
Could someone point me to how I could speed up this db availability time or where is the code responsible to plug the new db into pgbouncer so I could solve it by myself

**Comment by sfilargi** [comment]
@aek May you want to re-open this in order to get some attention.

**Comment by aek** [comment]
It will be better if @markokr reopen it to keep the track of the messages and comments

**Comment by spacejam101** [comment]
having the same issue

**Comment by aek** [comment]
This is how I have solve it. 
#346

**Comment by Melkij** [comment]
Please check yours server_login_retry. By default it is 15 seconds and this is exactly timeout after failed connect to avoid spamming DB with incorrect credentials.

**Comment by petere** [comment]
Can you reproduce this without using pgbouncer? Is there perhaps a small window between when a database is created and when it can be accessed?

I don't see how pgbouncer is doing anything special here. If the database has been successfully created, then pgbouncer should be able to connect to it, even if the creation is recent.

**Comment by Melkij** [comment]
> pgbouncer should be able to connect to it, even if the creation is recent.

but only after server_login_retry seconds after last failed connection attempt

Testcase above like
```
psql --port 6432 testdb; createdb --port 6432 testdb; psql --port 6432 testdb
```
is normal behavior of server_login_retry pgbouncer setting. It is enabled by default to avoid spamming database with connection errors due incorrect credentials.
Root cause here is trying connect first. Pgbouncer [will not retry too fast.](https://github.com/pgbouncer/pgbouncer/blob/master/src/objects.c#L1123)

If you set server_login_retry to 0 - second psql call in such testcase will successfully connect.

**Comment by aek** [comment]
I have tested without using pgboucer port(directly against PostgreSQL server) and I don't get any issue connecting to newly created databases. Even without a wait time works as expected 
```bash
createdb --port 5432 testdb; sleep 3s; psql --port 5432 testdb
createdb --port 5432 testdb; psql --port 5432 testdb
```

**Comment by petere** [comment]
Oh yeah, if you are trying to connect to the database before it exists, you get an error and then you are subject to `server_login_retry`. That's working as designed.

**Comment by aek** [comment]
That's not the case. I first create the database and after that I try to connect to that database without luck
