### ISSUE TITLE
Client goes out of sync when pgbouncer returns ReadyForQuery for CancelRequest 

### ISSUE THREAD

**Issue by cpatru** [pgbouncer/pgbouncer#141]
What I observed is that sometimes clients get out of sync and start reading the result of the previous query. This doesn't happen deterministically but it's roughly this sequence:

```
    1. A query will timeout.
    2. A cancel request is sent due to timeout.
    3. The query eventually completes.
    4. A new query is send and the response is a plain `ReadyForQuery` (result is not there).
    5. The next query receives the result of the previous query.
```

I wrote [this java console app](https://github.com/cpatru/pgbouncer-check) that can reproduce the issue. However, I couldn't get it to fail with local pgbouncer and postgres. It's only reproducing when pgbouncer and postgres are on separate boxes with arround 0.3ms latency. 

This is what the client, using pgjdbc, is reading off the buffer (left). You can see the `ReadyForQuery` being received in the middle of a query being executed, as a result of the `CancelRequest` (sent on a separate connection). On the right, is what pgbouncer is observing.

![pgbouncer_readyforquery](https://cloud.githubusercontent.com/assets/6660918/17589004/2b39feb2-5fca-11e6-8407-a3670700615e.jpg)

This only happening when hitting pgbouncer. It didn't repro when connecting to postgres directly.

`CancelRequests` are sent through a separate connection on the client. Pgbouncer handles them by trying to find the original connection that the `CancelRequest` is referring to and then it might decide to send a `ReadyForQuery` message on that connection. It only does this if it considers that client connection [not linked](https://github.com/pgbouncer/pgbouncer/blob/fdf5b8ea95fb0489ec6569df4b23c7c4b218ee79/src/objects.c#L1295).

I find the behaviour pgbouncer exhibits for `CancelRequest` not inline with the postgres protocol [documentation](https://www.postgresql.org/docs/9.1/static/protocol-flow.html) and may be breaking the correctness of the protocol.

I've commented [this line](https://github.com/pgbouncer/pgbouncer/blob/fdf5b8ea95fb0489ec6569df4b23c7c4b218ee79/src/objects.c#L1295) in pgbouncer and the problem went away. 

So it is a race condition that's making pgbouncer think that the client connection is [not linked](https://github.com/pgbouncer/pgbouncer/blob/fdf5b8ea95fb0489ec6569df4b23c7c4b218ee79/src/objects.c#L1282) as shown in this diagram.

![pgbouncer_cancel_request_flow](https://cloud.githubusercontent.com/assets/6660918/17588411/8c10dc46-5fc6-11e6-9f91-efaece58b586.jpg)

It became more clear that this has been a problem in the past when I saw [this fix](https://github.com/pgbouncer/pgbouncer/pull/6). But now I realise that it only fixed the problem for a subset of cases where the clients were lucky enough to have their message received by pgbouncer. All other cases where the request has been sent by the client but not received the pgbouncer are still broken. And I think this problem cannot be fixed.

The question is, why was this behaviour introduced and what is it trying to optimise?

**Comment by cpatru** [comment]
Here's the PR with the fix. @markokr 

https://github.com/pgbouncer/pgbouncer/pull/147

**Comment by PJMODOS** [comment]
Merged the patch, thanks!
