### ISSUE TITLE
Enable sslcompression with pgbouncer.

### ISSUE THREAD

**Issue by jlove73071** [pgbouncer/pgbouncer#145]
tried doing something like

```
host=myDatabase.com sslcompression=1
```

but it's not working. 
My setup uses pgbouncer as a unix socket to connect to a pg database on RDS to provide pooling for my db server. I see options to enable server tls/ssl, but no idea how to enable compression.

Note: My app connects directly to pgBouncer using login/pass/dbname over unix socket.

I want the pgbouncer's connections to the DB to be compressed. The sslcompression connection parameter appears to be unrecognized.

**Comment by PJMODOS** [comment]
World is moving away from ssl compression (TLS 1.3 removes support for it) due to concerns about security, I don't think it's worthwhile to add it to pgbouncer.

**Comment by jlove73071** [comment]
Seems like the baby is being thrown out with the bath water. Too bad PG doesn't natively implement compression without having to resort to this. The sad thing is that I'm using this all within the confines of a private subnet on AWS, would just like to reduce my bandwidth costs.

**Comment by jlove73071** [comment]
Would this not be trivial to implement just to maintain PG feature parity.

**Comment by markokr** [comment]
I know about the problems with compression but also about benefits for db connections.  So I would not mind supporting it as long it's supported by postgres, in off-by-default state.

But looking around I see following details:
- Compression is not supported by TLS1.3 (does not matter much, it takes 5-10 years until this is commonplace)
- Debian/Ubuntu ships libssl with support for libz compiled out.
- Centos(redhat too?) has compression of by default, needs to be turned on with env var
- OpenSSL 1.1 has compression off by default, needs to be enabled by app
- Postgres server does not configure compression (I guess it assumes its on-by-default in libssl)
- libpq can only turn off compression.

So it does not seem it's even supported by Postgres anymore.  It does seem it's not worth bothering anymore.

**Comment by GreenReaper** [comment]
[I filed a bug](http://www.postgresql-archive.org/BUG-14686-OpenSSL-1-1-0-breaks-PostgreSQL-s-sslcompression-assumption-defaults-to-SSL-OP-NO-COMPRESSN-td5964612.html) requesting that PostgreSQL actually do what it says it does w.r.t. the sslcompression parameter.

I included details of how to re-compile with it enabled and on by default on Debian. Here it provides a ~65% reduction in replication. Even if it's non-repetitive but large queries, there's compressible stuff in the protocol.

If the platform supports it by default, I suspect pgbouncer will by default as well over an SSL connection. If sslcompression is implemented here, I urge doing clearing the no-compression flag if the admin asks you to.

**Comment by petere** [comment]
SSL compression is now turned off in PostgreSQL, and TLSv1.3 is being adopted rapidly, so I think adding sslcompression to pgbouncer is now well and truly a lost cause. I'm closing this request. The focus should be on adding compression to the PostgreSQL protocol natively.

**Comment by GreenReaper** [comment]
We haven't seen native compression yet, and I wasn't willing to wait, so I forced it to work through environment overrides. 😼

[You probably need re-compile OpenSSL to re-enable use of zlib](https://www.percona.com/blog/2020/02/13/compression-of-postgresql-wal-archives-becoming-more-important/#comment-10971814); the comment system there chewed up my enabling patch:
```
--- ssl/ssl_lib.c.orig  2018-10-31 22:21:50.935869494 +0100
+++ ssl/ssl_lib.c       2018-10-31 22:27:10.055866781 +0100
@@ -3012,7 +3012,7 @@
      * middlebox compatibility by default. This may be disabled by default in
      * a later OpenSSL version.
      */
-    ret->options |= SSL_OP_NO_COMPRESSION | SSL_OP_ENABLE_MIDDLEBOX_COMPAT;
+    ret->options |= SSL_OP_ENABLE_MIDDLEBOX_COMPAT;

     ret->ext.status_type = TLSEXT_STATUSTYPE_nothing;

```
This won't do much unless you also link with zlib-dynamic (vs. no-zlib), which is usually in package configuration (e.g. `debian/rules`). Modified packages must be installed at both ends of the connection.

Then, set `OPENSSL_CONF` in the server and pgbouncer's environment:
> nano /etc/postgresql/12/main/environment
```
PGSSLCOMPRESSION = 1
OPENSSL_CONF = '/etc/postgresql/12/main/openssl.conf'
```

> systemctl edit pgbouncer

```
[Service]
Environment="OPENSSL_CONF=/etc/postgresql/12/main/openssl.conf"
```

Where `/etc/postgresql/12/main/openssl.conf` (or a similar file) is:
```
openssl_conf = default_conf

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.2
MaxProtocol = TLSv1.2
Compression = On
```

After all this, you should be able to make a connection and have it work. Set `log_connections = on` for the server and check to see:
```
LOG:  connection authorized: user=XXX database=XXX SSL enabled
(protocol=TLSv1.2, cipher=DHE-RSA-AES256-GCM-SHA384, bits=256, compression=on)
```

I just tried it on PostgreSQL 13 and it still works. For consistency, you'll probably also want `server_tls_protocols = tlsv1.2`.
You *cannot* set `server_tls_ciphers` or compression breaks (this happens with `ssl_ciphers` on the actual server too).

Obviously not everyone wants to recompile OpenSSL or override their server and client SSL compression settings, but it can be done. If you're considering this, bear in mind the maintenance burden, and that compression results in single-threaded CPU usage on the postmaster and client. For me, this limited bandwidth to ~45Mbps (but this can be equivalent to ~150Mbps uncompressed).
