### ISSUE TITLE
[Question] How to use a non superuser as auth_user

### ISSUE THREAD

**Issue by lirao** [pgbouncer/pgbouncer#149]
I'm trying to set up pgbouncer with auth_user and auth_query.
Setting just auth_user works perfectly fine, but overriding the auth_query parameter just doesn't work with a function just doesn't work, even though the docs suggest using a "non-admin user that calls SECURITY DEFINER fuction".
I've used the following query
```
create or replace function user_search(uname TEXT) returns table(uname name, pass text)
as $$ SELECT usename, passwd FROM pg_shadow WHERE usename=$1  $$ 
language sql SECURITY DEFINER;
```
with `auth_query = select user_search($1)` in the config file. 

Trying to login through pgbouncer with a user that's not on users.txt gave a `psql: ERROR:  unexpected response from login query`, and the verbose=2 logs showed that the return code is `S: pkt 'E', len=206`.

I don't even get prompted to type in my password, so I'm not sure what login is failing here. Is it the auth_user login? 

I've verified that my auth_query is usable when logged in as my auth_user.

Tried the example query from https://pgbouncer.github.io/config.html, and that also didn't work.

Did I set up anything wrong? Is my return format wrong? I tried tweaking the query and function around but none of my attempts worked... 

Would be great if the example config could also show the auth_query parameter that corresponds to the function creation statement!

pgbouncer version: 1.7.2
postgres version: 9.5.4 
OSX

**Comment by lirao** [comment]
Update: doesn't seem to be a problem with the auth_query, seems to be the non admin user auth_user that I have... What grants does this user need to have other than executing the function?

**Comment by lirao** [comment]
so far:
auth_query is a function + auth_user is not superuser (has access to function) = NO
auth_query is a select + auth_user is not superuser (granted access to pg_shadow/pg_authid) = NO
auth_query is a function + auth_user is a superuser = NO
auth_query is a select / default auth_query + auth_user is superuser = YES

**Comment by lirao** [comment]
Ok fixed it.
Heads up for the future people who tries to google this up:
REMEMBER TO CREATE THE FUNCTION IN YOUR TARGET DATABASE, NOT THE POSTGRES DATABASE

**Comment by markokr** [comment]
Added note to doc.

**Comment by edib** [comment]
why can not be something like that? : a dummy user that is registered in password.txt or pgbouncer.ini file can access the pg_shadow content  and get the password hash for every users who want to connect to the databases. Existing method (auth_file, and lirao's method) needs manual work.

**Comment by gridworkz** [comment]
I put my function in template1 db. Any time I create a new db it's there...
