### ISSUE TITLE
pgbouncer broken when accepting on port 6543 

### ISSUE THREAD

**Issue by sunf1re** [pgbouncer/pgbouncer#150]
on pgbouncer i have set it up on 8 different servers now all different flavors of linux and nothing will work i either get 
2016-10-12 14:51:49.945 27782 WARNING C-0x74d9a0: (nodb)/(nouser)@127.0.0.1:48680 Pooler Error: No such database: josh
2016-10-12 14:51:49.945 27782 LOG C-0x74d9a0: (nodb)/(nouser)@127.0.0.1:48680 login failed: db=josh user=postgres
in the logs or when i disable what user or db i am connecting to i get this:
psql: could not connect to server: Connection refused
    Is the server running on host "localhost" (127.0.0.1) and accepting
    TCP/IP connections on port 6543?

**Comment by petere** [comment]
We can't do much with this report without your complete configuration files and commands that you run.

**Comment by markokr** [comment]
Probably local config problem.  Closing.
