### ISSUE TITLE
No way to handle options passed in "options" connection parameter

### ISSUE THREAD

**Issue by nwp90** [pgbouncer/pgbouncer#152]
Unfortunately, PHP's pgsql connect() function seems to require that options such as `client_encoding` and `standard_conforming_strings` be passed within a single "options" parameter, which pgbouncer does not recognise (see http://php.net/manual/en/function.pg-connect.php).

So Moodle tries to pass client_encoding and standard_conforming_strings in a connection string like:

`host='localhost' port ='6432' user='myuser' password='password1' dbname='mydb' options='--client_encoding=utf8 --standard_conforming_strings=on'`

This could be worked around by setting `ignore_startup_parameters=options` in [pgbouncer] config and `client_encoding=utf8` and `standard_conforming_strings=on` in my [databases] config, but for the fact that pgbouncer doesn't recognise `standard_conforming_strings` as a valid option there either.

**Comment by markokr** [comment]
Well, libpq does not handle "standard_conforming_strings" as connect param either...

I don't want pgbouncer to get too deep into default settings business, esp. when DISCARD ALL and custom reset queries are thrown into mix.   Just set sane defaults in server and then use ignore_startup_parameters for stupid clients.

Esp. the "options" means the app/driver really wants to talk to actual postgres and nothing else.  I'm really unsymphatetic to such usage, Pgbouncer task is not to emulate all historical PostgreSQL quirks.  Just don't use pgbouncer for such apps.

Btw, is it actually safe to just override stdstr setting in one driver?  Lets say you have DB functions that have been written with stdstr=off in mind.  Won't they break if some driver just sets stdstr=on?

And app overriding it is one thing, but driver?  That feels wrong.  Driver is supposed to know stdstr setting (it's sent automatically by server) and then take account of it when generating queries.
