### ISSUE TITLE
Will PgBouncer reuse postgresql session sequence cache?

### ISSUE THREAD

**Issue by nitzanav** [pgbouncer/pgbouncer#158]
Hi,

I have a question that I [posted in stackoverflow](http://stackoverflow.com/questions/40315131) and got no response, I thought to try my luck here :)

I want to use postgres sequence with cache `CREATE SEQUENCE serial CACHE 100`.
The goal is to improve performance of 3000 usages per second of `SELECT nextval('serial');` by ~500 connection/application threads concurrently.

The issue is that I am doing intensive autoscaling and connections will be disconnected and reconnected occasionally leaving "holes" of unused ids in the sequence each time a connection is disconnected.

My question is: will the transaction pool mode of pgBouncer solve the "holes" issues that I described, will it reuse the session in a way that the next application connection will take this session from the pool and continue using the cache of the sequence? If not, which mode can solve this issue?

**Comment by petere** [comment]
answered on SO

**Comment by markokr** [comment]
Indeed.  Also note that seqs are supposed to have holes by default on some level and your app should survive this.

**Comment by nitzanav** [comment]
Thank you guys
