### ISSUE TITLE
Unable to configure Pgbouncer to connect to same database name in different hosts. 

### ISSUE THREAD

**Issue by rnovo-carecloud** [pgbouncer/pgbouncer#160]
Hello, I have multiple read replicas of the same database in different hosts.  But I have been unable to make the configuration work as it fails pulling the database if the connection name has a different name than the database :

this works : **dbA** = host=192.x.x.x port=5432 dbname=**dbA** user=user1

but this does not : 

Ex 
[databases]
;;; HOST 1
host1_db1 = host=192.x.x.1 port=5432 dbname=dbA user=user1
host1_db2 = host=192.x.x.1 port=5432 dbname=dbB user=user1
;;; HOST 2
host2_db1 = host=192.x.x.2 port=5432 dbname=dbA user=user1
host2_db2 = host=192.x.x.2 port=5432 dbname=dbB user=user1
;;; HOST 3
host3_db1 = host=192.x.x.3 port=5432 dbname=dbA user=user1
host3_db2 = host=192.x.x.3 port=5432 dbname=dbB user=user1

there is any way that this can be done using pgbouncer?.

**Comment by petere** [comment]
What do you mean by it doesn't work? This is a pretty standard configuration.

**Comment by markokr** [comment]
Unlikely to be pgbouncer problem.

If it is, and there is reproducible testcase then please reopen the bug.
