### ISSUE TITLE
Feature request: Per-user configuration of pool size

### ISSUE THREAD

**Issue by stevenwinfield** [pgbouncer/pgbouncer#166]
Hi,

We use pgbouncer in our production systems and on the whole we've been extremely pleased with it, though one feature we feel is missing is the ability to configure pool_size and reserve_pool_size on a per-user (or per-database/per-user) basis.

As many others have commented in similar feature requests, we have a small number of users (some automated) who need to use a lot of connections, and that is normal behaviour, but at the same time we would like to limit the pool size for other users.

Currently our options are to set the maximum number of connections for each user database-side, but then we lose pgbouncer's reserve pool behaviour, or set up more pgbouncer instances pointing at the same databases but with different pool sizes, but then the proper allocation of resources between these instances and managing their co-operation becomes cumbersome.

I imagine being able to add something like the following to the config file:
``[users]``
``username = default_pool_size=N reserve_pool_size=M ...``
...which would override the per-database settings, or allow new sections to be added to the config file:
``[databasename/users]``
``username = pool_size=N reserve_pool_size=M ...``
...to specify the pool sizes for <username> in database <databasename>.

Is this possible?

Best regards,
Steven.

**Comment by topharley** [comment]
You can use following syntax:

```
[databases]
yourdb = host=localhost port=5432 dbname=yourdb auth_user=postgres pool_size=200
yourdb_20_pool_size = host=localhost port=5432 dbname=yourdb auth_user=postgres pool_size=20 reserve_pool=20```

As you can see we add FAKE database "yourdb_20_pool_size" that is pointed to your real "yourdb" database using dbname=. And now we can override pool_size/reserve_pool. Of course we'll have to change our connection string for that user, change dbname "yourdb" to "yourdb_20_pool_size", but often int's not a big deal.

**Comment by notEpsilon** [comment]
Any plans for this?

**Comment by andruche** [comment]
Looks like this feature was added in issue #911
