### ISSUE TITLE
Feature request: Give client application_name in SHOW CLIENTS output

### ISSUE THREAD

**Issue by stevenwinfield** [pgbouncer/pgbouncer#167]
Pgbouncer sets the application name on the server connection when it is linked to a client, but there is currently no way to see the application names for all connected clients - particularly those that are idle or waiting for a server connection.

Thanks,
Steven.

**Comment by markokr** [comment]
Sounds like a good idea.

**Comment by ergdev** [comment]
I would love this too

**Comment by sribe-drw** [comment]
I'd like to +1 this; consider the case where apps are behind NAT (perhaps in K8s), and an app is leaking connections. There's no good way to find the culprit, but if SHOW CLIENTS would show us application_name, it would be trivial.
