### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by IvanVergiliev** [pgbouncer/pgbouncer#170]
I was wondering if a new version could be released? We'd like to use some of the new improvements, but I'd prefer not to build our own version if possible. Given that there have been no new releases for the past 10 months or so, is now a good time for one?

We're mostly interested in the deb packages.

**Comment by markokr** [comment]
I'm active again and slowly processing through backlog, I aim to release  in Jab/Feb merging all pullreqs/bugfixes that are mostly ready and don't need too much additional work

**Comment by julrodriguez** [comment]
@markokr ; thank you. would it be a notification informing the new release?

**Comment by darix** [comment]
So we are in april and 1.7.2 is still the last release. any thing left you want to fix before a new release?

**Comment by tehdiplomat** [comment]
Is there any update on this? I know the project is pretty stable, but it's been a long time since there's been a release.

**Comment by cb2109** [comment]
Also when you release do you have any influence over when the guys at EDB postgres pull your version into theirs? The fixes for the Windows bug "Fixed issue #161 unable to connect to EDB-PostGreSQL" would be really nice to have and compiling this sort of program on Windows is an (unavoidable) headache.

**Comment by petere** [comment]
new release is out
