### ISSUE TITLE
server_lifetime question

### ISSUE THREAD

**Issue by albertocsm** [pgbouncer/pgbouncer#172]
shouldn't a server connection be closed as soon as  **_now_ - _request_time_** > the value configured in **_server_lifetime_** ?

using _SHOW SERVERS;_ what i'm seeing is server connections being kept open indefinitely
pGBouncer logs dont show any trace of connections trying to be killed

I'm running  pgBouncer 1.7.2 in gliderlabs/alpine:3.2

are my expectations wrong?
might the OS be causing a miss behavior?

thks

**Comment by markokr** [comment]
I think you mean connect_time?

And no, the disconnects due to server_lifetime are deliberately throttled to avoid weird peaks when lots of connections are closed at the same time.

**Comment by albertocsm** [comment]
OK. Thks!
