### ISSUE TITLE
Issues connecting with Excel ODBC

### ISSUE THREAD

**Issue by ajlinux** [pgbouncer/pgbouncer#173]
Hi

I have recently installed PGBouncer 1.7.2-1.pgdg14.04+1 on my Postgresql 9.4 Server and all is working well with PGAdmin and other connections in code.  However when I use Excel 2016:

I get the following connection errors:

Unsupported startup parameter: extra_float_digits

Made a change to the pgbouncer.ini:

ignore_startup_parameters = extra_float_digits

Then get a new version of the error talking about geqo, which I believe I can also eliminate using:

ignore_startup_parameters = extra_float_digits, geqo

However I am not sure whether the above works at all - whether I should be using or not.  Using the geqo ignore param seems not to be a good idea as this is the query optimiser.

Should I be changing these parameters elsewhere instead?

Thanks in advance for your help

**Comment by Nayre** [comment]
Hello :)
experiencing same issue (server and bouncer versions are the same)
can I please ask for an extended version of how ignore_startup_parameter config line :) and advise on best practice to sort it out?

Thanks in advance!

**Comment by markokr** [comment]
There are few parameters that pgbouncer can accept during startup and guarantee valid setting during client connection.  For all the rest it rejects connection unless the parameter is mentioned in ignore_startup_parameters.

So you should add params to ignore list but also check if the parameter value is actually important to connecting app, then set it in postgresql.conf or per-user settings.

**Comment by Nayre** [comment]
Thanks for quick reply! 

I know that: client_encoding, datestyle, timezone and standard_conforming_strings are the ones accepted, but - what will happen if we add peqo to the ignored parameters list? 
Will it be disabled for all the connections at pgbounce's ports? Trying to understand what ignoring startup parameters means :) 'Let them go without pgbouncer worrying' or 'Disable that stuff' - thinking about all clients working without peqo query adjustments (a bit worrying vision :P) 
I'm guessing it's the answer is here, in documentation: "pgbouncer knows that they are handled by admin and it can ignore them" but I'm looking for confirmation :)

Warmest!

**Comment by markokr** [comment]
If pgadmin sets geqo on starup and its not ignored, it gets error.

IOW, client that sets geqo in startup packet can only connect throuth pgbouncer if that parameter is in ignore list.

**Comment by Nayre** [comment]
Righto, meaning I should be safe and sound if I'll go with: 

` ignore_startup_parameters = geqo, extra_float_digits ` ... & this will allow Excel connections in o/ 

Though, all my pgAdmin connections had no issues- maybe it's because geqo is True as default and there's no need to parse any weird arguments while connecting from good old pgAdmin? 

Thanks!

**Comment by markokr** [comment]
Yeah, pgadmin simply does not set any weird params in startup.

Closing.
