### ISSUE TITLE
Check pgbouncer settings and idle session timeout

### ISSUE THREAD

**Issue by ajlinux** [pgbouncer/pgbouncer#175]
Hi

Was wondering if you could help:

- Using PGBouncer and wanted to check whether in session mode if default_pool_size and max_client_connections are supposed to be set the same, i.e. both set to 120?

- Also I am having a problem that not all my idle connections seem to close down after the 10 mins.  I have set for server_idle_timeout to (600 secs)  This issue seems to be the most common with PGAdmin connections (but that could be a red herring)

- In order to solve the above I read an article which seemed to indicate to set min_pool_size to enabled and to a value of 10.  When I did this and re-loaded the config - no one could connect to my db at all.  Could you explain why, as I thought the setting meant it would always add 10 connections to my pool if they were needed, so I could have 130 rather than 120?

- To kill crashed PgAdmin sessions - should I enable - client_idle_timeout and set a timeout of say 5 minutes.  Or will this kill PgAdmin every 5 mins - which is not the behaviour I would like

Any help you can offer would be great.

Thanks

**Comment by Nayre** [comment]
Hi Arron & all :)

By max_client_connections, do you mean max_user_connections or max_client_conn? 
Some config settings from General section are overriden with Databsae part: i.e. default_pool_size is ignored if there's setting for max_db_connections (in db section of config file).

Dear pgBouncing devs ^^ Can you perhaps recall if there's any other settings which could mess up connection numbers or is it just:

**[pgbouncer]**
reserve_pool_size
max_db_connections
max_user_connections (all 3 in general config section)

**[databases]**
pool_size
max_db_connections

I'd much, much appreciate info as well, interesting questions, this :)
________________________

"set min_pool_size to enabled and to a value of 10. When I did this and re-loaded the config - no one could connect to my db at all" - I think that setting should only have effect if there's < 10 connections? Unfortuantely I can't currently reproduce this :( 

Thanks in advance for all your support dev team ^^'
Warmest & looking forward to learn more about your cool project!

**Comment by petere** [comment]
> * Using PGBouncer and wanted to check whether in session mode if default_pool_size and max_client_connections are supposed to be set the same, i.e. both set to 120?

Usually not, but it depends on what you want the behavior of your system to be if the number of configured connections are exceeded.

> * Also I am having a problem that not all my idle connections seem to close down after the 10 mins.  I have set for server_idle_timeout to (600 secs)

That would explain it then.

> * In order to solve the above I read an article which seemed to indicate to set min_pool_size to enabled and to a value of 10.  When I did this and re-loaded the config - no one could connect to my db at all.  Could you explain why, as I thought the setting meant it would always add 10 connections to my pool if they were needed, so I could have 130 rather than 120?

No, the `min_pool_size` just sets how many from your `pool_size` are preallocated.

> * To kill crashed PgAdmin sessions - should I enable - client_idle_timeout and set a timeout of say 5 minutes.  Or will this kill PgAdmin every 5 mins - which is not the behaviour I would like

TCP keepalive is typically the best way to deal with client programs disappearing abruptly.
