### ISSUE TITLE
Make pgbouncer multithreading

### ISSUE THREAD

**Issue by anioool** [pgbouncer/pgbouncer#179]
Hi,

Is it possible to allow pgbouncer use more than 1 CPU? I observe that always one CPU is loaded with pgbouncer.

Second question: Is there any specific network limit for pgbouncer? I am not able to get more than 1Gbps (140 MBps).

Thanks!

**Comment by eulerto** [comment]
@anioool pgbouncer is single process. Are you observing a CPU-bound scenario?
AFAIK there isn't network limit in pgbouncer code. Maybe you are bounded by what postgres could deliver. Did you do tests with and without pgbouncer? If you strace pgbouncer you will notice that most of its time is wasted on sendto and recvfrom calls (it means that it is maximizing the communication).

**Comment by anioool** [comment]
@eulerto I saw big correlation that cpu used by pgbouncer is being busy once througput is high. The bottleneck appears once I reach 1 Gbps (it is not a limit for instance on which pgbouncer is running). CPU during that time is above 80 %.

**Comment by eulerto** [comment]
@anioool What is your OS? Does it prepared (tuned) to support more than 1Gbps? Are your hardware and infra prepared to support more than 1Gbps? Could you share some profiling output (perf, oprofile, ...) while observing the bottleneck?

**Comment by cxmcc** [comment]
Yes we have observed CPU bound situations. Especially after enabling verbose logging.

**Comment by petere** [comment]
This is more of a usage/tuning discussion, not a software bug.
