### ISSUE TITLE
auth_query does not check if role is expired

### ISSUE THREAD

**Issue by lonepsycho** [pgbouncer/pgbouncer#181]
roles in postgresql does have expiration date/time, and it would be nice, if pgbouncer would follow that and auth_query in main.c file would be changed to `SELECT usename, passwd FROM pg_shadow WHERE usename=$1 AND (valuntil IS NULL OR valuntil > now())` so roles that are expired would not "ping" database anymore.

**Comment by PJMODOS** [comment]
Given that it's configurable and the default is mainly sup

**Comment by Talkless** [comment]
> I think it's not needed to change.

![Image](https://github.com/user-attachments/assets/3b1ab899-38de-49a0-b227-b5189e6e40b5)

https://github.com/pgbouncer/pgbouncer/commit/9912ee7f1af2e1b81d4d624a0da1cb49075ee78a

:-)
