### ISSUE TITLE
LDAP integration from the Greenplum fork

### ISSUE THREAD

**Issue by yazun** [pgbouncer/pgbouncer#185]
Would it be possible to integrate Greenplum patch (from 2 years ago) for LDAP?

There was already a request for this https://github.com/pgbouncer/pgbouncer/issues/11

The patch from their fork is here:

https://github.com/greenplum-db/pgbouncer/commit/080f47d0bddb776af6e8711a267f716dffd49189

and looks clean at the first sight.
Thanks

**Comment by svb007** [comment]
That would be great, as it is exactly what I've been looking for.  How easy/difficult is it to apply this fork to the current 1.7.2 source?

**Comment by petere** [comment]
I don't know ... that code says `Copyright (c) 2015 Pivotal Inc. All Rights Reserved`.

**Comment by petere** [comment]
The Greenplum code doesn't seem to be in a shape that's appropriate to integrate into PgBouncer. LDAP support would probably be welcome, but someone would have to think carefully about how to do it.
