### ISSUE TITLE
pgbouncer bytes sent/received details

### ISSUE THREAD

**Issue by saifulmuhajir** [pgbouncer/pgbouncer#186]
Is there any way that we can monitor network details of pgbouncer? I have one host that the number of bytes sent and received is way higher than other hosts. This particular host has average of bytes sent 5MiB/s while the other hosts has 90KiB/s in average.

Postgres version: 9.4
pgbouncer version: 1.5.4

Does this feature available in the newest version? Or is there other way I can find out the root cause?

**Comment by eulerto** [comment]
@saifulmuhajir 'show stats' connected in the pgbouncer database (see total_received and total_sent columns). Your user should be listed in stats_users parameter. Also, these statistics are lost when service is stopped.
