### ISSUE TITLE
Support failover between multiple upstream servers for the same database

### ISSUE THREAD

**Issue by lithp** [pgbouncer/pgbouncer#187]
[The documentation](https://pgbouncer.github.io/faq.html#how-to-failover) suggests some workarounds, such as updating the configuration and sending a `SIGHUP`. This works, but is unfortunate in that it requires an additional daemon which also needs to be monitored.

I think what needs to be done is:
- Change the config file format:
  - allow there to be multiple databases with the same name, currently last-write-wins
  - add some keys for failure checking such as the number of checks a server must fail before it's considered dead, the number of checks it must pass before it's considered alive, and the timeout between each failure check.
- Add some process which, while failure checking is enabled, periodically connects to the upstream servers and runs a query to check for reachability. 
  - If a server is down, it prevents the associated PgPool from being used. (Possibly by reordering pool_list, or toggling a "usable" flag PgPool which get_pool looks for)
  - also re-enables servers when they come back online.
  - This could be added to the janitor or a separate function which happens on an evtimer
  - I mean "process" in a very loose sense, this logic is a little complicated because you don't want to block the loop while waiting for a response

How open would you be to a PR which did this? If you're open to merging something which does this, what do you think the best approach is?

**Comment by PJMODOS** [comment]
The libpq now (in PG10 dev branch) has support for specifying different hosts and session attributes (if it needs writes or is okay with read-only) in the connection string. Maybe we should add support for that first instead of changing the config file format.

The behaviour of libpq is that if first host does not succeed it tries next one in the list. That would solve what you want as well I think? (plus the code might be mostly reused from libpq).
We could improve this behaviour by reordering the host list internally so that the one that was available last time will be picked as first next time. Then no background "process" is needed.

**Comment by PJMODOS** [comment]
I am happy to review/merge PR in this area.

**Comment by lithp** [comment]
Wow, appreciate the quick response!

The new `libpq` behavior is nice, and I like the idea of reordering the host list. I think the new libpg slows down every connection when the first node fails; when the first host is down it'll continuously fail/timeout connecting before trying to use the second host. Reordering fixes that nicely.

There's a little additional logic I'd like to add. My use-case is quickly failing over from a primary to a secondary. For that case it's not enough that we can connect, it's also important to run `SHOW transaction_read_only` and make sure the secondary has been promoted before failing over to it. For that, maybe adding an equivalent of  `server_reset_query` makes sense?

If a connection attempt has failed, or some number of connection attempts, it tries to connect to the second host, runs `server_usable_query`, and then reorders the hostnames.

Although now that I've written that out maybe it's a bad idea because it overloads the multiple host behavior. It will mean one thing in libpq and a different thing in pgbouncer.

**Comment by PJMODOS** [comment]
Well if you just care about read-only vs read-write then libpq now also has `target_session_attrs` parameter in connection string (see bottom of https://www.postgresql.org/docs/devel/static/libpq-connect.html page).

So maybe that's enough for a start. It's true that I can imagine some additional `server_usable_query` being needed eventually, but let's not overcomplicate things for the initial patch ;).

**Comment by lithp** [comment]
Just looked at the devel psql and the session attributes you alluded to. Adding support for `target_session_attrs` makes a lot of sense, more than `server_reset_query`.

**Comment by lithp** [comment]
Once again, appreciate the quick response and the advice. This looks like it'll take a little more of my time than I have available so I'm going with the external process approach. Hoping I'll be able to come back in a month or two with a PR for you.
