### ISSUE TITLE
PAM support when auth_type = hba

### ISSUE THREAD

**Issue by svb007** [pgbouncer/pgbouncer#193]
I needed this because it allows me to phase in PAM authentication from trust based authentication, and the attached patch did exactly what I needed. Is there any chance that you could make this change in git?

[pam_hba.patch.txt](https://github.com/pgbouncer/pgbouncer/files/857004/pam_hba.patch.txt)

**Comment by petere** [comment]
See PR #326 for ongoing discussion about this feature.

I'm going to close this issue, since attaching a patch file to an issue is not really the right way to discuss a patch.
