### ISSUE TITLE
Unable to connect using unix socket with 'server_tls_sslmode=verify-ca'

### ISSUE THREAD

**Issue by internetionals** [pgbouncer/pgbouncer#207]
We have pgbouncer that connects to multiple database (both locally and across the network) and we were relying on 'stunnel' for the forwarding of the secure connections. We recently upgraded to version 1.7.2 of pgbouncer and noticed it has native TLS support.

However requiring server certificate validation causes connections to the local database-server to be unable to connect.

Having the option to set the 'server_tls_sslmode' in the connect string for the specific databases would also be acceptable for our use case.

**Comment by petere** [comment]
This should be fixed in 1.8. Please check.
