### ISSUE TITLE
Does pgbouncer ignore ip address within pg_hba file?

### ISSUE THREAD

**Issue by dba-oncall** [pgbouncer/pgbouncer#216]
Even though I have auth_type set to hba, I can connect through the pgbouncer server from any ip address. It does validate the user but doesn't seem to validate ip address. Am I missing a configuration setting? Shouldn't it reject any connection attempts made from ip addresses that aren't white listed in the pb_hba.conf file?

pgbouncer config:
auth_type = hba
auth_file = /etc/pgbouncer/userlist.txt
auth_hba_file = /etc/pgbouncer/pg_hba.conf

**Comment by nilya** [comment]
@dba-oncall Attach the contents of your pg_hba.conf file.

**Comment by jkoceniak** [comment]
```
host    db1      user1           xx.xxx.xx.xxx/32        trust
host    db1      user2           xx.xxx.xxx.xx/32        trust
host    db1      user3           xx.xxx.xxx.xx/32        md5
local   all      all                                     trust
```

**Comment by gplv2** [comment]
This seems quite useless as contents in order for anyone else to assist.  You are probably hiding public IP addresses , which means your PGB is listening on public IP's, quite not done, a big nono too. You should probably mention the real IP addresses and the source IP you're connecting from if you want on topic help here on the subject.  I can with certainty state that in the 1.7.2 version of the bouncer software that this works perfectly.  In the case that your error is address related there is no other way for anyone here to help you, as you probably noticed by now.

**Comment by petere** [comment]
closing for lack of details
