### ISSUE TITLE
Cancellation causes unexpected ReadyForQuery to be sent in transaction mode

### ISSUE THREAD

**Issue by roji** [pgbouncer/pgbouncer#223]
Users of the Npgsql PostgreSQL driver have raised https://github.com/npgsql/npgsql/issues/1636, which I've tracked down to some problematic behavior on pgbouncer when cancellation and transaction pooling mode is involved.

To trigger the issue, set pgbouncer to transaction pooling mode, and then run statements, sending a cancel during/after each one. A C# code sample which reliably reproduces this [can be found here](https://github.com/npgsql/npgsql/issues/1636#issuecomment-317112549).

[Attached is a wireshark capture of the issue](https://github.com/pgbouncer/pgbouncer/files/1167287/UnexpectedReadyForQuery.zip) which clearly shows the problematic behavior. After an initial complex query which Npgsql issues for loading all types (and which is completely unrelated), you can see a packet containing P/B/D/E/S with the SQL `--command 0\n select 1`. The server responds correctly with the answer (1/2/T/D/C/Z).

At this point the client issues a cancellation, which of course occurs on another connection and port. Since no query is currently running, the cancellation is supposed to get ignored, or perhaps apply to the next command. Instead, an inexplicable ReadyForQuery is delivered on the primary connection, although nothing is running there (I'd have been less surprised to see a PostgreSQL error with code 57014). The next time a query is executed, this spurious ReadyForQuery is unexpected and protocol sync is broken.

Tested on Windows 10 with pgbouncer 1.7.1 running against a PostgreSQL 9.6.2, everything local on the same machine.

Thanks to @rafaelthca and @mausch for raising this.

**Comment by PJMODOS** [comment]
This should be fixed by 9bff5cae90c5c081c0a3044392362a49052782f2

**Comment by jcoleman** [comment]
@roji Can you confirm @PJMODOS's fix fixes this and close?

**Comment by roji** [comment]
@jcoleman @PJMODOS confirmed, I just tested with pgbouncer 1.9.0 and the same scenario which causes the problematic behavior on 1.7.1 now works perfectly fine. Thanks for the fix!
