### ISSUE TITLE
Connection read-only flag no reset

### ISSUE THREAD

**Issue by f0def** [pgbouncer/pgbouncer#224]
I use PgBouncer with `pool_mode=transaction` and `prepareThreshold=0`.
My application used Spring + Hibernate, but it is not necessary to repeat the problem.
Spring `org.springframework.data.jpa.repository.support.SimpleJpaRepository` mark `@Transactional(readOnly = true)` by default.

PgBouncer returns connection to PostgreSql from it's own pool. If one method in the application marked connection as `readOnly=true`. Another application can resolve from PgBouncer connection already marked as `readOnly`, but `java.sql.Connection.isReadOnly()` will always returns `false`. It does not know anything about it.

When people get a connection out of the pool, they do not need that it will be just for reading.

My test example will fall periodically. But if you change PgBouncer configuration, leaving only one connection `default_pool_size = 1`, then a single spoiled connection will not let anyone work.

```java
public class ReadOnlyTest {

  @Test
  public void start() {
    DataSource dataSource = postgresDataSource();

    try {
      for (int i = 0; i < 10; i++) {
        doo(dataSource);
      }
    } catch (SQLException e) {
      throw new RuntimeException("", e);
    }
  }

  private void doo(DataSource dataSource) throws SQLException {
    Connection con = DataSourceUtils.getConnection(dataSource);
    con.setReadOnly(true);
    DataSourceUtils.releaseConnection(con, dataSource);

    execute(dataSource, "create sequence if not exists sq_readonly");
    execute(dataSource, "drop sequence sq_readonly");
  }

  private void execute(DataSource dataSource, String sql) throws SQLException {
    Connection con = DataSourceUtils.getConnection(dataSource);
    //con.isReadOnly() always false, but really can be true
    Assert.isTrue(!con.isReadOnly(), "Connection is readonly");
    PreparedStatement ps = con.prepareStatement(sql);
    //org.postgresql.util.PSQLException: ERROR: cannot execute CREATE SEQUENCE in a read-only transaction
    //or
    //org.postgresql.util.PSQLException: ERROR: cannot execute DROP SEQUENCE in a read-only transaction
    ps.execute();
    ps.close();
    DataSourceUtils.releaseConnection(con, dataSource);
  }

  private DataSource postgresDataSource() {
    HikariConfig config = new HikariConfig();
    config.setDataSourceClassName("org.postgresql.ds.PGSimpleDataSource");

    String url = "jdbc:postgresql://pgbouncer-host:6543/test?prepareThreshold=0&preparedStatementCacheQueries=0&ApplicationName=readOnlyTest";

    config.addDataSourceProperty("url", url);
    config.addDataSourceProperty("user", "test");
    config.addDataSourceProperty("password", "test");
    config.setConnectionTestQuery("SELECT 1");
    config.setIdleTimeout(100);

    return new HikariDataSource(config);
  }
}
```

Tested on PgBouncer 1.7.2

**Comment by ToshaBritva** [comment]
same problem here

**Comment by rsaffi** [comment]
Same problem here too. By the way, how can we be sure this affects only Transaction Pooling?

**Comment by jamestenglish** [comment]
I am seeing the same problem? Does anyone have a solution yet?

**Comment by uspen** [comment]
I turned on session pooling

**Comment by dan-aksenov** [comment]
We have same problem.

**Comment by jamestenglish** [comment]
This does not appear to be a Pg Bouncer issue. I believe it is related to this issue with the Postgres JDBC Driver:
https://github.com/pgjdbc/pgjdbc/issues/848

In short the driver sets things on the session like: 
https://github.com/pgjdbc/pgjdbc/blob/master/pgjdbc/src/main/java/org/postgresql/jdbc/PgConnection.java#L699

Pg Bouncer expects a clean session in transaction mode. One work around which has thus far been working for us is to set: `server_reset_query_always = 1` when using transaction pooling. (Session pooling will always fire the reset query without override)

I say "thus far" because the Postgres JDBC Driver sets other things on the session too, see lines 838, 1501, 1504 and I am not sure what the consequences of clearing those other session states might be. We do pretty extensive testing on all our services and nothing else has blown up, but that might just be luck.

**Comment by cabecada** [comment]
we have had similar issues, and sadly but had to turn session pooling on.

**Comment by PJMODOS** [comment]
This is expected behaviour in transaction pooling mode. See https://pgbouncer.github.io/features.html (the read-only mode is set using `SET` command as @jamestenglish mentioned).

**Comment by alikhil** [comment]
What if we will set `server_reset_query_always = 1` and `server_reset_query = 'SET SESSION CHARACTERISTICS AS TRANSACTION READ WRITE'` ?

Since simply using `DISCARD ALL` may lead to performance degradation (according to the https://github.com/pgbouncer/pgbouncer/issues/110#issuecomment-182289389 )
