### ISSUE TITLE
pgbouncer accept wrong format numbers in config files

### ISSUE THREAD

**Issue by dbonne** [pgbouncer/pgbouncer#225]
Each integer configuration parameter loaded by pgbouncer can accept invalid strings as numbers:

Strings like 6o432 or 6_432 or 6___ are not detected as invalid by pgbouncer.

This is due to the use of the atoi function to convert the string to integer.

regards

**Comment by eulerto** [comment]
@dbonne you didn't inform which pgbouncer version and parameters you are observing this behavior. I tested version 1.7.2 with several integer parameters and always got a FATAL error.

**Comment by petere** [comment]
This was fixed in libusual/libusual@5c986914241a69683844fc01a465ed3c4e535399.
