### ISSUE TITLE
LDAP Integration proposal

### ISSUE THREAD

**Issue by nellaivijay** [pgbouncer/pgbouncer#230]
Hi,
I would like to propose the LDAPs authentication integration which is not yet integrated. Please refer the high level of flow diagram here(Pretty old architecture diagram which used the STunnel configuration ). I already tested in my local env around 4 years before.  Since the TLS/SSL feature enabled in the PGBouncer, Can I submit the pull request?
[PGBouncer v0.1 (005).pdf](https://github.com/pgbouncer/pgbouncer/files/1251474/PGBouncer.v0.1.005.pdf)

Thanks
Vijay

**Comment by petere** [comment]
Yes, send a pull request.
