### ISSUE TITLE
Why there is not pgbouncer release since Feb 2016

### ISSUE THREAD

**Issue by ahsanhadi** [pgbouncer/pgbouncer#236]
The last release of pgbouncer was in Feb 2016, i can see lots of commits after the last release but no github release since Feb 2016. Whats the reason for this?

**Comment by ChristophBerg** [comment]
Hi,
Debian would appreciate a new pgbouncer release - the current 1.7.2 supports openssl 1.0 only, but that version is being deprecated, so a release with openssl 1.1 support would be welcome.
Thanks!

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859551

**Comment by petere** [comment]
new release is out
