### ISSUE TITLE
Protocol level prepared statements

### ISSUE THREAD

**Issue by greenboxal** [pgbouncer/pgbouncer#242]
Is anyone working on that? If not, I'm interested in developing this feature.

**Comment by petere** [comment]
I'm not sure what you hope to get here. In the referenced bug it was discussed that transaction pool mode doesn't work with prepared statements but session pool mode does.

**Comment by kien-truong** [comment]
Am I right to presume Pgbouncer does not support Extended Query Protocol in Transaction Pool Mode due to the lack of this feature ?

**Comment by petere** [comment]
Extended query is supported in all pooling modes.

**Comment by JelteF** [comment]
Closing this because protocol-level prepared statements was merged in #845 and is now released in PgBouncer 1.21.0
