### ISSUE TITLE
Schema based multitenancy, search_path, transaction mode a possible solution

### ISSUE THREAD

**Issue by achix** [pgbouncer/pgbouncer#246]
Hello, just coming from https://github.com/pgbouncer/pgbouncer/pull/73 where the rational given to not accept the patch makes perfect sense. So I would like to propose something that :
- (sort of) would not break pgbouncer's simplicity
- would solve the problems that the specific patch failed to address
- would be more generic and solve more problems

In the general case, and specifically in schema-based multi-tenancy, app servers usually set the search_path, or set the application name, or do other initializations in the first SQL commands to be sent to the backend, most commonly in SQL that resides in some type of <new-connection-sql /> parameter of some datasource's definition.

What I propose is for pgbouncer to record and save in the client side connection's state the first keep_initial_stmts ( a small number) of SQL stmts sent, and replay them in each new server connection, same way pgbouncer handles application_name. Those statements are generic and could be any SQL stmt. The parsing would take place only on the initial phase of the first server connection. Subsequent server connections for the same client would simply replay the cached stmts. As in the patch of rabbit, only pool_mode=transaction would be supported.

The success of this is due to the fact that ppl who administer apps and app servers are usually the same ppl who manage pgsql. It is a simple contract that if kept with discipline would solve all the related problems and give transaction mode to much more situations, boosting pgsql's performance.

This approach IMHO, is well defined, does not leave points of doubt or corner cases, and would help the vast majority of ppl having such constraints with pgbouncer.

The obvious drawback, is the minimal one-time per client connection parsing that should be done.

What are your thoughts?

Thanx

**Comment by FreekingDean** [comment]
It seems to me that this was brought up & shot down in #73 . This is becoming more of an issue with the latest Security Update: https://www.postgresql.org/about/news/1834/ using `pg_dump` on a pg_bouncer instance will "fry" that session.
