### ISSUE TITLE
Build error on Fedora 27

### ISSUE THREAD

**Issue by devrimgunduz** [pgbouncer/pgbouncer#247]
Hi,

I cannot build pgbouncer on Fedora 27:

 `In file included from lib/usual/tls/tls.h:25:0,
                 from lib/usual/tls/tls_compat.h:5,
                 from lib/usual/tls/tls_util.c:19:
lib/usual/base.h:215:23: warning: this use of "defined" may not be portable [-Wexpansion-to-defined]
 #if _COMPILER_GNUC(4,0) || __has_attribute(warn_unused_result)
`

`ib/usual/tls/tls_verify.c: In function 'tls_check_subject_altname':
lib/usual/tls/tls_verify.c:124:5: warning: 'ASN1_STRING_data' is deprecated [-Wdeprecated-declarations]
     data = ASN1_STRING_data(altname->d.dNSName);
     ^~~~
In file included from /usr/include/openssl/opensslconf.h:42:0,
                 from /usr/include/openssl/bn.h:31,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from lib/usual/tls/tls_compat.h:14,
                 from lib/usual/tls/tls_verify.c:18:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
`

Not sure they have been fixed in git already, so reporting it. Do you consider a 1.7.3, btw?

**Comment by petere** [comment]
These are just warnings (that should be fixed). Why is the build failing?

**Comment by devrimgunduz** [comment]
Hi Peter,

This is the full log:

https://gist.github.com/devrimgunduz/dc0bd8fa05f23516c1df3af82da7a3c6


Regards, Devrim

**Comment by petere** [comment]
OK, the actual errors in that log are:

    lib/usual/tls/tls_ocsp.c:167:17: error: storage size of 'storectx' isn't known
    lib/usual/tls/tls_ocsp.c:168:14: error: storage size of 'tmpobj' isn't known

There have been SSL/TLS related updates in the master branch, so please try that.

**Comment by devrimgunduz** [comment]
Hi Peter,

git master works. Can we expect 1.7.3 (or whatever?)

Regards, Devrim

**Comment by darix** [comment]
OpenSSL 1.1 support would be nice indeed. the 2 errors are probably coming from building against 1.1

**Comment by petere** [comment]
Yes, I'm working toward a new release.

**Comment by petere** [comment]
new release is out
