### ISSUE TITLE
missing pam.h in 1.8 release tarball

### ISSUE THREAD

**Issue by darix** [pgbouncer/pgbouncer#261]
list of files that are in git but missing in the tarball:

```
./doc/todo.rst
./etc/optscan.sh
./etc/small.ini
./etc/test.ini
./etc/test.users
./include/pam.h
./.travis.yml
```

Maybe time for 1.8.1

**Comment by darix** [comment]
could it be that this should be a local file that is missing in the tarball?

**Comment by darix** [comment]
I pulled the master copy of pam.h. for my rpm. but a new release as 1.8.1 might be better.

**Comment by titanofold** [comment]
Compilation failed on Gentoo, as well.

pam.h is missing from the tarball.

**Comment by titanofold** [comment]
And trying to do `configure --without-pam` still results in it trying to include pam.h.

**Comment by titanofold** [comment]
And, now I see pam.c has its code wrapped  with an #ifdef HAVE_PAM.

**Comment by devrimgunduz** [comment]
Same on Fedora and Red Hat.

**Comment by devrimgunduz** [comment]
Can you please release 1.8.1?

**Comment by darix** [comment]
Please do a 1.8.1 release for this.
