### ISSUE TITLE
pgbouncer 1.8 : file missing ?

### ISSUE THREAD

**Issue by Pea13** [pgbouncer/pgbouncer#262]
Hi,

While building pgbouncer 1.8 on OpenBSD, i have the following error : 

===>  Building for pgbouncer-1.8
cc  -DHAVE_CONFIG_H -Iinclude -Ilib -I/usr/local/include  -O2 -pipe  -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wdeclaration-after-statement -Wold-style-definition -Wstrict-prototypes -Wundef -Wformat=2 -Wuninitialized -MD -MP -MT .objs/pgbouncer/src/admin.o -MF .objs/pgbouncer/src/admin.o.d -c -o .objs/pgbouncer/src/admin.o src/admin.c
In file included from src/admin.c:23:
include/bouncer.h:108:10: fatal error: 'pam.h' file not found
#include "pam.h"
         ^~~~~~~
1 error generated.

Of course, PAM is disabled on OpenBSD (with configure) : 

Results
  c-ares = no
  evdns = no
  udns = no
  tls = yes
  PAM = no

Is this file missing ?
Regards,

**Comment by Melkij** [comment]
Hi
Should be fixed a few hours ago in #261

**Comment by Pea13** [comment]
Oups sorry I missed this issue.
Thanks you.
