### ISSUE TITLE
psql: FATAL:  database "pgbouncer" does not exist 

### ISSUE THREAD

**Issue by danmbugua** [pgbouncer/pgbouncer#268]
Hey, 
I might have missed something.I have followed the documentation **https://pgbouncer.github.io/install.html** on how to install pgbouncer to the end but can't access the administrative database using **psql -p 6543 -U myuser pgbouncer**.

**Comment by petere** [comment]
You are probably connecting to some PostgreSQL database and not pgbouncer. Also, the default port is 6432.
