### ISSUE TITLE
sources of the connections

### ISSUE THREAD

**Issue by edib** [pgbouncer/pgbouncer#271]
We occasionally need that we have to find out long rurnning query source as an ip address, but all queries come from pgbouncer replace their original ip address with pgbouncer ip address. I have found a way that I get the pid of transaction in  pg_stat_activity, then search it in "show servers" output and get some number from the line and then search it in "show clients"output. It works but it is a really long run. Is there a way to get this information faster? 
And is there a "selecty" version of "show bla bla;" pgbouncer commands?

**Comment by Melkij** [comment]
Hello
Try using application_name_add_host setting. In this case pgbouncer will add client source address to application_name in pg_stat_activity.

**Comment by edib** [comment]
Thanks. super!
