### ISSUE TITLE
unencrypted to pgbouncer, client cert auth to postgresql

### ISSUE THREAD

**Issue by ttfkam** [pgbouncer/pgbouncer#272]
Can you connect to pgbouncer using plain auth or trust but have pgbouncer connect to the remote PostgreSQL database with client certificate authentication?

Is this possible? The docs are unclear. I see how you can cert auth to pgbouncer itself, but not in the scenario I described.

**Comment by ttfkam** [comment]
bump

**Comment by petere** [comment]
Yes, this is possible. Set `server_tls_sslmode = require` and related settings. This makes PgBouncer connect to the server using TLS. Client connections to PgBouncer are independent of this and may use any authentication and encryption setting you want.
