### ISSUE TITLE
Document settings that need Stop/Start, Online Restart or just Reloads..

### ISSUE THREAD

**Issue by diranged** [pgbouncer/pgbouncer#274]
It seems that different settings have different reload-requirement behaviors. Settings like `listen_addr` seem to require a full Stop/Start of the app, while other settings like `auth_file` can be reloaded with a simple HUP. None of this is documented though, making the automation of PGBouncer (in tools like Chef or Puppet) tricky.

**Comment by gplv2** [comment]
This could probably be implemented in the same way as it is in postgresql's pg_settings file if feasible inside pgbouncers code.
