### ISSUE TITLE
Proposed authentication mechanic 

### ISSUE THREAD

**Issue by evansd** [pgbouncer/pgbouncer#28]
I'm not very familiar with PgBouncer's internals, so please forgive me if this is a horribly naive question.

I understand that PgBbouncer needs some way to authenticate new connections without having to contact Postgres itself every time. But would it be possible for PgBouncer to use Postgres's authentication when establishing a new connection to the database and then store (in memory, not on disk) a hash of the credentials used. Subsequent authentication attempts could be checked against this hash without needing to contact Postgres.

This way, there's no need to configure authentication details in PgBouncer, but you still get the benefits of authentication over blindly trusting new connections.

Does that make sense?

**Comment by markokr** [comment]
Auth via database is released in 1.6rc1
