### ISSUE TITLE
Pgbouncer don't honor DB timezone but server timezone.

### ISSUE THREAD

**Issue by chaintng** [pgbouncer/pgbouncer#281]
My server has Japan timezone
I set Postgres DB to UTC
However, when i connect to Pgbouncer and run `SHOW timezone`, it still show Japan timezone (Server timezone)

I tried fix `timezone=UTC` in `[databases]` section of `pgbouncer.ini` file, but it still do not honor this value.

**Comment by gplv2** [comment]
few questions:

What version of pgbouncer ?
Where have you set the timezone of Postgres ? 
when you say : I connect to pgbouncer and run the show command, are you connecting to the internal pgbouncer database or to a real database on the psql server.

Can you post at least the relevant sections your postgresql.conf  and the full pgbouncer configuration.

I cannot reproduce this problem.

**Comment by chaintng** [comment]
I think i confuse with the wrong database. The timezone now show UTC in both db.

Thank you anyway
