### ISSUE TITLE
client_idle_timeout has no effect

### ISSUE THREAD

**Issue by cskr** [pgbouncer/pgbouncer#282]
Even when `client_idle_timeout` is set to a non-zero value, pgbouncer is neither disconnecting the client, not re-using the server connection for other clients. My client creates a connection, executes a single `SELECT` query and goes to sleep indefinitely.

My pgbouncer.ini:
```
[databases]
* = host=localhost

[pgbouncer]
listen_addr = *
auth_file = /home/cskr/pgusers.list
max_client_conn = 10000
default_pool_size = 25
autodb_idle_timeout = 60
server_idle_timeout = 60
client_idle_timeout = 30
ignore_startup_parameters = extra_float_digits
```
**Expected Behaviour:** 30 seconds after execution of the query, pgbouncer should close the client connection and re-use the server connection for subsequent clients.

**Actual Behaviour:** Neither the client connection is closed, nor the server connection is re-used for other clients. I tried setting `default_pool_size = 1`. In that case, the second client was blocked even after 30 seconds elapsed, until the first client's OS process was killed.

**Note:** I understand that the behaviour described above is an issue with how the client behaves, but I cannot fix the actual application doing this.

**Comment by cskr** [comment]
On further testing, it looks like the client connection is closed only if it never executed any query in its lifetime. However, if it executes even a single query before idling, it doesn't get closed.

Is this the intended behaviour? If so, can it be clarified in the documentation?

**Comment by petere** [comment]
A client is "idle" if it is not linked to a server. In session pooling mode, once you run the first query, the server will not be unlinked until you end the client session. If you use statement pooling mode, you will see the behavior you expect.

I'll see about clarifying the documentation on this.

**Comment by cskr** [comment]
Thanks for the clarification, @petere.

**Comment by qdw** [comment]
@petere is the session mode behavior you described (meant to be) true of server_idle_timeout as well?

(I have a pgbouncer in session pooling mode, and I want to disconnect server connections when they are idle for more than 15 seconds. But setting server_idle_timeout does not have this effect; connections can remain idle [even without issuing an initial query] indefinitely.)

Thanks!
