### ISSUE TITLE
md5 ignores pg_hba.conf of the postmaster

### ISSUE THREAD

**Issue by wibrt** [pgbouncer/pgbouncer#283]
Basis Setup:
* postgresql 10 cluster with pg_hba.conf allowing access to db1 for user1, no access to db2
* connecting on 5432: no access to db2 for user1, as expected
(* access db1 ok)

Pgbouncer:
* md5 auth, with auth_user set for password lookup
* connecting on 6432: access to db2 for user user1, which shouldn't happen?!
(* access db1 ok)

Can anyone confirm this?
Tested with 1.8.1 (apt.postgresql.org source)

**Comment by gplv2** [comment]
If you want hba auth, you cannot set it to md5.  You need to set it to hba.  you also need to specify the hba file on the bouncer.  don't expect the postgresql hba file to be fully supported by pgbouncer.  There are roles that it will not support :  you should get a warning in 1.8.1 on that:  https://github.com/pgbouncer/pgbouncer/commit/4f3dfc9b584aa177623ccfe4846322ebb55b9d63

like this:

```
; any, trust, plain, crypt, md5, hba
auth_type = hba
auth_file = /etc/pgbouncer/userlist.txt`

;; Path to HBA-style auth config
auth_hba_file = /etc/pgbouncer/pooler_hba.conf
```

in other words: your hba file needs to be configured in pgbouncer, not in postgresql (but you need one there too).

**Comment by petere** [comment]
Closing, since it was apparently a misunderstanding.
