### ISSUE TITLE
how to compile it as staticlly excuteable.

### ISSUE THREAD

**Issue by jeffery9** [pgbouncer/pgbouncer#291]
need to run as portable, thanks

**Comment by achix** [comment]
gcc -static, man gcc

**Comment by gplv2** [comment]
FYI:

LDFLAGS=-static ./configure  is not generating a statically linked pgbouncer executable.  It will fail on finding the SSL libraries at configure stage.

**Comment by petere** [comment]
You can use the `-static` option if you build without OpenSSL. But depending on your platform, it's not going to work well. glibc doesn't support static linking too well, especially when using NSS DSOs.
