### ISSUE TITLE
pgbouncer : no more connection allowed error

### ISSUE THREAD

**Issue by lkpatel** [pgbouncer/pgbouncer#293]
I have installed pgbouncer with session pool mode and configured to have default pool size equal to 300.  I am trying to initiate about 250 simultaneous connection using python multiprocessing from a single client. But still it is giving "psycopg2.OperationalError: ERROR:  no more connections allowed (max_client_conn)" error.  Without  pgbouncer I am getting no error as I have set maximum database connection = 500. I am invoking  psycopg2.connection.ping method for checking whether connection is alive or not before trying to get new connection. Is there any limit on no of connection per client as I can see only one or two connection in backend postgresql database ?

name    |   host    | port | database  | force_user | pool_size | reserve_pool | pool_mode | max_connections | current_connections 
-----------+-----------+------+-----------+------------+-----------+--------------+-----------+-----------------+---------------------
 NMS       | localhost | 5432 | NMS       |            |       300 |            0 |           |             300 |                   1
 pgbouncer |           | 6432 | pgbouncer | pgbouncer  |         2 |            0 | statement |             300 |                   0

Error trace:-
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'ping'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()  
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/PycharmProjects/NMS/discovery/discovery/lib/tests/testdevicetype.py", line 25, in worker
    print(hostname, check_device_type(hostname, snmp_creds))  
  File "/PycharmProjects/NMS/common/common/utils/pgsql.py", line 44, in __init__
    self.__cursor = self.__get_cursor(db, host, port, user, passwd) 
  File "/PycharmProjects/NMS/common/common/utils/pgsql.py", line 50, in __connect
    self.__connection = psycopg2.connect(database=_db, host=_host, port=_port, user=_user, password=_passwd)  
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: ERROR:  no more connections allowed (max_client_conn)

**Comment by lkpatel** [comment]
Thanks Melkij for quick reply. I have set following parameters

```
max_client_conn = 400
default_pool_size = 400
max_db_connections = 400
max_user_connections = 400
```
Also I tried with "transaction" pool mode but still what I see only one connection from my client. I am iniating all connection from a single host. I am using pgbouncer 1.7.2
pgbouncer=# show databases;
   name    |   host    | port | database  | force_user | pool_size | reserve_pool | pool_mode | max_connections | current_connections 
-----------+-----------+------+-----------+------------+-----------+--------------+-----------+-----------------+---------------------
 NMS       | localhost | 5432 | NMS       |            |       400 |            0 |           |             400 |                   1
 pgbouncer |           | 6432 | pgbouncer | pgbouncer  |         2 |            0 | statement |             400 |                   0
(2 rows) 

Is there any limit no of connection from  a single client ? How to pool connections originating from a single host ?

**Comment by gplv2** [comment]
Your default pool size is way too big,  set it to 20.  Also , make your max_user_connections bigger than your max_db_connections.  Make it 1500, it's a last resort limit.

**Comment by petere** [comment]
It looks like this was a usage error/misunderstanding, so I'm closing this issue for now.
