### ISSUE TITLE
PostgreSQL slower at load

### ISSUE THREAD

**Issue by atandrau** [pgbouncer/pgbouncer#294]
We are using PGBouncer on PostgreSQL on Heroku. At small loads all works well. At higher loads (1+ mil CPM), we see some SQL queries gradually become slower, starting at 2 seconds, going up to 30 seconds, up until timeout. Switching to non PGB works correctly.

Did anyone encounter similar issues before?

**Comment by petere** [comment]
Please use the Gitter chat for support and usage discussions.
