### ISSUE TITLE
unsupported startup parameter

### ISSUE THREAD

**Issue by sm2017** [pgbouncer/pgbouncer#295]
I am using PDO with Dsn = `pgsql:dbname=postgres;host=127.0.0.1;port=6432;options='--client_encoding=utf8 --application_name=myAppName'`

PgBouncer close the connection , The error is
>unsupported startup parameter: options=--client_encoding=utf8 --application_name=myAppName

So I add `options` to `ignore_startup_parameters` , I see that it accept my connection but don't affect `--application_name` , Also I cannot verify that it affect `--client_encoding`

**Comment by Melkij** [comment]
Hello
You can set application_name in DSN directly: "pgsql:port=6432;application_name=myAppName2;client_encoding=utf8"
PDO just replace ';' to ' ' in DSN and fix user credentials to build postgresql conninfo: https://github.com/php/php-src/blob/PHP-7.2.6/ext/pdo_pgsql/pgsql_driver.c#L1187

I think pgbouncer would not parse fully customizable "options" param.

**Comment by sm2017** [comment]
@Melkij Tanks a lot
