### ISSUE TITLE
Cannot use auth_query for connections to the "pgbouncer" database

### ISSUE THREAD

**Issue by gclough** [pgbouncer/pgbouncer#303]
**PROBLEM**
Users that connect to the `pgbouncer` database must have an entry in the `userlist.txt` file, and cannot authenticate against the database using `auth_query`.

This means, that as a DBA I need to keep my password on the database in sync with the password on the pgbouncer servers.

**EXPECTED**
Users that are in the `admin_users`, or `stats_users` list should follow the same process when they connect to the `pgbouncer` database as they do when connecting to any other database, and if there is no entry in `userlist.txt` then the password should be authenticated using `auth_query`.

**EXAMPLE**

***pgbouncer.ini***
```
[databases]
* = host=localhost port=5432 auth_user=pgbouncer

[pgbouncer]
auth_query = SELECT uname, phash FROM pgbouncer.user_lookup($1);
admin_users = postgres,gclough
```

***userlist.txt***
```
"pgbouncer" "password"
```

Logins work to both the database (port 5432) and pgbouncer (port 6432):

```
[root@localhost pgbouncer]# /usr/pgsql-9.6/bin/psql -h 127.0.0.1 -U gclough -p 5432 postgres
Password for user gclough: 
psql (9.6.9)
Type "help" for help.

postgres=# \q
```

```
[root@localhost pgbouncer]# /usr/pgsql-9.6/bin/psql -h 127.0.0.1 -U gclough -p 6432 postgres
Password for user gclough: 
psql (9.6.9)
Type "help" for help.

postgres=# \q
```

But if I try to login to `pgbouncer`, then it fails:

```
[root@localhost pgbouncer]# /usr/pgsql-9.6/bin/psql -h 127.0.0.1 -U gclough -p 6432 pgbouncer
psql: ERROR:  No such user: gclough
```

Unless I put my user into `userlist.txt`:

```
"pgbouncer" "password"
"gclough" "trustno1"
```

Then it works:

```
[root@localhost pgbouncer]# /usr/pgsql-9.6/bin/psql -h 127.0.0.1 -U gclough -p 6432 pgbouncer
Password for user gclough: 
psql (9.6.9, server 1.8.1/bouncer)
Type "help" for help.

pgbouncer=#
``` 

**ENVIRONMENT**

```
[root@localhost pgbouncer]# pgbouncer --version
pgbouncer version 1.8.1

[root@localhost pgbouncer]# cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core)

[root@localhost pgbouncer]# uname -a
Linux localhost.localdomain 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

***WORKAROUND?***

I tried to fudge it by creating a `pgbouncer` database entry in `pgbouncer.ini`, but that causes pgbouncer to crash hard:

https://github.com/pgbouncer/pgbouncer/issues/302

**Comment by PJMODOS** [comment]
The pgbouncer database is virtual database that is part of the pgbouncer instance. The connections to pgbouncer database must not depend on PostgreSQL instance behind the pgbouncer otherwise the SQL administration interface would be cut of if there are problems with the PostgreSQL instance (so you could not for example move to different PostgreSQL server like newly promoted standby via the SQL admin interface like you can now). So this simply can't work.
