### ISSUE TITLE
update pgbouncer to avoid GCC 7.x warnings

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [pgbouncer/pgbouncer#307]
Greetings,

I had to add CPPFLAGS='-Wno-expansion-to-defined' ./configure

to avoid GCC7.x warnings. Don't know which file to update, so if anyone could do it would be great thanks

**Comment by petere** [comment]
I have never seen that. What is the complete error message, with line numbers? What is your platform?

**Comment by petere** [comment]
Actually, I had already fixed that in libusual/libusual@51d444927e55fed0523e03dd17b392fc70556023, so it should be in pgbouncer 1.8.

**Comment by petere** [comment]
closing for now due to lack of further information
