### ISSUE TITLE
systemd example

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [pgbouncer/pgbouncer#308]
maybe it would be worth to add it as a systemd example?
----------------------------

[Unit]
Description=PostgreSQL connection pooler
After=network.target

[Service]
Type=simple
User=pgbouncer
Group=pgbouncer
ExecStart=/usr/local/bin/pgbouncer /etc/pgbouncer/pgbouncer.ini
ExecReload=/bin/kill -SIGHUP $MAINPID
TimeoutSec=300
OOMScoreAdjust=-1000
RuntimeDirectory=pgbouncer
RuntimeDirectoryMode=1775

[Install]
WantedBy=multi-user.target

**Comment by uspen** [comment]
Type=forking

**Comment by harisankar-krishna-2015** [comment]
With forking the pid file is required. The following works on OpenSUSE server 15.0 with kernel 4.4.

[Unit]
Description=pgBouncer connection pooling for PostgreSQL
After=postgresql.service

[Service]
Type=forking
User=postgres
Group=postgres
# Run ExecStartPre with root-permissions
PermissionsStartOnly=true
ExecStartPre=-/usr/bin/mkdir -p /var/run/pgbouncer /var/log/pgbouncer
ExecStartPre=/usr/bin/chown -R postgres:postgres /var/run/pgbouncer /var/log/pgbouncer
# Start pgBouncer 
ExecStart=/usr/local/bin/pgbouncer -d /etc/pgbouncer/pgbouncer.ini
ExecReload=/bin/kill -SIGHUP $MAINPID
PIDFile=/var/run/pgbouncer/pgbouncer.pid

[Install]
WantedBy=multi-user.target

**Comment by edib** [comment]
In Centos 7, "max open files" limit becomes problem. Below parameter should be added.
LimitNOFILE=65536

**Comment by oscar123mendoza** [comment]
@harisankar-krishna-2015 Do you really want to recursively update all the directories under `/var/run` and `/var/log` to be owned by the `postgres` or `pgbouncer` users? 

```
ExecStartPre=/usr/bin/chown -R postgres:postgres /var/run/pgbouncer /var/log/pgbouncer
```

**Comment by harisankar-krishna-2015** [comment]
> @harisankar-krishna-2015 Do you really want to recursively update all the directories under `/var/run` and `/var/log` to be owned by the `postgres` or `pgbouncer` users?
> 
> ```
> ExecStartPre=/usr/bin/chown -R postgres:postgres /var/run/pgbouncer /var/log/pgbouncer
> ```

chown is on the pgbouncer sub-folder.

**Comment by oscar123mendoza** [comment]
@harisankar-krishna-2015 So sorry I completely miss read this !

**Comment by mikkeljohnsen** [comment]
You should be able to ajust File descriptors from "/etc/sysconfig/pgbouncer".

This is a real problem, we hit 1024 limit quickly.
