### ISSUE TITLE
"show fds" crashes pgbouncer in 1.8.1

### ISSUE THREAD

**Issue by quixoten** [pgbouncer/pgbouncer#311]
This occurs even when not connection through a unix socket, e.g.

```
2018-07-16 16:00:15.683 723 LOG C-0x7fd30b31ebf8: pgbouncer/pgbouncer@10.64.33.195:46452 login attempt: db=pgbouncer user=pgbouncer tls=no
2018-07-16 16:00:27.245 2645 LOG File descriptor limit: 65536 (H:65536), max_client_conn: 80000, max fds possible: 109556
```

The first log line is from running:

```
watch "psql -U pgbouncer -h 10.64.33.195 -p 6432 pgbouncer -c 'show fds;'|grep 'America/Denver'|wc -l"
```

This doesn't always crash the process, but I had three instances of pgbouncer running, and the `watch` command running on each of those. They crashed within 15 to 16 minutes of each other.

**Comment by eulerto** [comment]
Could you provide a stack trace? Useful info https://wiki.postgresql.org/wiki/Getting_a_stack_trace_of_a_running_PostgreSQL_backend_on_Linux/BSD

**Comment by quixoten** [comment]
So far, I've only been able to reproduce this in our production environment. I'm unable to get a stack trace there due to downtime sensitivity. I'll continue to try in another environment, but the workloads are vastly smaller.

**Comment by eulerto** [comment]
You only need to enable core files (ulimit, limits.conf) for pgbouncer user. After that get a stack trace from the core file.

**Comment by film42** [comment]
It's interesting that `sk->pool` is checked a few lines down from `src/admin.c:333`. I'm guessing it's `NULL`.
https://github.com/pgbouncer/pgbouncer/blob/e8e8f64dd39f75e329117fddecc730f524c55973/src/admin.c#L333-L343

That _should_ prevent a crash, but it doesn't really explain why `sk->pool` or `sk->pool->db` is not set.

**Comment by achix** [comment]
maybe a diff of the config file against the distro config ?

**Comment by petere** [comment]
`sk->pool` could be unset if the client has not been assigned to a pool yet.  That would also explain that the crash happens only occasionally but repeatedly under load.

@quixoten Try adding `sk->pool && ...` to the `if` statement on line 333 of `admin.c`.

**Comment by petere** [comment]
I was able to reproduce this, by running `SHOW FDS` under `watch` as shown in the report and then having several clients connect repeatedly in a loop, with more clients than the pool size (maybe that wasn't important). It would segfault after 10 to 20 minutes. The committed patch fixed it for me and also is consistent with our earlier analysis.
