### ISSUE TITLE
Average Wait time / Units

### ISSUE THREAD

**Issue by fwiesel** [pgbouncer/pgbouncer#316]
Hi,

I have some trouble with the metric "average wait time".
I am seeing values vastly exceeding the lifetime of the pgbouncer instance, seeing something like "212233866028us" for an instance, which has been active for a couple of minutes.

I am slightly confused about the calculation of wait time here:
> https://github.com/pgbouncer/pgbouncer/blob/master/src/stats.c#L73

`old` and `cur` hold the accumulated `wait_time` of all the clients at a point in time.
The unit of `wait_time` is time, like `query_time`, and `xact_time`.
But unlike the other time metrics, it is divided over a different time (`dur`), which gives us a fraction.

I would assume, in order to get the average `wait_time`, we would have to divide by a number.
I would suggest to accumulate the number of waiters in stats, and average over the delta at the two points in time.

Sorry, if I am mistaken.
Otherwise, I am willing to offer a patch to implement said behaviour.

Thanks and cheers,
  Fabian

**Comment by curlup** [comment]
> divided over a different time (dur), which gives us a fraction.

seems legit. 

Otoh docs say 
> Time spent by clients waiting for a server in microseconds __(average per second)__.

So one might think of it as this:
* The unit of wait_time is time
* Dividing over a duration gives a fraction
* Multiply (virtually) to 1 second to get average per second 
* The unit is time again

WDYT?

**Comment by petere** [comment]
It also helps if you think about units of "time-of-waiting" vs units of "wall clock time".

I think this is all fine, so I propose to close this.

**Comment by fwiesel** [comment]
As it is working as indented, I am fine with it.
Thanks for taking the time and the explanations.

**Comment by mmickan** [comment]
I've seen massively inflated wait times and wonder if they might be the same issue reported here.  I agree that the maths used to calculate the average makes sense, but if activate_client() is called during CL_WAITING_LOGIN, client->wait_start is still 0, so current unix time (~49 years) is added to the total wait time.

I've just submitted https://github.com/pgbouncer/pgbouncer/pull/339 to address this.

**Comment by JelteF** [comment]
Re-opening this as I really think the current meaning of `avg_wait_time` does not make sense given its name. It's measuring total wait time per second, not average wait time. I think the approaches in #727 and #913 both are more useful than the current implementation.
