### ISSUE TITLE
Support service= and .pgpass

### ISSUE THREAD

**Issue by davidfetter** [pgbouncer/pgbouncer#32]
Is there any way to do this short of redoing pgbouncer to use libpq?

**Comment by markokr** [comment]
I'm backing down on this - pgpass pattern-matching is not something that fits pgbouncer.

pg-service is kind-of ok, except still quite libpq-specific.  I think better idea is to improve pgbouncer config language, which already can go quite far (eg. includes) without low-level changes (eg. it would easy to have separate section for one db).

I suspect main use-case for these features is not complex db setups, but newbies who could use existing files without thinking too much, but the complexity-vs-benefit ratio would be really bad in such case.
