### ISSUE TITLE
Installation on aws ec2 (kernel version 4.9.58) fails with the following error

### ISSUE THREAD

**Issue by vivekanandg** [pgbouncer/pgbouncer#338]
--> Running transaction check
---> Package pgbouncer.x86_64 0:1.9.0-1.rhel6 will be installed
--> Processing Dependency: libevent2 >= 2.0 for package: pgbouncer-1.9.0-1.rhel6.x86_64
--> Processing Dependency: python-psycopg2 for package: pgbouncer-1.9.0-1.rhel6.x86_64
--> Running transaction check
---> Package pgbouncer.x86_64 0:1.9.0-1.rhel6 will be installed
--> Processing Dependency: libevent2 >= 2.0 for package: pgbouncer-1.9.0-1.rhel6.x86_64
---> Package python-psycopg2.x86_64 0:2.7.5-1.rhel6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: python-psycopg2-2.7.5-1.rhel6.x86_64
--> Processing Dependency: libpython2.6.so.1.0()(64bit) for package: python-psycopg2-2.7.5-1.rhel6.x86_64
--> Running transaction check
---> Package pgbouncer.x86_64 0:1.9.0-1.rhel6 will be installed
--> Processing Dependency: libevent2 >= 2.0 for package: pgbouncer-1.9.0-1.rhel6.x86_64
---> Package python26.x86_64 0:2.6.9-2.89.amzn1 will be installed
---> Package python26-libs.x86_64 0:2.6.9-2.89.amzn1 will be installed
--> Finished Dependency Resolution
**Error: Package: pgbouncer-1.9.0-1.rhel6.x86_64 (pgdg96)
           Requires: libevent2 >= 2.0**
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

Any workarounds?

**Comment by petere** [comment]
You will have to report that to whoever supplied those packages.
