### ISSUE TITLE
tcp and sockets

### ISSUE THREAD

**Issue by MichaelDBA** [pgbouncer/pgbouncer#341]
If I want to run pgbouncer on the postgresql server, how do I make sure that tcp is used for incoming client requests, but sockets, not tcp, are used for pgbouncer talking locally with postgresql?

**Comment by Melkij** [comment]
Hi
You can check `show servers;` command in pgbouncer console or something like
`select client_addr, count(*) from pg_stat_activity group by 1;`
from database. Unixsock will be marked as NULL in client_addr.

**Comment by MichaelDBA** [comment]
From pg_stat_activity I see my apps using NULL client_addr, but when I connect to pgbouncer and issue show servers, I get 127.0.0.1 as client address for these apps.

**Comment by eulerto** [comment]
> It seems if you do not specify host, it will default to sockets, but is there any other way to make PG use sockets?

No. Just omit `host` from the connection string in `databases` section.

**Comment by Melkij** [comment]
> It seems if you do not specify host, it will default to sockets, but is there any other way to make PG use sockets?
You can specify unixsock directory in host.

```
[databases]
db = host=/tmp/ port=5432
```

**Comment by MichaelDBA** [comment]
Thanks all, finally got it working with above tips and setting pgbouncer.ini setting (unix_socket_dir = /tmp)

Also, had to remove all entries from pg_hba.conf except the first one for postgres' pg_hba.conf:
```
# "local" is for Unix domain socket connections only
local       all         all          md5
```
