### ISSUE TITLE
pooler error: server conn crashed?

### ISSUE THREAD

**Issue by mystycs** [pgbouncer/pgbouncer#347]
`2018-12-10 20:56:59.349 8659 WARNING C-0x1b44e68: ckandb/ckandb_user@127.0.0.1:46198 pooler error: server conn crashed?
`

Sometimes i have network problems and the server side postgres loses connection to my app.

How can i set pgbouncer to reset the connections after a few seconds of this connection issue?

Right now it only reconnects if someone refreshes the web app, but i would like it to do this itself.

**Comment by tuukkamustonen** [comment]
I just bumped into a number of `pooler error: server conn crashed?`. For me, they were caused by `idle_in_transaction_session_timeout` - pgBouncer doesn't seem to detect the reason why server dropped the connection and so reports this generic message.

I wonder if it would be possible to give more detailed error message in case connections gets dropped due to `idle_in_transaction_session_timeout`?

**Comment by petere** [comment]
There are various timeout settings that can help in case of network issues, such as `query_timeout`, `query_wait_timeout`, and `client_idle_timeout`. Which one of these is appropriate depends on the specific circumstances.

**Comment by petere** [comment]
Also, the original reporter might be looking for the `server_login_retry` setting.

**Comment by blueyed** [comment]
> Also, the original reporter might be looking for the `server_login_retry` setting.

Is this supposed to be set to 0 then?
(Assuming / understanding it so that using the default of 15s means that it can take 15s to get a "server conn crashed?" error on successive retries)

**Comment by blueyed** [comment]
Is pgbouncer capable of handling a crashed server connection in this case, without causing an exception with the app itself?

I am seeing this sporadically on GCP, using a simple config like this:
```
[pgbouncer]
…
max_db_connections = 90
default_pool_size = 90
max_client_conn = 100
log_connections = 0
log_disconnections = 0
```

It looks like "server conn crashed" usually would happen when reading fails: https://github.com/pgbouncer/pgbouncer/blob/9a346b0e451d842d7202abc3eccf0ff5a66b2dd6/src/server.c#L534-L536 - so it is not related to creating a connection only, and therefore it is not really possible to retry in this case always I assume.

The logs in this case:
```
2022/06/22 21:44:02 Reading data from project:region:service had error: read tcp 169.254.8.1:59950->34.77.237.33:3307: read: connection reset by peer
2022-06-22 21:44:02.583 UTC [11] WARNING C-0x7f0c538b8340: db/db-user@127.0.0.1:51448 pooler error: server conn crashed?
ERROR:xxx.healthcheck:get_db_status failed: django.db.utils.OperationalError(psycopg2.OperationalError): server conn crashed?
…
DEBUG:urllib3.connectionpool:Resetting dropped connection: o158426.ingest.sentry.io
```

Given that there is also a dropped connection with Sentry reporting the crash it looks like a generic network issue.

Noteworthy is that it happened later again, but without crashing the app apparently!?
```
2022/06/22 21:44:46 Reading data from project:region:service had error: read tcp 169.254.8.1:59290->34.77.237.33:3307: read: connection reset by peer
2022-06-22 21:44:46.470 UTC [11] WARNING C-0x7f0c538b8110: db/db-user@127.0.0.1:50590 pooler error: server conn crashed?
```
So here it was happening where it could be recovered from / retried then maybe?

Is there something that can be improved here?
I can see that there are situations where it is not possible to fix a broken a connection, but wonder if the current behavior is expected to be lived with?

For now I will try `server_login_retry = 0` additionally, and see how it behaves.
