### ISSUE TITLE
pgbouncer.pid file damage

### ISSUE THREAD

**Issue by wdc596933938** [pgbouncer/pgbouncer#351]
Does pgbouncer take measures to deal with damaged PID files? In practical use, I found that when the PID file was damaged, pgbouncer could not start correctly. Has anyone encountered and solved this problem?
![image](https://user-images.githubusercontent.com/19362234/50203818-b997e880-039d-11e9-8f6f-061b3d0b6cda.png)
Pgbouncer start filed and print log `pidfile exists, another instance running?`

**Comment by petere** [comment]
Yes, that behavior is to be expected. What else did you have in mind? Why is your pid file damanged?

**Comment by petere** [comment]
I double-checked the code that handles the PID file. It appears to be working correctly when the PID file is corrupted. So I think this is a one-off local problem, not a bug in pgbouncer.
