### ISSUE TITLE
pgfoundry.org/projects/pgbouncer: 404 - page not found

### ISSUE THREAD

**Issue by florianb** [pgbouncer/pgbouncer#36]
Hi - i'm trying to find out more about pgbouncer and always get directed to http://pgfoundry.org/projects/pgbouncer. Unfortunately this url shows always "Requested Page not Found (Error 404)".

**Comment by danmbox** [comment]
Someone should fix the `README`...

**Comment by markokr** [comment]
Seems pgfoundry is going down...

**Comment by markokr** [comment]
Seems it's up again, but we are already moving homepage to away from pgfoundry: https://pgbouncer.github.io/
