### ISSUE TITLE
PGBouncer connections are not killed when the database becomes unreachable

### ISSUE THREAD

**Issue by jhammerman79** [pgbouncer/pgbouncer#364]
Good afternoon PGBouncer devs,

We are simulating network outages by blocking the postgres port on a primary in an HA repmgr setup:

iptables -A INPUT -p tcp --destination-port 5432 -j DROP

The only setting that would cause the connection to error out and surface to the client (allowing it to enter it's retry loop) was query_timeout. I alternatively experimented with setting the following configuration options (since query_timeout is the most dangerous setting):

server_fast_close
server_idle_timeout
server_connect_timeout
server_login_retry
client_login_timeout
query_wait_timeout
client_idle_timeout
idle_transaction_timeout

To no effect.

Is there a setting we are missing? This is with pgbouncer version 1.9.0.

Thanks in advance for any assistance anyone can provide!
Joseph Hammerman

**Comment by parrish** [comment]
Anecdotally, I failed to reproduce this.

**Comment by PJMODOS** [comment]
Me neither, will need proper reproduction case.

**Comment by joehammerman** [comment]
OK thanks guys! I will see if I can reproduce the next time I spin my test truss.

**Comment by eulerto** [comment]
Since there is not a reproducible test case, there is no evidence of bugs here. If and when you have something concrete, feel free to open another issue.
