### ISSUE TITLE
pgbouncer is not containerized

### ISSUE THREAD

**Issue by unacceptable** [pgbouncer/pgbouncer#368]
I didn't see an official container for pgbouncer, so I have created a pgbouncer container and organization on hub.docker.com.

https://hub.docker.com/r/pgbouncer/pgbouncer

I would like to incorporate this `docker build` into pgbouncer's CI process, but I am not seeing how your team handles version releases.  Obviously, it's done via tags, but I am not seeing how this is done via Travis CI.  At my company, we have configured automated git tagging based on PR's to certain branches.

Can someone help me to understand how the current release process works so I can put in a PR with a Dockerfile and an updated CI pipeline?  

Additionally, I don't want to be part of the pgbouncer organization on Docker Hub as well, so I would like to talk about transferring ownership of that organization.

**Comment by PJMODOS** [comment]
Our release process does not involve any binary building, we officially only release source code hence no containerization. The linux packages (deb and rpm) are released by PGDG not us.

**Comment by PJMODOS** [comment]
But nice work though, I don't mind merging PR containing Dockerfile, not sure how would the image get updated as like I said above, we don't deal with binaries ourselves.

**Comment by ScriptMyJob** [comment]
Roger that.  I guess I will just leave this in GitLab for now, and maintain the pgbouncer/pgbouncer docker hub repo unless this open source team has any objections.  I guess you all could always hit me up if you wanted to transfer ownership or re-evaluate this, and I would be happy to oblige.  Thanks for helping to create awesome software!

On a side note anyone reading this issue in the future: PR's for this Dockerfile are always welcome.

**Comment by PJMODOS** [comment]
I am happy with you maintaining this on gitlab, like I said the packages are also done externally, but if you need something to get committed here to make it easier, I am happy to merge.

**Comment by thenewguy** [comment]
@unacceptable @PJMODOS Any chance you would revisit this?  It would be pretty trivial to have a ci runner containerize the realize and publish to the docker hub as part of your push workflow.  An official image would be greatly appreciated

**Comment by markokr** [comment]
"Official" image requires that specific distribution channel (dockerhub account in this case) is also owned and maintained by pgbouncer maintainers.

Unless some maintainer accepts that task, it might be simpler to keep things as-is and let people who are interested in specific binary distribution format, maintain that distribution.

**Comment by hyperized** [comment]
As an example you could get inspired by:

- https://github.com/hyperized/pgbouncer-docker
- https://hub.docker.com/r/hyperized/pgbouncer

This setup utilizes the auto build feature of Docker hubs requiring no further dependencies.

![afbeelding](https://user-images.githubusercontent.com/827954/83648614-8c052600-a5b6-11ea-849a-567c793e34a2.png)

**Comment by unacceptable** [comment]
@PJMODOS I just read your response form 5/21 now that GitHub has GitHub actions maybe I could just commit the Dockerfile and a build job here?

**Comment by hyperized** [comment]
@unacceptable Github actions is not required, Docker Hubs provides everything you might need.
