### ISSUE TITLE
total_wait_time grows by large jumps

### ISSUE THREAD

**Issue by DavidPavlicek** [pgbouncer/pgbouncer#370]
While ago, our pgbouncer monitoring tool starts reporting errors when it tries to parse pgbouncer's show stats report. It complains that total_wait_time is too big to parse it to integer! OK, that's a clear message. But why is so high, when no other users, applications or pgbouncer log complain about database issues? But really strange is how it grows. Total_wait_time difference between few consecutive measurements stays pretty low (few tents or hundreds of us), then suddenly grows by few billions(!) and then again stays low as shown on this [graph](https://i.stack.imgur.com/PlXXc.png)

We use pgbouncer in session pooling mode with max_pool_size and max_client_connections set to 200. Underlying postgres max_connections is also set to 200. A typical number of connected sessions is around 100/130 (most of them in idle state) and 60 pools. So there shouldn't be an issue...

pgbouncer version: 1.8.1
OS: Debian Linux 8.5
PG: 10.3

**Comment by petere** [comment]
Are you using `auth_user` or related functionality? If so, there was a bug, see #393.

**Comment by DavidPavlicek** [comment]
Yes, we use `auth_user` facility to access our database. #393 definitely could be our case...

**Comment by jooyg62** [comment]
-[ RECORD 1 ]-----+---------------------
database          | ******
total_xact_count  | 1002714
total_query_count | 1022148
total_received    | 783936303
total_sent        | 1659890576
total_xact_time   | 306458282
total_query_time  | 280741535
total_wait_time   | 5574247036117366727
avg_xact_count    | 0
avg_query_count   | 0
avg_recv          | 372
avg_sent          | 306
avg_xact_time     | 340
avg_query_time    | 340
avg_wait_time     | 102565085899
-[ RECORD 2 ]-----+---------------------
database          | *****
total_xact_count  | 199095964
total_query_count | 199295332
total_received    | 115777317739
total_sent        | 305395696030
total_xact_time   | 62941448324
total_query_time  | 62830581092
total_wait_time   | 16492311827424936337
avg_xact_count    | 125
avg_query_count   | 125
avg_recv          | 81171
avg_sent          | 172590
avg_xact_time     | 383
avg_query_time    | 381
avg_wait_time     | 102564663976
-[ RECORD 3 ]-----+---------------------
database          | pgbouncer
total_xact_count  | 304170
total_query_count | 304170
total_received    | 0
total_sent        | 0
total_xact_time   | 0
total_query_time  | 0
total_wait_time   | 0
avg_xact_count    | 0
avg_query_count   | 0
avg_recv          | 0
avg_sent          | 0
avg_xact_time     | 0
avg_query_time    | 0
avg_wait_time     | 0
-[ RECORD 4 ]-----+---------------------
database          | postgres
total_xact_count  | 0
total_query_count | 0
total_received    | 0
total_sent        | 0
total_xact_time   | 0
total_query_time  | 0
total_wait_time   | 1064
avg_xact_count    | 0
avg_query_count   | 0
avg_recv          | 0
avg_sent          | 0
avg_xact_time     | 0
avg_query_time    | 0
avg_wait_time     | 0

**Comment by eulerto** [comment]
Since we didn't have a reply from the OP even in the upstream issue, let's close it.
