### ISSUE TITLE
pgbouncer failover

### ISSUE THREAD

**Issue by willzhang** [pgbouncer/pgbouncer#372]
if pgbouncer down,what i shoud do？

**Comment by willzhang** [comment]
pgbouncer failover

**Comment by hyperized** [comment]
Maybe this can help: https://www.percona.com/blog/2018/10/02/scaling-postgresql-using-connection-poolers-and-load-balancers-for-an-enterprise-grade-environment/

**Comment by willzhang** [comment]
what about this way?
![img](https://github.com/willzhang/blog/raw/master/image/other/pgbouncer.png)

**Comment by PJMODOS** [comment]
@willzhang that link gives me 404

**Comment by petere** [comment]
Not really a bug. Unclear what to do here.
