### ISSUE TITLE
is pgbouncer abandoned?

### ISSUE THREAD

**Issue by williamdenton** [pgbouncer/pgbouncer#373]
There are many open PRs and Issues that have not been commented on by an owner or contributor. I'm concerned that the knowledge holders/domain experts have lost interest in maintaining pgbouncer. 

There haven't been meaningful commits to master in months and there are valuable contributions building up in the form of unreviewed PRs.

I am hoping this issue will be noticed by a maintainer so the community can engage in  a more productive way, whether that be a fork, new maintainers or just some help in triaging the many open issues and pull requests to lighten the load for the existing maintainers.

Perhaps getting the attention of some cloud vendors (aws/gcp/azure) could find a new champion as postgres becomes more popular in the cloud.

**Comment by uspen** [comment]
try yandex/odyssey

**Comment by MichaelDBA** [comment]
yikes, this doesn't seem like good news.

**Comment by PJMODOS** [comment]
nope, still alive

**Comment by williamdenton** [comment]
I'm relieved that you're still active here @PJMODOS. What can we do to help?
I use 'We' in the royal sense, as my c/c++ skills aren't adequate to be able to contribute technically, but I sense there is quite a community here who would like to be able to contribute.

I'm sorry if i offended you with my comment above, and i really appreciate your efforts, i see you have been busy triaging some of the issues in the last couple of days since my message which is awesome to see. Thank you.
