### ISSUE TITLE
Pgbouncer artificially limiting identifier names to 63 characters

### ISSUE THREAD

**Issue by lremes** [pgbouncer/pgbouncer#374]
We are using vault database secret backend with Azure Kubernetes Service and Azure DB for postgresql as described at https://learn.hashicorp.com/vault/identity-access-management/vault-agent-k8s

The setup we have is working, and we are able to generate working credentials with "vault read database/creds/[dbname]" for kubernetes pods.

The issue we are facing is that we would like use pgbouncer sidecar (https://hub.docker.com/_/microsoft-azure-oss-db-tools-pgbouncer-sidecar)
to manage the connections, but the psql role name generated by vault is too long for pgbouncer. pgbouncer limits the username to 63 characters, but Azure DB for PostgreSQL requires that @hostname is included in the username.

So the vault generated psql role name is:
v-kubernet-dbname-xxxxxxxxxxxxxxxxxxxx-xxxxxxxxxx
or 
v-kubernet-[dbname]-[20 chars]-[10 chars]

As Azure postgresql expects @hostname after the username:
v-kubernet-dbname-xxxxxxxxxxxxxxxxxxxx-xxxxxxxxxx@db_hostname

So this leaves 19 characters for the dbname and hostname parts.

The obvious solution is to shorten the database name and hostname, but that really is not very sustainable solution.

If Postgres accepts names of a certain length and pgbouncer places an artificial limit on the names, it's not properly acting as a transparent bouncer.
So the artificial limits should be removed, or at least a flag/config option should be provided to bypass the restriction.

**Comment by PJMODOS** [comment]
The rolname (used for storing user names) in PostgreSQL is limited to 63 characters, if whatever is running on Azure allows more then it's modified version of PostgreSQL, we don't promise to support those. We also don't claim to be fully transparent.

The maximum length of username in pgbouncer affects the memory usage so I am not too keen on increasing it arbitrarily for a fork of PostgreSQL without knowing more about how it works and why it needs such behavior. It's possible to change it in source (`MAX_USERNAME`) and make binaries with that however. This would make it work in your situation (such change should not be problem to integrate into the docker image you mentioned).

**Comment by lremes** [comment]
Azure Database for Posgresql service uses the @db_hostname part of the username to route traffic to servers. Thus, it is a mandatory when using Azure Database for Postgresql, and this limitation will lead to random and unavoidable errors using the Azure Database for Postgresql service, since the length of rolname@db_database may not always be predictable.

**Comment by petere** [comment]
There are discussions elsewhere about increasing user name and password lengths. It needs some further analysis how if affects performance and memory usage.

**Comment by markokr** [comment]
I guess creation/deletion of PgUser/PgDatabase should not be that heavy traffic, which means it should be OK to make username/password and dbname regular malloced strings.

Although it would still be good idea to limit them with some config setting to not let nonsense traffic reach servers.
