### ISSUE TITLE
PGBouncer exposing database information

### ISSUE THREAD

**Issue by caiges** [pgbouncer/pgbouncer#375]
This issue could be interpreted numerous ways from a security standpoint but a colleague of mine (@tnoeding) and I were working on our pooling setup and noticed that pgbouncer responds differently to list databases than PostgreSQL does, exposing that certain users or databases exist.

Output directly from PostgreSQL:
```
$ psql -h localhost -p 32786 -l
Password for user blars:

$ psql -h localhost -p 32786 -l tacos
Password for user blars:  
```

Output directly from PGBouncer:
```
$ psql -h localhost -p 5432 -l 
psql: ERROR:  no such user: blars

$ psql -h localhost -p 5432 -l tacos
psql: ERROR:  no such database: tacos
```

**Comment by PJMODOS** [comment]
Those error messages have nothing to do with what's in the actual postgres database instance, but with what's configured in pgbouncer (ie, does pgbouncer have that user and that database), if you configured pgbouncer to load its users and databases from real database automatically but don't actually want to do that then that's configuration problem.
