### ISSUE TITLE
stat() of auth_file blocking connections

### ISSUE THREAD

**Issue by doubleshot** [pgbouncer/pgbouncer#377]
If you strace a pgbouncer PID you'll see that the auth_file is constantly being stat'd. If there is a high disk i/o event on the disk that stores the userlist.txt, pgbouncer itself seems to not accept new connections until the stat() is able to succeed.

We ran into this issue with a heavy logrotation done on the / partition which stores the auth_file, while postgres db was running on a different set of disks. 

Output from strace:
```recvfrom(217, "2\0\0\0\4C\0\0\0\rSELECT 0\0Z\0\0\0\5I", 4096, 0, NULL, NULL) = 25
sendto(172, "2\0\0\0\4C\0\0\0\rSELECT 0\0Z\0\0\0\5I", 25, 0, NULL, 0) = 25
epoll_wait(4, [], 512, 225)             = 0
stat("/etc/pgbouncer/userlist.txt", {st_mode=S_IFREG|0600, st_size=489, ...}) = 0
epoll_wait(4, [{EPOLLIN, {u32=123, u64=123}}], 512, 334) = 1
```

This is a **theory** based on pgbouncer connection stats, disk i/o, and a heavy log rotation that happened on the root partition when our app failed to connect. I will try to reproduce this in a lab, but would like to know if this is possible that a delay in the stat() call of the auth_file could block/hinder connections to pgbouncer. 
If so, I would recommend a flag for caching/disabling the checking of changes to this file.

Thanks

**Comment by petere** [comment]
I can confirm from looking at the code that it stats the file three times a second. I agree that that's not good. I think we should change that so it only looks at the file on explicit reload.
