### ISSUE TITLE
Allow setting used upstream DNS server addresses (and ports) in configuration

### ISSUE THREAD

**Issue by WRMSRwasTaken** [pgbouncer/pgbouncer#379]
Background:

I am running a PostgreSQL cluster managed by [patroni](https://github.com/zalando/patroni) with Consul as DCS backend. patroni supports registering the current write master in Consul (thanks to zalando/patroni#771) and I entered the `master.<cluster name>.service.consul.` in `pgbouncer.ini`.

Now the problem: pgbouncer doesn't seem to have any configuration options to set the used upstream DNS servers (like [HAProxy](https://cbonte.github.io/haproxy-dconv/1.9/configuration.html#5.3.2) for example). To get service discovery working (and letting pgbouncer connect to the current write master) I had to set up a forwarding zone on my Unbound servers entered in the system's `resolv.conf` running pgbouncer for the `.consul` zone pointing to my Consul cluster.

This works flawlessly, and pgbouncer reconnects to the new master in case of a failover (also thanks to `close_needed` introduced in 1.9). But it would be nice not to depend on the system resolvers set in  `resolv.conf` (and therefore not to depend on a intermediate resolver).

At least c-ares seems to support setting custom DNS servers with `ares_set_servers`.

**Comment by petere** [comment]
Seems reasonable. Which DNS library are you using? What should the configuration look like?

**Comment by WRMSRwasTaken** [comment]
I'm using `adns: c-ares 1.15.0`.

I'd suggest using a new parameter in the `[pgbouncer]` section allowing comma separated IPs with ports.

Another suggestion would be a new `[dns]` section, although I'd have to think of how to declare multiple DNS servers, maybe by writing the parameter multiple times (one per IP-Port combination).

**Comment by petere** [comment]
@WRMSRwasTaken Please test the branch mentioned above.

**Comment by WRMSRwasTaken** [comment]
Hi,

I compiled the branch and it seems to work so far by setting just the used IPs. I didn't find a way to set the used ports for upstream DNS Servers in the custom `resolv.conf` file tho.

Looking in the c-ares documentation or in the `resolv.conf` manpage, it seems that there's no way to set the ports for DNS Servers in general, which I'd need because Consul's DNS Server normally listens on port `8600`.

My workaround is now to set the listen address for Consul's DNS Server to `127.0.0.200:53` and enter `nameserver 127.0.0.200` in the `/etc/pgbouncer/resolv.conf` file.

What I didn't test is a PostgreSQL failover to see if pgbouncer picks up the new master IP, although I don't see any problems here because that was working before too by using the system wide `resolv.conf`.

**Comment by petere** [comment]
Yeah, specifying the port number of a DNS server seems to be unsupported in most resolv.conf implementations, with OpenBSD the only exception I could find. It's also poorly supported in general across the DNS tooling ecosystem.

I suggest if the port stuff is of interest to lobby the libevent or c-ares developers to add this functionality. It should be pretty easy to do there.
