### ISSUE TITLE
cancelling wrong backends

### ISSUE THREAD

**Issue by okbob** [pgbouncer/pgbouncer#38]
We can detect situations, when Cancel request is propagated to wrong backend

I monitored communication between our client and server:

<pre>
10:57:06.249 P=1425635826.162500, s=288765600834197 type=BackendKeyData, B -> F                                                        
10:57:06.251 BACKEND KEY DATA pid=3067576038, key=1243797643
10:57:06.291 P=1425635826.164933, s=288765600834197 type=Query, F -> B                                                                 
10:57:06.293 QUERY query=CREATE TABLE "qt_18899f852226f58864cead54c43a2f04" AS 
10:57:07.671 P=1425635827.072222, s=288765600834212 type=BackendKeyData, B -> F                                                        
10:57:07.672 BACKEND KEY DATA pid=4175989218, key=577030691 

10:57:07.725 P=1425635827.074654, s=288765600834212 type=Query, F -> B                                                                 
10:57:07.727 QUERY query=CREATE TABLE "qt_c0f71f417b9c7cf4ac41759fb2004e3b" AS (

10:57:08.048 P=1425635827.428023, s=288765600834217 type=CancelRequest, F -> B                                                         
10:57:08.049 CANCEL REQUEST pid=4175989218, key=577030691                                                                              
                                                                                                                  
10:57:08.052 P=1425635827.429549, s=288765600834197 type=ErrorResponse, B -> F                                                         
10:57:08.054 ERROR RESPONSE                                                                                                            
10:57:08.055 File: 'postgres.c'                                                                                                        
10:57:08.058 Severity: 'ERROR'                                                                                                         
10:57:08.059 Message: 'canceling statement due to user request after 1264.050 ms'                                                      
10:57:08.060 Code: '57014'                                                                                                             
10:57:08.063 Routine: 'ProcessInterrupts'                                                                                              
10:57:08.064 Line: '2982'   

10:57:12.290 P=1425635830.882542, s=288765600834212 type=CommandComplete, B -> F                                                       
10:57:12.291 COMMAND COMPLETE command='SELECT 25607'
</pre>

The wrong process was cancelled. This issue is relative often - we have 956 cancel requests and 6 requests was wrong (it is about four days monitoring)

**Comment by petere** [comment]
This bug report is old. There have been a number of changes in PgBouncer's cancel handling in the meantime. I haven't heard of issues like this for some time. Are you still seeing this issue?

**Comment by okbob** [comment]
I have not a idea. But I have not any reference about this bug more

**Comment by petere** [comment]
OK, let's close this then, and we'll look at it again when we have more information.
