### ISSUE TITLE
Statement_timeout via -c options gets ignored

### ISSUE THREAD

**Issue by tuukkamustonen** [pgbouncer/pgbouncer#381]
I'm having hard time to understand how to allow `statement_timeout`. Using:

```ini
...
[pgbouncer]
pool_mode = session
ignore_startup_parameters = options
...
```

And `psycopg2` module in python:

```python
>>> conn = psycopg2.connect("dbname=unstable options='-c statement_timeout=1ms'")
>>> cur = conn.cursor()
>>> cur.execute("select pg_sleep(1)")
>>> 
```

It returns without timing out like it should. In logs, on connection, I get:

```
2019-04-08 10:25:09.908 4410 DEBUG C-0x55f7e34f9b38: (nodb)/(nouser)@127.0.0.1:58830 ignoring startup parameter: options=-c statement_timeout=1ms
```

So I think my setup should be fine(?), but `statement_timeout` has no effect.

`SET LOCAL statement_timeout = '1ms';` works correctly:

```python
>>> cnn = psycopg2.connect("host=127.0.0.1 user=unstable password=unstable dbname=unstable options='-c statement_timeout=1ms'")
>>> cur = cnn.cursor()
>>> cur.execute("SET LOCAL statement_timeout = '1ms'")
>>> cur.execute("select pg_sleep(1)")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
psycopg2.extensions.QueryCanceledError: canceling statement due to statement timeout
```

Any pointers?

**Comment by tuukkamustonen** [comment]
Nevermind, the docs say that the idea of `ignore_startup_parameters` is for pgBouncer really to _ignore_ those parameters.

I think I need to find a way to call `SET LOCAL statement_timeout` after opening any connection.

**Comment by Melkij** [comment]
> after opening any connection
any? You can set timeout for user:

> alter user username set statement_timeout to 'new value';

This timeout will be applied to every connection of this user.

**Comment by tuukkamustonen** [comment]
@Melkij That's good to know, too. Or I think I could set it on database level, automatically for all connections (but I don't want to do that, because I might want to set different timeouts for different queries, like reads vs writes).

**Comment by oceancode11** [comment]
So, is it not possible to set `statement_timeout` via options when using pgbouncer? Thank you!

**Comment by tuukkamustonen** [comment]
Hi, you can use `connect_query`, at least. Like:

```ini
[databases]
mydb = host=... port=... dbname=... connect_query='SET statement_timeout=30000'
```
