### ISSUE TITLE
DNS changes not detected

### ISSUE THREAD

**Issue by joekohlsdorf** [pgbouncer/pgbouncer#383]
I have the issue that pgBouncer doesn't see DNS changes, `SHOW DNS_HOSTS;` shows `ttl=0` and outdated IPs.

Version: `pgbouncer 1.9.0, libevent 2.1.8-stable (epoll), adns: c-ares 1.13.0, tls: LibreSSL 2.6.5`
Also tried the `udns` backend and get the same result.

I cranked up log level to maximum and the only time I see any activity resolving DNS is when the first client connects to pgBouncer.
`dns_max_ttl` is set to 5s. Activating SOA zone checks won't help as my domains are CNAMES to other CNAMES. TTL in DNS is 5s and I have no upstream caching.

In `SHOW LISTS;` the counter `dns_queries` shows a negative number.

The documentation on DNS is quite thin but from what I understand pgBouncer should update DNS every `dns_max_ttl` and invalidate open connections to old IPs. The logs tell me that DNS lookups aren't asynchronous because I don't see lookups every 5s.

Any hints on how I could debug this further? Also, what is the actual expected behavior?
I played with SOA zone checks and see that these get fired every `dns_zone_check_period`.

**Comment by markokr** [comment]
The max_ttl just means cached answer is dropped.  Next request will happen when new connection is needed and that may still take some time.  And when different answer is given then that does not affect other connections as different answer is normal for round-robin DNS.

For fast change detection you can use dns_zone stuff, when SOA serial changes all names under it will be requeried, CNAMEs should work fine.  So new destination is taken into use as fast as possible.

I don't think there is any particular support for dropping old connections based on DNS changes, in case of takeover/failover you are supposed to do it yourself (as in, kill old machine).

**Comment by PJMODOS** [comment]
Well if some IP disappears from the DSN record, we mark everything using that IP as dirty which will clean the connections from pool once they are done with whatever they are doing.

**Comment by joekohlsdorf** [comment]
The problem with doing DNS lookups when needing a new connection is that needing a new connection is rare, after all that is the reason for having a connection pool.

What I am trying to achieve is to redirect traffic from one replica to another by making changes in DNS. I have to reload pgBouncer for it to pick up the updated IPs.
As pointed out there is code to reconnect when IPs change and it works well, I reload the config and this forces a DNS lookup which invalidates connections if IPs have changed.

I have messed with the dns_zone settings but didn't get far because I have a CNAME chain and don't control all domains of the chain. I think the zone stuff wouldn't be needed at all if DNS was asynchronous. The code to run DNS operations in an asynchronous manner is already there, but instead of checking if the SOA serial changed we could just do traditional DNS lookups.

**Comment by markokr** [comment]
PJMODOS: thanks for remainder, seems I've forgotten some of the details.

joe: It's mainly documentation bug indeed.  The main reason for such DNS setup was having ability to react fast on DNS changes but without creating flood of DNS traffic when there are many hostnames in use.

When DNS changes are not seen in SOA, you are on your own.  You could re-query all hostnames yourself and then bump the SOA serial, or even better do periodic hierarchical scan of SOA serials, which would require much less traffic.

**Comment by ats1999** [comment]
> It is easy to misunderstand this. dns_max_ttl isn't the lifetime for a hostname, this only holds true when the pooler needs to open a new connection which is rare.


Yes, it is easy to misunderstand. I did & AI did.

**Comment by ats1999** [comment]
> PJMODOS: thanks for remainder, seems I've forgotten some of the details.
> 
> joe: It's mainly documentation bug indeed. The main reason for such DNS setup was having ability to react fast on DNS changes but without creating flood of DNS traffic when there are many hostnames in use.
> 
> When DNS changes are not seen in SOA, you are on your own. You could re-query all hostnames yourself and then bump the SOA serial, or even better do periodic hierarchical scan of SOA serials, which would require much less traffic.


Its not always possible if you are using service like RDS, we are in no control over there.
