### ISSUE TITLE
Document why query_timeout cannot be as a substitute for statement_timeout

### ISSUE THREAD

**Issue by tuukkamustonen** [pgbouncer/pgbouncer#385]
The docs say:

> **query_timeout**
> Queries running longer than that are canceled. This *should be used only with slightly smaller server-side statement_timeout*, to apply only for network problems. [seconds]

Could it clarify *why* `query_timeout` shouldn't be used as a substitute for `statement_timeout`?

(I'm finding it problematic to set `statement_timeout` properly with my current codebase/ORM, so `query_timeout` would be useful, if not permanent, at least temporary, solution.)

**Comment by tuukkamustonen** [comment]
Found that I can use`connect_query='SET statement_timeout=...'` in `pgbouncer.ini`.

Still would love to know why `query_timeout` is not suitable alternative.

**Comment by petere** [comment]
`statement_timeout` in PostgreSQL aborts a running statement, and then you can run another statement.

`query_timeout` in PgBouncer kills the whole connection. So it's a very brutal solution, especially since the job of PgBouncer is to keep connections open.
