### ISSUE TITLE
A lot of client connections opened

### ISSUE THREAD

**Issue by mazzy89** [pgbouncer/pgbouncer#387]
![image](https://user-images.githubusercontent.com/5463218/57012952-37e87f00-6c09-11e9-951b-055e240d69f9.png)

I have three instances of pgbouncer running.

I'm trying to understand if it is fine to have so many client connections opened with a low number of current database connections opened.

I've read that it could be fine to have a high number of client connections but I'm wondering if these client connections which are not used actively from the servers will be closed anyhow.

**Comment by MichaelDBA** [comment]
Hi,

pgbouncer has a lot of flexibility tuning regarding db and client 
connectivity.

Work with these two parameters to control client connectivity to 
pgbouncer (as opposed to db connectivity between pgbouncer and PG database).

max_client_conn - default = 100
client_idle_timeout - default is disabled, no timeout limit

Regards,
Michael Vitale

Salvatore Mazzarino wrote on 5/1/2019 6:06 AM:
> but I'm

**Comment by mazzy89** [comment]
Thank you @MichaelDBA for quickly reacting on this.

I've tuned `client_idle_timeout` param and I'll check it later if these somehow improved the thing.

**Comment by mazzy89** [comment]
Now that I've set up `client_idle_timeout` (value 600), I get in the logs messages like this:

```
2019-05-01 17:39:18.467 1 WARNING C-0x55b17d99eda0: db/username@127.0.0.1:60502 pooler error: client_idle_timeout
```

I don't think it is supposed to happen. I mean the client connection could go in idle but why does pgbouncer report it as an error?

**Comment by petere** [comment]
In PostgreSQL, timeouts are generally reported as errors, so you can detect them (e.g., `statement_timeout`). Also, in the normal protocol flow, the connection closure has to be initiated from the client, so if the server side wants to close the connection, it has to report an error of some kind. So this is all working normally, it seems to me.

**Comment by petere** [comment]
This seems to be working correctly, so closing.
