### ISSUE TITLE
Does pgbouncer 1.10 support ldap user on Postgresql v11.2?

### ISSUE THREAD

**Issue by booncheow** [pgbouncer/pgbouncer#397]
$psql -U ldapuser -h dbhostname -p 6413 testdb
Password for user ldapuser:
psql: ERROR:  auth failed

$psql -U ldapuser -h dbhostname -p5413 testdb
Password for user ldapuser:
psql (11.2)
Type "help" for help.
testdb=>   <<<< login is good

ldap setting in pg_hba.conf
host    all             all             0.0.0.0/0               ldap ldapserver=ldap.hostname.com ldapport=389 ldapprefix="ad\" ldapsuffix=""

pgbouncer.ini
testdb = host=localhost port=5413 dbname=testdb

listen_addr = *
listen_port = 6413

auth_type = md5
auth_file = userlist.txt

userlist.txt
"ldapuser" "ldap://ldap.hostname.com:389/ldapuser"

Is my setting for ldapuser in userlist.txt correct? 
Is ldapprefix=ad\ required? if yes, how to specify in userlist.txt?

**Comment by petere** [comment]
PgBouncer has no LDAP support of any kind, so I'm not sure what you're trying to set up here, but it's probably not going to work like that.

**Comment by booncheow** [comment]
Was referring to below old discussion -- 
https://pgbouncer-general.pgfoundry.narkive.com/Ma3f7HBg/about-ssl-and-ldap-suport
and it gave me the impression that it supports ldap. 

So the true is, pgbouncer does not support ldap. 

thank you.
