### ISSUE TITLE
Question - help with odd project

### ISSUE THREAD

**Issue by danizen** [pgbouncer/pgbouncer#398]
AWS has an [interesting fork/patch](https://aws.amazon.com/blogs/big-data/query-routing-and-rewrite-introducing-pgbouncer-rr-for-amazon-redshift-and-postgresql/) of pgbouncer that does python calls to try to route queries to appropriate databases and rewrite them to make them more efficient.

In my slightly less large scale world, I would just like pgbouncer to call AWS Secrets Manager to rewrite the auth_file when there is a failure to authenticate.  I asked AWSlabs whether they'd care to collaborate on it in https://github.com/awslabs/pgbouncer-rr-patch/issues/41, and I'm wondering whether someone here can suggest where in `handle_auth_response` I would know that this was an authentication failure.

Given the work of awslabs, I can probably take it from there.

**Comment by petere** [comment]
`handle_auth_response` isn't called during authentication failure, it's called to handle `auth_query`.

I'm not very familiar with the setup your describe, but I don't think this is the right place to look. Perhaps you can use PAM or write your own authentication type similar to PAM.
