### ISSUE TITLE
Feature: have separate log controls for client and server connects/disconnects

### ISSUE THREAD

**Issue by leandropls** [pgbouncer/pgbouncer#402]
I'm using pgbouncer as a connection pool for my application. Because of that, I have much more frequent client connects/disconnects than server connects/disconnects.

I'd like to keep logging only server connects/disconnects and hide the client ones.

I'm willing to work on this if this feature gets approved.

**Comment by petere** [comment]
Seems reasonable. See previous attempt at #123.

**Comment by leandropls** [comment]
Wow, work is almost done then, right? Seems like the only feature missing is handling the legacy config parameters, right?
