### ISSUE TITLE
FATAL @src/objects.c:298 in function put_in_order(): put_in_order: found existing elem

### ISSUE THREAD

**Issue by petere** [pgbouncer/pgbouncer#41]
Under certain circumstances, when making a configuration change and reloading, pgbouncer will crash on the next suitable connection attempt.  (This issue is similar to http://permalink.gmane.org/gmane.comp.db.postgresql.pgbouncer.general/898, but not the same.  Reproducible in 1.5.4 and 1.6rc1.)

Setup:
- `pgbouncer.ini`

``` ini
[databases]
* =
;test = user=postgres

[pgbouncer]
logfile = pgbouncer.log
pidfile = pgbouncer.pid

listen_addr = 127.0.0.1
listen_port = 6432

auth_type = trust
auth_file = userlist.txt
```
- `userlist.txt`

```
"postgres" "foo"
```
- You need a regular PostgreSQL server running on port 5432 with a database called `test`.
1. Start pgbouncer.
2. Connect: `psql -h localhost -p 6432 -U postgres test`
3. Disconnect
4. Uncomment the `test` database entry in `pgbouncer.ini`.
5. Reload: `kill -HUP $(cat pgbouncer.pid)`
6. Connect again.

Now pgbouncer will crash with this message:

```
FATAL @src/objects.c:298 in function put_in_order(): put_in_order: found existing elem
```

It is important that the newly added database entry contains a `user` parameter, otherwise it doesn't crash.

**Comment by rsn86** [comment]
After changing pool_size and max_db_connections and reloading:

PgBouncer chrased with this message:

2015-11-17 15:38:10.038 15862 DEBUG C-0x24260d8: (nodb)/(nouser)@10.1.61.64:59991 got var: user=postgres
2015-11-17 15:38:10.038 15862 DEBUG C-0x24260d8: (nodb)/(nouser)@10.1.61.64:59991 got var: database=db_1g_ext_descanso
2015-11-17 15:38:10.038 15862 DEBUG C-0x24260d8: (nodb)/(nouser)@10.1.61.64:59991 got var: client_encoding=UTF8
2015-11-17 15:38:10.038 15862 DEBUG C-0x24260d8: (nodb)/(nouser)@10.1.61.64:59991 got var: DateStyle=ISO
2015-11-17 15:38:10.038 15862 DEBUG C-0x24260d8: (nodb)/(nouser)@10.1.61.64:59991 got var: TimeZone=Brazil/East
2015-11-17 15:38:10.039 15862 DEBUG C-0x24260d8: (nodb)/(nouser)@10.1.61.64:59991 ignoring startup parameter: extra_float_digits=2
2015-11-17 15:38:10.040 15862 FATAL @src/objects.c:299 in function put_in_order(): put_in_order: found existing elem

I changed from this:
[databases]
db_1g_ext_descanso = port=5432 dbname=db_1grau_producao user=postgres password=md5... pool_size=180 reserve_pool=20 max_db_connections=200

To this:
[databases]
db_1g_ext_descanso = port=5432 dbname=db_1grau_producao user=postgres password=md5... pool_size=200 reserve_pool=20 max_db_connections=220

And: pkill -HUP pgbouncer

**Comment by gbroccolo** [comment]
Hi,

I reproduced again this issue with pgBouncer 1.6.1, just overwriting the authorization file on the filesystem, without performing any reload of the pgBouncer service.

The service has crashed and restarted logging the following error:

FATAL @src/objects.c:299 in function put_in_order(): put_in_order: found existing elem

I suspect that this FATAL has been emitted when the function put_in_order() has been called by add_user(), when the list of user is updated: indeed, put_in_order() exit with the FATAL if the passed list of users does not coincide with the existing one. A similar FATAL is emitted if a new
database pool is defined, probably explaining the issues listed above by petere and rsn86.

Any idea about this?

**Comment by PJMODOS** [comment]
I can't reproduce this any more on latest version of pgbouncer so I would suggest you to upgrade and report back with exact steps to reproduce if the issue persists.

**Comment by rsaffi** [comment]
I have just stumbled on this. Currently running `pgbouncer version 1.7.2`.
Made a change to one of the database entries on the config file and issued a `RELOAD;` on the admin console of pgbouncer. Next connection attempt triggered the FATAL:

> 2017-08-29 11:45:04.936 3748 FATAL @src/objects.c:299 in function put_in_order(): put_in_order: found existing elem

**Comment by Nastradamus** [comment]
@PJMODOS ,

I reproduced this bug in 1.7.2:

1. Create pool:
`bug = dbname=postgres user=test_role`

2. Connect to this pool:
`psql -p 6432 -d bug -Utest_role -c 'select 1'`

3. Remove user mapping from pool:
`bug = dbname=postgres`

4. Do an online restart to avoid "WARNING losing forced user not supported, keeping old setting"
`sudo -u postgres bash -c '/usr/sbin/pgbouncer -d -R /etc/pgbouncer/pgbouncer-dev.ini'`

5. Put user mapping back to pool:
`bug = dbname=postgres user=test_role`

6. Reload pgbouncer:
`/etc/init.d/pgbouncer-dev reload`

7. Connect to pool:
`psql -p 6432 -d bug -Utest_role -c 'select 1'`

8. Pgbouncer will crash with message:
`2018-03-02 13:51:22.042 29017 FATAL @src/objects.c:299 in function put_in_order(): put_in_order: found existing elem`

**Comment by lawrencejones** [comment]
Hey @Nastradamus, I believe the following PR should fix this issue:

https://github.com/pgbouncer/pgbouncer/issues/250

I'm not sure when it might get a review though.

**Comment by chethanhr89** [comment]
Hi I am facing the same issue. But here I have not changed anything. PGBouncer is going down with error
FATAL @src/objects.c:366 in function put_in_order(): put_in_order: found existing elem
version is 1.19.0
any idea what could be the reason?

**Comment by JelteF** [comment]
Update to a recent version that should fix it

**Comment by chethanhr89** [comment]
To provide an accurate RCA, we first need to identify the root cause of the issue. Once the reason is confirmed, we can verify whether the bug has been addressed in the latest version.

**Comment by JelteF** [comment]
Then do some actual research instead of posting to a 8 year old issue asking for help... AND then not listening to the project maintainer telling you to upgrade to a non-ancient version.
