### ISSUE TITLE
[Q] proper way to cancel a query

### ISSUE THREAD

**Issue by utrack** [pgbouncer/pgbouncer#411]
What's the proper way to signal that we don't want the query's results anymore?

`PKT_CANCEL` can be used when we're connecting to postgres directly; however, what happens when I send that via pgbouncer? I feel like cancellation query can(will) hit a wrong replica.

To cancel current query we need to acquire a secret key via `BackendKeyData` - is it sent to the client each time a connection is acquired? Especially in transactional mode.

Also, is there any way to signal per-query/per-transaction timeout when operating in transactional mode?

**Comment by utrack** [comment]
I've found that you're converting <pid,secret> of a conn to pgBouncer to <pid,secret> of a conn to pg replica. Only the part about per-query timeout is left :)

**Comment by petere** [comment]
There are various timeout settings in PgBouncer and also in the PostgreSQL backend that you could use, depending on what you are trying to achieve.
