### ISSUE TITLE
Pooler Error: pgbouncer cannot connect to server

### ISSUE THREAD

**Issue by abdomazzika** [pgbouncer/pgbouncer#412]
Hi,

We are using pgbouncer stable helm chart version 0.2.0 in our k8s cluster to connect to sql instance running on Google Cloud
So problem is pgbouncer is failing intermittently, log says that 'Pooler Error: pgbouncer cannot connect to server'.

And this is my configuration:

[pgbouncer]
    listen_addr = *
    listen_port = 5432
    unix_socket_dir = /var/run/postgresql
    auth_type = md5
    auth_file = /etc/pgbouncer_users/userlist.txt
    admin_users = pgbouncer_admin
    pool_mode = transaction
    server_reset_query = DISCARD ALL
    max_client_conn = 3000
    default_pool_size = 750
    min_pool_size = 200
    max_db_connections = 750
    max_user_connections = 3000
    dns_max_ttl = 600
    ignore_startup_parameters = extra_float_digits

So i can prevent this behavior from happening again ( if anything missing i can add in a configuration or something i don't know ! ). Thanks

**Comment by petere** [comment]
Check the logs.

**Comment by petere** [comment]
closing because no response
