### ISSUE TITLE
new server fails on autogen.sh step

### ISSUE THREAD

**Issue by jayverizon** [pgbouncer/pgbouncer#419]
I've been asked to build pgbouncer on a new AWS EC2 instance running some flavor of linux. uname -a is only producing GNU/Linux, so I can't tell what vendor created it. Anyway, I followed the below steps as noted in the instructions:

$ git clone https://github.com/pgbouncer/pgbouncer.git
$ cd pgbouncer
$ git submodule init
$ git submodule update
$ ./autogen.sh

but, autogen.sh fails with:

./lib/mk/std-autogen.sh: line 78: libtoolize: command not found
./lib/mk/std-autogen.sh: line 81: libtoolize: command not found

This error did not occur when I built this on a since deleted server.

I'm open to ideas as for fixing this,
Jay

**Comment by markokr** [comment]
The readme says about building from Git:

> Additional packages required: autoconf, automake, libtool, pandoc

**Comment by jayverizon** [comment]
Yep, I was missing autoconf and automake on this new server. Thanks.
