### ISSUE TITLE
relation does not exist errors

### ISSUE THREAD

**Issue by kos12345** [pgbouncer/pgbouncer#425]
i have  postgresql version 9.6.  client wrote on Ruby on Rails.
i try use pgbouncer to  connect to database.
And postgres was reporting tons of "relation" does not exist errors. Here are some snippets from the logs:
QUERY: SELECT  "table1".* FROM "table1" WHERE "table1"."type" = ('....')  LIMIT 1
ERROR: relation "table1" does not exist.

Restart  pgbouncer did not solve the problem.

**Comment by Melkij** [comment]
Do you use transaction pool mode? If so - most likely someone called `set search_path to ...` query through pgbouncer. This is not compatible with transaction pool mode and pgbouncer can not do something usefull here. Pgbouncer does not inspect queries.

**Comment by kos12345** [comment]
Yes. transaction pool mode.  Thnak you!
