### ISSUE TITLE
The 'min_pool_size' setting is not always respected.

### ISSUE THREAD

**Issue by barqshasbite** [pgbouncer/pgbouncer#426]
This could be considered a bug or "by design", depending on how you look at it.

The behavior of 'min_pool_size' is not entirely clear. Or perhaps the documentation is not clear.

My expectation was that it would maintain the 'min_pool_size' at all times. However this does not appear to be the case.

The documentation currently states:

> Add more server connections to pool if below this number. Improves behavior when usual load comes suddenly back after period of total inactivity.

However, it appears (from testing and looking at the code) that 'min_pool_size' is only used and respected when the number of clients connected to the pool is greater than 0:
```
    /* launch extra connections to satisfy min_pool_size */
    if (cur < cf_min_pool_size &&
        cur < pool->db->pool_size &&
        cf_pause_mode == P_NONE &&
        cf_reboot == 0 &&
        pool_client_count(pool) > 0)
    {
        log_debug("launching new connection to satisfy min_pool_size");
        launch_new_connection(pool);
    }
```

When the 'min_pool_size' setting was introduced, the documentation more accurately (but still not quite right) stated:

> Minimal pool size.  PgBouncer will open this many connections to backend database **after first client connect**.  Optional, not recommended in most normal setups.

It at least indicated the need for a client to connect before the 'min_pool_size' setting was used.

Due to this behavior, it is possible for a pool to drop to zero connections over a prolonged period (due to 'server_lifetime') and then cause a sudden spike in connections when a client connects. This can cause performance problems for both the clients and the database server, which is the opposite of what 'min_pool_size' is supposed to do.

It would be better if the restriction of having at least one client connected be optional (or removed if it is a bug). Adding a new setting that defaults to the current behavior may be the safest approach.

**Comment by andrp92** [comment]
Heeey this issue is very serious, is anybody paying attetion to it?

**Comment by PJMODOS** [comment]
Yes it's by design, I can imagine having option to change the behavior, but nobody is working on adding that at the moment AFAIK.
