### ISSUE TITLE
Why make is error ?

### ISSUE THREAD

**Issue by fhbzyc** [pgbouncer/pgbouncer#43]
/usr/bin/ld: .objs/pgbouncer/lib/usual/crypto/csrandom.o: undefined reference to symbol 'pthread_once@@GLIBC_2.2.5'
/usr/bin/ld: note: 'pthread_once@@GLIBC_2.2.5' is defined in DSO /lib64/libpthread.so.0 so try adding it to the linker command line

my system is Centos7.

**Comment by markokr** [comment]
its a bug, -lpthread is missing from build.  but i will remove its usage from 1.6 final

**Comment by sezal** [comment]
The same thing on Ubuntu. Is there any suggestions how to build from trunk?

**Comment by sezal** [comment]
Adding -lpthread to Makefile helped
```
pgbouncer_LDADD := $(CARES_LIBS) $(LIBS) -lpthread
```

**Comment by markokr** [comment]
pthread req is removed now.
