### ISSUE TITLE
Identify the real client IP Instead of Pgbouncer Host IP

### ISSUE THREAD

**Issue by sianyin** [pgbouncer/pgbouncer#435]
Hi,

I need to trace the real client IP in postgresql instead of pgbouncer IP. I know there is an option to add the IP to application_name but sometimes it is overwritten. 

Can pgbouncer add additional parameter to pass into postgresql?
There is a connect_query parameter, but it seem doesn't pass in the parameter needed, else I would have insert the client info to DB tables.

Is the anyway I can achieve this purpose?
 
Regards
Sian Yin

**Comment by petere** [comment]
That's what `application_name_add_host` is for. You say the application name is sometimes overwritten. How does that happen?
