### ISSUE TITLE
OpenSSL not found when cross-compiling for Windows on Ubuntu

### ISSUE THREAD

**Issue by SeppPenner** [pgbouncer/pgbouncer#442]
Hi, I have the following setup:

Ubuntu 19.04 (Desktop) with the following packages installed:

* [GNU Make >= 3.81](https://www.gnu.org/software/make/)
* [Libevent >= 2.0](http://libevent.org/)
* [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/)
* [OpenSSL >= 1.0.1](https://www.openssl.org/)
* [Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
* [libtoolize](https://manpages.debian.org/stretch/libtool/libtoolize.1.en.html)
* [gcc-mingw-w64](http://mingw-w64.org/doku.php)
* [mingw-w64](http://mingw-w64.org/doku.php)
* [libssl-dev](https://packages.debian.org/de/jessie/libssl-dev)

(All of them have the latest version available).

I'm running the following commands:

```bash
git clone https://github.com/pgbouncer/pgbouncer.git
cd pgbouncer
git submodule init
git submodule update
./autogen.sh
./configure --host=i686--w64-mingw32 ...
make
```

However, when running **configure**, I get the error that OpenSSL couldn't be found. More specific: 

```bash
conftest.c:48:14: fatal error: openssl/ssl.h: No such file or directory
```

Any suggestions? I already tried to install OpenSSL from the sources as described [here](https://stackoverflow.com/questions/17915098/openssl-ssl-h-no-such-file-or-directory-during-installation-of-git) and specify the folder with the `--with-openssl=/usr/bin/openssltestinstall` with no success.

When I just run `./configure --host=i686-w64-mingw32 --without-openssl...`, it works, but the **make** command fails with `usual/event.h: File or directory not found`...

**EDIT**: I have now installed **autoconf, automake, libtool, pandoc** as well. Now, the **configure** command only tells: `checking for OpenSSL... configure: error: not found`. The **make** command still fails, but with `i686-w64-mingw32-gcc_ error_ LIBEVENT_CFLAGS@: File or directory not found. make: *** [/home/demo/pgbouncer/lib/mk/antimake.mk:1230 .objs/pgbouncer/src/admin.o] Error 1]`

**Comment by petere** [comment]
If you do this, you would need to install a Windows port of OpenSSL. You can't just link against the normal Ubuntu OpenSSL library.

**Comment by SeppPenner** [comment]
Ah okay, I will try that.

**Comment by SeppPenner** [comment]
Ok, I now tried to build this from the Source in Windows using MinGW. The problem is that I can only do the following steps:

```bash
git clone https://github.com/pgbouncer/pgbouncer.git
cd pgbouncer
git submodule init
git submodule update
```

`./autogen.sh` only tells me:

```log
Using autoconf: 2.68
Using aclocal: 1.11
```
, nothing more...

`./configure ...` doesn't work either because there is only a `config.mak.in` and a `configure.ac` file?

@petere Can you give me a hint here? I'm not really familiar with `make` and that stuff...

**Comment by petere** [comment]
Try running

    sh -x ./lib/mk/std-autogen.sh ./lib

and see what it prints out.

**Comment by SeppPenner** [comment]
@petere I get the following message:

```log
$ sh -x ./lib/mk/std-autogen.sh ./lib
+ set -e
+ USUAL_DIR=./lib
+ test -n ./lib
+ test -f ./lib/m4/usual.m4
+ ACLOCAL=aclocal
+ AUTOCONF=autoconf
+ AUTOHEADER=autoheader
+ test '' = ''
+ test autoconf = autoconf
+ for ac in 70 69 68 67 66 65 64 63 62 61 60 59
+ ac=2.70
+ which autoconf-2.70
+ which autoconf2.70
+ for ac in 70 69 68 67 66 65 64 63 62 61 60 59
+ ac=2.69
+ which autoconf-2.69
+ which autoconf2.69
+ for ac in 70 69 68 67 66 65 64 63 62 61 60 59
+ ac=2.68
+ which autoconf-2.68
+ AUTOCONF_VERSION=2.68
+ echo 'Using autoconf: 2.68'
Using autoconf: 2.68
+ break
+ test '' = ''
+ test aclocal = aclocal
+ for am in 1.16 1.15 1.14 1.13 1.12 1.11 1.10 1.9
+ which aclocal-1.16
+ which aclocal1.16
+ for am in 1.16 1.15 1.14 1.13 1.12 1.11 1.10 1.9
+ which aclocal-1.15
+ which aclocal1.15
+ for am in 1.16 1.15 1.14 1.13 1.12 1.11 1.10 1.9
+ which aclocal-1.14
+ which aclocal1.14
+ for am in 1.16 1.15 1.14 1.13 1.12 1.11 1.10 1.9
+ which aclocal-1.13
+ which aclocal1.13
+ for am in 1.16 1.15 1.14 1.13 1.12 1.11 1.10 1.9
+ which aclocal-1.12
+ which aclocal1.12
+ for am in 1.16 1.15 1.14 1.13 1.12 1.11 1.10 1.9
+ which aclocal-1.11
+ AUTOMAKE_VERSION=1.11
+ echo 'Using aclocal: 1.11'
Using aclocal: 1.11
+ break
+ export AUTOCONF_VERSION AUTOMAKE_VERSION
+ test x = x
+ LIBTOOLIZE=glibtoolize
+ which glibtoolize
+ LIBTOOLIZE=libtoolize
+ rm -f config.guess config.sub install-sh ltmain.sh libtool
+ cp -p ./lib/mk/install-sh .
+ libtoolize --help
+ grep '[-][-]install'
+ libtoolize -i -f -q -c
libtoolize: $pkgltdldir is not a directory: `/mingw/share/libtool'
```

**Comment by petere** [comment]
> ```
> + libtoolize -i -f -q -c
> libtoolize: $pkgltdldir is not a directory: `/mingw/share/libtool'
> ```

That looks like your Libtool installation is defective.

**Comment by SeppPenner** [comment]
Sorry for disturbing you here, but I still don't see the issue...

My MinGW installation is located under "C:\MinGW\share", the folder for `libtool` looks like this: https://github.com/SeppPenner/MinGW-libtool.

I have now installed all packages available using the MinGW-Get installer for Windows while the setup still fails with the same error...

![image](https://user-images.githubusercontent.com/9639361/72966727-e6e47080-3dbf-11ea-9d23-96baa76293f6.png)

**Comment by petere** [comment]
This might have something to do with how MinGW deals with Unix vs Windows paths (`/mingw/share` vs `C:/MinGW/share`), but that's really beyond the remit of this forum to debug. If Libtool outright doesn't work , you need to take that up with whoever provided you with that package.

You can also download a tarball and use that to build instead of a Git checkout. That already has all the autotools stuff included.

**Comment by SeppPenner** [comment]
Ok, thank you for your time. I will try that :)

**Comment by SeppPenner** [comment]
Hello @petere. It's again me :) Sorry for bothering you again.

I have now:
1. Uninstalled my MinGW installation.
2. Installed MinGW and all packages again.
3. Checked out the commit with version tag v1.12.0.

`./autogen.sh` gives me now:

```log
$ ./autogen.sh
Using autoconf: 2.68
Using aclocal: 1.11
configure.ac:17: error: possibly undefined macro: PKG_PROG_PKG_CONFIG                                                         If this token and others are legitimate, please use m4_pattern_allow.                                                   See the Autoconf documentation.                                                                                   configure.ac:57: error: possibly undefined macro: PKG_CHECK_MODULES 
```

I guess, I'm coming closer to the real problem now.

**Comment by petere** [comment]
You need to install pkg-config.

**Comment by SeppPenner** [comment]
It's installed now. I followed https://stackoverflow.com/questions/1710922/how-to-install-pkg-config-in-windows and put it in the `C:\MinGW` folder. When I open the MinGW shell, and type `pkg-config.exe`, I get `Must specify package names on the command line`, so it should be working properly...

However, I still get the same error...
![Test](https://user-images.githubusercontent.com/9639361/76168642-f81bed80-6171-11ea-933c-c17cae6a7312.png)

Do you have any other ideas on this issue?

**Comment by petere** [comment]
You should get the pkg-config package from wherever you get the rest of your MinGW installation, not some random place.

**Comment by SeppPenner** [comment]
Well, I'm using the official installation from http://www.mingw.org/ with the MinGW installation manager. There is no `pkg-config` available.

By the way, I wouldn't call ftp.gnome.org `some random place`...

**Comment by petere** [comment]
I suggest using https://www.msys2.org/ for your MinGW needs. This is what I use and we even have CI for it: https://ci.appveyor.com/project/petere/pgbouncer-pgbouncer

In any case, this is not really a PgBouncer issue. It's just a matter of getting your local software installed in a self-consistent way. Other Autoconf-using software works the same way.

**Comment by SeppPenner** [comment]
Ok, thank you. I will try this.

That's true and I'm sorry to bother you here. It's just that I didn't find anyone who was able to build pgbouncer on their own. There is an unresolved Stackoverflow issue for this (Some other guy opened it) as well: https://stackoverflow.com/questions/37925410/how-to-install-pgbouncer-on-windows-7-x64

**Comment by SeppPenner** [comment]
Short update: It works now, thank you really much. Was a hard way for someone who doesn't have much experience with C or C++ and the build tools.

However, I'm still failing one small thing. I can't get `pandoc` to work properly. I have installed it from https://pandoc.org/installing.html and added `C:\Program Files\Pandoc` to the system environment variables.

```bash
# make
     CCLD     pgbouncer.exe
make -C doc
python filter.py frag-usage-man.md usage.md >pgbouncer_1.md
pandoc -s -t man -o pgbouncer.1 pgbouncer_1.md
make[1]: pandoc: No such file or directory
make[1]: *** [Makefile:23: pgbouncer.1] Fehler 127
rm pgbouncer_1.md
make: *** [Makefile:171: doc/pgbouncer.1] Fehler 2
```

**Comment by petere** [comment]
I haven't figured out how to get Pandoc working on Windows yet either. There is an evil workaround that you can see here: https://github.com/pgbouncer/pgbouncer/blob/master/.appveyor.yml

Again, alternatively, you can try to build from the release tarballs, which have the autoconf stuff and the pandoc stuff prebuilt.

**Comment by SeppPenner** [comment]
> I haven't figured out how to get Pandoc working on Windows yet either. There is an evil workaround that you can see here: https://github.com/pgbouncer/pgbouncer/blob/master/.appveyor.yml

Looks really ugly... :D

> Again, alternatively, you can try to build from the release tarballs, which have the autoconf stuff and the pandoc stuff prebuilt.

Thank you, this works perfect! :) 👍

**Comment by SeppPenner** [comment]
I put my steps under https://sepppenner.github.io/PgBouncerWinBinaries/ or https://github.com/SeppPenner/PgBouncerWinBinaries for anyone who is interested.
