### ISSUE TITLE
Feature request: Support encrypting passwords in auth_file

### ISSUE THREAD

**Issue by MannerMan** [pgbouncer/pgbouncer#444]
If one wants to autenticate both connecting clients and connections to the postgres server from pgbouncer using SCRAM, one has to provide passwords in `auth_file` in plain text. Documentation mentions this;

> **scram-sha-256**
    Use password check with SCRAM-SHA-256. auth_file has to contain SCRAM secrets or plain-text passwords. Note that SCRAM secrets can only be used for verifying the password of a client but not for logging into a server. To be able to use SCRAM on server connections, use plain-text passwords

I also confirmed this was the case by testing a SCRAM hash defined in `auth_file`, clients could authenticate, but server connections from pgbouncer could not. Using a plain-text password in `auth_file` resolves the issue. This is to my understanding a side-effect of the SCRAM cryptography method; pgbouncer needs to know the full password to be able to authenticate against postgres.

Using plain text passwords in configuration files is generally not compliant with various security standards, meaning in effect one must keep using the less-secure md5 authentication method to be somewhat compliant. 

I noticed 'pgpool-II' supports aes-encypting passwords for this reason:
https://www.pgpool.net/docs/41/en/html/auth-aes-encrypted-password.html

> SCRAM authentication guards against the man-in-the-middle type of attack, so Pgpool-II    requires the user password to authenticate with the PostgreSQL backend.
> 
> However, storing the clear text passwords in the "pool_passwd" file is not a good idea.
> 
> You can instead store AES256 encrypted passwords, which will be used for authentication. The password is first encrypted using the AES256 encryption with the user provided key and then the encrypted password is base64 encoded and an AES prefix is added to the encoded string. 

Maybe pgbouncer could add something similar?

**Comment by petere** [comment]
This has been addressed by ba1abfe4d94c155a8db22d0b40d513b047c9bf06.
