### ISSUE TITLE
Prompted for password

### ISSUE THREAD

**Issue by MichaelDBA** [pgbouncer/pgbouncer#447]
Im using pbouncer to connect to an AWS RDS PG instance.

So I have added user/passwords to userlist.txt file with the passwords in plain text since the documentation says if auth_type = md5, then the password can either be md5 format or plain text.

I had to use plain text since RDS does not allow pg_bouncer to query the pg_shadow or pg_authid tables.

But when I try to connect to either the local pgbouncer database or the remote PG database, I am always prompted for a password.  Why?  and how to get around this.

pgbouncer.ini:
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
 
userlist.txt file is populated this way:
"user id" "plain text password"

**Comment by petere** [comment]
You are confusing the client->pgbouncer authentication with the pgbouncer->server authentication.

The `auth_type` setting you show above says to authenticate clients connecting to pgbouncer using the md5 method against the passwords stored in the `auth_file`. So that's why you are getting a password prompt.

When pgbouncer is connecting to the server, the authentication method chosen is determined by the server.

So if you don't want the password prompt, choose a different `auth_type`.

**Comment by MichaelDBA** [comment]
So back to the original reason I am having this problem.  I am trying to connect pgbouncer to an AWS RDS instance, which prohibits anyone from querying the pg_shadow table.  So if md5 is turned on from the database end, I need to have a userlist.txt file with user/password pairs, right?
That's the whole point about the mkauth.py functionality, right?  To get user/md5 pairs for server authentication.

**Comment by petere** [comment]
pgbouncer doesn't query pg_shadow unless you explicitly tell it to, using an `auth_query` setting.

**Comment by MichaelDBA** [comment]
So, it seems it works with RDS if I define auth_type = trust, but put the md5 hash for each user in the userlist.txt file.  If I make auth_type = md5, it won't work.  With trust, it will accept either plain text password or md5 hash password.  

So, it is a bit of a pain for me in RDS since I have to know the passwords of each user, get the md5 hash of it (select 'md5' || md5('mypassword' || 'myuser')), and put that md5 hash password in the userlist.txt file.

This is all because RDS does not allow you to query the pg_shadow table.

Anything I am missing here?  Again I am using pgbouncer v1.12.

**Comment by MichaelDBA** [comment]
Can I get a comment regarding my last comment?

**Comment by petere** [comment]
> So, it seems it works with RDS if I define auth_type = trust, but put the md5 hash for each user in the userlist.txt file. If I make auth_type = md5, it won't work. With trust, it will accept either plain text password or md5 hash password.

This doesn't make sense. If you set auth_type = trust, then it won't ask for a password at all. That part doesn't have anything to do with RDS either, since it's just the communication between the client and pgbouncer.

> So, it is a bit of a pain for me in RDS since I have to know the passwords of each user, get the md5 hash of it (select 'md5' || md5('mypassword' || 'myuser')), and put that md5 hash password in the userlist.txt file.
> 
> This is all because RDS does not allow you to query the pg_shadow table.
> 
> Anything I am missing here?

Nothing. RDS is just annoying like that.
