### ISSUE TITLE
PGbouncer stopped connecting to RDS instances randomly about 5 hours ago

### ISSUE THREAD

**Issue by arskinner** [pgbouncer/pgbouncer#454]
We've had pgbouncer running for months, connecting to Amazon Postgres RDS instances without issue.

Suddenly today around 5am pacific time pgbouncer can no longer connect to the instances.

I created a vanilla EC2 instance and installed the latest pgbouncer fresh, and have the same issue.

However from the same EC2 instance I am able to connect directly to RDS using psql.

PGbouncer prints this in the log (with -v -v on)

```
2020-01-10 17:47:41.794 UTC [10758] LOG C-0x808800: dev_primary/pgbouncer@unix(10759):6432 closing because: client_login_timeout (server down) (age=60s)
2020-01-10 17:47:41.794 UTC [10758] WARNING C-0x808800: dev_primary/pgbouncer@unix(10759):6432 pooler error: client_login_timeout (server down)
```

Any help is appreciated, thanks!

**Comment by arskinner** [comment]
Well we figured out this issue here and I guess it's largely our fault.

Our server installation scripts were cloning from master. Some commit to master over the last 12-24 hours must have broken connections. Might want to look into that, but this can be closed I think. Fixed by pinning the clone to the release tag.

**Comment by petere** [comment]
Hmm, the only significant change in that time frame would be 1e5322a78e6f9ede78ed65594bfaa75907e45c3d, but that shouldn't affect any behavior. It would be helpful if you could try to reproduce the issue.

**Comment by jcust** [comment]
We ran into this issue as well when we were doing updates to our environment (pgbouncer on EC2, database is Aurora PostgreSQL). We were also cloning from master, and going back to 1.11.0 fixed the problem.

We observed the same symptoms as @arskinner:

- client_login_timeout (server down) errors in pgbouncer logs
- able to connect directly to the RDS endpoint using `psql` on the same instance

pggbouncer config (nothing out of the ordinary, but in case it helps):

```
[pgbouncer]
listen_port = 6432
listen_addr = 127.0.0.1
auth_type = md5
auth_file = /etc/pgbouncer/users.txt
logfile = /var/log/pgbouncer.log
verbose = 1
pidfile = /var/run/pgbouncer/pgbouncer.pid
default_pool_size = 25
max_client_conn = 800
server_tls_protocols = secure
server_idle_timeout = 180
server_tls_sslmode = require
server_tls_ca_file = /etc/pgbouncer/certs/rds-combined-ca-bundle.pem
```

**Comment by arskinner** [comment]
@jcust Thanks for the corroboration, nice to know I'm not crazy. FWIW 1.12.0 works fine too (for us).

**Comment by petere** [comment]
So I've been wondering why we have reports about things not working with RDS specifically, while the test suite and all local tests are working. Could this have something to do with DNS? Does your `[databases]` configuration specify host names (not IP addresses)? If so, which DNS backend is your pgbouncer built with (check the `LOG process up` line)?
