### ISSUE TITLE
Connection params to turn off PreparedStatements 

### ISSUE THREAD

**Issue by TXAggie2000** [pgbouncer/pgbouncer#456]
We have a third party application that connects to our pgbouncer.  This application uses preparedstatements and we have no control over the code.  When connected directly to postgresql database, we have no issues, but going through pgbouncer we continue to have errors.  I have added the params: prepareThreshold=0&preparedStatementCacheQueries=0 to the connection string, and for a while it works fine, but will randomly stop working and the application throws the error (prepared statement "S_1" does not exist).  Session level pooling is not an option, so with no control over the calling code, how can I get this to work with pgbouncer?

**Comment by petere** [comment]
It appears you are using JDBC, so `prepareThreshold=0` is the right configuration, but if that doesn't work, then it's beyond the scope of this forum to analyze that.
