### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by nguyenxuanluong-luvina** [pgbouncer/pgbouncer#463]
Hi, I'm attending to using to using pgbouncer on windows, but seem compile instruction not so details for me ( a newbie)
Could you adding more detail
I did following steps but failed:
1. Installed MinGW 
2. Clone git pgbouncer project 
3. cd pgbouncer
4. Run : ./configure ...

```
D:\pgbouncer>./configure ...
'.' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by eulerto** [comment]
@nguyenxuanluong-luvina Run `autogen.sh` before `configure`. Indeed, `Building on Windows` section definitely should have all steps.

**Comment by petere** [comment]
It sounds like you are running `configure` under a Windows shell of some kind, not the MinGW (MSYS) bash.

**Comment by SeppPenner** [comment]
@nguyenxuanluong-luvina Follow my steps under https://sepppenner.github.io/PgBouncerWinBinaries/ or https://github.com/SeppPenner/PgBouncerWinBinaries.

I also had a lot of issues, but @petere helped me 👍 (https://github.com/pgbouncer/pgbouncer/issues/442).

**Comment by SeppPenner** [comment]
@petere This guy from http://winpg.jp/~saito/pgbouncer/ (Website doesn't exist anymore) somehow got a file called `pgbevent.dll` for Windows. Do you know how I can get this file for the 1.12 release from the build process?

You can check the zip file I copied from the Saito page here: https://github.com/SeppPenner/PgBouncerWinBinaries/tree/master/Downloads_Saito.

**Comment by char101** [comment]
[pgbevent](https://github.com/pgbouncer/pgbouncer/blob/master/win32/pgbevent.c) is right there in the win32 directory. You'll just need to compile it as a dll.
