### ISSUE TITLE
log client close request (age=0)

### ISSUE THREAD

**Issue by sylvioneto** [pgbouncer/pgbouncer#464]
Hello, I have the pgbouncer deployed in Kubernetes - GCP, and I/m getting plenty of entries with the message below in Stackdriver Logging:
```
severity:  "ERROR"  
textPayload:  "2020-01-15 15:30:55.849 1 LOG C-0x55b5c3ed17e0: airflow/airflow@10.153.129.36:48374 closing because: client close request (age=0)
```
Its severity is ERROR but I'm not facing any problem with pgbouncer. So I'm wondering if that should be set as INFO message and not ERROR.

pgbouncer version: 1.9.0

**Comment by petere** [comment]
Well, as you can see, pgbouncer logs it as `LOG`. I don't know why your Kubernetes stack turns that into "ERROR", but it might be something other than pgbouncer doing it.
