### ISSUE TITLE
Allow IntervalStyle parameter (like DateStyle)

### ISSUE THREAD

**Issue by iamed2** [pgbouncer/pgbouncer#470]
IntervalStyle is a similar parameter to DateStyle (controls output format for a data type, passed in the same way to PostgreSQL connections). Currently the [Julia PostgreSQL client library](https://github.com/invenia/LibPQ.jl/blob/master/src/connections.jl) only supports parsing one IntervalStyle format, and it is not the default one, so it would be nice to have support for connecting with this option.

**Comment by petere** [comment]
OK, this should be fairly easy to add, but why in the world does anyone even use this parameter? It's mostly obsolete and deprecated, I think.

**Comment by iamed2** [comment]
It's a more compact interval format for transport (in text format) than `postgres`. It's also still parsed by [Java](https://download.java.net/java/GA/jdk14/docs/api/java.base/java/time/Duration.html#parse(java.lang.CharSequence)).

**Comment by sj26** [comment]
We were bitten by this recently because Rails also sets intervalstyle:

https://github.com/rails/rails/blob/v7.0.4.3/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L882-L883

GitLab seem to hit it as well:

https://gitlab.com/gitlab-org/gitlab/-/issues/349912
