### ISSUE TITLE
Cannot set pool_size

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [pgbouncer/pgbouncer#471]
Hi,
when I set pool_size it says invalid value in configuration,
however I can set default_pool_size, any idea?

my config

------------------------------

[databases]

template1 =
postgres =
test_pgbench =

[pgbouncer]

log_stats = 0
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /run/pgbouncer/pgbouncer.pid

listen_addr = 127.0.0.1,10.0.0.1,10.0.0.76,10.0.0.138,10.0.0.230,10.0.0.5
listen_port = 6432
unix_socket_dir = /run/postgresql

;;; any, trust, plain, crypt, md5

auth_type = trust
auth_file = /etc/pgbouncer/userlist.txt

;;; auto, session, transaction, statement
pool_mode = session

admin_users = postgres
stats_users = postgres

;;; Syslog settings
syslog = 0
syslog_facility = daemon
syslog_ident = pgbouncer
log_connections = 0
log_disconnections = 0
log_pooler_errors = 1
stats_period = 3600
verbose = 0

;;; short timeouts
server_check_delay = 33
server_lifetime = 33
server_idle_timeout = 33
server_connect_timeout = 33
server_fast_close = 1
server_login_retry = 33
query_timeout = 66
query_wait_timeout = 33
idle_transaction_timeout = 66
client_idle_timeout = 66
client_login_timeout = 33
suspend_timeout = 33
max_client_conn = 16000
default_pool_size = 3200

;;; Low-level tuning options
;pkt_buf = 4096
;listen_backlog = 256
;sbuf_loopcnt = 5
;max_packet_size = 2147483647

;;; networking options, for info: man 7 tcp
tcp_user_timeout = 12500
tcp_keepalive = 1
tcp_keepidle = 1
tcp_keepintvl = 15
tcp_keepcnt = 3
tcp_defer_accept = 15
tcp_socket_buffer = 8192
dns_max_ttl = 15
dns_zone_check_period = 0
dns_nxdomain_ttl = 15

;;; Hackish security feature.  Helps against SQL-injection - when PQexec is disabled,
;;; multi-statement cannot be made.
disable_pqexec = 0

**Comment by petere** [comment]
This configuration works for me (after making some adjustments to the paths).

Note that `tcp_user_timeout` is a new option, not released yet. Are you using the master branch?

**Comment by petere** [comment]
stale, closing
