### ISSUE TITLE
Set version information when built for Windows

### ISSUE THREAD

**Issue by SeppPenner** [pgbouncer/pgbouncer#473]
Is there a way to add a version information to the pgbouncer.exe file (when building for Windows manually) somehow? This would be really helpful.

**Comment by petere** [comment]
Doesn't

    pgbouncer.exe --version

show anything useful?

**Comment by SeppPenner** [comment]
This works, yes. I just looked into the Windows settings under "details" and there was no version information. This was a bit confusing :D

**Comment by petere** [comment]
> I just looked into the Windows settings under "details" and there was no version information.

I don't know what that means (not a Windows user).

Suggestions for improvement are welcome, but if they are specific to Windows you'd probably have to do most of the implementation work, too.

**Comment by SeppPenner** [comment]
Ah ok. I'm talking about this window: 
![image](https://user-images.githubusercontent.com/9639361/79693328-38d74e00-826a-11ea-8dbb-2100a64e8b1c.png). There, a file version and some other properties can be set.

> Suggestions for improvement are welcome, but if they are specific to Windows you'd probably have to do most of the implementation work, too.

I would really like to do that but I have no idea how (and I'm working with C# most of the time, not C).

I guess, it's ok if there is a command to get the version information.

**Comment by petere** [comment]
OK, that's something we can fix.
