### ISSUE TITLE
SSL routines errors

### ISSUE THREAD

**Issue by trourance** [pgbouncer/pgbouncer#477]
Hi,
I'm using pgbouncer 1.12.0 which replaces the previous combo stunnel/pgbouncer.
I'm connecting with JDBC clients and today I've received the following errors in pgbouncer:
`WARNING TLS handshake error: handshake failed: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error`
`WARNING TLS handshake error: handshake failed: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac`
and on the client side, I had the following:
`org.postgresql.util.PSQLException: SSL error: point has incorrect order`
`org.postgresql.util.PSQLException: SSL error: Received fatal alert: bad_record_mac`

What does it mean and why do I get those issues randomly ?

**Comment by petere** [comment]
Does it work if you are using a client other than JDBC (say, psql)?

**Comment by trourance** [comment]
Yes it does. It seems it's due to an issue with openj9 on the client side, sorry for the noise.

https://github.com/eclipse/openj9/issues/9132
