### ISSUE TITLE
Where does pgbouncer handle authentication failures

### ISSUE THREAD

**Issue by danizen** [pgbouncer/pgbouncer#486]
I am interested in providing an alternate version where pgbouncer takes some asynchronous action when it fails to login to a pool using the privileges it has.  That would allow pgbouncer to auto-heal from a secret rotation that changes the password.

**Comment by petere** [comment]
Login from client _to_ pgbouncer is in `src/client.c`, function `handle_client_startup()`. Login _from_ pgbouncer to backend server is in `src/proto.c`, function `answer_authreq()`.

**Comment by danizen** [comment]
Thanks,

-Dan
