### ISSUE TITLE
DNS resolution problem

### ISSUE THREAD

**Issue by randlega** [pgbouncer/pgbouncer#491]
I've recently changed operating systems from Ubuntu Xenial to Ubuntu Focal and I am having a problem with DNS resolution with pgbouncer version 1.12. On xenial I was using a custom build of pgbouncer 1.7 so that we could use c-ares as the backend. On focal I'm using the upstream package from the mirror which uses pgbonucer 1.12 and c-ares 1.15 by default.

The problem I'm experiencing is that on xenial I could use a hostname without a suffix (e.g. hosta) and the DNS lookup would succed. On focal, if I try the same format, I get a `lookup_failed` error in the logs. If I try using a FQDN the lookup succeeds, after a failed attempt (see tcpdumps below). 

I can restore the previous functionality in xenial by forcing the decision here to only support IPv4. https://github.com/pgbouncer/pgbouncer/blob/pgbouncer_1_12_0/src/dnslookup.c#L901

Example Host: hosta
```
18:53:50.571577 IP (tos 0x0, ttl 64, id 43732, offset 0, flags [DF], proto UDP (17), length 59)
    my.host.com.34588 > my.dns.server.domain: 42184+ AAAA? hosta. (31)
18:53:50.571731 IP (tos 0x0, ttl 127, id 29504, offset 0, flags [none], proto UDP (17), length 59)
    my.dns.server.domain > my.host.com.34588: 42184 ServFail 0/0/0 (31)
18:53:50.571789 IP (tos 0x0, ttl 64, id 62948, offset 0, flags [DF], proto UDP (17), length 59)
    my.host.com.35890 > my.dns.server.domain: 42184+ AAAA? hosta. (31)
18:53:50.572071 IP (tos 0x0, ttl 127, id 28845, offset 0, flags [none], proto UDP (17), length 59)
    my.dns.server.domain > my.host.com.35890: 42184 ServFail 0/0/0 (31)
18:53:50.572139 IP (tos 0x0, ttl 64, id 57126, offset 0, flags [DF], proto UDP (17), length 59)
    my.host.com.44615 > my.dns.server.domain: 42184+ AAAA? hosta. (31)
18:53:50.572471 IP (tos 0x0, ttl 127, id 1393, offset 0, flags [DF], proto UDP (17), length 59)
    my.dns.server.domain > my.host.com.44615: 42184 ServFail 0/0/0 (31)
18:54:05.690588 IP (tos 0x0, ttl 64, id 46920, offset 0, flags [DF], proto UDP (17), length 72)
```

Example Host: hosta.my.domain: Note the double suffix on the first query.
```
18:56:09.933303 IP (tos 0x0, ttl 64, id 5520, offset 0, flags [DF], proto UDP (17), length 85)
    myhost.my.domain.57893 >my.dns.server.domain: 21475+ AAAA? hosta.my.domain.my.domain (57)
18:56:09.933450 IP (tos 0x0, ttl 127, id 29511, offset 0, flags [none], proto UDP (17), length 159)
   my.dns.server.domain > myhost.my.domain.57893: 21475 NXDomain* 0/1/0 (131)
18:56:09.933484 IP (tos 0x0, ttl 64, id 5521, offset 0, flags [DF], proto UDP (17), length 72)
    myhost.my.domain.57893 >my.dns.server.domain: 14377+ A? hosta.my.domain. (44)
18:56:09.933616 IP (tos 0x0, ttl 127, id 29512, offset 0, flags [none], proto UDP (17), length 88)
   my.dns.server.domain > myhost.my.domain.57893: 14377* 1/0/0 hosta.my.domain. A A_VALID_IP (60)
```

I tried building the latest version of pgbouncer, but I encountered the same problem.

**Comment by petere** [comment]
If it's an issue in c-ares then we should figure out a way to produce an issue report for them.

**Comment by randlega** [comment]
@petere Do you know of I way I could prove that the issue is in c-ares? Based on other articles I've read, it sounds like the problem may be an interaction with pgbouncer/c-ares/systemd-resolvd.

I don't know of an easy way to narrow down which of the three is the problem.

Things I have tried:

- bypass the systemd-resolvd stub-resolver by changing the /etc/resolv.conf symlink
- disabling LLMNR via networkd for the target interface

I will find some of the articles I was reading, and link them below.

**Comment by petere** [comment]
The first thing I'd try is building with a different adns backend and see if that makes a difference. Build with `--without-cares`, which will use libevents's built-in DNS.
