### ISSUE TITLE
pgbouncer systemd notify seems not working proprely.

### ISSUE THREAD

**Issue by dan-aksenov** [pgbouncer/pgbouncer#492]
- pgbouncer version - 1.12 and 1.14
- Centos 7, bouncer installed from pgdg repository, running as systemd service.
- Clean pgbouncer.ini (syslog is set to 0, anyway)

I have a lots of **pgbouncer specific** logging to /var/log/messages in addition to pgbouncer.log:
Example:
`pgbouncer: 2020-06-15 13:48:03.221 TZ [33892] LOG C-0x1ea50e0: db_name/username@ip:port login attempt: db=db_name user=username tls=no`
My colleague from other company confirms the same thing with his installation.
**I wonder is it expected behaviour?**

**Comment by markokr** [comment]
Perhaps stdout is enabled which is read by systemd?

**Comment by dan-aksenov** [comment]
Here's unitfile. 
StandardOutput is commented, and according to description it should write only during "early-startup", before pgbouncer.ini takes effect.
There's same setting for postgresql's unitfile, which seems to work correctly.

```
# It's not recommended to modify this file in-place, because it will be
# overwritten during package upgrades.  If you want to customize, the
# best way is to create a file "/etc/systemd/system/pgbouncer.service",
# containing
#       .include /lib/systemd/system/pgbouncer.service
#       ...make your changes here...
# For more info about custom unit files, see
# http://fedoraproject.org/wiki/Systemd#How_do_I_customize_a_unit_file.2F_add_a_custom_unit_file.3F

[Unit]
Description=A lightweight connection pooler for PostgreSQL
After=syslog.target
After=network.target

[Service]
Type=simple

User=pgbouncer
Group=pgbouncer

# Path to the init file
Environment=BOUNCERCONF=/etc/pgbouncer/pgbouncer.ini

PIDFile=/var/run/pgbouncer/pgbouncer.pid

# Where to send early-startup messages from the server
# This is normally controlled by the global default set by systemd
# StandardOutput=syslog

ExecStart=/usr/bin/pgbouncer ${BOUNCERCONF}
ExecReload=/usr/bin/kill -HUP $MAINPID
KillSignal=SIGINT

# Give a reasonable amount of time for the server to start up/shut down
TimeoutSec=300

[Install]
WantedBy=multi-user.target
```

**Comment by dan-aksenov** [comment]
cant it be because 
Bouncer 
```
[Service]
Type=simple
```
and Postgresql is 
```
[Service]
Type=notify
```
Which means:
> identical to Type=simple, but with the stipulation that the daemon will send a signal to systemd when it is ready.

**Comment by dan-aksenov** [comment]
More info. As said in 1.13:
> Add support for systemd service notifications. Right now, this allows using Type=notify service units. More integration is planned for future versions.

But when I edit unitfile to notify - `systemctl start` hangs indefinitely.
`systemctl status` says "activating" after process is actually started and serves connections.
It seems - process doesn't report status to systemd on startup.

**Comment by petere** [comment]
What is the logging configuration in your `pgbouncer.ini`?

**Comment by dan-aksenov** [comment]
I guess that's enough
```
 logfile                   | /var/log/pgbouncer/pgbouncer.log                       
 syslog                    | 0                                                      
 syslog_facility           | daemon                                                 
 syslog_ident              | pgbouncer                                              
 verbose                   | 0                                                      
 log_stats                 | 1                                                      
 log_connections           | 1                                                      
 log_disconnections        | 1                                                      
 log_pooler_errors         | 1                                                      
 application_name_add_host | 0          
```

**Comment by petere** [comment]
To turn off logging to stderr, you need to use the command-line option `-q`. Just specifying `logfile` in the configuration does not turn off logging to stderr.

I realize that this is a bit unusual, but that's how it works.

The option `-d` (daemon) also implies `-q`, to perhaps in pre-systemd times this worked correctly out of the box. Maybe we need to revisit this so that it works sensibly out of the box under systemd as well.

**Comment by lemonsquash** [comment]
> More info. As said in 1.13:
> 
> > Add support for systemd service notifications. Right now, this allows using Type=notify service units. More integration is planned for future versions.
> 
> But when I edit unitfile to notify - `systemctl start` hangs indefinitely.
> `systemctl status` says "activating" after process is actually started and serves connections.
> It seems - process doesn't report status to systemd on startup.

I do have this problem, too.

After updating to the latest CentOS 7 package (pgbouncer-1.13.0-2.el7), systemctl start hangs and eventually runs into timeout. pgBouncer - Service started fine, though, but gets killed again by systemd after the timeout. Thats not good.

It is reproducible (actually I am experiencing this on all of my pgBouncer installations with CentOS 7.8).

Workaround is to manually edit the unit file (/usr/lib/systemd/system/pgbouncer.service) and replace `Type=notify` with `Type=simple`. 

Before I did the update, there was simply no Type in the unit file, so it defaults to simple.

Could this be a Bug? Or is there something in the config I should change to allow for systemd notify to work? Config itself is pretty straight forward, mostly default, just some performance tweaks.

**Comment by petere** [comment]
@lemonsquash Where did you get the package from?

**Comment by lemonsquash** [comment]
@petere The package is from CentOS/Fedora epel repository 
(http://ftp-stud.hs-esslingen.de/pub/epel/7/x86_64/Packages/p/)

**Comment by petere** [comment]
@lemonsquash I think that package is broken. We recently had a similar report in the gitter chat.

**Comment by lemonsquash** [comment]
@petere Thanks, sounds like a broken package after some further investigation. From what I read until now, there could be a problem with the configuration options at compile time or something.

I am going to file a new bug report with redhat / fedora then.
