### ISSUE TITLE
Why pgbouncer ignore options?

### ISSUE THREAD

**Issue by heckad** [pgbouncer/pgbouncer#493]
I tried to connect to Postgres throw pgbouncer with PGOPTIONS env var. Example:
```
PGOPTIONS=--search_path=myschema psql "host=rc1b-0q6sslyu3dq3mnhk.mdb.yandexcloud.net \
>       port=6432 \
>       sslmode=verify-full \
>       dbname=db1 \
>       user=crubs \
>       target_session_attrs=read-write"
```
What I expect:
```
SHOW search_path;
[('my_schema',)]
```
What I got:
```
SHOW search_path;
[('"$user", public',)]
```
Why is this happen?

**Comment by petere** [comment]
Do you not see a warning `unsupported startup parameter: option` in the log?

**Comment by heckad** [comment]
This was the odyssey written by yandex and launched in compatibility mode with pgbouncer.

**Comment by heckad** [comment]
> Do you not see a warning `unsupported startup parameter: option` in the log?

When can the pgbouncer write this message?

**Comment by petere** [comment]
When you connect using an unsupported startup parameter.
