### ISSUE TITLE
Configure-error: ./configure: line 6469: syntax error near unexpected token `CARES,'

### ISSUE THREAD

**Issue by kostya-lemb** [pgbouncer/pgbouncer#50]
Debian Wheezy
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux

#./configure --enable-evdns
...
checking for crypt... yes
checking for lstat... yes
checking for libevent... found
checking whether libevent version >= 1.3b... yes
checking for event_loopbreak... yes
checking for event_base_new... yes
checking for evdns_base_new... yes
checking whether to use c-ares for DNS lookups... auto
./configure: line 6469: syntax error near unexpected token `CARES,'
./configure: line 6469: `  PKG_CHECK_MODULES(CARES, libcares >= 1.6.0, use_cares=yes, use_cares=no)'

**Comment by benchub** [comment]
I had a similar problem, even if used --with-cares=no, or --without-cares, or even when I hacked configure to explicitly not enter that if block. When I took the whole block out, I still ran into the Makefile trying to include CARES_LIBS and CARES_CFLAGS.

**Comment by benchub** [comment]
....and my issues was a missing pkg-config. After installing that and re-running autogen.sh, things worked great.

**Comment by markokr** [comment]
Problem was missing pkg.m4.

Not sure how much effort should be made to check dev-deps when building from git.
