### ISSUE TITLE
SBUF_EV_FLUSH event, transaction mode, release_server question

### ISSUE THREAD

**Issue by parans** [pgbouncer/pgbouncer#500]
I have a question related to handling of server connections by pgbouncer in transaction mode, Looking through the source I see that pgbouncer releases server connections https://github.com/pgbouncer/pgbouncer/blob/ad6b5af4e27c8e9059b7a1e7dd541ea3b7c72624/src/server.c#L554 on receiving SBUF_EV_FLUSH event from postgres db. When is this event sent by postgres ? What is the scenario? Is this event sent by postgres after a commit is issued by a client? 

_begin;
insert into table ()....
update table set item = val;
commit;_

In the above scenario; When is SBUF_EV_FLUSH called? Postgres wire protocol suggests postgres sends a 'ReadyForQuery' packet at the end of a query, but this packet is being handled in SBUF_EV_READ event and the server connection is not being released in that case https://github.com/pgbouncer/pgbouncer/blob/master/src/server.c#L512 . 
I need this information to justify the throughput gains of pgbouncer to my customers

**Comment by markokr** [comment]
SBUF_EV_FLUSH is internal event, it just means no pending network data.

The read criteria is SBUF_EV_FLUSH + server->ready.  Latter is set by ReadyForQuery if no tx is open.

**Comment by parans** [comment]
Thank you @markokr for the quick response, Going over the the code I see that the internal event is sent to the callback function here https://github.com/pgbouncer/pgbouncer/blob/master/src/sbuf.c#L771 and If my understanding is correct after a commit is issued the standarad steps of [Parse, Bind, Execute] happens ending with postgres returning a 'Ready for query' during which server->ready = true is set (because the transaction ended). Since after the commit there is no more pending items to be sent https://github.com/pgbouncer/pgbouncer/blob/master/src/sbuf.c#L516 , the  SVBUF_EV_FLUSH is generated. Am I somewhere in the ballpark?

**Comment by markokr** [comment]
Yes

**Comment by petere** [comment]
Looks like this question was answered. More questions about obscure code details are welcome. ;-)
