### ISSUE TITLE
Feature Request: multiple authentication methods

### ISSUE THREAD

**Issue by MichaelDBA** [pgbouncer/pgbouncer#501]
It would be really neat if pgbouncer supported multiple authentication methods through the databases section.

For instance I could have 2 db aliases where the absence of auth_user would imply using the default, auth_type=pam and the other implies validation using the auth_query in the database for the app users.
```
connect_apps = port=6432 dbname=connectdb auth_user=pgbouncer
connect_users = port=6432 dbname=connectdb 
auth_type = pam
```
This would accomplish a common scenario where we have individual users in an SDLC environment accessing the databases and app users where connection pooling applies the most.

Also, by distinguishing regular users from app users, we can now take advantage of sizing the pools more efficiently, which is already in pgbouncer.

If only pgadmin4 would work nicely with pgbouncer.  It hates db aliases! Requested a feature request there to support pgbouncer aliases (only a global change i think), but they would not budge.

**Comment by petere** [comment]
As you can see in the discussion in #326, applying PAM in a non-global manner is appearing to be quite complicated. If we were to solve that, then pg_hba.conf support for PAM would probably be first on the list. I suspect your feature might then best fit into some kind of pg_hba.conf facility, but that's far in the future, I'm afraid.

**Comment by MichaelDBA** [comment]
OK, thanks for addressing this nonetheless!

**Comment by svb007** [comment]
Are we perhaps able to revisit this now that online restart has been disabled? If I can get rid of this patch, I'd be very grateful: 
@@ -592,6 +592,10 @@
 		rule->rule_method = AUTH_CERT;
 	} else if (eat_kw(tp, "scram-sha-256")) {
 		rule->rule_method = AUTH_SCRAM_SHA_256;
+#ifdef HAVE_PAM
+	} else if (eat_kw(tp, "pam")) {
+		rule->rule_method = AUTH_PAM;
+#endif
 	} else {
 		log_warning("hba line %d: unsupported method: buf=%s", linenr, tp->buf);
 		goto failed;
