### ISSUE TITLE
feature request: Failover for client connections

### ISSUE THREAD

**Issue by zurikus** [pgbouncer/pgbouncer#503]
Hello to everyone,
We are in process of designing PostgreSQL cluster with 3 nodes ( 1 - Primary, 2 - Stanadby without delay, 3 - Standby with delay ) and Pgbouncer as connection pooler on every node. 
We are using [database] section for db mapping and it is looking like follows:

```
[databases]

--- Rule for primary
db1 = host=10.7.0.198 dbname=db1 auth_user=pgbouncer

--- Rule for standby without delay 
db1_ro = host=10.7.0.199 dbname=db1 auth_user=pgbouncer

--- Rule for delayed standby 
db1_ro_delayed = host=10.7.0.200 dbname=db1 auth_user=pgbouncer

```

Such DB mapping give us opportunity to reserve Pgbouncer in pgbouncer failure scenario.
It would be really great if Pgbouncer could make Client connection Failover as in Unplanned Standby node failure scenario Pgbouncer will continue to send requests to failed node.

For example, provide 2 connection strings for one DB : 

```
--- Rule for standby without delay 
db1_ro = host=10.7.0.199 dbname=db1 auth_user=pgbouncer 
db1_ro = host=10.7.0.198 dbname=db1 auth_user=pgbouncer 
```

And use second if first failed...

Or

We can see in PGbouncer documentation, that "host" parameter can have DNS and multiple IPs could be returned and then PGbouncer will RoundRobin connection between these IP.

May be client connection Failover algorithm could be implemented as well? 
Multiple hosts IPs could be provided in "hosts" parameter then with some special key "balancing = failover" for example and pgbouncer failover instead of RoundRobin? 

What do you think about it?

**Comment by petere** [comment]
Something like this would surely be interesting, but it's not really planned at the moment. Most people use an external agent, for example repmgr, to detect failure and make adjustments to the pgbouncer configuration based on events.

**Comment by zurikus** [comment]
Thank you Petere for response. I will look in direction of some external agents to workaround this situation.
