### ISSUE TITLE
Cannot do SCRAM authentication when using auth_query

### ISSUE THREAD

**Issue by fljdin** [pgbouncer/pgbouncer#508]
Hi,

I'm testing new SCRAM support in version 1.14, and a unexpected behavior occurs with an `auth_query` configuration.

```
$ psql -h localhost -p 6432 -U appuser demo -c "\conninfo"

[manually interrupt pgbouncer]
psql: error: could not connect to server: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
```
DEBUG C-0x55f6f9be6d00: (nodb)/(nouser)@127.0.0.1:41332 got var: user=appuser
DEBUG C-0x55f6f9be6d00: (nodb)/(nouser)@127.0.0.1:41332 got var: database=demo
DEBUG C-0x55f6f9be6d00: (nodb)/(nouser)@127.0.0.1:41332 using application_name: psql
DEBUG C-0x55f6f9be6d00: (nodb)/(nouser)@127.0.0.1:41332 got var: client_encoding=UTF8
DEBUG C-0x55f6f9be6d00: demo/(nouser)@127.0.0.1:41332 pause_client
DEBUG C-0x55f6f9be6d00: demo/(nouser)@127.0.0.1:41332 P: got connection: 127.0.0.1:41332 -> 127.0.0.1:6432
DEBUG zone_register(localhost)
DEBUG S-0x55f6f9beda80: demo/pgbouncer@(bad-af):0 dns_callback: inet4: 127.0.0.1:5432
DEBUG S-0x55f6f9beda80: demo/pgbouncer@127.0.0.1:5432 launching new connection to server
DEBUG S-0x55f6f9beda80: demo/pgbouncer@127.0.0.1:5432 S: connect ok
LOG S-0x55f6f9beda80: demo/pgbouncer@127.0.0.1:5432 new connection to server (from 127.0.0.1:39658)
DEBUG pktbuf_dynamic(512): 0x55f6f9be63d0
DEBUG launch_new_connection: already progress
DEBUG S-0x55f6f9beda80: demo/pgbouncer@127.0.0.1:5432 calling login_answer
DEBUG S-0x55f6f9beda80: demo/pgbouncer@127.0.0.1:5432 S: req SASL
DEBUG S-0x55f6f9beda80: demo/pgbouncer@127.0.0.1:5432 S: SASL advertised mechanism: SCRAM-SHA-256
ERROR S-0x55f6f9beda80: demo/pgbouncer@127.0.0.1:5432 cannot do SCRAM authentication: password is SCRAM secret but client authentication did not provide SCRAM keys
LOG S-0x55f6f9beda80: demo/pgbouncer@127.0.0.1:5432 closing because: failed to answer authreq (age=0s)
DEBUG launch_new_connection: last failed, not launching new connection yet, still waiting 14 s
DEBUG launch_new_connection: last failed, not launching new connection yet, still waiting 14 s
DEBUG launch_new_connection: last failed, not launching new connection yet, still waiting 14 s
DEBUG launch_new_connection: last failed, not launching new connection yet, still waiting 14 s
```

### Workaround

Works when open a first session with `pgbouncer` role described in `userlist.txt`

```
$ psql -h localhost -p 6432 -U pgbouncer demo -c "\conninfo"
Password for user pgbouncer: 
You are connected to database "demo" as user "pgbouncer" on host "localhost" (address "127.0.0.1") at port "6432".

$ psql -h localhost -p 6432 -U appuser demo -c "\conninfo"
Password for user appuser: 
You are connected to database "demo" as user "appuser" on host "localhost" (address "127.0.0.1") at port "6432".

```

### Platform

* Linux 4.19.126-1-MANJARO SMP Wed Jun 3 22:30:22 UTC 2020 x86_64 GNU/Linux
* postgres (PostgreSQL) 12.3
* PgBouncer 1.14.0
* libevent 2.1.11-stable
* adns: c-ares 1.16.1
* tls: OpenSSL 1.1.1g  21 Apr 2020

### How to reproduce

Start a fresh cluster with `password_encryption = scram-sha-256`, a database and two roles.

```
initdb --auth-local=peer --auth-host=scram-sha-256 pgsql/data
pg_ctl -D pgsql/data -l logfile start

createdb demo
createuser --pwprompt pgbouncer
createuser --pwprompt appuser

psql demo -c "grant select on pg_shadow to pgbouncer"
```
Content of `pgbouncer.ini` file
```ini
[pgbouncer]
logfile = /home/pgbouncer/pgbouncer.log
pidfile = /home/pgbouncer/pgbouncer.pid
listen_addr = 127.0.0.1
listen_port = 6432
unix_socket_dir = /tmp
unix_socket_mode = 0777
auth_type = scram-sha-256
auth_file = /home/pgbouncer/userlist.txt
auth_user = pgbouncer
auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=$1

admin_users = postgres,pgbouncer
stats_users = postgres,pgbouncer
max_client_conn = 100
default_pool_size = 20

[databases]
demo = host=localhost dbname=demo
```
Content of `userlist.txt` file
```
"pgbouncer" "SCRAM-SHA-256$4096:GL1fchgRtvV1+z/eQDZh+Q==$D99zYSIaC0v…3yM0="
```

**Comment by fljdin** [comment]
Hi,

Same issue with a dedicated user for a database, and no `auth_query` configuration, but no hung behavior on client side.

```
$ psql -h localhost -p 6432 -U appuser demo
Password for user appuser: 
psql: error: could not connect to server: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 6432?
ERROR:  server login failed: wrong password type
```

```
DEBUG C-0x557895c8dcd0: (nodb)/(nouser)@127.0.0.1:44082 got var: user=appuser
DEBUG C-0x557895c8dcd0: (nodb)/(nouser)@127.0.0.1:44082 got var: database=demo
DEBUG C-0x557895c8dcd0: (nodb)/(nouser)@127.0.0.1:44082 using application_name: psql
DEBUG C-0x557895c8dcd0: (nodb)/(nouser)@127.0.0.1:44082 got var: client_encoding=UTF8
LOG C-0x557895c8dcd0: demo/appuser@127.0.0.1:44082 login attempt: db=demo user=appuser tls=no
DEBUG C-0x557895c8dcd0: demo/appuser@127.0.0.1:44082 P: got connection: 127.0.0.1:44082 -> 127.0.0.1:6432
DEBUG C-0x557895c8dcd0: demo/appuser@127.0.0.1:44082 C: selected SASL mechanism: SCRAM-SHA-256
DEBUG C-0x557895c8dcd0: demo/appuser@127.0.0.1:44082 SCRAM client-first-message = "n,,n=,r=4AWAe9Xo03WpmAFF4cxokbZg"
DEBUG C-0x557895c8dcd0: demo/appuser@127.0.0.1:44082 stored secret = "SCRAM-SHA-256$4096:y+LnFLsTYJLLhKwr9KU7JQ==$Vzq7u03ARF7S4kvzr6FOwiEgEieHS9z5Sr0sEhlFl1k=:VVQD4pkZhDTJhcDlRWL5MP6wPXXK6Baq7cLZIy/SKj4="
DEBUG C-0x557895c8dcd0: demo/appuser@127.0.0.1:44082 SCRAM server-first-message = "r=4AWAe9Xo03WpmAFF4cxokbZgIDX5FqnzZ835qeNfNGDVjX4O,s=y+LnFLsTYJLLhKwr9KU7JQ==,i=4096"
DEBUG C-0x557895c8dcd0: demo/appuser@127.0.0.1:44082 SCRAM client-final-message = "c=biws,r=4AWAe9Xo03WpmAFF4cxokbZgIDX5FqnzZ835qeNfNGDVjX4O,p=SV33bRxOAwph4aPW8L7Wm9vuc0xvqsUCrU/oe8Mfpoo="
DEBUG C-0x557895c8dcd0: demo/appuser@127.0.0.1:44082 SCRAM client-final-message-without-proof = "c=biws,r=4AWAe9Xo03WpmAFF4cxokbZgIDX5FqnzZ835qeNfNGDVjX4O"
DEBUG C-0x557895c8dcd0: demo/appuser@127.0.0.1:44082 SCRAM server-final-message = "v=QNJxXqAoE7Y17RozSvDyH8xI2SrjienEb632B4fUrlE="
DEBUG finish_client_login: no welcome message, pause
DEBUG C-0x557895c8dcd0: demo/appuser@127.0.0.1:44082 pause_client
DEBUG zone_register(localhost)
DEBUG S-0x557895c94a50: demo/appuser@(bad-af):0 dns_callback: inet4: 127.0.0.1:5432
DEBUG S-0x557895c94a50: demo/appuser@127.0.0.1:5432 launching new connection to server
DEBUG launch_new_connection: already progress
DEBUG S-0x557895c94a50: demo/appuser@127.0.0.1:5432 S: connect ok
LOG S-0x557895c94a50: demo/appuser@127.0.0.1:5432 new connection to server (from 127.0.0.1:51720)
DEBUG pktbuf_dynamic(512): 0x557895c8d5d0
DEBUG launch_new_connection: already progress
DEBUG S-0x557895c94a50: demo/appuser@127.0.0.1:5432 calling login_answer
DEBUG S-0x557895c94a50: demo/appuser@127.0.0.1:5432 S: req SASL
DEBUG S-0x557895c94a50: demo/appuser@127.0.0.1:5432 S: SASL advertised mechanism: SCRAM-SHA-256
ERROR S-0x557895c94a50: demo/appuser@127.0.0.1:5432 cannot do SCRAM authentication: password is SCRAM secret but client authentication did not provide SCRAM keys
LOG C-0x557895c8dcd0: demo/appuser@127.0.0.1:44082 closing because: server login failed: wrong password type (age=0s)
WARNING C-0x557895c8dcd0: demo/appuser@127.0.0.1:44082 pooler error: server login failed: wrong password type
LOG S-0x557895c94a50: demo/appuser@127.0.0.1:5432 closing because: failed to answer authreq (age=0s)
```

Content of `pgbouncer.ini` file

```ini
[pgbouncer]
logfile = /home/pgbouncer/pgbouncer.log
pidfile = /home/pgbouncer/pgbouncer.pid
listen_addr = 127.0.0.1
listen_port = 6432
unix_socket_dir = /tmp
unix_socket_mode = 0777
auth_type = scram-sha-256
auth_file = /home/pgbouncer/userlist.txt

admin_users = postgres,pgbouncer
stats_users = postgres,pgbouncer
max_client_conn = 100
default_pool_size = 20

[databases]
demo = host=localhost dbname=demo user=appuser
```
Content of `userlist.txt` file

```
"pgbouncer" "SCRAM-SHA-256$4096:GL1fchgRtvV1+z/eQDZh+Q==$D99zYSIaC0v…3yM0="
"appuser" "SCRAM-SHA-256$4096:y+LnFLsTYJLhKwr9KU7JQ==$Vzq7u07S9z5Sr…Kj4="
```

**Comment by fljdin** [comment]
> Same issue with a dedicated user for a database, and no `auth_query` configuration, but no hung behavior on client side.

As described in documentation, this test includes an intermediate credential and cannot securely be used in a SCRAM authentication. I'm right?

> SCRAM secrets can only be used for logging into a server if the client 
authentication also uses SCRAM, the PgBouncer database definition does 
not specify a user name, and the SCRAM secrets are identical in PgBouncer
and the PostgreSQL server (same salt and iterations, not merely the same
password). fThis is due to an inherent security property of SCRAM: The
stored SCRAM secret cannot by itself be used for deriving login credentials.

**Comment by petere** [comment]
This appears to be working as it is supposed to. What are you expecting?

**Comment by fljdin** [comment]
My previous answer about md5-hashed password in auth_file was inspired by clear documentation.

> SCRAM secrets can only be used for logging into a server if the client authentication also uses SCRAM, the PgBouncer database definition does not specify a user name, and the SCRAM secrets are identical in PgBouncer and the PostgreSQL server (same salt and iterations, not merely the same password). This is due to an inherent security property of SCRAM: The stored SCRAM secret cannot by itself be used for deriving login credentials.

**Comment by MannerMan** [comment]
@fljdin Did you get it to work with a SCRAM secret set in `userlist.txt` for the pgbouncer-user? When I were testing pass-through authentication like you here we could not get it work without using a plain-text password in `userlist.txt`.

**Comment by petere** [comment]
> @fljdin Did you get it to work with a SCRAM secret set in `userlist.txt` for the pgbouncer-user? When I were testing pass-through authentication like you here we could not get it work without using a plain-text password in `userlist.txt`.

The pgbouncer user needs to have some other way of authenticating than using a SCRAM secret.

**Comment by MannerMan** [comment]
> > @fljdin Did you get it to work with a SCRAM secret set in `userlist.txt` for the pgbouncer-user? When I were testing pass-through authentication like you here we could not get it work without using a plain-text password in `userlist.txt`.
> 
> The pgbouncer user needs to have some other way of authenticating than using a SCRAM secret.

Alright, I was asking since #444 was closed as addressed by specifying secrets as SCRAM, but this would be a use-case where it would have been useful to encrypt `userlist.txt`, since SCRAM cannot be used here and md5/plain is not very secure. Of course one could go the certificate route for authentication instead.

**Comment by vamfoom** [comment]
I created a user in postgres called pgbouncer and setup userlist.txt with scram credential.  I also set the auth_query to query postgres.  I see this in pgbouncer's log:

2021-10-04 17:13:55.357 GMT [22215] ERROR S-0xa2e810: dbsv/pgbouncer@127.0.0.1:5432 cannot do SCRAM authentication: password is SCRAM secret but client authentication did not provide SCRAM keys

Does  passthrough not work?

**Comment by petere** [comment]
@vamfoom It is not possible to assess your case without more information such as version information, configuration files, and the commands that you entered.

**Comment by Bhautik0110** [comment]
:roll_eyes: Repeat.

**Comment by Bhautik0110** [comment]
@petere My question is If I specified a password for the delegate user. and log in with another user. Does pgbouncer query the database server and verify credentials using delegated user for scram-sha-256 method?

**Comment by petere** [comment]
It connects to the database server as the delegate user (`auth_user`), downloads the SCRAM secret stored in `pg_authid` for the real user, and then reconnects as the real user and supplies the downloaded SCRAM secret during the login process.

**Comment by Bhautik0110** [comment]
@petere Why I got the error `cannot do SCRAM authentication: password is SCRAM secret but client authentication did not provide SCRAM keys` for other than delegate user?

**Comment by petere** [comment]
I don't know. You'd have to show us the complete setup of what you are doing. The error message is pretty explicit about what the prerequisites are.

**Comment by Bhautik0110** [comment]
Thanks for the reply @petere. Issue: https://github.com/pgbouncer/pgbouncer/issues/761

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/scram-sasl/info/issues/1
