### ISSUE TITLE
Escaping double quotes in auth_file password

### ISSUE THREAD

**Issue by brandonweng-db** [pgbouncer/pgbouncer#509]
We're using pgbouncer for the first time and I had a quick question about how double quotes are escaped in pgbouncer when it's reading the auth_file. 

Is there a particular reason pgbouncer uses `""` to escape quotes in auth_file passwords instead of the usual `\"`? 
https://github.com/pgbouncer/pgbouncer/blob/229ae86bf8f27e1c528c9e7d083956ded3b8ca38/src/loader.c#L463

I wasn't able to find this in the [pgbouncer config docs](https://www.pgbouncer.org/config.html#authentication-file-format) but the code was pretty intuitive. 

Thanks in advanced!

**Comment by petere** [comment]
The origin of this syntax is probably the syntax of SQL. I'll see about documenting this.

**Comment by brandonweng-db** [comment]
Got it, thanks so much!
