### ISSUE TITLE
auth_type=any should use client username & password

### ISSUE THREAD

**Issue by nickelozz** [pgbouncer/pgbouncer#51]
Hello guys,

I'm rather new to pgBouncer and I'm trying to add a connection pooling feature for my app written in PHP (Laravel 5). From what I understand pgBouncer uses a "userlist.txt" file for authenticating entering connections, depending on whatever option is set for "auth_type" in "pgbouncer.ini". I decided to use a separate server dedicated to pooling connections so there's no PostgreSQL installed there...instead I use a RDS from AWS.

However, if I read [the docs](https://pgbouncer.github.io/config.html) correctly, whenever I use the "auth_type=any" on my pgbouncer.ini, it won't authenticate against the "userlist.txt" file (which is exactly what I want)...but will force a "pgbouncer" user on the connection string to my PostgreSQL RDS instead of using the credentials I'm sending for the connection. Is there any way to prevent pgBouncer from doing this? or am I doing something wrong here?

Any help would be very much appreciated!

**Comment by markokr** [comment]
You should use user=baz password=foo in database line to force auth info to use for server.

There is no good way to do a "passthrough auth" mode if thats what you wanted.
