### ISSUE TITLE
Overallocation of session in transactional mode

### ISSUE THREAD

**Issue by chefun** [pgbouncer/pgbouncer#511]
Hello, we're seeing some strange behaviour on one of our clusters.
We're using PGBouncer 1.14 (in a Docker-Container) in front of a Patroni 1.6.5-Cluster (with PostgreSQL 12.3)
A user on a database, where we would expect no more than 100 Connections in the Frontend seems to be able to allocate 123 Connections on the clientside, whereas only 3 Connections are in use on serverside.
Section in pgbouncer.ini looks like this:
[databases]
OUR_DATABASE = host=OUR_HOST port=5000 dbname=OUR_DATABASE auth_user=pgbouncer pool_size=100 pool_mode=transaction max_db_connections=20
We didn't configure reserve_pool_size, so that's probably not the cause.
Please find additional information in the attached file.
Do you have any advise for us?
Best regards,Che
[configuration.txt](https://github.com/pgbouncer/pgbouncer/files/4988409/configuration.txt)

**Comment by eulerto** [comment]
Check `show clients`. pgbouncer will accept connection until `max_client_conn` application connections.

**Comment by chefun** [comment]
My Bad. I thought the lower pool_size would be the limit.
Thank you.
