### ISSUE TITLE
CentOS 7 pgbouncer.pid Permissions Issue

### ISSUE THREAD

**Issue by daBee** [pgbouncer/pgbouncer#514]
2020-07-31 04:58:34.089 EDT [3682] FATAL could not open pidfile '/var/run/pgbouncer/pgbouncer.pid': Permission denied

It seems the ownership of `/var/run/pgbouncer` gets refreshed to `pgbouncer:pgbouncer` often, so changing permissions isn't possible.  

Should I change the location for the pid file?  If so, what location should I use?  I've read the following options:

    ~/.my_app/my_app.pid

...or...

    /opt/my_app/etc/

The latter is owned by `root` and faces the same issue:

    0 drwxr-xr-x.   2 root root         6 Apr 11  2018 opt/

Is there a suggestion where this should function?  The package for CentOS 7, as above, puts it into an odd place, in its own directory:

    /var/run

is an alias to:

    /run

Then this:

     0 drwx------   2 pgbouncer pgbouncer   40 Jul 31 13:49 pgbouncer/

This obviously needs a proper location for it to work.  Worked fine on my Mac:

    /usr/local/var/run/pgbouncer.pid

**Comment by eulerto** [comment]
How did you install pgbouncer? PGDG repository? If so, the OS user that runs the service is `pgbouncer`.
How are you starting the service? `systemctl start pgbouncer`?
If you want to use a different OS user, create `/etc/systemd/system/pgbouncer.service.d/custom.conf` (create `pgbouncer.service.d` directory) and add:

```
[Service]
User=foo
Group=bar
```

Change ownership from directories:

```
chown -R foo. /var/run/pgbouncer
chown -R foo. /var/log/pgbouncer
```

**Comment by daBee** [comment]
`Yum` install.  I was hoping the package manager would have taken care of this.  It seems `pgbouncer` is indeed the user, given the ownership that's shown up.  As for startup:

    pgbouncer -d /etc/pgbouncer/pgbouncer.ini

I'd rather juse find another directory to park `pgbouncer.pid` and tell `pgbouncer.ini` to look there.  Any suggestions on a `linux` distro?  As above, I'm considering `/opt/pgbouncer/etc/`.

**Comment by eulerto** [comment]
I don't understand why you want to change the pid file location. Make sure `pidfile` in your `pgbouncer.ini` is the same as `PIDFile` in `/usr/lib/systemd/system/pgbouncer.service`. Unless you have a strong reason, use the default package location (CentOS 7 uses `/var/run/pgbouncer/pgbouncer.pid`).

**Comment by daBee** [comment]
So that it could work.  The pointer in the `ini` file is working properly.  Permissions disallow the `pid` file to be used.  Like I said before, `/var/run/pgbouncer/pgbouncer.pid` is unuseable due to permissions.  Because `pgbouncer.pid` is run by the `pgbouncer` user.  I'd rather just relocate it to where it's readable.

**Comment by daBee** [comment]
Here are the entries in `/usr/lib/systemd/system/pgbouncer.service`:

```User=pgbouncer
Group=pgbouncer

# Path to the init file
Environment=BOUNCERCONF=/etc/pgbouncer/pgbouncer.ini

PIDFile=/var/run/pgbouncer/pgbouncer.pid```

I tried starting it:

    pgbouncer -d /etc/pgbouncer/pgbouncer.ini

With the usual result:

    2020-08-02 12:51:25.595 EDT [21201] FATAL could not open pidfile '/var/run/pgbouncer/pgbouncer.pid': Permission denied

So instead of changing around users and groups, can I not just change the location of the `pidfile`?

**Comment by eulerto** [comment]
You should use `systemctl start pgbouncer`. Your user doesn't have permission to write into `pidfile` directory.

```
[root@centos7 ~]# ls -dl /var/log/pgbouncer
drwx------. 2 pgbouncer pgbouncer 105 Aug  2 12:52 /var/log/pgbouncer
[root@centos7 ~]# ls -dl /var/run/pgbouncer/
drwx------. 2 pgbouncer pgbouncer 60 Aug  2 00:57 /var/run/pgbouncer/
[root@centos7 ~]# systemctl start pgbouncer
[root@centos7 ~]# systemctl status pgbouncer
● pgbouncer.service - A lightweight connection pooler for PostgreSQL
   Loaded: loaded (/usr/lib/systemd/system/pgbouncer.service; disabled; vendor preset: disabled)
   Active: active (running) since Sun 2020-08-02 17:39:41 UTC; 3s ago
 Main PID: 6274 (pgbouncer)
   CGroup: /system.slice/pgbouncer.service
           └─6274 /usr/bin/pgbouncer /etc/pgbouncer/pgbouncer.ini

Aug 02 17:39:41 centos7 systemd[1]: Started A lightweight connection pooler for PostgreSQL.
Aug 02 17:39:41 centos7 pgbouncer[6274]: 2020-08-02 17:39:41.192 UTC [6274] LOG kernel file descriptor limit: 1024 (hard: 4096); max_client_conn: 100, max expected fd use: 214
Aug 02 17:39:41 centos7 pgbouncer[6274]: 2020-08-02 17:39:41.193 UTC [6274] LOG listening on 0.0.0.0:6432
Aug 02 17:39:41 centos7 pgbouncer[6274]: 2020-08-02 17:39:41.193 UTC [6274] LOG listening on [::]:6432
Aug 02 17:39:41 centos7 pgbouncer[6274]: 2020-08-02 17:39:41.193 UTC [6274] LOG listening on unix:/tmp/.s.PGSQL.6432
Aug 02 17:39:41 centos7 pgbouncer[6274]: 2020-08-02 17:39:41.193 UTC [6274] LOG process up: PgBouncer 1.14.0, libevent 2.0.21-stable (epoll), adns: libc-2.17, tls: OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Comment by daBee** [comment]
Well I think it went a little further, but now the log is the issue, from what I gather:


	[Sun Aug 02 14:37 rich@server1 ~] systemctl start pgbouncer
	==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
	Authentication is required to manage system services or units.
	Authenticating as: Rich (rich)
	Password: Failed to start pgbouncer.service: Connection timed out
	See system logs and 'systemctl status pgbouncer.service' for details.
	[Sun Aug 02 14:38 rich@server1 ~] polkit-agent-helper-1: pam_authenticate failed: Authentication failure
	^C
	[Sun Aug 02 14:39 rich@server1 ~] systemctl status pgbouncer.service
	● pgbouncer.service - A lightweight connection pooler for PostgreSQL
		 Loaded: loaded (/usr/lib/systemd/system/pgbouncer.service; disabled; vendor preset: disabled)
		 Active: failed (Result: exit-code) since Sun 2020-08-02 14:37:05 EDT; 2min 25s ago
		Process: 24342 ExecStart=/usr/bin/pgbouncer ${BOUNCERCONF} (code=exited, status=1/FAILURE)
	 Main PID: 24342 (code=exited, status=1/FAILURE)

	Aug 02 14:37:05 server1.project33.ca systemd[1]: Started A lightweight connection pooler for PostgreSQL.
	Aug 02 14:37:05 server1.project33.ca pgbouncer[24342]: 2020-08-02 14:37:05.935 EDT 24342 FATAL Cannot open logfile: '/var/log/pgbouncer/pgbouncer.log': Permission denied
	Aug 02 14:37:05 server1.project33.ca systemd[1]: pgbouncer.service: main process exited, code=exited, status=1/FAILURE
	Aug 02 14:37:05 server1.project33.ca systemd[1]: Unit pgbouncer.service entered failed state.
	Aug 02 14:37:05 server1.project33.ca systemd[1]: pgbouncer.service failed.

**Comment by eulerto** [comment]
Use `root` user or `sudo`.

**Comment by daBee** [comment]
Same issue when attempted using root:

	[Sun Aug 02 15:34 root@server1 /var/run] systemctl status pgbouncer.service
	● pgbouncer.service - A lightweight connection pooler for PostgreSQL
		 Loaded: loaded (/usr/lib/systemd/system/pgbouncer.service; disabled; vendor preset: disabled)
		 Active: failed (Result: exit-code) since Sun 2020-08-02 15:34:25 EDT; 2min 10s ago
		Process: 26056 ExecStart=/usr/bin/pgbouncer ${BOUNCERCONF} (code=exited, status=1/FAILURE)
	 Main PID: 26056 (code=exited, status=1/FAILURE)

	Aug 02 15:34:25 server1.project33.ca systemd[1]: Started A lightweight connection pooler for PostgreSQL.
	Aug 02 15:34:25 server1.project33.ca systemd[1]: pgbouncer.service: main process exited, code=exited, status=1/FAILURE
	Aug 02 15:34:25 server1.project33.ca systemd[1]: Unit pgbouncer.service entered failed state.
	Aug 02 15:34:25 server1.project33.ca systemd[1]: pgbouncer.service failed.
	[Sun Aug 02 15:36 root@server1 /var/run]

**Comment by daBee** [comment]
Not sure why using `sudo`, that it can't open the `logfile`, which is owned by `rich:rich`:

	[Sun Aug 02 16:13 rich@neb /var/log/pgbouncer] systemctl status pgbouncer.service
	● pgbouncer.service - A lightweight connection pooler for PostgreSQL
		 Loaded: loaded (/usr/lib/systemd/system/pgbouncer.service; disabled; vendor preset: disabled)
		 Active: failed (Result: exit-code) since Sun 2020-08-02 16:12:13 EDT; 1min 47s ago
		Process: 27190 ExecStart=/usr/bin/pgbouncer ${BOUNCERCONF} (code=exited, status=1/FAILURE)
	 Main PID: 27190 (code=exited, status=1/FAILURE)

	Aug 02 16:12:13 neb.sourcer.ca systemd[1]: Started A lightweight connection pooler for PostgreSQL.
	Aug 02 16:12:13 neb.sourcer.ca pgbouncer[27190]: 2020-08-02 16:12:13.141 EDT 27190 FATAL Cannot open logfile: '/var/log/pgbouncer/pgbouncer.log': Permission denied
	Aug 02 16:12:13 neb.sourcer.ca systemd[1]: pgbouncer.service: main process exited, code=exited, status=1/FAILURE
	Aug 02 16:12:13 neb.sourcer.ca systemd[1]: Unit pgbouncer.service entered failed state.
	Aug 02 16:12:13 neb.sourcer.ca systemd[1]: pgbouncer.service failed.

**Comment by eulerto** [comment]
As root:

```
systemctl start pgbouncer
systemctl status pgbouncer
```

If pgbouncer did not start, execute:

```
tail /var/log/pgbouncer/pgbouncer.log
```

and share the output here.

service runs as _pgbouncer_ user and it will try to open the logfile as _pgbouncer_ not _rich_. If you change the ownership, set to _pgbouncer_ again.

```
chown -R pgbouncer. /var/run/pgbouncer
chown -R pgbouncer. /var/log/pgbouncer
```

**Comment by daBee** [comment]
As `root`:

	[Sun Aug 02 16:37 root@server1 ~] systemctl start pgbouncer
	[Sun Aug 02 16:37 root@server1 ~]
	[Sun Aug 02 16:37 root@server1 ~] systemctl status pgbouncer
	● pgbouncer.service - A lightweight connection pooler for PostgreSQL
		 Loaded: loaded (/usr/lib/systemd/system/pgbouncer.service; disabled; vendor preset: disabled)
		 Active: failed (Result: exit-code) since Sun 2020-08-02 16:37:53 EDT; 8s ago
		Process: 27951 ExecStart=/usr/bin/pgbouncer ${BOUNCERCONF} (code=exited, status=1/FAILURE)
	 Main PID: 27951 (code=exited, status=1/FAILURE)

	Aug 02 16:37:53 server1.project33.ca systemd[1]: Started A lightweight connection pooler for PostgreSQL.
	Aug 02 16:37:53 server1.project33.ca pgbouncer[27951]: 2020-08-02 16:37:53.357 EDT 27951 FATAL Cannot open logfile: '/var/log/pgbouncer/pgbouncer.log': Permission denied
	Aug 02 16:37:53 server1.project33.ca systemd[1]: pgbouncer.service: main process exited, code=exited, status=1/FAILURE
	Aug 02 16:37:53 server1.project33.ca systemd[1]: Unit pgbouncer.service entered failed state.
	Aug 02 16:37:53 server1.project33.ca systemd[1]: pgbouncer.service failed.
	[Sun Aug 02 16:38 root@server1 ~]
	[Sun Aug 02 16:38 root@server1 ~]
	[Sun Aug 02 16:38 root@server1 ~] tail /var/log/pgbouncer/pgbouncer.log
	[Sun Aug 02 16:38 root@server1 ~] chown -R pgbouncer. /var/run/pgbouncer
	[Sun Aug 02 16:39 root@server1 ~] chown -R pgbouncer. /var/log/pgbouncer
	[Sun Aug 02 16:39 root@server1 ~] ll /var/log/pgbouncer/pgbouncer.log
	0 -rw-rw-r-- 1 pgbouncer pgbouncer 0 Aug  2 14:36 /var/log/pgbouncer/pgbouncer.log
	[Sun Aug 02 16:39 root@server1 ~]
	[Sun Aug 02 16:39 root@server1 ~]
	[Sun Aug 02 16:39 root@server1 ~] systemctl start pgbouncer
	[Sun Aug 02 16:39 root@server1 ~] systemctl status pgbouncer
	● pgbouncer.service - A lightweight connection pooler for PostgreSQL
		 Loaded: loaded (/usr/lib/systemd/system/pgbouncer.service; disabled; vendor preset: disabled)
		 Active: active (running) since Sun 2020-08-02 16:39:29 EDT; 3s ago
	 Main PID: 28009 (pgbouncer)
		 CGroup: /system.slice/pgbouncer.service
						 └─28009 /usr/bin/pgbouncer /etc/pgbouncer/pgbouncer.ini

	Aug 02 16:39:29 server1.project33.ca systemd[1]: Started A lightweight connection pooler for PostgreSQL.
	Aug 02 16:39:29 server1.project33.ca pgbouncer[28009]: 2020-08-02 16:39:29.958 EDT [28009] LOG kernel file descriptor limit: 1024 (hard: 4096); max_client_conn: 100, max expected fd use: 232
	Aug 02 16:39:29 server1.project33.ca pgbouncer[28009]: 2020-08-02 16:39:29.959 EDT [28009] LOG listening on 0.0.0.0:6432
	Aug 02 16:39:29 server1.project33.ca pgbouncer[28009]: 2020-08-02 16:39:29.959 EDT [28009] LOG listening on [::]:6432
	Aug 02 16:39:29 server1.project33.ca pgbouncer[28009]: 2020-08-02 16:39:29.959 EDT [28009] WARNING cannot listen on unix:/var/run/postgresql/.s.PGSQL.6432: bind(): Permission denied
	Aug 02 16:39:29 server1.project33.ca pgbouncer[28009]: 2020-08-02 16:39:29.959 EDT [28009] LOG process up: PgBouncer 1.14.0, libevent 2.0.21-stable (epoll), adns: libc-2.17, tls: OpenSSL 1.0....  26 Jan 2017
	Hint: Some lines were ellipsized, use -l to show in full.

**Comment by eulerto** [comment]
Service is up. There is still a WARNING. That's because `unix_socket_dir` is set to a directory that `pgbouncer` user does not have access. Open `/etc/pgbouncer/pgbouncer.ini` and adjust it to `/var/run/pgbouncer` or even `/tmp` (instead of `/var/run/postgresql`).

**Comment by daBee** [comment]
OK, with regards to `unix_socket_dir`, I set it to `/var/run/pgbouncer`, as it wasn't showing up on the LAN.  I will try `/tmp`.  

I got it going, but I cannot see it on the LAN on port 6432.  Invisible.  `unix_socket_dir` is set to `/tmp` **only**.  It says address already in use?

	[Sun Aug 02 21:37 rich@server1 ~] pgbstart
	==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
	Authentication is required to manage system services or units.
	Authenticating as: Rich (rich)
	Password:
	==== AUTHENTICATION COMPLETE ===
	[Sun Aug 02 21:37 rich@server1 ~] pgbstatus
	● pgbouncer.service - A lightweight connection pooler for PostgreSQL
		 Loaded: loaded (/usr/lib/systemd/system/pgbouncer.service; disabled; vendor preset: disabled)
		 Active: active (running) since Sun 2020-08-02 21:37:31 EDT; 3s ago
	 Main PID: 5112 (pgbouncer)
		 CGroup: /system.slice/pgbouncer.service
						 └─5112 /usr/bin/pgbouncer /etc/pgbouncer/pgbouncer.ini

	Aug 02 21:37:31 server1.project33.ca systemd[1]: Started A lightweight connection pooler for PostgreSQL.
	Aug 02 21:37:31 server1.project33.ca pgbouncer[5112]: 2020-08-02 21:37:31.955 EDT [5112] LOG kernel file descriptor limit: 1024 (hard: 4096); max_client_conn: 100, max expected fd use: 232
	Aug 02 21:37:31 server1.project33.ca pgbouncer[5112]: 2020-08-02 21:37:31.956 EDT [5112] LOG listening on 0.0.0.0:6432
	Aug 02 21:37:31 server1.project33.ca pgbouncer[5112]: 2020-08-02 21:37:31.956 EDT [5112] LOG listening on [::]:6432
	Aug 02 21:37:31 server1.project33.ca pgbouncer[5112]: 2020-08-02 21:37:31.956 EDT [5112] WARNING cannot listen on unix:/tmp/.s.PGSQL.6432: bind(): Address already in use
	Aug 02 21:37:31 server1.project33.ca pgbouncer[5112]: 2020-08-02 21:37:31.956 EDT [5112] LOG process up: PgBouncer 1.14.0, libevent 2.0.21-stable (epoll), adns: libc-2.17, tls: OpenSSL 1.0.2k...  26 Jan 2017
	Hint: Some lines were ellipsized, use -l to show in full.

**Comment by daBee** [comment]
OK Monday morning.  Says it is up, with recent status, yet nmap on two pointers to the same box, doesn't show port 6432 as eing active with pgbouncer.

	● pgbouncer.service - A lightweight connection pooler for PostgreSQL
		 Loaded: loaded (/usr/lib/systemd/system/pgbouncer.service; disabled; vendor preset: disabled)
		 Active: active (running) since Sun 2020-08-02 21:37:31 EDT; 7h ago
	 Main PID: 5112 (pgbouncer)
		 CGroup: /system.slice/pgbouncer.service
						 └─5112 /usr/bin/pgbouncer /etc/pgbouncer/pgbouncer.ini

	Aug 03 04:53:31 server1.project33.ca pgbouncer[5112]: 2020-08-03 04:53:31.956 EDT [5112] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
	Aug 03 04:54:31 server1.project33.ca pgbouncer[5112]: 2020-08-03 04:54:31.956 EDT [5112] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
	Aug 03 04:55:31 server1.project33.ca pgbouncer[5112]: 2020-08-03 04:55:31.956 EDT [5112] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
	Aug 03 04:56:31 server1.project33.ca pgbouncer[5112]: 2020-08-03 04:56:31.957 EDT [5112] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
	Aug 03 04:57:31 server1.project33.ca pgbouncer[5112]: 2020-08-03 04:57:31.957 EDT [5112] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
	Aug 03 04:58:31 server1.project33.ca pgbouncer[5112]: 2020-08-03 04:58:31.956 EDT [5112] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
	Aug 03 04:59:31 server1.project33.ca pgbouncer[5112]: 2020-08-03 04:59:31.956 EDT [5112] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
	Aug 03 05:00:31 server1.project33.ca pgbouncer[5112]: 2020-08-03 05:00:31.957 EDT [5112] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
	Aug 03 05:01:31 server1.project33.ca pgbouncer[5112]: 2020-08-03 05:01:31.956 EDT [5112] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
	Aug 03 05:02:31 server1.project33.ca pgbouncer[5112]: 2020-08-03 05:02:31.956 EDT [5112] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us
	[Mon Aug 03 05:02 rich@server1 ~] nmap localhost

	Starting Nmap 6.40 ( http://nmap.org ) at 2020-08-03 05:03 EDT
	Nmap scan report for localhost (127.0.0.1)
	Host is up (0.00030s latency).
	Other addresses for localhost (not scanned): 127.0.0.1
	Not shown: 993 closed ports
	PORT     STATE SERVICE
	22/tcp   open  ssh
	25/tcp   open  smtp
	80/tcp   open  http
	139/tcp  open  netbios-ssn
	443/tcp  open  https
	445/tcp  open  microsoft-ds
	5432/tcp open  postgresql

	Nmap done: 1 IP address (1 host up) scanned in 0.09 seconds
	[Mon Aug 03 05:03 rich@server1 ~] nmap 0.0.0.0

	Starting Nmap 6.40 ( http://nmap.org ) at 2020-08-03 05:03 EDT
	Nmap scan report for 0.0.0.0
	Host is up (0.00034s latency).
	Not shown: 993 closed ports
	PORT     STATE SERVICE
	22/tcp   open  ssh
	25/tcp   open  smtp
	80/tcp   open  http
	139/tcp  open  netbios-ssn
	443/tcp  open  https
	445/tcp  open  microsoft-ds
	5432/tcp open  postgresql

	Nmap done: 1 IP address (1 host up) scanned in 0.09 seconds

Just checked the `ini` file:

  listen_addr = *
  listen_port = 6432

**Comment by eulerto** [comment]
nmap does not scan all ports by default, instead, it scan the [most common 1k ports](https://nmap.org/book/man-port-specification.html) for each protocol. You should specify a port range:

`nmap -sT -p0-65535 localhost`

**Comment by daBee** [comment]
OK, I see it now on the server.  But not on the LAN.  I am performing your nmap on my workstation and trying to connect with a `Postgres` client, and still nothing.

**Comment by daBee** [comment]
OK, I was assuming port `6432` would have naturally been opened.  I poked a hole in the firewall, and we have success.  

Thank you!
