### ISSUE TITLE
Create or download binaries for pgbouncer 

### ISSUE THREAD

**Issue by TiedtTech** [pgbouncer/pgbouncer#515]
Hi,
I'm following the steps in the URL https://www.pgbouncer.org/install.html#building-on-windows for building pgbouncer on Windows.

I already installed the MinGW, however I have no idea how to use it or how to compile the pgbouncer.

Does anyone have any step by step tutorial for compiling pgbouncer on Windows? Or do you have the compiled binaries link to make available? It would be nice to have the binaries here on GitHub.

**Comment by petere** [comment]
done: https://github.com/pgbouncer/pgbouncer/releases/tag/pgbouncer_1_15_0
