### ISSUE TITLE
pgbouncer-1.14.0/src/pooler.c:474: undefined reference to `sd_listen_fds_with_names'

### ISSUE THREAD

**Issue by msdnchina** [pgbouncer/pgbouncer#516]
My configure command is :  ./configure --prefix=/home/pgbouncer/soft --with-pam --with-systemd 
when I execute make command, at last ,there are following errors:
     CC       lib/usual/tls/tls_config.c
     CC       lib/usual/tls/tls_conninfo.c
     CC       lib/usual/tls/tls_ocsp.c
     CC       lib/usual/tls/tls_peer.c
     CC       lib/usual/tls/tls_server.c
     CC       lib/usual/tls/tls_util.c
     CC       lib/usual/tls/tls_verify.c
     CCLD     pgbouncer
.objs/pgbouncer/src/pooler.o: In function `pooler_setup':
/home/pgb/pgbouncer-1.14.0/src/pooler.c:474: undefined reference to `sd_listen_fds_with_names'
collect2: error: ld returned 1 exit status
make: *** [pgbouncer] Error 1

**Comment by msdnchina** [comment]
sorry,  I forget tell you my OS version: my OS is RHEL, RHEL version is RHEL7.8 x86-64bit

**Comment by eulerto** [comment]
This was already fixed in commit 33adb9c92896e411df181cabb605b48511fcb079. It was reported in #505.

**Comment by msdnchina** [comment]
Thank you！
