### ISSUE TITLE
'systemd type:notify fix' not working on Centos 8

### ISSUE THREAD

**Issue by hisahin** [pgbouncer/pgbouncer#517]
CentOS Linux release 8.1.1911 (Core)
PgBouncer 1.13.0

Hi,

When install package from repo, on systemd type setted notify. 
I cant start service. But i change type from notify to simple, service started successfuly.

**Comment by petere** [comment]
We have learned that some binaries of PgBouncer are built incorrectly. Where are you getting yours from?

**Comment by petere** [comment]
Closing this since it's probably a packaging issue. We have seen a number of similar ones.
