### ISSUE TITLE
TLS 1.3 not enforcing ciphers

### ISSUE THREAD

**Issue by marco44** [pgbouncer/pgbouncer#518]
When using TLS 1.3, the client_tls_ciphers seems to be ignored
Let's say this is my configuration:
```
client_tls_protocols=tlsv1.2
client_tls_ciphers=AES128+SHA256
client_tls_sslmode=require
```
When connecting, I get: `SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-SHA256, bits: 128, compression: off)`

If I comment out the `client_tls_protocols`, this is not enforced anymore: `SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)`

**Comment by petere** [comment]
Yes, this is correct. This was also recently "discovered" in PostgreSQL. The consensus there was to leave it for now and just document it. I will do the same in PgBouncer.
