### ISSUE TITLE
Modifiying a query - where in the code?

### ISSUE THREAD

**Issue by GildedHonour** [pgbouncer/pgbouncer#519]
I need to modify each SQL query depneding on some condition, after it's been processed by pgbouncer and right before it gets sent futher to Postgresql server. I can't find a place in the code. Where is it?

**Comment by markokr** [comment]
There is no such place...  PgBouncer may even never see full query as a whole, as it processes data with limited buffer.

**Comment by GildedHonour** [comment]
@markokr 
>as it processes data with limited buffer.
where in code does it process it before sending it to PG server?

**Comment by markokr** [comment]
client.c / handle_client_work()

**Comment by GildedHonour** [comment]
This's this: `SBuf *sbuf = &client->sbuf;` ?

**sbuf** contains an SQL query, right? 

Then I'd do `char *my_q = sbuf->io->buf` to get an actual text, or part of it, of a query?

**Comment by markokr** [comment]
Yes, part of query is visible somewhere there.

**Comment by GildedHonour** [comment]
I sent a query multiple times and I haven't the text of a query:

```
sbuf->io->buf ===> Q
pkt->data ===> (null)
pkt->len  ===> 25
```

Where can it be?

**Comment by jonahharris** [comment]
It's there. You're just seeing the first byte 'Q' (Postgres Query Request) followed by the packet length, which it's viewing as a null-terminator. It seems you're not understanding how strings in C work. Regardless, as Marko said, you may never get the full query in a single packet if it's larger than the buffer size.

**Comment by GildedHonour** [comment]
@jonahharris No.

My question was: where, or in what field, and in what variable, is **the body** of query stored? Regardless of whether it can or not be seen as a whole at once.

**Comment by jonahharris** [comment]
What aren't you getting - Marko and I have already told you that?

**Comment by jonahharris** [comment]
What you're already trying to do has already been done by AWS [here](https://github.com/awslabs/pgbouncer-rr-patch/blob/master/src/rewrite_query.c#L55). As I said, and as Marko said, the query is in sbuf->io->buf 5 bytes in (after the 'Q' for Query Packet + the 4 byte length).

**Comment by GildedHonour** [comment]
> As I said, and as Marko said, the query is in sbuf->io->buf 5 bytes in (after the 'Q' for Query Packet + the 4 byte length).

Point me out to a message where you or Marko said precisely that.

**Comment by jonahharris** [comment]
In reply to your comment specifically about sbuf->io->buf:

> Yes, part of query is visible somewhere there.

And in my reply:

> It's there. You're just seeing the first byte 'Q' (Postgres Query Request) followed by the packet length, which it's viewing as a null-terminator

Honestly, if you can't figure out where the query is after two people have told you, or find AWS's patch via [a simple Google search](https://lmgtfy.com/?q=pgbouncer+rewrite+query), you probably shouldn't be mucking around in this code.

@markokr free to close this issue.

**Comment by GildedHonour** [comment]
I said **precisely**. There's no such a message. 

Go learn to read.

**Comment by jonahharris** [comment]
LOL. I'll be sure to get right on that, nameless dude.

That notwithstanding, for the record, the easiest way to understand the basics of overall query access in PGBouncer is to look at the [admin query processing code](https://github.com/pgbouncer/pgbouncer/blob/master/src/admin.c#L1447), which represents a fake PG server. There, you can see the usage of just the pkt->type and pkt->data (rather than the underlying sbuf.)

**Comment by GildedHonour** [comment]
SOL. MOL. DOL. JOL.

You're a kid. An unhappy and bitter one.
