### ISSUE TITLE
pgbouncer appears to lose sync when parameter is set in transaction mode

### ISSUE THREAD

**Issue by roji** [pgbouncer/pgbouncer#52]
I'm working on the .NET driver for PostgreSQL, Npgsql, and I think I've come across an issue.

During my tests, I set pgbouncer in transaction mode, and sent a packet containing a `SET statement_timeout=30000` simple query message, followed by a regular extended protocol query: this seemed to make pgbouncer "lose sync" in some way. I know SET isn't supported in transaction mode, but I'd have expected a clear error rather than the strange behavior below:

Messages sent (as in wireshark): Q/P/D/B/E/S (the first Q is the SET)
Messages received: C/Z

pgbouncer logs:
```
2015-05-24 11:58:13.192 24481 WARNING S-0x8a677a0: npgsql_tests/npgsql_tests@127.0.0.1:5432 got packet 'S' from server when not linked
2015-05-24 11:58:13.192 24481 WARNING S-0x8a677a0: npgsql_tests/npgsql_tests@127.0.0.1:5432 got packet 'S' from server when not linked
2015-05-24 11:58:13.192 24481 WARNING S-0x8a677a0: npgsql_tests/npgsql_tests@127.0.0.1:5432 got packet 'C' from server when not linked
2015-05-24 11:58:13.192 24481 WARNING S-0x8a677a0: npgsql_tests/npgsql_tests@127.0.0.1:5432 got packet 'Z' from server when not linked
```

pgbouncer 1.5.4 on Ubuntu utopic, PostgreSQL 9.3. Let me know if there's any other info that can help.

**Comment by markokr** [comment]
Losing the setting by getting differerent server connection should be normal.  But not losing protocol sync.

Could you send pgbouncer -v -v -v log about that query exchange?

**Comment by roji** [comment]
Here you go: https://gist.github.com/roji/4f3205c2e8ffcdd786fb

My repro simply connects, sends a Q with `set statement_timeout=30000`, sends a trivial P/D/B/E/S sequence and closes the connection. Then it tries to connect again and sends another trivial P/D/B/E/S and the error occurs.

I can reproduce this really easily here, let me know if you need any more info.

**Comment by markokr** [comment]
problem seems to be that client sent stream of several sync commands (Q and S) to server and pgbouncer switches server after the first.

need to think how to solve it.  keep a counter?

**Comment by markokr** [comment]
Counter should solve bind-sync-exec problem in #44 too?

**Comment by PJMODOS** [comment]
yeah I think counter would help with #44 as well

**Comment by markokr** [comment]
Pushed experimental patch to master, please test if it solves the issue.

**Comment by roji** [comment]
Confirmed, using the latest master the problem doesn't occur, thanks!
