### ISSUE TITLE
Makefile:2: config.mak: No such file or directory

### ISSUE THREAD

**Issue by marmiro** [pgbouncer/pgbouncer#520]
Hello. I'm trying to install it:

```
    $ ./configure --prefix=/usr/local
    $ make
```
And it'll thrown an error:

```
Makefile:2: config.mak: No such file or directory
Please run ./configure
make: *** [config.mak] Error 1
```

But why?

It's MacOs.

**Comment by petere** [comment]
What version? From git or tarball? Any interesting output from `configure`?

**Comment by petere** [comment]
closing because no feedback

**Comment by udit47** [comment]
Hi I got this error as well. when installing from git & tarball both

./configure completes with no error 

Please run ./configure
Makefile:2: config.mak: No such file or directory
make: *** [Makefile:132: config.mak] Error 1
