### ISSUE TITLE
reason for auth_query FUNCTION

### ISSUE THREAD

**Issue by mr-deamon** [pgbouncer/pgbouncer#523]
Hi all
This is a question, not a bug! I am working on a green-field approach to setup a postgres-12 cluster and migrate data (and settings) from the existing 9.6-cluster to it.

I am wondering why everybody (for [example](https://www.enterprisedb.com/postgres-tutorials/pgbouncer-authquery-and-authuser-pro-tips)) is suggesting to create a FUNCTION when my predecessor simply configured `auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=$1`.

Is there a security-concern about this way of doing it?
Thanks for enlighting me. :-)

EDIT: Just saw that this is even the default after installing pgbouncer: https://github.com/pgbouncer/pgbouncer/blob/master/etc/pgbouncer.ini#L123

**Comment by petere** [comment]
Querying `pg_shadow` requires superuser access. By defining a function you can give specific access to that function to a dedicated non-superuser. So this follows least-privilege ideas and makes everything a bit more secure in principle.

**Comment by mr-deamon** [comment]
Thanks for your insight, that completely makes sense and i will change my setup!
