### ISSUE TITLE
server_lifetime parameter not working as expected

### ISSUE THREAD

**Issue by caseyallenshobe** [pgbouncer/pgbouncer#524]
I'm using pool_mode = transaction.  The documentation on pgbouncer.org is a bit sparse, but in reading through it, it sounded like lowering the server_lifetime setting to, say 180, would limit connections from pgBouncer to the server to 3 minutes (or a little longer to finish up the current transaction).  But that's not what's happening.  Instead I open a connection to the database, do nothing for 5 minutes, and the connection is still active.

Here's what I'm trying to accomplish - we use a hardware load balancer to balance database connections between a pool of replica nodes.  The load balancer will keep the connection to whatever backend node it is assigned to until it is closed.  So if there is a replica down for a bit and it comes back up, it won't be getting any traffic, since everything is continuing to flow over the established connections to the other nodes.  The desire is that within a relatively small time window after a node comes back online, we would like connections to end up rebalanced across all the nodes.  The server_lifetime setting sounded appropriate for this, but doesn't appear to be doing what it sounds like it should.

Any advice greatly appreciated!

**Comment by eulerto** [comment]
@caseyallenshobe could you share your configuration parameters?

Take a look at the [check_unused_servers](https://github.com/pgbouncer/pgbouncer/blob/master/src/janitor.c#L414). Connections are not killed exactly in `server_lifetime` but **after** it exceeds it. pgbouncer will close the connection depending on your pool size and the last time one connection was closed due to lifetime. It is like that because it would avoid relaunching connections after successive connection peaks. In the worst case (close a connection a fraction of us ago and your pool size is one), you close the connection in `2 * server_lifetime`.

Documentation is correct when it says

> The pooler will close an unused server connection that has been connected longer than this.

**Comment by caseyallenshobe** [comment]
Here is the configuration:
```
logfile = /var/log/postgresql/pgbouncer.log
pidfile = /var/run/postgresql/pgbouncer.pid
listen_port = 6432
listen_backlog = 256
unix_socket_dir = /var/run/postgresql
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
pool_mode = transaction
server_reset_query = DISCARD ALL
max_client_conn = 10000
default_pool_size = 8
server_lifetime = 180
min_pool_size = 2
idle_transaction_timeout = 60
ignore_startup_parameters = extra_float_digits
```

**Comment by petere** [comment]
Yeah, I think this is just a misunderstanding of what the parameter is supposed to do.

**Comment by caseyallenshobe** [comment]
petere, could you please let me know what my error in understanding is?  Is there another way to accomplish the result I'm desiring?

**Comment by petere** [comment]
What you appear to expect is that PgBouncer would close a connection that is in use. That doesn't happen.

What happens is: After the client closes the connection, PgBouncer decides what to do with the server connection: Either put it back into the pool for the next client, or close it, if it has been longer than `server_lifetime`.

I think to get closer to what you want, you need to get the client to close the connection if it's not needed. That would then kick off that cycle of deciding what to do with the server connection. You could look at `client_idle_timeout`, but better let the client do it itself.

**Comment by caseyallenshobe** [comment]
No, client connections are all short-lived - the application makes many separate connections doing small amounts of work usually taking a few seconds or less.  If the server_lifetime is exceeded for a connection, then shouldn’t that connection be closed by pgbouncer as soon as the current running transaction completes?

**Comment by caseyallenshobe** [comment]
I worked with the people who were testing this more, and identified some problems in the way they were testing that were incorrect.  pgBouncer is actually closing the connections shortly after the server_lifetime setting, and it's working as it should.  I apologize for the false bug report!
