### ISSUE TITLE
FEATURE requested : Add a command to get the global status of the pgbouncer server (paused or resumed)

### ISSUE THREAD

**Issue by lohengrin1870** [pgbouncer/pgbouncer#528]
Hello,
I try to find a command which indicates if a pgbouncer has been paused but didn't find : the only way is to look in the log file. Would it be possible to implement such command ? Thank you and best regards

**Comment by petere** [comment]
The per-database pause mode can be seen in the output of `SHOW DATABASES`. The global pause mode is currently not visible. Any suggestions how to show that?

**Comment by davidfetter** [comment]
Is there any difference between `global pause mode` and `all databases are paused`? If not, a thing that scans for unpaused databases and stops if it finds one that's not would be a thing that could be made directly visible. This would be a pretty trivial thing to do with https://github.com/davidfetter/pgbouncer_wrapper or https://github.com/CrunchyData/pgbouncer_fdw

**Comment by petere** [comment]
> Is there any difference between `global pause mode` and `all databases are paused`?

Yes, see here: https://github.com/pgbouncer/pgbouncer/blob/master/src/admin.c#L1071-L1088

**Comment by davidfetter** [comment]
So I see that the `cf_pause_mode` global, which at a quick glance changes how pgbouncer responds to `SIGUSR2` and I'm not quite sure what else that would make any difference, gets set there in one case but not the other. I guess reference counting would be a bit of a pain, as it always is when there's a potential for a race condition, if there was some desire to make the conditions equivalent. Is that the reason they're different, or is it more along the lines of how that would change `all databases are paused` from doing nothing on `SIGUSR2` to suddenly waking up? I guess if people were counting on that difference, it could be a pretty important one.

**Comment by lohengrin1870** [comment]
Thanks for your involvement. The issue we have faced is that we have a script (promote and follow) at one time which has launched a SIGUSR1 to the pgbouncer process but didn't launch the SIGUSR2 signal...The pgbouncer was blocked but didn't know that the SIGUSR1 was received by the pgbouncer. It's only in the log. So I thought it would be a good idea to have a command which shows that the pgbouncer is paused, what do you think ?

**Comment by lohengrin1870** [comment]
Hello
Did you have an update about this feature requested ? I can see that there is a PR still opened, is there any chance to see this feature one day ? What's blocking ? 
@eulerto Anyway thank you for having implemented this feature
