### ISSUE TITLE
Pooler Error: bad packet header: '70'

### ISSUE THREAD

**Issue by fluancefg** [pgbouncer/pgbouncer#53]
Hi,
I'm trying to setup a connection pooler with JDBC through stunnel. The connection pooler is configured in session mode.
When I send a query in Java, I almost always get the above error, but sometimes it works as expected without any error.
It only happends when there's an authentication process (md5 or plain). When setting the auth_type to 'trust', it works as expected without any error.
I dont't know where and what to investigate. Any help or ideas are welcome.

**Comment by fluancefg** [comment]
It only happends when there's an authentication process (md5 or plain). When setting the auth_type to 'trust', it works as expected without any error.

**Comment by fluancefg** [comment]
The reason of this bug has been identified by Michal Trojnara, author of stunnel.
PgBouncer incorrectly assumes that all the authentication messages fit within a single network packet.  This may be true, unless the network uses a very low MTU, or the username is very long, or SSL/TLS adds its handshake before authentication (which is the case here).
This bug has been introduced by the following commit: https://github.com/pgbouncer/pgbouncer/commit/18f4e290b19418f837e3b3b50b8545269fd5e349

**Comment by markokr** [comment]
I applied improved Michal's fix in fd3c7138b6a
