### ISSUE TITLE
LDAPS auth with PGBouncer.

### ISSUE THREAD

**Issue by bharathregal** [pgbouncer/pgbouncer#530]
All,
We are working on enabling PGBouncer across all our DBInstances but we are facing issue while enabling LDAPS for PGBouncer. All our existing PGDB hosts are configured with LDAPS and are working perfectly fine. Can we do the same(LDAPS Auth) using PGBouncer?

Couple options that we tried:
1. Auth_type = PG_HBA with PG_HBA file holding configs related to LDAPS.
2. Have users_list.txt file populated with LDAP Query as posted in below link
https://gpdb.docs.pivotal.io/510/admin_guide/access_db/topics/pgbouncer.html#topic_m2h_5dj_5s

Does PGBouncer have LDPAS/LDAP/Radius Auth capabilities? If so, pls adivise.
If not for above options, any other choices for Integrated auth using PGBouncer?

**Comment by achix** [comment]
Hello,
haven't caught up with the latest releases to be frank, but the way to have pgbouncer authenticate via LDAP is with auth_type = pam
(not hba)

**Comment by petere** [comment]
Yes, using PAM is the way to go for LDAP.
