### ISSUE TITLE
How can i use so_reuseport at Centos 7 with Oracle VM?

### ISSUE THREAD

**Issue by killerwzb** [pgbouncer/pgbouncer#531]
Hi all:

   I use so_reuseport at Centos 7 ,if i run two pgbouncer ,the first one is successed, but the other one is failed.

   The error message like this : 2020-09-28 09:09:51.133 CST [2652] FATAL unix socket is in use, cannot continue
  The pgboucer.ini 
  [databases]
  a1 =  host=127.0.0.1 port=5432 dbname=test1 pool_size=50
  a2 =  host=127.0.0.1 port=5432 dbname=test pool_size=30
  [pgbouncer]
  listen_port = 6688
  listen_addr = localhost
  auth_type = md5
  auth_file = /home/postgres/pgbouncer/bin/userlist.txt
  ;;logfile = /home/postgres/pgbouncer/pgbouncer.log
  ;;pidfile =/home/postgres/pgbouncer/pgbouncer.pid
  unix_socket_dir = /tmp
  #unix_socket_mode = 0777
  admin_users = wzb
  stats_users = wzb
  pool_mode = session
  max_client_conn=1000
  default_pool_size=30
  so_reuseport = 1

  Thanks.

**Comment by petere** [comment]
You need to define a different Unix-domain socket for the two instances. The reuseport setting only applies to TCP/IP sockets.
