### ISSUE TITLE
Pgbouncer setup with repmgr for Posgtes Master , standby1 standby2  issue

### ISSUE THREAD

**Issue by kaurav1108** [pgbouncer/pgbouncer#532]
Hi Team,
I am facing an issue as i have setup the below HA concept for Postgres sql.
node1 : Master
node2 : standby1
node3: standby2
node4 : pgbouncer server

ssh keys are exchange bettween servers,
note : replication between master and standby hapenning successful as my goal is as as a client i want to connect postgres HA database without changing configuration of host and port for that i have used pgbouncer
when my master is down so replication will make my standby1 as new master and sending that entry to pgbouncer.database.ini file to pgbouncer nodes .

so do i need to create separate DB on pgbouncer node to connet the database or pgbouncer will check the entry pgbouncer.database.ini file and try to connect the database, if this like then it is not hapenning
**as i am getting psql: ERROR:  pgbouncer cannot connect to server**

failover.sh content:
#!/usr/bin/env bash
set -u
set -e
set -x

# Configurable items
PGBOUNCER_HOSTS="dewsttlas401.de.pri.o2.com"
PGBOUNCER_DATABASE_INI="/home/pgbouncer/pgbouncer.database.ini"
PGBOUNCER_DATABASE="gitlabdb"
PGBOUNCER_PORT=3232

REPMGR_DB="gitlabdb"
REPMGR_USER="gitlabdb"

# 1. Promote this node from standby to primary

/usr/pgsql-11/bin/repmgr standby promote -f /opt/app/postgresdb/repconf/repmgr.conf --log-to-file

# 2. Reconfigure pgbouncer instances

PGBOUNCER_DATABASE_INI_NEW="/tmp/pgbouncer.database.ini"

for HOST in $PGBOUNCER_HOSTS
do
    # Recreate the pgbouncer config file
    echo -e "[databases]\n" > $PGBOUNCER_DATABASE_INI_NEW

/usr/pgsql-11/bin/psql -d $REPMGR_DB -U $REPMGR_USER -p 7433 -t -A \
      -c "SELECT '${PGBOUNCER_DATABASE}= ' || conninfo || ' application_name=pgbouncer_${HOST}' \
          FROM repmgr.nodes \
          WHERE active = TRUE AND type='primary'" >> $PGBOUNCER_DATABASE_INI_NEW

/usr/pgsql-11/bin/psql -d $REPMGR_DB -U $REPMGR_USER -p 7433 -t -A \
      -c "SELECT '${PGBOUNCER_DATABASE}= ' || conninfo || ' application_name=pgbouncer_${HOST}' \
          FROM repmgr.nodes \
          WHERE node_name='${HOST}'" >> $PGBOUNCER_DATABASE_INI_NEW

    rsync $PGBOUNCER_DATABASE_INI_NEW pgbouncer@$HOST:$PGBOUNCER_DATABASE_INI

/usr/pgsql-11/bin/psql -tc "SELECT pg_reload_conf()" -h $HOST -p $PGBOUNCER_PORT -U gitlabdb gitlabdb

done

# Clean up generated file
#rm $PGBOUNCER_DATABASE_INI_NEW

echo "Reconfiguration of pgbouncer complete"

repmgf.conf : 
node_id=2
node_name=dewsttlas403.de.pri.o2.com
conninfo='host=dewsttlas403.de.pri.o2.com user=gitlabdb dbname=gitlabdb port=7433 password=gitlabdb'
data_directory='/opt/app/postgresdb/gitlabdb11'
failover=automatic
priority=60
connection_check_type='ping'
primary_visibility_consensus=true
standby_disconnect_on_failover=true
promote_command='/opt/app/postgresdb/failover.sh'
follow_command='/usr/pgsql-11/bin/repmgr standby follow -f /opt/app/postgresdb/repconf/repmgr.conf --log-to-file --upstream-node-id=%n'
log_file='/opt/app/postgresdb/repconf/repmgr.log'
log_level=DEBUG
reconnect_attempts=4
reconnect_interval=5
pg_bindir='/usr/pgsql-11/bin/'
pg_ctl_options='-D /opt/app/postgresdb/gitlabdb11'
service_start_command = '/usr/pgsql-11/bin/pg_ctl -D /opt/app/postgresdb/gitlabdb11 -l logfile start'
service_stop_command = '/usr/pgsql-11/bin/pg_ctl -D /opt/app/postgresdb/gitlabdb11 stop'
use_replication_slots=true

**Comment by kaurav1108** [comment]
@oceancode11  can you help the same

**Comment by petere** [comment]
This looks more like a request for setup help and not an actual issue report.
