### ISSUE TITLE
pgbouncer needs a reload after starting

### ISSUE THREAD

**Issue by pikrzysztof** [pgbouncer/pgbouncer#534]
`systemctl start pgbouncer` will run pgbouncer but pgbouncer will be useless, claiming that no users exist. You need to reload pgbouncer for it to start working.

To be specific, this is what the user sees:

```
root@cron2-584489bf74-n6mxg:/cron# psql -U duma -h db.gambit -p 6432 duma 
psql: error: could not connect to server: ERROR:  no such user: duma
## pgbouncer reload happens here
root@cron2-584489bf74-n6mxg:/cron# psql -U duma -h db.gambit -p 6432 duma 
psql (12.4 (Ubuntu 12.4-0ubuntu0.20.04.1), server 12.2 (Ubuntu 12.2-2.pgdg18.04+1))
Type "help" for help.

duma=> \q
```
here's what pgbouncer sees:
[pgbouncer.log](https://github.com/pgbouncer/pgbouncer/files/5347120/pgbouncer.log)

`dpkg -l` claims i'm using pgbouncer `1.14.0-1.pgdg18.04+1` (ubuntu 18.04). I'm using postgresql `12.2-2.pgdg18.04+1`

```
root@sov-lisa:/var/log/postgresql# pgbouncer --version
PgBouncer 1.14.0
libevent 2.1.8-stable
adns: c-ares 1.14.0
tls: OpenSSL 1.1.1  11 Sep 2018
```

here's my pgbouncer.ini:

```
[databases]
duma = dbname=duma host=db.gambit port=5432
molly = dbname=duma host=db.gambit port=5432
readduma = dbname=duma host=read-db.gambit port=5432
clonedb = dbname=duma host=clone-db.gambit port=5432


[pgbouncer]
verbose = 10
auth_user = dbpool
auth_type = md5
; this stores plaintext password for pgbouncer to login and use auth_query
auth_file = /etc/pgbouncer/userlist.txt
auth_query = SELECT uname, phash FROM user_lookup($1)

logfile = /var/log/postgresql/pgbouncer.log
pidfile = /var/run/postgresql/pgbouncer.pid
listen_addr = *

; pgbouncer needs a restart (not a reload) to change listen_port
listen_port = 6432
unix_socket_dir = /var/run/postgresql

admin_users = dbpool
pool_mode = transaction
server_reset_query =

ignore_startup_parameters = extra_float_digits
max_client_conn = 2000
default_pool_size = 50
log_connections = 1
log_disconnections = 1
log_pooler_errors = 1

; disconnect people in 'idle in transaction' state (seconds)
idle_transaction_timeout = 300
```

and my userlist.txt has only one row:
```
"dbpool": "censored"
```

Here's how I setup pgbouncer auth query:

      CREATE SCHEMA IF NOT EXISTS AUTHORIZATION {{ dbpool_user.name }};
      ALTER USER {{ dbpool_user.name }} set search_path to "$user";
      CREATE OR REPLACE FUNCTION {{ dbpool_user.name }}.user_lookup(in i_username text, out uname text, out phash text)
      RETURNS record AS $$
      BEGIN
        SELECT usename, passwd FROM pg_catalog.pg_shadow
        WHERE usename = i_username INTO uname, phash;
        RETURN;
      END;
      $$ LANGUAGE plpgsql SECURITY DEFINER;
      REVOKE ALL ON FUNCTION {{ dbpool_user.name }}.user_lookup(text) FROM public, {{ dbpool_user.name }};
      GRANT EXECUTE ON FUNCTION {{ dbpool_user.name }}.user_lookup(text) TO {{ dbpool_user.name }};

**Comment by petere** [comment]
I think this is the same issue as #391.

**Comment by petere** [comment]
Closing this as #391 has been fixed. In the next release, this should work better.
