### ISSUE TITLE
pgbouncer ldap authorization does not work!

### ISSUE THREAD

**Issue by vldanch** [pgbouncer/pgbouncer#535]
ERROR:
```
2020-10-08 11:23:59.887 UTC [18371] LOG C-0x5631fb63df70: postgres/user@ip:42038 login attempt: db=postgres user=user tls=no
2020-10-08 11:23:59.887 UTC [18371] LOG C-0x5631fb63df70: postgres/user@ip:42038 closing because: password authentication failed (age=0s)
2020-10-08 11:23:59.887 UTC [18371] WARNING C-0x5631fb63df70: postgres/user@ip:42038 pooler error: password authentication failed
```
`version PgBouncer 1.14.0`
Setting by reference: [ldap-configuration](https://gpdb.docs.pivotal.io/510/admin_guide/access_db/topics/pgbouncer.html)
```
cat /etc/postgresql/12/main/pg_hba.conf

host  all  all  0.0.0.0/0  ldap ldapscheme=ldap ldaptls=0 ldapserver=dc01.test.ru ldapport=389 ldapbasedn="OU=omg,OU=csp,OU=Users,OU=csp,DC=test,DC=ru" ldapbinddn="CN=ldap,OU=ServiceAccount,OU=Users,OU=test,DC=test,DC=ru" ldapbindpasswd=pass ldapsearchattribute="sAMAccountName"
```
```
cat /etc/pgbouncer/pgbouncer.ini
[databases]
postgres = host=127.0.0.1 port=5432 dbname=postgres

[pgbouncer]
pidfile = /var/run/pgbouncer/pgbouncer.pid
logfile = /var/log/postgresql/pgbouncer.log
listen_port = 6432
listen_addr = 0.0.0.0
auth_type = plain
auth_file = /etc/pgbouncer/userlist.txt
ignore_startup_parameters = extra_float_digits
```
```
cat /etc/pgbouncer/userlist.txt
"user" "ldap://dc01.test.ru:389/user"
```
Is it possible to fix something like that?

**Comment by eulerto** [comment]
This setup is not supported. pgbouncer authentication using LDAP is possible if you use PAM (`auth_type = pam`). This issue is related to #469

**Comment by vldanch** [comment]
@eulerto want to say that this solution works? [click](https://severalnines.com/database-blog/one-security-system-application-connection-pooling-and-postgresql-case-ldap)

**Comment by petere** [comment]
Setting up PAM is outside the scope of the PgBouncer documentation. Also, we can't take responsibility for the quality or clarity of other web sites.  Is there anything _inside_ PgBouncer that needs to be done here?

**Comment by vldanch** [comment]
@petere inside you need to make support for ldap =))))))

**Comment by petere** [comment]
Okay, we already have issue #469 for that.
