### ISSUE TITLE
Pgbouncer configuration for Postgres HA

### ISSUE THREAD

**Issue by desalehemant87** [pgbouncer/pgbouncer#536]
Hi Team,

We have setup Pgbouncer along with 1 master Postgres db and 2 standby db's.

Pgbouncer is successfully routing request to master , also whenever master is down it is making secondary db as master and routing the request.

But whenever pgbouncer itself is down then we can not achieve single point of failover.

Is there any way to have pgbouncer running in HA mode , i.e can we have 2 pgbouncer instances running , when one is down other should automatically take over the control.

Please suggest.

**Comment by uspen** [comment]
so_reuseport

**Comment by desalehemant87** [comment]
> so_reuseport

Hi,
Could you please help how can we have 2 pgbouncers running for the HA setup

**Comment by uspen** [comment]
pgbouncer-one.ini and pgbouncer-two.ini

`[pgbouncer]`

`listen_addr = 0.0.0.0`
`listen_port = 6432`
`so_reuseport = 1`

for one:
`.......`
`logfile = /var/log/pgbouncer/one.log`
`pidfile = /run/pgbouncer/one.pid`
`unix_socket_dir = /run/pgbouncer/one`

for two:
`.......`
`logfile = /var/log/pgbouncer/two.log`
`pidfile = /run/pgbouncer/two.pid`
`unix_socket_dir = /run/pgbouncer/two`

systemd unit:

`# /etc/systemd/system/pgbouncer@.service`
`.include /lib/systemd/system/pgbouncer.service`
`[Service]`
`Environment=BOUNCERCONF=/etc/pgbouncer/pgbouncer-%i.ini`
`PIDFile=/run/pgbouncer/%i.pid`

**Comment by petere** [comment]
Or you run two pgbouncers on different hosts and use a hardware load balancer or HAProxy and something like that.
