### ISSUE TITLE
Bizarre typos/nonsensical sentences in config file documentation

### ISSUE THREAD

**Issue by gityerhubhere** [pgbouncer/pgbouncer#54]
http://pgbouncer.github.io/config.html

'Config file is in "ini" format. Section names are between " and ". Lines starting with ";" or "" are taken as comments and ignored. The characters ";" and "" are not recognized when they appear later in the line.'

What? Between <quote> and <quote>? Lines starting with a semi-colon or... empty char? This makes the project appear like a joke for people forced to use pgbouncer with PostgreSQL due to PostgreSQL being so slow with making new connections so you have to use a pooler. Please go through and fix the nonsensical documentation.

**Comment by PJMODOS** [comment]
The above mentioned typos have been fixed, mostly issues with markdown conversion.
I suggest you to improve your communication skills.
