### ISSUE TITLE
is it possible to hide DB credentials from startup output

### ISSUE THREAD

**Issue by FleZzz** [pgbouncer/pgbouncer#547]
in case using pgbouncer/pgbouncer docker image
in log stream output db credentials listed from 
https://gitlab.com/aztek-io/oss/containers/pgbouncer-container/-/blob/master/entrypoint.sh#L59
is there some quiet options to hide it without customizing entrypoint?

```
Creating pgbouncer config in /etc/pgbouncer
#pgbouncer.ini

[databases]
* = host = test port=5432 user=user password=passs dbname=test

```

also question about how to pass credentials for incoming connections (by default they are stored in userlist.txt)

**Comment by petere** [comment]
I don't understand this. What specifically is pgbouncer logging that you don't like? Can you show an example?

**Comment by FleZzz** [comment]
here is example about credentials in output

`docker run -ti -e DATABASES_HOST=testhost -e DATABASES_DBNAME=testdb -e DATABASES_USER=user -e DATABASES_PASSWORD=pass pgbouncer/pgbouncer
`
```
Creating pgbouncer config in /etc/pgbouncer
#pgbouncer.ini

[databases]
* = host = testhost port=5432 user=user password=pass dbname=testdb

[pgbouncer]
listen_addr = 0.0.0.0
auth_type = any
ignore_startup_parameters = extra_float_digits

# Log settings
admin_users = postgres

# Connection sanity checks, timeouts

# TLS settings

# Dangerous timeouts

Starting pgbouncer.
2020-11-18 07:57:32.090 UTC [1] LOG kernel file descriptor limit: 1048576 (hard: 1048576); max_client_conn: 100, max expected fd use: 112
2020-11-18 07:57:32.090 UTC [1] LOG listening on 0.0.0.0:6432
2020-11-18 07:57:32.091 UTC [1] LOG listening on unix:/tmp/.s.PGSQL.6432
2020-11-18 07:57:32.091 UTC [1] LOG process up: PgBouncer 1.14.0, libevent 2.1.8-stable (epoll), adns: c-ares 1.15.0, tls: LibreSSL 2.7.5

```

im asking about hiding 
* = host = testhost port=5432 user=user password=pass dbname=testdb
string

**Comment by petere** [comment]
Well, there are many ways to set up authentication in pgbouncer. You don't have to do it that way. If the Docker setup you are working with is only giving you the option of doing it that way, you need to check with them if there are any changes possible.

As a direction to research, I would consider a setup using either SCRAM (thus no plain text password) or TLS certificates (thus no passwords at all).
