### ISSUE TITLE
Why are there duplicate information sections on the website?

### ISSUE THREAD

**Issue by gityerhubhere** [pgbouncer/pgbouncer#55]
"Config" and "Usage" seem to repeat the same information, but in slightly different ways. It's very confusing to me, and it made me very disoriented when trying to set up pgbouncer. Is there a good reason for these to be separate and repeat so much info in different ways?

**Comment by PJMODOS** [comment]
Not sure what you mean, config describes the configuration options, the usage has quickstart part which shows only couple of config options that make sense as part of quickstart and rest is mostly about admin commands.
