### ISSUE TITLE
server_idle_timeout does't work 

### ISSUE THREAD

**Issue by Benjaminhu** [pgbouncer/pgbouncer#553]
Config settings:

```
default_pool_size = 10
max_client_conn = 500
pool_mode = transaction
query_timeout = 300
reserve_pool_size = 10
server_idle_timeout = 30
server_lifetime = 60
```

The connection does not close after 30 seconds, but after 60 seconds.
I find that only `server_lifetime` affects it.
The status of the connection is `idle` all the way.

Env:
```
PgBouncer 1.14.0 or PgBouncer 1.12.0 (They work the same ie the setting does not work)
AWS - RDS - PostgreSQL 10.11
```

**Comment by petere** [comment]
Works for me.

Can you show a concrete set of steps that you use to reproduce this? Maybe there is a misunderstanding somewhere.

**Comment by Benjaminhu** [comment]
I am no longer working on the project, I cannot provide more information.
