### ISSUE TITLE
[Question] Binary build

### ISSUE THREAD

**Issue by ltagliamonte-dd** [pgbouncer/pgbouncer#554]
Hello folks!!
I was wondering if there is an official apt mirror that keeps track of the pgbouncer releases so that I don't have to build the binary on my own, currently on a default debian i only have:
```
root@a5b103aaf774:/# apt list -a pgbouncer
Listing... Done
pgbouncer/stable 1.9.0-2 amd64
```
Thanks!

**Comment by ltagliamonte-dd** [comment]
i've found `apt.postgresql.org` but it has only 1.14:
```
apt list -a pgbouncer
Listing... Done
pgbouncer/buster-pgdg 1.14.0-1.pgdg100+1 amd64
pgbouncer/stable 1.9.0-2 amd64
```

**Comment by BSVogler** [comment]
For the postgres repo I get ` pgbouncer : Depends: libevent-2.1-6 (>= 2.1.8-stable) but it is not installable` even after a `sudo apt-get install libevent-dev`

**Comment by petere** [comment]
`apt.postgresql.org` is the recommended place. If the package there is not up to date, please give them a ping, and I'm sure it will be updated soon.

**Comment by petere** [comment]
pgbouncer 1.15.0 was uploaded to Debian proper today, so I expect that it will appear on `apt.postgresql.org` soon.

**Comment by petere** [comment]
It's available on `apt.postgresql.org` now.
