### ISSUE TITLE
Pgbouncer "pause" command is not updating "paused" column values in databases view

### ISSUE THREAD

**Issue by zurikus** [pgbouncer/pgbouncer#557]
Hello to everyone, 

Is there any explanation why pgbouncer "pause" command, without providing explicit DB name in it, does not  update "paused" column in "databases" view? 

Can this be considered as a bug?

**Comment by petere** [comment]
A global pause is different from a per-database pause. See also #528.

**Comment by zurikus** [comment]
Hi Petere, thank you for response.

I liked the comment https://github.com/pgbouncer/pgbouncer/issues/528#issuecomment-730526799
Some kind of command to show if pgbouncer is paused or not would be usefull for me as well. 

At this moment during switchover I'm executing custom script, that pauses all pgbouncer DB-es one by one explicitly (without pgbouncer DB) and checking column "paused" with "show databases" by awking result. 

But it is not so convinient so much and error prone as this custom pgbouncer pause script should be up to date all the time.

**Comment by petere** [comment]
Yes, let's follow the discussion in the other issue.
