### ISSUE TITLE
Credential rotation support

### ISSUE THREAD

**Issue by sezaru** [pgbouncer/pgbouncer#563]
Hello, is it possible to configure pgbouncer to support credential rotation?

My scenario is that I have a system that creates new database credentials with a TTL (These are created by HashiCorp Vault), whenever an old credential expires:

```sql
CREATE ROLE "{{name}}" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}'; 
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "{{name}}"; 
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO \"{{name}};
```

When my backend sends a new query to its connection pool and the request fails with `permission denied for table ...` it will automatically close that connection, request a new credential, and insert a new connection to the pool.

This works great, but as soon as I add PGBouncer to the mix it breaks.

If I force my database connection with a username and password like this:
```ini
[databases]
data_db_dev = host=192.167.10.2 port=5432 user=postgres password=postgres dbname=data_db_binance_dev

[pgbouncer]
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
auth_user = pgbouncer
auth_query = SELECT p_user, p_password FROM public.lookup($1)
```

It will connect fine with the new credential from my end, but from pgbouncer the connection to the database will be via `postgres` user, so my queries will keep working even when that credential expires, basically ignoring my ROLE settings.

Another alternative is removing the user/password from the config:
```ini
data_db_dev = host=192.167.10.2 port=5432 dbname=data_db_binance_dev
```

This seems to work better since pgbouncer will connect with the new credential too instead of the `postgres` user, but when the credential expires, it will not recognize it and will keep the connection alive.

So, is there some workaround to make this work?

**Comment by petere** [comment]
If I understand this correctly, you want PgBouncer to close the server connections when the users/passwords on the server change. But PgBouncer doesn't know when this happens, so you have to tell it somehow. Then you can run the `RECONNECT` command, which will cause all connections to close and reopen. Another way would be to do it on the server side. Just forcibly close all incoming connections. This seems more sensible to me in terms of separation of concerns, but your ideas might be different.

**Comment by petere** [comment]
closing as stale
