### ISSUE TITLE
ERROR:  password authentication failed (docker)

### ISSUE THREAD

**Issue by IvanChernoborodov** [pgbouncer/pgbouncer#570]
Trying to run on local machine.

Postgresql - 5432 (I can connect to it easily)

Running pgbouncer
docker run --rm \
    -e DATABASE_URL="postgres://test_user:test_user@localhost/local_prod_db" \
    -p 6432:5432 \
    edoburu/pgbouncer

Trying to connect to pgbouncer through python(django) 6432 and got ERROR:  password authentication failed.

**Comment by RonquilloAeon** [comment]
I'm experiencing a similar issue in production - `pooler error: password authentication failed`. It just started happening this morning.

**Comment by RonquilloAeon** [comment]
@IvanChernoborodov try specifying the image version `edoburu/pgbouncer:1.15.0`. For some reason, `pgbouncer:latest` wasn't working for me.

**Comment by IvanChernoborodov** [comment]
@RonquilloAeon Thanks for the answer but I'm getting the same issue anyway.
My pgbouncer.ini 
```
pgbouncer % docker run --rm \
    -e DATABASE_URL="postgres://user:password@my_remote_db_host/db_name" \
    -p 5432:5432 \
    -v ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro \
    edoburu/pgbouncer


pooler error: password authentication failed

pgbouncer.ini

[databases]
* = host=my_remote_db_host port=5432 dbname=db_name password=password

[pgbouncer]
listen_addr = *
listen_port = 5432
auth_type = md5
auth_file = ./userlist.txt
pool_mode = session
max_client_conn = 1300
default_pool_size = 20
ignore_startup_parameters = extra_float_digits
server_tls_sslmode = disable



userlist.txt
"user" "md53f84a3c26198d9b94054ca7a3839366d"

```

**Comment by eulerto** [comment]
It seems to be related to [this issue](https://github.com/edoburu/docker-pgbouncer/issues/33). If you provide your own configuration files it should work.

```bash
docker run --rm \
    -e DATABASE_URL="postgres://foo:secretpassword@localhost/foodb" \
    -p 6432:6432 \
    -v /tmp/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro \
    -v /tmp/userlist.txt:/etc/pgbouncer/userlist.txt:ro \
    edoburu/pgbouncer
```

**Comment by humblemodulo** [comment]
Not to revive a closed thread, but I am very confused by the "pgbouncer.ini" and "userlist.txt" configuration requirements.  I'm providing each file manually:


[userlist.txt]
```
"postgres" "md5891d7d5079424b1cb973187d354d78de"
```

[pgbouncer.ini]

```
[databases]
custom_db = dbname=custom_db host=pgservice port=5432 user=DBUSER password=PASSWORD


[pgbouncer]
listen_port = 5432
listen_addr = *
auth_type = md5
pool_mode = session
auth_file = /etc/pgbouncer/userlist.txt
logfile = /etc/pgbouncer/logs/pgbouncer.log
```


Whenever I attempt to `psql postgres://127.0.0.1:6432/pgbouncer`, I receive the password prompt,  enter the password then receive `password authentication failed`.  I've tried changing `auth_type` to no avail.  Honestly, I'm not even sure if `auth_type` is pertinent to PGBOUNCER or the actual POSTGRES instance.  No doubt I'm suffering from lack of sleep, but clearer documentation with highly explicit examples would be nice.  Perhaps use different passwords so it's clear that POSTGRES passwords aren't required to match PGBOUNCER admin passwords.

Anyway, a bit of clarity would be appreciated regarding how **exactly** to successfully connect to (and through) the bouncer.

**Comment by JelteF** [comment]
your ini file uses listen_port 5432, while your connection string uses port 6432 could that be the reason? i.e. are you actually connecting to the pgbouncer process that is using your config.
