### ISSUE TITLE
Ability to use environment variables in config file

### ISSUE THREAD

**Issue by michaelcrobinson** [pgbouncer/pgbouncer#58]
Hi there,

We are looking at using pgbouncer as a connection pool between our application servers and postgres database. While I've had success configuring pgbouncer to talk to our database, I'm thinking about how we might implement this to production.  Our rails application uses environment variables to handle many configuration parameters across qa/staging/production environments. Does pgBouncer have the ability to use OS environment variables as values in the ini file? For example if I had:

>POSTGRESQL_USERNAME=dbuser
>POSTGRESQL_PASSWORD=qwrqerqwr
>POSTGRESQL_DATABASE=mydb
>POSTGRESQL_HOST=xxx.xxx.xxx.xxx

Then in a pgbouncer.ini file:

>[databases]
>$POSTGRESQL_HOST = host=$POSTGRESQL_HOST user=POSTGRESQL_USER password=POSTGRESQL_PASSWORD

If not supported is there any interest in implementing such a feature? This would allow us to use a single ini file across all environments without any manual intervention after completing deployment. 

Thanks!

**Comment by gregburek** [comment]
This would be nice. Currently, we generate configs at app boot time from config vars in order to run stunnel and pgbouncer alongside an app. https://github.com/heroku/heroku-buildpack-pgbouncer

**Comment by PJMODOS** [comment]
I am not big fan of having ini config depend on environment variables. I think generating the config is the way to go here.

**Comment by PJMODOS** [comment]
Or, alternatively use the %include directive ( http://pgbouncer.github.io/config.html#include-directive )

**Comment by taitelman** [comment]
if you use the PGBouncer as docker you can easily override many of the ENV parameter today. just look at https://github.com/edoburu/docker-pgbouncer/blob/master/entrypoint.sh
