### ISSUE TITLE
Error running pgbouncer.exe: libevent-2-1-7.dll: cannot open shared object file

### ISSUE THREAD

**Issue by gabigeo** [pgbouncer/pgbouncer#581]
Trying to run provided windows executable version 1.15 (pgbouncer-1.15.0-windows-x86_64.zip).
A popup error window appears with the message 
"The code execution cannot proceed because libevent-2-1-7.dll was not found. Reinstalling the program may fix this problem."

Can't this dll be included?
Thanks

**Comment by tamho1** [comment]
+1
I have tried using vcpkg but it retrieves the 2.1.12 version, as "event.dll". 
I'm able to build libevent 2.1.7 from source as "event.lib", but still haven't been able to build the dynamic library version.

**Comment by eulerto** [comment]
According to the [PgBouncer 1.15 release](https://github.com/pgbouncer/pgbouncer/releases/tag/pgbouncer_1_15_0), this package is **experimental**. It does **not** contain dependencies.

You should get the libvent dll files from MSYS2. The package name is [mingw-w64-libevent](https://packages.msys2.org/package/mingw-w64-x86_64-libevent?repo=mingw64). Install [MSYS2](https://www.msys2.org/) and then use `pacman` to install the referred package (see instructions in the package page). Copy the `libevent*.dll` files into your PgBouncer directory.

**Comment by eulerto** [comment]
PR #621 should fix this issue.
