### ISSUE TITLE
Log message does not provide enough context

### ISSUE THREAD

**Issue by pgodfrin-nov** [pgbouncer/pgbouncer#588]
Our install, with Kubernetes, combines the postgres log with the pgbouncer log. When pgbouncer issues a message it's not clear that the source is pgbouncer, the second line does provide a filename, so that helps.
```
2021-05-04 15:09:25.484 UTC [1] FATAL cannot load config file
2021-05-04 15:09:25.484 UTC [1] ERROR syntax error in configuration (/etc/pgbouncer/pgbouncer-sidecar.ini:33), stopping loading
```
Would it be helpful to have an option for format the log header, similar to the postgres log_line_prefix parameter?

**Comment by petere** [comment]
I don't think we want to start worrying about disambiguating our own log messages in case the logs are combined with some other software. If you are doing that, you might want to use syslog, so that the source is automatically tagged.

**Comment by eulerto** [comment]
I would say if your Kubernetes installation is combining the logs from 2 different softwares, it should provide a tag for each log message too. Postgres doesn't provide a tag either (application name is not a tag; there are a lot of messages that won't provide it).
