### ISSUE TITLE
Excessive Error logs: sbuf_send_pending: no dst sock?

### ISSUE THREAD

**Issue by gearheadSBC350** [pgbouncer/pgbouncer#590]
We have a pgbouncer instance in a docker container that is connected to a replicant/slave postgres database, twice now a week apart the log file will inflate up to 25gb with this error: 

sbuf_send_pending: no dst sock?

We were unable to find any info about what this might mean to track down what is causing this. Only able to find a reference to it in source code in pgboucer/src/sbuf.c line 522.

https://github.com/pgbouncer/pgbouncer/blob/e4beeab9c52d538075fbb5db0e5442cdf2fb90e5/src/sbuf.c#L522

Looking for info on what this means so we can root cause.

**Comment by gearheadSBC350** [comment]
Our sbuf_loopcnt is not set in the config so it is set to default of 5. Verbose was not set, and there are not any other sbuf messages in our log or loopcnt messages that we could find. 

We are using this pgbouncer docker container, latest version: https://github.com/brainsam/pgbouncer which looks like it runs pgbouncer version 1.7.2. 

I've attached our settings/config file and a log snippet but the log snippet is just the error repeated.

I can get a verbose log if the error happens again. It's intermittent so doesn't happen all the time.
Although after digging into find our actual pgbouncer version, maybe upgrading to a more recent version could solve our issue. I did not think the docker container used an older version.
[pgbouncer.config.txt](https://github.com/pgbouncer/pgbouncer/files/6468817/pgbouncer.config.txt)

[pgbouncer.log](https://github.com/pgbouncer/pgbouncer/files/6468826/pgbouncer.log)

**Comment by eulerto** [comment]
Did you check your Postgres log around this date/time? Is there any related action (such as those I mentioned in my previous reply)?

My advice is to use the latest version (1.7.2 is too old) and set `verbose = 1`. If it happens again provide as much information as possible.

**Comment by gearheadSBC350** [comment]
After upgrading to latest version we have not seen this issue reoccur. Thank you for the help
