### ISSUE TITLE
online reboot via systemd

### ISSUE THREAD

**Issue by petere** [pgbouncer/pgbouncer#593]
The online reboot (takeover) functionality currently does not work when using systemd. That's because systemd doesn't allow the process to start its own "successor" during a restart; it needs to manage that itself. I think there is a way to have this functionality, though, and I'll sketch here how I think it could be done.

The current takeover process goes approximately like this:

1. New process is started with `-R` option.
2. New process checks if there is an existing Unix-domain socket. If not, continue with normal (non-takeover) startup.
3. `takeover_part1()`:
    1. Launch new connection to "pgbouncer" database on old process.
    2. `SHOW FDS` and use results to initialize local pools.
4. Then follows most of the normal startup.
5. `takeover_finish()`:
    1. Shut down old server.
    2. Resume all local pools.

In a systemd-enabled implementation of this, instead of having the new process fetch the state information from the old process via `SHOW FDS`, the old process needs to save the information into (some kind of) a file. Systemd will take care of passing over the file descriptors and informing the new process that there is state information to be read. Some details of how this is supposed to work can be found here: https://www.freedesktop.org/software/systemd/man/sd_pid_notify_with_fds.html#FDSTORE=1

So I think what we need here is:

1. A way to serialize the `SHOW FDS` information to a file.
2. Do that on shutdown if running under systemd and restarting.
3. In `takeover_part1()`, get the file descriptors from systemd and load that file, instead of connecting to the old process.
4. `takeover_finish()` can probably skip everything except the final `resume_all()` call.

**Comment by sohooo** [comment]
Would also be interested in this! :+1:

**Comment by notEpsilon** [comment]
Interested

**Comment by JelteF** [comment]
I'm going to close this in favor of the approach here: https://github.com/pgbouncer/pgbouncer/pull/902

We've decided that (de-)serializing full PgBouncer in memory state is not maintainable and too likely to break things. The approach in #902 will result in mostly the same benefit without all the maintenance burden and likely bugs.
