### ISSUE TITLE
Getting error as unix:5432 closing because: unclean server (age=0s) while connecting to the server using pgbouncer

### ISSUE THREAD

**Issue by akamath46297** [pgbouncer/pgbouncer#595]
PgBouncer version 1.14.0

**pgbouncer.ini that works** 

```ini
[databases]
* = port = 5432 auth_user = testuser

[pgbouncer]
ignore_startup_parameters = ssl_renegotiation_limit
listen_addr = 0.0.0.0
listen_port = 6432
user = postgres
pool_mode = transaction
admin_users = testuser
stats_users = 
auth_type = hba
auth_hba_file = pgb_hba.conf
auth_file = userlist.txt
auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=\$1
max_client_conn = 5000
default_pool_size = 50
min_pool_size = 0
client_tls_sslmode = require 
client_tls_protocols = secure 
client_tls_ciphers = {******}
client_tls_key_file = key.pem 
client_tls_cert_file = cert.pem 
client_tls_ca_file = ca.pem 
```

Now when I change it to `client_tls_sslmode = disable` and restart the docker container which has pgbouncer my connections fail and I see below error in the pgbouncer logs

```
021-05-14 03:10:12.536 UTC [1] LOG S-0x55d540d854b0: postgres/testuser@unix:5432 new connection to server
2021-05-14 03:10:12.540 UTC [1] LOG C-0x55d540d223b0: postgres/postgres@[SomeIP]:39743 login attempt: db=postgres user=postgres tls=no
2021-05-14 03:10:12.540 UTC [1] LOG C-0x55d540d223b0: postgres/postgres@[SomeIP]:39743 closing because: login rejected (age=0s)
2021-05-14 03:10:12.540 UTC [1] LOG S-0x55d540d854b0: postgres/testuser@unix:5432 closing because: unclean server (age=0s)
2021-05-14 03:10:12.540 UTC [1] WARNING C-0x55d540d223b0: postgres/postgres@[SomeIP]:39743 pooler error: login rejected 
```

ini file after the changes 

```ini
[databases]
* = port = 5432 auth_user = testuser

[pgbouncer]
ignore_startup_parameters = ssl_renegotiation_limit
listen_addr = 0.0.0.0
listen_port = 6432
user = postgres
pool_mode = transaction
admin_users = testuser
stats_users = 
auth_type = hba
auth_hba_file = pgb_hba.conf
auth_file = userlist.txt
auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=\$1
max_client_conn = 5000
default_pool_size = 50
min_pool_size = 0
client_tls_sslmode = disable
client_tls_protocols = secure 
client_tls_ciphers = {******}
client_tls_key_file = key.pem 
client_tls_cert_file = cert.pem 
client_tls_ca_file = ca.pem 
```

From psql I get error as 

    psql: ERROR:  login rejected

If I pass `sslmode = require` I get below error

    psql: server does not support SSL, but SSL was required

Can you please help understand why connections are rejected ? Also when `client_tls_sslmode = disable` why the it says does not support SSL as the documentation says it will just be ignored just like postgres host vs hostssl:

    disable
    Plain TCP. If client requests TLS, it’s ignored. Default.

**Comment by akamath46297** [comment]
When I set the client_tls_sslmode = allow and restart the pgbouncer docker container I see that connection without sslmode=disable succeed but sslmode=disable throw the same error - 

2021-05-14 03:29:47.012 UTC [1] LOG S-0x560a97e33590: postgres/testuser@unix:5432 new connection to server
2021-05-14 03:29:47.018 UTC [1] LOG C-0x560a97dd1f10: postgres/postgres@[SomeIP]:6814 login attempt: db=postgres user=postgres tls=no
2021-05-14 03:29:47.018 UTC [1] LOG C-0x560a97dd1f10: postgres/postgres@[SomeIP]:6814 closing because: login rejected (age=0s)
2021-05-14 03:29:47.018 UTC [1] LOG S-0x560a97e33590: postgres/@unix:5432 closing because: unclean server (age=0s)
2021-05-14 03:29:47.018 UTC [1] WARNING C-0x560a97dd1f10: postgres/postgres@[SomeIP]:6814 pooler error: login rejected

**Comment by akamath46297** [comment]
@eulerto tagging you here..

**Comment by akamath46297** [comment]
Can anyone help with this issue?

**Comment by petere** [comment]
Was your PgBouncer built with TLS support?

**Comment by akamath46297** [comment]
@petere here is how we configure it 

ARG VERSION=1.14.0

 apk --update add autoconf autoconf-doc automake c-ares c-ares-dev curl gcc libc-dev libevent libevent-dev libtool make openssl-dev pkgconfig postgresql-client && \
  apk upgrade --available && \
  curl -o /tmp/pgbouncer-$VERSION.tar.gz -L https://pgbouncer.github.io/downloads/files/$VERSION/pgbouncer-$VERSION.tar.gz && \
  cd /tmp && \
  tar xvfz /tmp/pgbouncer-$VERSION.tar.gz && \
  cd pgbouncer-$VERSION && \
  ./configure --prefix=/usr && \
  make && \

**Comment by petere** [comment]
Check `pgbouncer --version` or the first few lines in the log after you start to check whether the binary was actually built with SSL support.
