### ISSUE TITLE
Connection pool is affected by server_idle_timeout setting

### ISSUE THREAD

**Issue by justabaka** [pgbouncer/pgbouncer#60]
Hello.

I'm currently testing pgbouncer in a transation pooling mode with a single postgresql slave host that is virtualized (KVM). 

INTRO: Our service's load cycle is the following: constant low request/load rate then a massive spike, rinse and repeat. For some reason the KVM DB host's performance degrades a lot during that load spike: when a few dozens of new clients connect to the database, the load average and sys CPU usage spikes, postgres spends like 80% of the CPU time in clone and wait4 syscalls (we know that it forks for every new connection). Pgbouncer looks like a solution to our problem: everything is fine if transaction/statement pooling is used. But there's a little bit of a problem.

ISSUE: For some reason pooled connections are affected by the server_idle_timeout setting and are closed for being idle and then instantly reopened to satisfy min_pool_size causing the same connection-related severe DB host performance degradation. I believe this behaviour is erroneous and unwanted, is there any chance it will be changed?

UPD: I've read the souce code and found out that server_idle_timeout can be set to 0 and the issue's gone, the supplied ini file lacks this information.
UPD2: But if there are any extra connections (>min_pool_size), they'll be open until they die due to server_liftetime, so this ticked is still valid.

**Comment by markokr** [comment]
Thanks for the report.  Please see if the above patch fixes your issue.

**Comment by justabaka** [comment]
Thanks for the patch, it looks good. I'll report once I'm able to test it.

**Comment by PJMODOS** [comment]
So was this actually fixed or not?

**Comment by markokr** [comment]
I was leaving open until 1.7 and/or reporter tests it, but it seems simpler to close, and let reporter re-open if there are problems.  Less noise in bugtracker.
