### ISSUE TITLE
[users] pool_mode=session in Azure

### ISSUE THREAD

**Issue by marloncristian** [pgbouncer/pgbouncer#607]
PostgreSQL Version 11.6
pgbouncer version 1.8.1

Hi Everyone; I am trying to set up a user-specific configuration in pbgouncer.ini but it seems to be not working. I read some threads about problems with pgBouncer and Postgres in Azure, but I don't know if this is the case.

This is my pgbouncer.ini:
```
[databases]
metabase = host=meu-acerto-prd.postgres.database.azure.com dbname=metabase user=metabase_admin@meu-acerto-prd password=****

[users]
metabase_admin = pool_mode=session

[pgbouncer]
logfile = /var/log/postgresql/pgbouncer.log
pidfile = /var/run/postgresql/pgbouncer.pid
listen_addr = *
listen_port = 5432
unix_socket_dir = /tmp
server_tls_sslmode = verify-ca
server_tls_ca_file = /etc/pgbouncer/root.crt
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
stats_users = stats
pool_mode = transaction
ignore_startup_parameters = extra_float_digits
```

My default pool_mode is *transaction* but this specific user requires transaction mode *session*. But when I check the pool mode using *SHOW POOLS* he is still using *transaction* instead of *session*.

```
pgbouncer=# show pools;
 database  |             user              | cl_active | cl_waiting | sv_active | sv_idle | sv_used | sv_tested | sv_login | maxwait | maxwait_us |  pool_mode
-----------+-------------------------------+-----------+------------+-----------+---------+---------+-----------+----------+---------+------------+-------------
 metabase  | metabase_admin@meu-acerto-prd |        15 |          0 |         0 |       4 |       0 |         0 |        0 |       0 |          0 | transaction
 pgbouncer | pgbouncer                     |         1 |          0 |         0 |       0 |       0 |         0 |        0 |       0 |          0 | statement
(2 rows)
```

My userlist.txt looks like this:
```
"admin" "*****"
"stats" "*****"
"metabase_admin" "md5****"
```

My main hypothesis is that Azure requires a hostname to authenticate and pgbouncer uses the database user and not the pgbouncer user to identify the user-specific settings and probably the missing @hostname causes a mismatch. As far as I know, I cant use a key with @ inside ini file so, I am running out of options.

**Comment by eulerto** [comment]
Azure probably has its own modified pgbouncer version. BTW, version 1.8.1 is really old.

Regarding the user name, [libusual restrict keys](https://github.com/libusual/libusual/blob/master/usual/cfparser.c#L127) to alphanumeric characters and underscore, point, minus, and asterisk.

You contact your vendor (Azure) and possibly open a support ticket.

**Comment by marloncristian** [comment]
Hi @eulerto, thanks for answering.

Yes, Azure has its own version of Bouncer but we have decided not to use it. We are running pgBouncer on a dedicated ubuntu VM.

**Comment by eulerto** [comment]
As I said you should patch libusual (to accept "@" as a valid user name character). I'm not sure if it will be sufficient but if you don't want to use the Azure pgbouncer service, you might give it a try, I strongly recommend that you use the latest pgbouncer version since you are running your own pgbouncer server.

**Comment by marloncristian** [comment]
We have decided to move forward in another direction and replicate dynamic rebuilt the userlist through automation.
