### ISSUE TITLE
Pgbouncer idle session timeout 

### ISSUE THREAD

**Issue by deepakbabu-vine** [pgbouncer/pgbouncer#609]
Hi 

Can someone help me with this?
Our DB is hosted in Amazon RDS with the Postgres v11

- I am having a problem that all my idle connections seem to close down after 15 mins. I have set for server_idle_timeout to (14400 secs), Even we tried TCPKeepAlive but it doesn't seem to work for us. 
- The application reconnects again and again which takes a few moments every time. We can observe in the PgAdmin as well

**Comment by hellower** [comment]
https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/config-idle-timeout.html

check  EDB timeout.

**Comment by deepakbabu-vine** [comment]
I checked it, it is set to 3600 seconds.

**Comment by petere** [comment]
Can you show what it says in the pgbouncer logs when this happens? I would figure out whether it's triggered on the TCP level, or whether pgbouncer does it itself.

**Comment by deepakbabu-vine** [comment]
We are not getting any logs when this happens. When we check the previous logs, we mostly get these logs repeatedly

- closing because: client unexpected eof (age=251s)
- closing because: server lifetime over (age=3604s)
- new connection to server (from <ip_address>)

We also noticed that when this timeout occurs, we get 503 errors in the developer's console in PgAdmin

**Comment by deepakbabu-vine** [comment]
We found the root cause for this issue, which is not related to pgBouncer, so closing this issue
