### ISSUE TITLE
how to show pgbouncer stats in an app?

### ISSUE THREAD

**Issue by chrnoe** [pgbouncer/pgbouncer#610]
I want to see the pgbouncer stats in a .net application, but I can't connect to the virtual pgbouncer database. Connections to the postgresql behind work properly.
How can I show these information in an .net client? I tried [Npgsql](https://stackoverflow.com/questions/67266493/how-to-get-pgbouncer-stats-with-c-sharp/67274513#67274513) and the [devart](https://forums.devart.com/viewtopic.php?f=3&t=45317) provider, but it didn't work, and both said, it's not possible to get an connection to pgbouncer itself with these providers. 

Can't believe, that it's possible to get the pgbouncer stats only in a console. I suppose, there must be another way. What can I do?

**Comment by petere** [comment]
It should work to connect to the `pgbouncer` database from any client application.

**Comment by petere** [comment]
I don't think there is a list, but I'd expect most except the two you listed should work. As you have discovered, they need to use the simple query protocol, and no run any SQL commands behind your back.

**Comment by chrnoe** [comment]
I hoped to get some information, how to reach this connect exactly. What providers do work. I think, Devart and especially Npgsql are the very most common tools in this area. And I thought, the connect from .NET to pgbouncer is a widely used scenario. Thought, this problem is well-known and solved. But probably not.
There are really no recommandations for this task and the provider?

**Comment by petere** [comment]
PgBouncer provides a network protocol. Which third-party products support that protocol is not something we can keep track of. If you want some third-party product to improve their support, you should talk to them.
