### ISSUE TITLE
auth_query not working

### ISSUE THREAD

**Issue by kolbasky** [pgbouncer/pgbouncer#613]
Hello, we have PG 11 and pgbouncer 1.11.0.
The config looks like:
```
[databases]
* = host=/var/run/postgresql/ auth_user=pgbouncer
db1 = host=/var/run/postgresql/ dbname=db1 pool_mode=session auth_user=pgbouncer
db2 = host=/var/run/postgresql/ dbname=db2 pool_mode=session auth_user=pgbouncer

[pgbouncer]
pidfile=/var/run/pgbouncer/pgbouncer.pid
logfile=/var/log/pgbouncer/pgbouncer.log
listen_port = 6543
listen_addr = *
auth_type = hba
auth_hba_file = /etc/pgbouncer/pg_hba.conf
auth_file = /etc/pgbouncer/userlist.txt
admin_users = pgbouncer
max_client_conn = 10000
default_pool_size = 20
min_pool_size = 1
reserve_pool_size = 5
reserve_pool_timeout = 3
pool_mode = transaction
ignore_startup_parameters = extra_float_digits
pkt_buf = 8192
auth_user = pgbouncer
auth_query = select p_user, p_password FROM public.lookup($1)

[users]
someuser1 = max_user_connections=10
someuser2 = max_user_connections=30

```

My hba file looks like:
```
host all zabbix 127.0.0.1/32 trust
local all zabbix trust
local all all md5
host all all 0.0.0.0/0 md5
host all all ::0/0 md5
```

When i create a new user in postgres - the auth_query works fine. I don't have to add any new lines to userlist.txt
But as soon as i add this user to [users] section the auth_query stops working (for this user) and i get error "password authentication failed" when trying to log into PG through pgbouncer. I tried specifying auth_user for this user (like i do in databases section), but it doesn't work.
So i have to either add user's password to userlist.txt, but it is inconvenient as i have three pg nodes so have to write three times. And it always causes troubles when the password gets changed. Or i have to remove this user from [users] section. But i need to limit connections for some users and increase for others.

Is there any way to enable auth_query for users, specified in [users] section?

**Comment by eulerto** [comment]
It is a known bug. See #484.

**Comment by kolbasky** [comment]
> It is a known bug. See #484.

Submitted more than a year ago... Any chance it will be fixed in near future?

**Comment by eulerto** [comment]
It is on my list to fix it.

**Comment by eulerto** [comment]
#1052 fixed it.
