### ISSUE TITLE
Features page doesn't list session-level advisory locks as incompatible with "transaction" pooling

### ISSUE THREAD

**Issue by danmaz74** [pgbouncer/pgbouncer#617]
While working on a project I discovered that a Ruby gem we wanted to use is incompatible with PgBouncer in "transaction" pooling mode, because that mode doesn't work with session-based advisory locks. I also noticed that this incompatibility isn't listed in the "features" page https://www.pgbouncer.org/features.html

I think it would be very useful to add a new row in the table about advisory locks.

**Comment by eulerto** [comment]
Good point. It seems that table was written before the advisory lock support (8.2). :-/
