### ISSUE TITLE
windows binary release start failed 

### ISSUE THREAD

**Issue by luxixing** [pgbouncer/pgbouncer#618]
OS: Window Server 2016
CPU: 64

Error Message:
![image](https://user-images.githubusercontent.com/1990233/122864193-c030bd80-d356-11eb-8336-cdabbdba747d.png)

extra dll:
![image](https://user-images.githubusercontent.com/1990233/122864354-0f76ee00-d357-11eb-800b-a8060eb9fb1d.png)

libevent-2.1.7 download reference:https://github.com/pgbouncer/pgbouncer/issues/581#issuecomment-859909218

pgbouncer windows package: https://github.com/pgbouncer/pgbouncer/releases/download/pgbouncer_1_15_0/pgbouncer-1.15.0-windows-x86_64.zip

how can i start windows binary release ?

**Comment by luxixing** [comment]
> OS: Window Server 2016
> CPU: 64
> 
> Error Message:
> ![image](https://user-images.githubusercontent.com/1990233/122864193-c030bd80-d356-11eb-8336-cdabbdba747d.png)
> 
> extra dll:
> ![image](https://user-images.githubusercontent.com/1990233/122864354-0f76ee00-d357-11eb-800b-a8060eb9fb1d.png)
> 
> libevent-2.1.7 download reference:[#581 (comment)](https://github.com/pgbouncer/pgbouncer/issues/581#issuecomment-859909218)
> 
> pgbouncer windows package: https://github.com/pgbouncer/pgbouncer/releases/download/pgbouncer_1_15_0/pgbouncer-1.15.0-windows-x86_64.zip
> 
> how can i start windows binary release ?

resolved 

1. download and install msys2-x86_64-20210604.exe （https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20210604.exe）
2.  open mingw64.exe，install openssl(libssl和libcrypto)
```
pacman -S mingw-w64-x86_64-openssl
```
3. mingw64.exe, install libevent
```
pacman -S mingw-w64-x86_64-libevent
```

**Comment by eulerto** [comment]
PR #621 should fix this issue.
