### ISSUE TITLE
Google Cloud SQL - pg_shadow permission issue

### ISSUE THREAD

**Issue by msenmurugan** [pgbouncer/pgbouncer#625]
We have deployed PgBouncer in the k8s cluster which will talk to the Google Cloud SQL Postgres server.

We are using Vault dynamic Postgres credentials for each of our services. So, during each Pod startup, the new user will be created to an existing role and this new user will talk with PgBouncer to create/get a Postgres connection.

Tried to create the below function and used it as auth_query but we are getting `ERROR:  permission denied for relation pg_shadow
CONTEXT:  SQL function "lookup" statement 1`

```
CREATE OR REPLACE FUNCTION pgbouncer.user_lookup(in i_username text, out uname text, out phash text)
RETURNS record AS $$
BEGIN
    SELECT usename, passwd FROM pg_catalog.pg_shadow
    WHERE usename = i_username INTO uname, phash;
    RETURN;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
REVOKE ALL ON FUNCTION pgbouncer.user_lookup(text) FROM public, pgbouncer;
GRANT EXECUTE ON FUNCTION pgbouncer.user_lookup(text) TO pgbouncer;
```

As part of Google Cloud SQL, there is no superuser. How can we authenticate these dynamic users without updating the users_list? what should be the auth_query for this scenario?

**Comment by petere** [comment]
I don't know how Google Cloud SQL works, but in general it seems you'll need to find some other way to get the passwords.

**Comment by msenmurugan** [comment]
Thanks @petere for the answer. 

I have the following setup

* Google Cloud SQL can be accessed via cloud sql proxy in the Kubernetes cluster. Cloud SQL proxy container is exposed internally via Kubernetes service `postgresql`
* PgBouncer will proxy the application request to `postgresql` Kubernetes service which will internally proxy the request to Google Cloud SQL
* PgBouncer is installed with the following configuration.

`cat pgbouncer.ini`
```
;; database name = 1
[databases]
* = host=postgresql port=5432   dbname=postgres


[pgbouncer]

;;; Administrative settings
;logfile = /var/log/pgbouncer/pgbouncer.log
;pidfile = /var/run/pgbouncer/pgbouncer.pid

;;; Where to wait for clients
listen_addr = 0.0.0.0
listen_port = 5432
unix_socket_dir = var/run/postgresql
;unix_socket_mode = 0777
;unix_socket_group =
;client_tls_sslmode = disable
;client_tls_ca_file = <system default>
;client_tls_key_file =
;client_tls_cert_file =
;client_tls_ciphers = fast
;client_tls_protocols = all
;client_tls_dheparams = auto
;client_tls_ecdhcurve = auto
;server_tls_sslmode = disable
;server_tls_ca_file = <system default>
;server_tls_key_file =
;server_tls_cert_file =
;server_tls_protocols = all
;server_tls_ciphers = fast
; any, trust, plain, crypt, md5, cert, hba, pam

;;; Authentication settings

auth_type = hba
;auth_file = /8.0/main/global/pg_auth
;auth_file = /etc/pgbouncer/userlist.txt
auth_hba_file = /etc/pgbouncer/pghba.conf

;;; Users allowed into database 'pgbouncer'
admin_users = pgbouncer
stats_users = pgbouncer, stats, root, monitor

;;; Pooler personality

pool_mode = transaction
server_reset_query = DISCARD ALL
;server_reset_query_always = 0
;ignore_startup_parameters = extra_float_digits
;server_check_query = select 1
;server_check_delay = 30
;application_name_add_host = 0

;;; Connection limits

max_client_conn = 100
default_pool_size = 10
min_pool_size = 10
reserve_pool_size = 10
reserve_pool_timeout = 5
;max_db_connections = 0
;max_user_connections = 0
;server_round_robin = 0
;syslog = 0
;syslog_facility = daemon
;syslog_ident = pgbouncer

;;; Logging

log_connections = 1
log_disconnections = 0
log_pooler_errors = 1
log_stats = 1
stats_period = 60
verbose = 0

;;; Timeouts

;server_lifetime = 3600
;server_idle_timeout = 600
;server_connect_timeout = 15
;server_login_retry = 15
;query_timeout = 0
;query_wait_timeout = 120
;client_idle_timeout = { .Values.clientIdleTimeout}
;client_login_timeout = 60
;autodb_idle_timeout = 3600
;suspend_timeout = 10
;idle_transaction_timeout = 0

;;; Low-level tuning options

;pkt_buf = 4096
;listen_backlog = 128
;sbuf_loopcnt = 5
;max_packet_size = 2147483647

;tcp_defer_accept = 0
;tcp_socket_buffer = 0
tcp_keepalive = 1
tcp_keepcnt = 5
tcp_keepidle = 30
tcp_keepintvl = 30

;dns_max_ttl = 15
;dns_zone_check_period = 0
;dns_nxdomain_ttl = 15

;disable_pqexec = 0
;conffile
;service_name = pgbouncer
;job_name = pgbouncer
;%include /etc/pgbouncer/pgbouncer-other.ini
```

`cat userlist.txt`
```
"pgbouncer" "md5XXXXXXXX"
```

`cat pghba.conf`
```
host all all 0.0.0.0/0 trust
```

After setting up the configuration, my understanding is that PgBouncer should allow any user (users not in the userlist.txt) to connect to `postgresql`.

But it's throwing with an error
```
PGPASSWORD=XXXXXXXX psql -h 127.0.0.1 -U pericles -p 5432 postgres
psql: ERROR:  No such user: pericles
```

I have tried auth_type=trust as well and it is the same behavior. Even for auth_type=`hba` or `trust`, should the user credentials be part of userlist.txt? 

Whether there is a way to pass through a request to Postgres to do the authentication instead of doing authentication at the PgBouncer level?

**Comment by petere** [comment]
These questions are a bit beyond PgBouncer development. How you orchestrate the deployment and run time is up to everyone using it.
