### ISSUE TITLE
unable to run pgbouncer on port 5432 and connect to postgresql using unix socket

### ISSUE THREAD

**Issue by PeterFokkinga** [pgbouncer/pgbouncer#627]
Basically, what I want is a "transparent" PgBouncer running on my PostgreSQL server. Transparent meaning that clients can connect to the standard PostgreSQL 5432 port and getting their connections pooled.

However, it appears that PgBouncer 

in postgresql.conf
`port = 7777`

results in a socket `/var/run/postgresql/.s.PGSQL.7777` (this is on Ubuntu 20.04 btw)

PgBouncer however expects to find  `/var/run/postgresql/.s.PGSQL.5432`

I did try an override in pgbouncer.ini
```
[databases]
* = host=/var/run/postgresql port=7777 
```

But this doesn't make a difference.

**Comment by eulerto** [comment]
What is the exact error message in the log file? You are probably running PgBouncer using an OS user that doesn't have permission to access `/var/run/postgresql`.

**Comment by PeterFokkinga** [comment]
PgBouncer is installed from `https://apt.postgresql.org/pub/repos/apt/ focal-pgdg` (ubuntu / debian package) and runs as user postgres, same as the postgresql server.

The log for startup of PgBouncer:
```
DEBUG parse_ini_file: 'verbose' = '2' ok:1
DEBUG loading auth_file: "/etc/pgbouncer/userlist.txt"
DEBUG pktbuf_dynamic(128): 0x55a77c5056a0
DEBUG make_room(0x55a77c5056a0, 9): realloc newlen=256
DEBUG pktbuf_dynamic(128): 0x55a77c505390
NOISE connect(4, unix:/var/run/postgresql/.s.PGSQL.5432) = No such file or directory
NOISE event: 128, SBuf: 192, PgSocket: 560, IOBuf: 4108
LOG kernel file descriptor limit: 1024 (hard: 524288); max_client_conn: 50, max expected fd use: 62
DEBUG adns_create_context: c-ares 1.15.0
DEBUG add_listen: 0.0.0.0:5432
NOISE old TCP_DEFER_ACCEPT on 7 = 0
NOISE install TCP_DEFER_ACCEPT on 7
LOG listening on 0.0.0.0:5432
DEBUG add_listen: [::]:5432
NOISE old TCP_DEFER_ACCEPT on 8 = 0
NOISE install TCP_DEFER_ACCEPT on 8
LOG listening on [::]:5432
DEBUG add_listen: unix:/var/run/postgresql/.s.PGSQL.5432
LOG listening on unix:/var/run/postgresql/.s.PGSQL.5432
LOG process up: PgBouncer 1.15.0, libevent 2.1.11-stable (epoll), adns: c-ares 1.15.0, tls: OpenSSL 1.1.1f  31 Mar 2020
```

```
# ls -al /var/run/postgresql
otal 12
drwxrwsr-x  3 postgres postgres  160 Jul 12 11:44 .
drwxr-xr-x 34 root     root     1120 Jul 12 11:38 ..
drwxr-s---  2 postgres postgres  140 Jul 12 11:44 13-main.pg_stat_tmp
-rw-r--r--  1 postgres postgres    6 Jul 12 11:41 13-main.pid
-rw-r--r--  1 postgres postgres    6 Jul 12 11:44 pgbouncer.pid
srwxrwxrwx  1 postgres postgres    0 Jul 12 11:44 .s.PGSQL.5432
srwxrwxrwx  1 postgres postgres    0 Jul 12 11:41 .s.PGSQL.7777
-rw-------  1 postgres postgres   70 Jul 12 11:41 .s.PGSQL.7777.lock
```

As you can see from the log and resulting file in /var/run/postgresql, PgBouncer creates a socket `.s.PGSQL.5432` where it listens for incoming connections. But instead of using the PostgreSQL `s.PGSQL.7777`  socket file it searches for `.s.PGSQL.5432` and fails.

**Comment by eulerto** [comment]
Are you referring to the following message?

> NOISE connect(4, unix:/var/run/postgresql/.s.PGSQL.5432) = No such file or directory

This message is harmless and is called by `check_old_process_unix()`.

It is not clear if you can connect to PgBouncer. There is no connection error from PgBouncer to Postgres.

**Comment by PeterFokkinga** [comment]
Thanks, that message together with "launch_new_connection: already progress" and "safe_recv(10, 4015) = Resource temporarily unavailable" got my thinking into the wrong direction.

Cause of my connection problems was that I had `auth_type = hba` together with `auth_query = SELECT p_user, p_password FROM public.lookup($1)` and either that combination does not work or the pg_hba.conf needs more adapting. With `auth_type = md5` I can now connect.
