### ISSUE TITLE
Cannot change user. Failed to assume identity of user "my_user": Operation not permitted.

### ISSUE THREAD

**Issue by DenisRazinkin** [pgbouncer/pgbouncer#636]
I try to use directive "user"

https://www.pgbouncer.org/config.html#user
```
user
If set, specifies the Unix user to change to after startup. Works only if PgBouncer is started as root or if it’s already running as given user. Not supported on Windows.

Default: not set
```
2021-08-03 21:01:38.011 25350 FATAL @src/system.c:58 in function
change_user(): failed to assume identity of user 'my_user': Operation
not permitted [1]

But when trying to run from root got:  "PgBouncer should not run as root".

In my case, I would like to use transparent peer authentication: postgresql is configured to use peer auth and I want to configure pgbouncer which uses connection pool with original client process user.
**User** directive from databases section does not help: pgbouncer provides user name differs from authenticated user name (user of running pgbouncer instance). So I got peer auth error: 
"provided user name (my_user) and authenticated user name (postgres) do not match"

**Comment by eulerto** [comment]
It works for me. The `user` parameter should be in the `[pgbouncer]` section. If you are starting the service as `root`, PgBouncer process will be owned by the `user` value. As described, if you are starting PgBouncer with a non-root user, `user` value should match your current OS user.

If you are using `auth_type = hba`, you can use peer authentication method. However, all Unix-domain socket connections should be done by the same user, e.g. you should force an specific user in your connection string. If not, you are not allowed to connect with users that don't match the OS user that owns PgBouncer process.

You are probably confusing a connection string parameter `user` in `[databases]` section with parameter `user` in `[pgbouncer]` section.

**Comment by DenisRazinkin** [comment]
@eulerto thx for answer
There is only one way in my case is to configure several pgbouncer instances, isn't it?
I have several system processes and users, each user have grants to some functions and tables.
For example:
**instance 1:**
```
[databases]
my_db = host=/tmp port=5432 dbname=my_db
[pgbouncer]
listen_port = 6432
user = user1
auth_type = hba
...
```
**instance 2:**
```
[databases]
my_db = host=/tmp port=5432 dbname=my_db
[pgbouncer]
listen_port = 6433
user = user2
auth_type = hba
...

```
I think it is not good idea to proxy all connections throught pgbouncer from postgres superuser  grants

**Comment by eulerto** [comment]
I didn't understand what you want to achieve using `user` parameter (section `[pgbouncer]`). It is only useful for starting the service as root and switching to a non-privileged user.

**Comment by DenisRazinkin** [comment]
I want to proxy connections from pgbouncer to postgresql database with the same user privileges of client process because the database uses peer authentication.
I tried to create several database aliases for different users in pgbouncer config:
user1_db_conn = host=/tmp port=5432 dbname=my_db user=user1
user2_db_conn = host=/tmp port=5432 dbname=my_db user=user2

but got error of auth on proxied connection on the postgresql side:
> provided user name (user1) and authenticated user name (postgres) do not match

So, `user` parameter (in section [`pgbouncer`]) must be the same as user in connection string and i must to configure several pgbouncer instances to implement transparent peer authentication for each system user..

**Comment by petere** [comment]
What you are attempting to do doesn't work. A single pgbouncer instance can't run as multiple different users. If you need that, then you need to run multiple instances, as you have mentioned.
