### ISSUE TITLE
Is "GRANT CONNECT" required for auth_user + auth_query?

### ISSUE THREAD

**Issue by jflambert** [pgbouncer/pgbouncer#637]
I've been scraping information from various blogs and I think I finally have something that works for my needs: use `auth_user` and `auth_query` so that `auth_file` only has a single entry and won't require any maintenance.

But I'm a little shaky on a "GRANT CONNECT" that I seemingly have to do on `auth_user`.

First my pgbouncer.ini

```
[databases]
* = host=timescaledb port=5432 auth_user=pgbouncer

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 5432
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
auth_query = SELECT username, password FROM pgbouncer.get_auth($1)
admin_users = postgres, pgbouncer
stats_users = postgres, pgbouncer
pool_mode = transaction
server_reset_query = DISCARD ALL
ignore_startup_parameters = extra_float_digits
```

`userlist.txt` is just `pgbouncer` with the password `pgbouncer`
```
"pgbouncer" "md5be5544d3807b54dd0637f2439ecb03b9"
```

And finally, here is some SQL that will automatically run as "postgres" whenever a new database is created.
```
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'pgbouncer') THEN
    CREATE ROLE pgbouncer;
  END IF;
END; $$;

ALTER ROLE pgbouncer LOGIN PASSWORD 'pgbouncer';

CREATE SCHEMA IF NOT EXISTS pgbouncer AUTHORIZATION pgbouncer;

CREATE OR REPLACE FUNCTION pgbouncer.get_auth(p_usename TEXT)
RETURNS TABLE(username TEXT, password TEXT) AS
$$
BEGIN
  RAISE WARNING 'PgBouncer auth request: %', p_usename;

  RETURN QUERY
  SELECT usename::TEXT, passwd::TEXT FROM pg_catalog.pg_shadow
  WHERE usename = p_usename;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

REVOKE ALL ON FUNCTION pgbouncer.get_auth(p_usename TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION pgbouncer.get_auth(p_usename TEXT) TO pgbouncer;

DO $$ BEGIN
  EXECUTE FORMAT('GRANT CONNECT ON DATABASE %s TO pgbouncer;', current_database());
END; $$;
```

I have scoured the following articles and none of them mention how crucial it is to `GRANT CONNECT` to `pgbouncer` for each new database. Is that normal? I'm using pgbouncer 1.15.0 and postgresql 13.

-- https://www.2ndquadrant.com/en/blog/understanding-user-management-in-pgbouncer/
-- https://www.2ndquadrant.com/en/blog/pg-phriday-securing-pgbouncer/
-- http://www.pgbouncer.org/config.html
-- https://www.enterprisedb.com/postgres-tutorials/pgbouncer-authquery-and-authuser-pro-tips
-- https://github.com/edoburu/docker-pgbouncer
-- https://www.cybertec-postgresql.com/en/pgbouncer-authentication-made-easy/

**Comment by petere** [comment]
Yes, the `auth_user` needs `CONNECT` privilege on each database because, well, it needs to connect to it. That is just the standard way PostgreSQL works, nothing particular to PgBouncer. However, `CONNECT` privilege is usually granted by default, so if you don't have it, maybe you have some nonstandard setup somewhere.

**Comment by jflambert** [comment]
Thank you Peter. Not sure why CONNECT wasn't granted by default, I used the exact instructions I pasted, on postgresql 13.2!
