### ISSUE TITLE
default_pool_size per database not working in 1.16.0

### ISSUE THREAD

**Issue by mr-deamon** [pgbouncer/pgbouncer#638]
Hi there
in my config i have specified default_pool_size per database because i am serving from different backends. This does not seem to work anymore in 1.16.0:

`unrecognized connection parameter: default_pool_size`
affected config-line
`ksldwh = host=127.0.0.1 port=15001 auth_user=pgbouncer default_pool_size=50`

if i remove the last part, pgbouncer starts as expected. this config has been in use a while in version 1.15.0

**Comment by Melkij** [comment]
Hello
default_pool_size was never allowed here. But before [the fix](https://github.com/pgbouncer/pgbouncer/commit/a926a97526a4a9bf353c465a888edbe4b77288f2), the error was simply written to the log.

You need
```
ksldwh = host=127.0.0.1 port=15001 auth_user=pgbouncer pool_size=50
```
`pool_size` is the correct [parameter name](https://www.pgbouncer.org/config.html#section-databases) to configure individual pool.
