### ISSUE TITLE
Cannot login with auth_type=hba

### ISSUE THREAD

**Issue by xpj** [pgbouncer/pgbouncer#64]
Hi all,

  we just found issue with using `auth_type=hba` for tuning access rights on pgbouncer. 

We created `pg_hba.conf`, added it to `pgbouncer.ini` and started pgbouncer. But we were not able to connect to underlaying PostgreSQL server.

During investigation of this issue we found following code (`client.c` method `finish_set_pool` line `221`)
```
	auth = cf_auth_type;
	if (auth == AUTH_HBA) {
		auth = hba_eval(parsed_hba, &client->remote_addr, !!client->sbuf.tls,
				client->db->name, client->auth_user->name);
	}

	switch (auth) {
	case AUTH_ANY:
	case AUTH_TRUST:
		ok = finish_client_login(client);
		break;
	case AUTH_PLAIN:
	case AUTH_MD5:
		ok = send_client_authreq(client);
		break;
	case AUTH_CERT:
		ok = login_via_cert(client);
		break;
	case AUTH_PEER:
		ok = login_as_unix_peer(client);
		break;
	default:
		disconnect_client(client, true, "login rejected");
		ok = false;
	}
	return ok;
```

Gotcha in this is following:

In code, `auth` is assigned with correct auth_type from `pg_hba.conf` (md5) and also correctly switch-ed in `switch`, so the `send_client_authreq()` method is called.

But in the `send_client_authreq()` (`client.c` line `70`) our new `auth` type from `pg_hba.conf` is not used and instead global `cf_auth_type` is used. And it is set to `hba`.

```
static bool send_client_authreq(PgSocket *client)
{
	uint8_t saltlen = 0;
	int res;
	int auth = cf_auth_type;

	if (cf_auth_type == AUTH_MD5) {
		saltlen = 4;
		get_random_bytes((void*)client->tmp_login_salt, saltlen);
	} else if (cf_auth_type == AUTH_PLAIN) {
		/* nothing to do */
	} else {
		return false;
	}

	SEND_generic(res, client, 'R', "ib", auth, client->tmp_login_salt, saltlen);
	if (!res)
		disconnect_client(client, false, "failed to send auth req");
	return res;
}
```
Can you please incorporate fix to next version? 
Thank you,
Pavel

**Comment by markokr** [comment]
Thanks, should be fixed now.  Please test if it works for you.

**Comment by xpj** [comment]
Thanks for fast fixing. 

Works good.

Thanks you,
Pavel

**Comment by markokr** [comment]
Thanks for the report.
