### ISSUE TITLE
java postgresql jdbc connection.createArrayOf is very slow

### ISSUE THREAD

**Issue by linimihu** [pgbouncer/pgbouncer#640]
We use this https://jdbc.postgresql.org/documentation/head/arrays.html in own java code. It is very slow throught pgbouncer.
For example if we connect from jdbc to postgres server directly then the create an array with 300 element is some milliseconds but if we connect jdbc throught pgbouncer it runs 5 minutes.
You can try this sql, the where section contains an array:
```
create table text_table ( x_text text );
insert into text_table values ('AB'), ('LA');
select * from text_table where x_text = any ( array['AB', 'AC', 'AD', 'AX', 'DS', 'SAS'] );
```
The java code is the following, not MWE but I hope it helps:
```
Class.forName("org.postgresql.Driver");
String sql = "select * from text_table where x_text = any ( ? )";
java.sql.Connection conn = DriverManager.getConnection(dbServer, dbLogin, dbPassword);
conn.setAutoCommit(false);
PreparedStatement stmt = conn.prepareStatement(sql);
// the duration of the following 2 line is 5 minutes throught pgbouncer
stmt.setArray(1, connection.createArrayOf("text", new String[]{"AB", "AC", "AD", "AX", "DS", "SAS"}));
ResultSet rset = stmt.executeQuery();
conn.setAutoCommit(true);
rset.close();
stmt.close();
conn.close()
```
The more elements in the array, the longer this method runs.
```
pgbouncer=# show version;
     version      
------------------
 PgBouncer 1.16.0
```
Debian 10, Postgresql 13.3, jdbc postgresql-42.2.5.jar, oracle java 8
PgBouncer is in session pool mode.

**Comment by petere** [comment]
PgBouncer has no awareness of arrays or anything on this level. Are all queries slow, or just specific ones?

**Comment by linimihu** [comment]
Only those queries are slow that use the createArrayOf function. We have a system that we developing for own company for 15 years, and we changed the connection pool from native java to pgbouncer in this week. There are more hundreds function but only few are slow. We can switch the 2 connection pool so we tested it.

**Comment by linimihu** [comment]
Hello, I ran some debug in our java code and there is not problem with createArrayOf method call. So sorry for my misunderstanding. I've close this issue.
