### ISSUE TITLE
Help needed to improve connection pooling 

### ISSUE THREAD

**Issue by rjoroy89** [pgbouncer/pgbouncer#641]
Hi ,

I have recently started using pgBouncer 1.15.0 in my environment (PostgreSQL 12.5 on Ubuntu 18.04) and I am frequently running into "FATAL:  sorry, too many clients already". I can confirm that we have never faced this issue before. Yet to take it to production environment so wanted to identify and fix the problem or parameters hence requesting your help on the same.

Below is my current setting 
```ini
[databases]
* = port = 5432
[pgbouncer]
logfile = /var/log/postgres/pgbouncer.log
pidfile = /etc/pgbouncer/pgbouncer.pid
listen_addr = *
listen_port = 6432
unix_socket_dir = /data/sockets/
auth_type = hba
auth_file = /etc/pgbouncer/userlist.txt
auth_hba_file = /data/pgdata/12/pg_hba.conf
auth_user = pgbouncer
auth_query = SELECT * FROM pgbouncer.get_auth($1)
admin_users = pgbouncer
stats_users = pgbouncer
pool_mode = session
max_client_conn = 800
default_pool_size = 295
reserve_pool_size = 5
ignore_startup_parameters = extra_float_digits
server_lifetime = 600
```

I have 3 databases and 3 active users for each of these databases. max_connection parameter set in postgresql.conf is 400. Before using pgbouncer, at peak hours the max connections at any point of time was approximately 300(both active and non-active) now it is easily hitting  the upper limit and throwing the error. 

Thanks

**Comment by rjoroy89** [comment]
Out of the current 390+ clients connected, only 10 are active at any point in time as per pg_stat_activity results. So, I am suspecting the connections closure is not handled at the application level probably but cannot weigh in much on that thought as the issue was not seen before using pgbouncer. As I said, the max no of connections both active and idle never touched 300 even in production env.

Is it ok to enforce client_idle_timeout in my case to handle this at the pgbouncer layer itself? 

And even if I enforce it to lets say 600s, will pgbouncer close the connections by actually confirming the idle status of connections in pg_stat_activity/postgres? Why I ask because even though I can see 390+ connections/clients are listed as idle in pg_stat_activity, they are all listed as active when I connect to pgbouncer and execute show clients or show servers;

Please help me in solving this problem.

Thanks!

**Comment by rjoroy89** [comment]
I just updated my pgbouncer.ini like below - 
`[databases]
1stdb = port = 5432 pool_size = 220
2nddb = port = 5432 pool_size = 90
3rddb = port = 5432 pool_size = 70
[pgbouncer]
logfile = /var/log/postgres/pgbouncer.log
pidfile = /etc/pgbouncer/pgbouncer.pid
listen_addr = *
listen_port = 6432
unix_socket_dir = /data/sockets/
auth_type = hba
auth_file = /etc/pgbouncer/userlist.txt
auth_hba_file = /data/pgdata/12/pg_hba.conf
auth_user = pgbouncer
auth_query = SELECT * FROM pgbouncer.get_auth($1)
admin_users = pgbouncer
stats_users = pgbouncer
pool_mode = session
max_client_conn = 500
reserve_pool_size = 5
ignore_startup_parameters = extra_float_digits
server_lifetime = 200
server_idle_timeout = 120
client_idle_timeout = 200`

Hoping to see a better control in idle connections..

**Comment by Melkij** [comment]
> Out of the current 390+ clients connected, only 10 are active at any point in time as per pg_stat_activity results.

You use pool_mode = session. Real server connection to DB is provided for each client and can not be reused until this client disconnects. So there is absolutely no difference is client active or not. In session pool mode we can not give that server connection to another client without session state change hazards.

Usually pgbouncer is used with pool_mode = transaction. This mode will significantly reduce the number of your connections from pgbouncer to the database (from several hundred to a couple of dozen, I think), but imposes restrictions: you will not be able to reliably use features that require saving the session context. Each transaction in this pool mode can be transferred to some other base connection.

**Comment by rjoroy89** [comment]
Thanks for your valuable time and responding to my request!

Yeah thats the reason I avoided using transaction pooling mode and looks like I should employ a scheduled job to terminate idle clients to solve my problem here.

**Comment by eulerto** [comment]
If you are using `pool_mode = session`, your application should close the connection when it executes what was requested. Keep in mind that open a PgBouncer connection is much cheaper than a Postgres connection so your application must be designed to (i) open a connection, (ii) execute the transaction(s) and (iii) close the connection. Hence, PgBouncer will be capable to reduce the number of connections to Postgres significantly when there is no demand for it.

**Comment by rjoroy89** [comment]
Thanks @eulerto for your valuable time in responding to my query. I have informed application team to review the code responsible for opening and closing its connections. For now as a temporary fix to the problem, I have inserted a cronjob to kill all "idle" connections older than 5 mins from the cluster.

Thanks!
