### ISSUE TITLE
max_client_conn and default_pool_size

### ISSUE THREAD

**Issue by xiangma0510** [pgbouncer/pgbouncer#643]
I have done a lot of tests, but I still haven't distinguished how the following parameters are calculated. There is always a difference from what I imagined. The introduction in the official document seems to be too simple

- default_pool_size  
   this can limit connection pool size,but when the following two values ​​are specified, it is found that default_pool_size will overflow
- reserve_pool_size
- reserve_pool_timeout

- max_client_conn
  When this parameter is set to 0, the default maximum value is 1600, when it is set to 5000, the maximum is 3200, why?

- max_db_connections
- max_user_connections

Hope you can help me explain clearly, I was confused
thank you very much!

**Comment by xiangma0510** [comment]
`show lists` command output is not the same with the settings

**Comment by eulerto** [comment]
The connection pooling principle is there might be connections open between PgBouncer and Postgers. It means connections are reused by multiple client connections (connection between a client application and PgBouncer).

Having said that `default_pool_size` is the maximum number of connections allowed per user/database pair. The documentation is clear.

If you set `reserve_pool_size` (default is 0), the maximum number of connections to the pool might be increased by its number if a client is waiting for `reserve_pool_timeout` seconds.

`max_client_conn` is explained in the [documentation](http://www.pgbouncer.org/config.html). The [default is 100](https://github.com/pgbouncer/pgbouncer/blob/master/src/main.c#L256). PgBouncer does not limit `max_client_conn`.

`max_db_connections` is a hard limit per database. Let's say you have 8 roles and your default_pool_size is 5 and max_db_connections is 12. If role A uses its 5 connections and role B uses its 5 connections, there is only 2 connections available for the other 6 roles. The documentation is clear IMO.

`max_user_connections` is a hard limit per user. Let's say you have 9 databases and your default_pool_size is 5 and max_user_connections is 12. If role A uses its 5 connections to database X and users its 5 connections to database Y, there is only 2 connections available for this role. Again the documentation is clear.

```
$ psql -p 6432 pgbouncer
psql (13.4, server 1.15.0/bouncer)
Type "help" for help.

pgbouncer=# show version;
     version      
------------------
 PgBouncer 1.15.0
(1 row)

pgbouncer=# show lists;
     list      | items 
---------------+-------
 databases     |     3
 users         |     4
 pools         |     1
 free_clients  |    49
 used_clients  |     1
 login_clients |     0
 free_servers  |     0
 used_servers  |     0
 dns_names     |     0
 dns_zones     |     0
 dns_queries   |     0
 dns_pending   |     0
(12 rows)
```

Are you using a modified PgBouncer version (probably in a cloud provider)?

**Comment by xiangma0510** [comment]
I have a test:
```json
default_pool_size = 50
reserve_pool_size = 10
reserve_pool_timeout = 5
max_client_conn = 100
max_db_connections = 0
max_user_connections = 0

postgres@pg-test-1:5432/postgres=# show max_connections ;
 max_connections
-----------------
 200
```

```shell
pgbench -h 10.37.129.41 -p 5433 -U u1 -d db1 -C -c 60 -T 1000
pgbench -h 10.37.129.41 -p 5433 -U u2 -d db2 -C -c 60 -T 1000
```

```shell
postgres@pg-test-1:6432/pgbouncer=# show lists;
     list      | items
---------------+-------
 databases     |     4
 users         |     8
 pools         |     4
 free_clients  |   101
 used_clients  |    99
 login_clients |     0
 free_servers  |     8
 used_servers  |    92
 dns_names     |     0
 dns_zones     |     0
 dns_queries   |     0
 dns_pending   |     0
(12 rows)

Time: 0.801 ms
```
Problem one:
I created two pgbench tests. The two are two users connecting to different databases. Each pgbench has 60 connections. According to the document, can my used_servers reach 110? Default_pool_size*pools+reserve_pool_size=50*2+10=110, why is the current limit of 92? It shows that there are free_servers. 
Problem Two:
Max_client_conn is set to 100 and used_clients=97. This is understandable, but free_clients=103. Why? The sum of the two is 200. Is this because of the connection pool restriction? Normally, the client should be reach to 200? pools*max_client_conn=2*100

**Comment by xiangma0510** [comment]
If max_client_conn limits the global, why are there so many free_clients=103?

**Comment by xiangma0510** [comment]
I did another test:
Settings:
```
default_pool_size = 50
reserve_pool_size = 0
reserve_pool_timeout = 0
max_client_conn = 180
max_db_connections = 0
max_user_connections = 0
max_connections=200 (postgresql)
```
```shell
$ show lists;
     list      | items
---------------+-------
 databases     |     4
 users         |     8
 pools         |     4
 free_clients  |    29
 used_clients  |   171
 login_clients |     2
 free_servers  |    50
 used_servers  |   150
 dns_names     |     0
 dns_zones     |     0
 dns_queries   |     0
 dns_pending   |     0
(12 rows)

Time: 0.793 ms
```
I started three pgbench, each one has 60 sessions max,I can see used_server has reached to limit used_pools * default_pool_size = 3 * 50 =150,used_clients may limited by used_servers，so cannot reached to 180,In my understanding, free_clients should be 9, not 29

**Comment by artem-hw9** [comment]
I have a similar problem. I tried to monitor free clients and servers.
But data from **show lists** do not match with settings from configuration file

```shell
[databases]
* = auth_user=postgres

[pgbouncer]
max_client_conn = 100
default_pool_size = 20
...
``` 
```shell
pgbouncer=# show lists;
     list      | items 
---------------+-------
 databases     |     2
 users         |     5
 peers         |     0
 pools         |     3
 peer_pools    |     0
 free_clients  |    32
 used_clients  |    18
 login_clients |     0
 free_servers  |    46
 used_servers  |     4
 dns_names     |     0
 dns_zones     |     0
 dns_queries   |     0
 dns_pending   |     0
``` 
I noticed that summ both parameters is  50
free_clients + used_clients = 50
free_servers + used_servers = 50

What does this data really mean? **free_clients** and **free_servers**

**Comment by JelteF** [comment]
To avoid re-allocating over and over again PgBouncer internally keeps a cache of memory chunks for clients and servers. That is what free_clients and free_servers mean. So there's simply a few bytes allocated for servers and clients. This could definitely be described better in the docs though.
