### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by MichaelDBA** [pgbouncer/pgbouncer#654]
I get this error:
`ERROR accept() failed: Too many open files`

We are using the default pool mode: session.  It seems that the parameter, client_idle_timeout, does not apply to session mode.  

It seems we are having a lot of clients that are ending their pgbouncer session without closing it but later connect again.  I'm guessing this is what is causing our error noted above.

If so, is there anything we can do in session mode to get rid of those idle front end connections to pgbouncer?  Or do we have to keep increasing hard ulimit for nofile for pgbouncer user?

**Comment by eulerto** [comment]
When you start the PgBouncer service, it indicates how many file descriptors is required for it.

```
LOG kernel file descriptor limit: 1024 (hard: 4096); max_client_conn: 1000, max expected fd use: 5212
```

In this case, PgBouncer expect the soft limit to be at least **5212**. The current value is **1024**.

You can check your current limit settings using the following command:

```
grep files /proc/`pgrep pgbouncer`/limits
Max open files            1024                 4096                 files     
```

If you are using Debian/Ubuntu, you can adjust it by adding the `ulimit` command to `/etc/default/pgbouncer`.

```
ulimit -n 25000
```

After that, restart the service and check the limit setting again.

```
root@ubuntu1804:~# /etc/init.d/pgbouncer restart
[ ok ] Restarting pgbouncer (via systemctl): pgbouncer.service.
root@ubuntu1804:~# grep files /proc/`pgrep pgbouncer`/limits
Max open files            25000                25000                files     
```

If you are using CentOS/RHEL, you have to add `LimitNOFILE` parameter to the PgBouncer service. It probably provides a Drop-In file that includes `LimitNOFILE`. You can check it using:

```
[root@centos7 ~]# systemctl status -l pgbouncer
● pgbouncer.service - A lightweight connection pooler for PostgreSQL
   Loaded: loaded (/usr/lib/systemd/system/pgbouncer.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/pgbouncer.service.d
           └─limit_nofile.conf
   Active: active (running) since Thu 2021-11-18 13:15:22 UTC; 10s ago
```

In this case, the file `/etc/systemd/system/pgbouncer.service.d/limit_nofile.conf` contains the new setting. After that, check your current limit settings.

```
[root@centos7 ~]# grep files /proc/`pgrep pgbouncer`/limits
Max open files            65536                65536                files     
```

If you change `LimitNOFILE` value, execute `systemctl daemon-reload` and restart the service.

**Comment by MichaelDBA** [comment]
Thanks for all that info, but I guess that means there is no way to limit the number of attempted client connections to PGBouncer, correct?

**Comment by eulerto** [comment]
Do you mean attempts after reaching this limit? No. You need to reduce `max_client_conn` and/or pool size. However, PgBouncer does not fail the service, instead it suspend for some time (5s) and try again hoping the admin can fix it. See this comment.

```c
		/*
		 * probably fd limit, pointless to try often
		 * wait a bit, hope that admin resolves somehow
		 */
		log_error("accept() failed: %s", strerror(errno));
		evtimer_assign(&ev_err, pgb_event_base, err_wait_func, NULL);
		safe_evtimer_add(&ev_err, &err_timeout);
		suspend_pooler();
```

**Comment by MichaelDBA** [comment]
gotcha thanks for that last tip regarding max_client_conn.  Closing this now.
