### ISSUE TITLE
Restart server pgbouncer not responding

### ISSUE THREAD

**Issue by mikkeljohnsen** [pgbouncer/pgbouncer#658]
When a server is restarted, pgbouncer is not always responding afterwards.

Could you make this change to the systemd service:
```
...
After=syslog.target network-online.target
Wants=network-online.target
...
```

Not sure who is making the RPM package, but the service file is not the same ?

**Comment by petere** [comment]
You are going to have to provide a lot more details about what you are doing, what is going wrong, and why you think this fixes it. `network-online.target` is generally not recommended. AFAICT, the existing use of `network.target` is correct.
