### ISSUE TITLE
did we build any Image for pgboucner version 1.12.0 with  pgbouncer-rr-patch ?

### ISSUE THREAD

**Issue by surajmachamasi** [pgbouncer/pgbouncer#661]
reaching out in community for image of pgboucner with rr-patch. 

pgboucner--rr-patch git link: 
https://github.com/awslabs/pgbouncer-rr-patch

**Comment by petere** [comment]
This isn't really a development issue. I suggest you use the Discussions feature or ask on Gitter. You might also want to clarify what is meant by "image".
