### ISSUE TITLE
Can't connect with multi-case username

### ISSUE THREAD

**Issue by kwobrien** [pgbouncer/pgbouncer#662]
For our app, we are using the auth_query against a table that we have set up in PostgreSQL to authenticate the user.

We allow the username to be multi-cased, e.g. myUserName.

I understand that PostgreSQL will lowercase usernames (or rather roles) when you add a new user to PostgreSQL, and so I believe it is also true that the username must be lowercased before attempting to connect to PostgreSQL, regardless of whether you're using pgbouncer or connecting directly.

I tried to set up the auth_query so that it returns a lowercased usename from the query to our users table thinking that the value  for the usename column that is returned would be the value that pgbouncer will use to authenticate to PostgreSQL. However I still get an authentication error in this case.

I am wondering if this is by design, or if it is possible to support our use case where a user might try to authenticate with a multi-cased username, and it will succeed if
1. The username provided by the user matches the username in the pgbouncer users table exactly and
2. The lowercase version of the username is valid for authenticating with PostgreSQL

If on the other hand, this should already be supported an I'm just doing something wrong, I would appreciate some guidance.

Here is the auth_query I'm using
```
auth_query=select LOWER(usename),passwd from my_schema.pgbouncer_users where usename=$1 
```

**Comment by petere** [comment]
I think you misunderstood something. PostgreSQL supports mixed-case user names just fine, and if you create a mixed-case username you also need to use it to connect. So the lowercasing you are attempting here isn't the right solution in any case.
