### ISSUE TITLE
the default config `auth_type=trust` is not secure

### ISSUE THREAD

**Issue by zxdvd** [pgbouncer/pgbouncer#664]
I installed pgbouncer and add a database and a user with md5 password. Then I connected to it
 using `pgcli postgres://xxx@localhost:6432/xx` and it didn't ask for password.

Then I found it is because the default config `auth_type = trust`. I think it is not secure. I also found
 someone confused about this in [stackoverflow](https://stackoverflow.com/questions/53254946/pgbouncer-works-even-with-the-wrong-password).

I suggest to change it `auth_type = md5` or others.

**Comment by petere** [comment]
The default is actually `md5`. Only the sample configuration file shows `trust`.

**Comment by zxdvd** [comment]
Sorry I mean the sample file and some distributions like debian use the sample file as default config.
