### ISSUE TITLE
Db name and user name in logs for shared pgbouncer service

### ISSUE THREAD

**Issue by arbansal01** [pgbouncer/pgbouncer#669]
In our scenario, we have 2 cluster

Cluster will contain separate namespaces of each application. Each application will be pointed to same pgbouncer shared service
Cluster will have pgbouncer namespace having separate conf for each application databases in pgbouncer.ini
Now, when we check he pgbouncer logs, there are statements where dbname and dbuser are coming as blank. As mentioned, pgbouncer will be shared by mutiple apps so it will be difficult for us to track that logs are coming for which dbs.

Attach is the sample log file. Please share how can we add dbname and dbuser in logs

![image](https://user-images.githubusercontent.com/60982521/149046904-583e0373-52bf-4790-aa4e-ce350c0ac338.png)

**Comment by petere** [comment]
Database and user are only known once the client sends over the information in the startup handshake. If the client disconnects before that is complete, PgBouncer simply doesn't know what the database and user are, and so it can't log them. Notice that the log lines you pointed out are all "client unexpected eof", so it looks like the client connects and then disconnects before really logging in.
