### ISSUE TITLE
WARNING C-0x1370560: (nodb)/(nouser)@127.0.0.1:52689 pooler error: unsupported startup parameter: search_path

### ISSUE THREAD

**Issue by bagafoot** [pgbouncer/pgbouncer#674]
Hello, 
In some clients connection I get this warninng, I add it to ignore_startup_parameters then client getting error when queried beacuse of search path, cannot find table. 
how to fix that ?

**Comment by petere** [comment]
If you are using session mode, then you should just set search_path using a normal `SET` command, not using a startup parameter. If you are using transaction mode, then you can't use session-level features, so you need to find another solution.
