### ISSUE TITLE
Setting SO_REUSEPORT_LB for FreeBSD jail

### ISSUE THREAD

**Issue by fahadshery** [pgbouncer/pgbouncer#677]
Hi,

Here is the system info:
```bash
 uname -a
FreeBSD pgbouncer 12.2-RELEASE-p11 FreeBSD 12.2-RELEASE-p11 75566f060d4(HEAD) TRUENAS  amd64
```

I installed using:
```bash
pkg install pgbouncer
```

Since I got about 32 cpu threads available, I now want to run `multiple pgbouncers` on the same listening port, According to the [docs](https://www.pgbouncer.org/config.html), I have to set `SO_REUSEPORT_LB=1` in the `.ini` file since I am using `FreeBSD` but I am getting the following error:

```bash
service pgbouncer start
Starting pgbouncer.
2022-01-30 15:53:51.512 GMT [35925] ERROR unknown parameter: pgbouncer/SO_REUSEPORT_LB
2022-01-30 15:53:51.514 GMT [35925] ERROR invalid value "1" for parameter SO_REUSEPORT_LB in configuration (/usr/local/etc/pgbouncer.ini:298)
2022-01-30 15:53:51.514 GMT [35925] FATAL cannot load config file
/usr/local/etc/rc.d/pgbouncer: WARNING: failed to start pgbouncer
```

However, just setting the `SO_REUSEPORT=1` works. Does it mean I don't need to do anything and it would spawn multiple instances of `pgbouncer` on its own?

Here is the installed version:
```bash
pgbouncer -V
PgBouncer 1.16.0
libevent 2.1.12-stable
adns: evdns2
tls: OpenSSL 1.1.1l-freebsd  24 Aug 2021
```

thank you for this brilliant project.

**Comment by fahadshery** [comment]
> The PgBouncer setting is called `so_reuseport`. You are using the wrong spelling of the option in your example.

Yes, As per my last message:
> However, just setting the SO_REUSEPORT=1 works.

The docs read like this:
> On FreeBSD, it applies the socket option SO_REUSEPORT_LB instead.

So it's a little bit confusing.

Finally my question is, what do I need to do to spin up multiple instances of `pgbouncer` apart from just setting the `so_reuseport=1`

Cheers,

**Comment by petere** [comment]
See this post for some ideas: https://www.2ndquadrant.com/en/blog/running-multiple-pgbouncer-instances-with-systemd/
