### ISSUE TITLE
Build failure on Solaris

### ISSUE THREAD

**Issue by fazalmajid** [pgbouncer/pgbouncer#68]
pgbouncer 1.6 fails to build on Solaris (more specifically SmartOS) with errors in lib/usual/bits.h. The fix is to include <limits.h> in bits.h (see http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/limits.h.html for more details)

    --- bits.h.dist Tue Sep  1 12:03:04 2015
    +++ bits.h      Tue Sep  1 12:03:40 2015
    @@ -29,6 +29,7 @@
     #include <usual/base.h>

     #include <string.h>
    +#include <limits.h>

     /** Checks if integer has only one bit set */
     static inline bool is_power_of_2(unsigned int n)

The other issue is lib/usual/crypto/csrandom.c fails due to a missing type in the crypto_range function. This patch fixes the issue:

    --- csrandom.c.dist     Tue Sep  1 12:13:13 2015
    +++ csrandom.c  Tue Sep  1 12:13:55 2015
    @@ -40,7 +40,7 @@
            arc4random_buf(buf, nbytes);
     }

    -uint32_t csrandom_range(upper_bound)
    +uint32_t csrandom_range(uint32_t upper_bound)
     {
            return arc4random_uniform(upper_bound);
     }

Issue 1:

         CC       lib/usual/hashing/lookup3.c
    In file included from lib/usual/base.c:20:0:
    lib/usual/bits.h: In function 'safe_mul_uint':
    lib/usual/bits.h:184:33: error: 'UINT_MAX' undeclared (first use in this function)
      _USUAL_MUL_SAFE_(unsigned int, UINT_MAX);
                                     ^
    lib/usual/bits.h:174:7: note: in definition of macro '_USUAL_MUL_SAFE_'
      if ((max / a) >= b)  \
           ^
    lib/usual/bits.h:184:33: note: each undeclared identifier is reported only once for each function it appears in
      _USUAL_MUL_SAFE_(unsigned int, UINT_MAX);
                                     ^
    lib/usual/bits.h:174:7: note: in definition of macro '_USUAL_MUL_SAFE_'
      if ((max / a) >= b)  \
           ^
    lib/usual/bits.h: In function 'safe_mul_ulong':
    lib/usual/bits.h:190:34: error: 'ULONG_MAX' undeclared (first use in this function)
      _USUAL_MUL_SAFE_(unsigned long, ULONG_MAX);
                                      ^
    lib/usual/bits.h:174:7: note: in definition of macro '_USUAL_MUL_SAFE_'
      if ((max / a) >= b)  \
           ^
    lib/usual/crypto/csrandom.c: In function 'csrandom_range':
    lib/usual/crypto/csrandom.c:43:10: warning: old-style function definition [-Wold-style-definition]
     uint32_t csrandom_range(upper_bound)
              ^
    lib/usual/crypto/csrandom.c:43:10: warning: type of 'upper_bound' defaults to 'int' [-Wimplicit-int]
    lib/usual/crypto/csrandom.c:43:10: error: argument 'upper_bound' doesn't match prototype
    In file included from lib/usual/crypto/csrandom.c:19:0:
    lib/usual/crypto/csrandom.h:38:10: error: prototype declaration
     uint32_t csrandom_range(uint32_t upper_bound);
              ^
    In file included from lib/usual/crypto/md5.c:23:0:
    lib/usual/bits.h: In function 'safe_mul_uint':
    lib/usual/bits.h:184:33: error: 'UINT_MAX' undeclared (first use in this function)
      _USUAL_MUL_SAFE_(unsigned int, UINT_MAX);
                                     ^
    lib/usual/bits.h:174:7: note: in definition of macro '_USUAL_MUL_SAFE_'
      if ((max / a) >= b)  \
           ^
    lib/usual/bits.h:184:33: note: each undeclared identifier is reported only once for each function it appears in
      _USUAL_MUL_SAFE_(unsigned int, UINT_MAX);
                                     ^
    lib/usual/bits.h:174:7: note: in definition of macro '_USUAL_MUL_SAFE_'
      if ((max / a) >= b)  \
           ^
    lib/usual/bits.h: In function 'safe_mul_ulong':
    lib/usual/bits.h:190:34: error: 'ULONG_MAX' undeclared (first use in this function)
      _USUAL_MUL_SAFE_(unsigned long, ULONG_MAX);
                                      ^
    lib/usual/bits.h:174:7: note: in definition of macro '_USUAL_MUL_SAFE_'
      if ((max / a) >= b)  \
           ^
    /home/majid/build/pgbouncer-1.6/lib/mk/antimake.mk:1222: recipe for target '.objs/pgbouncer/lib/usual/crypto/csrandom.o' failed

Issue 2:

         CC       lib/usual/crypto/csrandom.c
    lib/usual/crypto/csrandom.c: In function 'csrandom_range':
    lib/usual/crypto/csrandom.c:43:10: warning: old-style function definition [-Wold-style-definition]
     uint32_t csrandom_range(upper_bound)
              ^
    lib/usual/crypto/csrandom.c:43:10: warning: type of 'upper_bound' defaults to 'int' [-Wimplicit-int]
    lib/usual/crypto/csrandom.c:43:10: error: argument 'upper_bound' doesn't match prototype
    In file included from lib/usual/crypto/csrandom.c:19:0:
    lib/usual/crypto/csrandom.h:38:10: error: prototype declaration
     uint32_t csrandom_range(uint32_t upper_bound);
              ^
    xmlto man usage.xml
    /home/majid/build/pgbouncer-1.6/lib/mk/antimake.mk:1222: recipe for target '.objs/pgbouncer/lib/usual/crypto/csrandom.o' failed

**Comment by markokr** [comment]
Fixed in git, fix will be in 1.6.1
