### ISSUE TITLE
 pgbouncer : Depends: libevent-2.0-5 (>= 2.0.10-stable) but it is not installable

### ISSUE THREAD

**Issue by hamedbaftam** [pgbouncer/pgbouncer#681]
Hi, when i execute "sudo apt-get install pgbouncer" got this error:

The following packages have unmet dependencies:
 pgbouncer : Depends: libevent-2.0-5 (>= 2.0.10-stable) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by petere** [comment]
You will have to talk to whoever is providing those packages. This project is only responsible for the source code.
