### ISSUE TITLE
Support for PG14 pipeline mode?

### ISSUE THREAD

**Issue by machty** [pgbouncer/pgbouncer#682]
PG 14 introduces pipeline mode, wherein the client can send multiple queries without having to first read the response from the prior query. 

https://www.postgresql.org/docs/14/libpq-pipeline-mode.html

This seems like something that might be a challenge for pgbouncer; is it supported? Are there plans to support it? How might it work?

**Comment by petere** [comment]
The libpq pipeline mode is only a feature of the libpq API. It does not change the PostgreSQL protocol. Consequently, it is unrelated to PgBouncer. Other (non-libpq) drivers already operate in de-facto pipeline mode and PgBouncer supports that just fine. So there is nothing to do here.
