### ISSUE TITLE
tcp_defer_accept=1 but not set in the configuration file and the documentation says otherwise

### ISSUE THREAD

**Issue by lohengrin1870** [pgbouncer/pgbouncer#686]
Hello
I am using 
`pgbouncer 1.16.1` and `1.16` and I have noticed a strange behaviour. The installed package is : `pgbouncer-1.16.1-1.rhel7.x86_64` and as a matter of fact it's installed on `Red Hat Enterprise Linux Server release 7.9 (Maipo)`
I am querying the configuration and I can see that `tcp_defer_accept` is set to `1` but we didn't set that in the configuration file.
Moreover according to the documentation it's supposed that the default is `45` on Linux but 'show config' says that the default is blank, could you please explain this behaviour and what are the side effects ?
Thank you in advance for your comments

**Comment by petere** [comment]
The documentation is a bit confusing. In PgBouncer, `tcp_defer_accept` is a Boolean option and it defaults to 1 on Linux. The actual underlying socket option `TCP_DEFER_ACCEPT` takes an integer value that indicates seconds. When the PgBouncer option is enabled, then the socket option is set to 45 (seconds). That value is hardcoded.

I'll see about cleaning this up.
