### ISSUE TITLE
Section [databases] in external file

### ISSUE THREAD

**Issue by cesarfreire** [pgbouncer/pgbouncer#691]
There's some way to configure PGBouncer to use the databases section from an external file?

I want to make this section changeable from other built-in routines.

Something like:

`auth_file = /etc/pgbouncer/userlist.txt`

but

`databases_file = /etc/pgbouncer/databases.txt`

**Comment by petere** [comment]
There is an `%include` directive. See pgbouncer(5) man page.

**Comment by cesarfreire** [comment]
Oh... sorry. Thanks @petere !
