### ISSUE TITLE
Yet Another Server Side Prepared Statements Patch

### ISSUE THREAD

**Issue by dashorst** [pgbouncer/pgbouncer#695]
I know this is completely unsolicited, but I'd like to ask for your consideration to evaluate whether and under what conditions [these commits][patch] can be integrated with pgbouncer.

## TL;DR

- we have [patched pgbouncer to support prepared statements][patch]
- the proposed [changes to pgbouncer can be seen in this diff][diff]
- we want to contribute the patch to the pgbouncer community
- do you want this feature at all (e.g. prepared statement support)
- do you want this patch at all?
- what must we do to make this patch acceptable?

## The Case for Server Side Prepared statements support

One of the biggest issues when we migrated from Oracle to Postgresql and using pgbouncer was the lack of server-side prepared statement caching. This resulted in an enormous amount of inbound network traffic from our application servers due to the queries being constantly sent over for parsing, and in a really high CPU usage on the database server due to having to parse the statements.

After deploying the code in this prepared statements patch project our CPU usage was considerably lower, and the network traffic went from 400mbit/s to 20mbit/s IIRC (it was in summer 2020 so specific details are becoming vague)

### Figure 1: Database CPU usage before and after using the patched PG Bouncer

![db-cpu-usage](https://user-images.githubusercontent.com/46626/158636579-15f18ace-65c9-4ad3-b4d2-c88e44804b38.png)

As you can see in this graph the CPU usage after the upgrade to the patched pgbouncer is significantly lower than before.

### Figure 2: Network traffic before and after using the patched PG Bouncer

![network](https://user-images.githubusercontent.com/46626/158638296-65fffe04-f0b5-4c2c-ad6e-59db933e4d41.png)

The contrast between running without server side prepared statements and using server side prepared statements is very apparent in the "incoming" network traffic graph in Figure 2. The amount of incoming traffic on the database server goes from WOW to practically non-existent.

### Figure 3: application response times before and after the patch

** Before the patch **
![response-times-before-ps](https://user-images.githubusercontent.com/46626/158636607-f59fa223-20dc-40d3-a909-bc3c57442ff9.png)

** After the patch **
![response-times-after-ps](https://user-images.githubusercontent.com/46626/158636605-c3656b78-7238-4c16-b258-0513090e5e36.png)

As you can see using the patch the response times of our application dropped significantly in a good way. Lower is better.

## Proposal

This patch introduces [prepared statement tracking](https://github.com/pgbouncer/pgbouncer/issues/new#how-it-works), allowing to run PgBouncer in transaction pooling mode with server side prepared statements. It only supports the extended query protocol parse, bind, execute and close [message formats](https://www.postgresql.org/docs/12/protocol-message-formats.html)[](https://github.com/pgbouncer/pgbouncer/issues/new#getting-started). E.g. the flow used by the PostgreSQL JDBC driver to create server prepared statements.

We use this code in our production environment and _for our use_ it is battle tested. But we know that the world is larger than us, but we are unable to prepare for that as we have limited resources and we just don't know what other users run into. 

I know the code is not in a PR presentable way, but we are willing to work on that to make it more amendable for the upstream project to absorb. We think this patch provides a great reduction in resource usage for users of pgbouncer and are willing to (within reason) work with the community to get this upstream if the community is willing to adopt the code patch.

- is the general idea of "Server Side Prepared Statements" a feature you are willing to adopt?
- if so, would our (~28 commits) patch be something you would take a look at?
- if so, what should we do for you to adopt the code into the pgbouncer code base if that is a possibility?

Thank you for your project and time. We hope we can work together in bringing server side prepared statements to pgbouncer. If you are not willing to either implement the feature or use our code that is totally fine--no hard feelings (but we may need a 🥃  or so to drink away our disappointment) we understand that adding features to a project creates work and adopting other peoples code is even more work.

The patched code base can be found here: [https://github.com/topicusonderwijs/pgbouncer-ps-patch][patch]

[patch]: https://github.com/topicusonderwijs/pgbouncer-ps-patch
[diff]: https://github.com/topicusonderwijs/pgbouncer/compare/pgbouncer_1_14_0...topicusonderwijs:pgbouncer-ps-patch?expand=1

**Comment by jcdickinson** [comment]
I am going to be trying this out in our environment (.Net and Ruby) over the next few weeks, hopefully. Thanks for sharing your code!

**Comment by jcdickinson** [comment]
Some initial tests from our integration environment and load tests:

Before:

![Without Patch](https://user-images.githubusercontent.com/522465/161335176-657cc4d2-9a67-4f9f-84b4-877331ff8145.png)

After:

![With Patch](https://user-images.githubusercontent.com/522465/161335250-5d9da799-3ad2-44d9-9a38-fff38404880a.png)

Looking fantastic!

**Comment by jcdickinson** [comment]
These are the number of connections to pgsql by state. Light purple is an idle connection, purple is a stale connection, yellow is a used connection. All it does is prove that your patch works with clients other that JDBC. I'm going to be doing load testing this week.

**Comment by abonander** [comment]
Prepared statements don't just represent a performance improvement, but also a small improvement in ergonomics and a significant one in security.

The extended query interface in the Postgres protocol allows supplying dynamic data to the query via bind arguments which are sent completely out-of-band from the regular query and so are not subject to SQL injection vulnerabilities. This also means that you don't have to remember to sanitize user input or worry about forgetting to do.

Context: I am a maintainer of [SQLx, a SQL client for Rust](https://github.com/launchbadge/sqlx). The design of SQLx very strongly pushes users towards prepared statements for all the above reasons, as well because they support additional functionality in SQLx like compile-time query checking.

PgBouncer has been a thorn in our side because of its lack of support for prepared statements in the default transaction-pooling mode--or rather, lack of awareness of them, because it appears to allow `Parse` messages through even in transaction pooling mode, so prepared statements _appear_ to work but with various bugs, leading users to conclude instead that there must be something wrong with SQLx.

**Comment by dashorst** [comment]
@jcdickinson Not sure if this is something that is prevalent in Ruby/.Net, but we also made a JDBC driver that "until a modification happens on a connection, uses autocommit, from the modification on disables autocommit until a commit or rollback on the connection, after which it enables autocommit again". This saved us a lot on long running (idle) transactions when a web requests acquires a connection and puts it into transaction mode until the end of the request. https://github.com/olavloite/smartcommit

**Comment by petere** [comment]
Could you provide this patch as a pull request or at least some branch of yours that can be checked out and used directly? The current format is a bit unwieldy for examining.

**Comment by dashorst** [comment]
> Could you provide this patch as a pull request or at least some branch of yours that can be checked out and used directly? The current format is a bit unwieldy for examining.

- I've cloned out the repository (topicusonderwijs/pgbouncer-ps-patch) and the pgbouncer repository next to one another.
- I've checked out the pgbouncer_1_14_0 tag in the pgbouncer repository.
- I've run the `install-pgbouncer-ps-patch.sh` script with parameter `../pgbouncer`

I then created a branch in our pgbouncer repository: pgbouncer-ps-patch and pushed the patch.

The results can be seen here: https://github.com/topicusonderwijs/pgbouncer/compare/pgbouncer_1_14_0...topicusonderwijs:pgbouncer-ps-patch?expand=1

**Comment by cobolbaby** [comment]
Is there any progress on this request?

**Comment by JelteF** [comment]
@dashorst could you please create a pull request to this repo using the branch that you shared? That will allow me to create review comments on specific lines.

**Comment by JelteF** [comment]
To be clear, this sounds like a great feature! But it will almost certainly need a few rounds of review and some testing on my part.

**Comment by dashorst** [comment]
I redid the PR, you can find it [here](https://github.com/pgbouncer/pgbouncer/pull/757). I have no idea if it works or not.

**Comment by JelteF** [comment]
Closing this now that #845 is merged and released
