### ISSUE TITLE
Feature request: support auth_host (coupled to auth_user/auth_query)

### ISSUE THREAD

**Issue by dko-slapdash** [pgbouncer/pgbouncer#708]
When pgbouncer runs on the same host as postgres cluster, it would be very convenient if we didn't need to have auth_user's password in userlist.txt and instead would just use local authentication to send auth_query. Below is a config illustration of what I'm trying to achieve:

```
[databases]
* = host=127.0.0.1

[pgbouncer]
...
auth_host = /var/run/postgresql # <-- this directive doesn't exist yet
auth_user = postgres
auth_query = SELECT usename, passwd FROM pg_shadow WHERE usename=$1
...
```

Since pgbouncer runs as user postgres, the same as the main postgres cluster's user, it can access pg_shadow without a password with default pg_hba. So if we had auth_host directive (proposed in this feature request), then pgbounder would be almost transparent for clients; no passwords hardcoding in userlist.txt (and no need in userlist.txt at all, especially when an idea in #573 is implemented too), no hustle.

**Comment by Turkish** [comment]
I think you can use auth_dbname for this (https://github.com/pgbouncer/pgbouncer/pull/764)

**Comment by JelteF** [comment]
Yeah, `auth_dbname` is the way to go for this.
