### ISSUE TITLE
pooler error: invalid server parameter

### ISSUE THREAD

**Issue by manmanblue** [pgbouncer/pgbouncer#720]
I'm using pgbouncer 1.15 

sometimes an error occurs, my java app received "invalid server parameter" exception， and the pgbouncer server log "pooler error: invalid server parameter".

does it have anything with some timeout configs?

how to prevent this from happening again? 

tks!

**Comment by petere** [comment]
This happens if pgbouncer got an error from the server while trying to run `SET` commands at the beginning of a connection. You could check the logs of the server to find the full error.
