### ISSUE TITLE
Cannot get system entropy

### ISSUE THREAD

**Issue by chungonion** [pgbouncer/pgbouncer#721]
I also opened an issue on [Bitnami's pgbouncer](https://github.com/bitnami/bitnami-docker-pgbouncer/issues/35) repo, as I used their image for hosting pgbouncer on docker

May I know what exactly the root cause that could have trigger `Cannot get system entropy` error when user authentication is going to be take place? Are there additional settings to ensure pgbouncer to obtain entropy or simple because my machine might not generate enough entropy? 

Thank you!

**Comment by petere** [comment]
It could be a number of things, depending on the underlying system and configuration. For example, maybe `/dev/urandom` isn't readable. It might be worth stracing the pgbouncer process to see the exact sequence of steps that precede this error.

**Comment by chungonion** [comment]
> It could be a number of things, depending on the underlying system and configuration. For example, maybe `/dev/urandom` isn't readable. It might be worth stracing the pgbouncer process to see the exact sequence of steps that precede this error.

Thanks @petere . You mentioned stracing the pgbouncer process, it will be great if you could further explain a bit on the method to trace the `pgbouncer` process... I tried to read the log but that is not so helpful. The `Cannot get system entropy` soon appeared after `login attempt:`, and I am clueless on what exactly triggered this error...

Once again thank you for the assistance!

**Comment by petere** [comment]
When you start pgbouncer, instead of running

    pgbouncer options...

you run

    strace pgbouncer options...

and see what it prints out.

**Comment by chungonion** [comment]
> When you start pgbouncer, instead of running
> 
> ```
> pgbouncer options...
> ```
> 
> you run
> 
> ```
> strace pgbouncer options...
> ```
> 
> and see what it prints out.

Sure I will have a look first, thank you!

**Comment by chungonion** [comment]
Just would like to share my findings. I think the issue might have been caused by the CPU, 32 bit could not work properly (DS713+) but when I ditched to a newer 64 bit model (DS720+) it works! Thank you!

**Comment by petere** [comment]
32-bitness by itself wouldn't explain this, but well, if it works for you ...
