### ISSUE TITLE
pgBouncer segfaults when an incorrect db name is passed

### ISSUE THREAD

**Issue by HalacliSeda** [pgbouncer/pgbouncer#723]
Hi,
I am using pgBouncer 1.17.0
pgBouncer service gives an error when mistyped database name.
An example:
 psql -h 127.0.0.1 -p 5432 -U postgres -d postgress
Password for user postgres: 
psql: error: connection to server at "127.0.0.1", port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

Journal error:
 kernel: pgbouncer[153489]: segfault at 28 ip 000056510544cf81 sp 00007fff7ce91640 error 4 in pgbouncer[56510543a000+65000]

How can I resolve this error? Thank you.

**Comment by nicolasjulian** [comment]
Hello, 
We also got this error, in our prod also got the same behavior when using **pgBouncer 1.17.0**
```bash
psql: error: connection to server at "127.0.0.1" , port 6432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

pgbouncer.log
```bash
Jun 16 06:44:26 database-server pgbouncer[186088]: stats: 29 xacts/s, 32 queries/s, in 17542 B/s, out 17376 B/s, xact 5112 us, q>
Jun 16 06:45:01 database-server systemd[1]: pgbouncer.service: Main process exited, code=dumped, status=11/SEGV
Jun 16 06:45:01 database-server systemd[1]: pgbouncer.service: Failed with result 'core-dump'.
Jun 16 06:45:03 database-server systemd[1]: pgbouncer.service: Scheduled restart job, restart counter is at 218.
Jun 16 06:45:03 database-server systemd[1]: Stopped pgbouncer PostgreSQL connection pooler.
Jun 16 06:45:03 database-server systemd[1]: Starting pgbouncer PostgreSQL connection pooler...
```

dmesg.log
```bash
[Thu Jun 16 06:43:23 2022] Code: 00 00 00 31 c0 e8 dd 11 02 00 e9 b5 fb ff ff 31 f6 48 89 ef e8 4e ed ff ff e9 6c fd ff ff 48 8b 45 18 f3 0f 6f 85 e8 00 00 00 <48> 8b 40 28 0f 11 80 b8 08 00 00 f3 0f 6f 8d f8 00 00 00 0f 11 88
[Thu Jun 16 06:44:59 2022] pgbouncer[186088]: segfault at 28 ip 000055659786ed63 sp 00007ffffa117760 error 4 in pgbouncer[556597866000+34000]
[Thu Jun 16 06:44:59 2022] Code: 00 00 00 31 c0 e8 dd 11 02 00 e9 b5 fb ff ff 31 f6 48 89 ef e8 4e ed ff ff e9 6c fd ff ff 48 8b 45 18 f3 0f 6f 85 e8 00 00 00 <48> 8b 40 28 0f 11 80 b8 08 00 00 f3 0f 6f 8d f8 00 00 00 0f 11 88
```

Is this a bug version 1.17.0 ? or a kind of misconfiguration?

**Comment by mbsabath** [comment]
seems like this may be a bug introduced here: https://github.com/pgbouncer/pgbouncer/pull/687

**Comment by mbsabath** [comment]
I've been digging in to this a bit more. Looks like the mock authentication when a DB doesn't exist works fine when authentication method is set to trust, but segfaults with a non existent DB when the authentication method is set to `md5`. I'm working on a PR to see if I can track down exactly where the segfault is coming from

**Comment by mbsabath** [comment]
I think I have it resolved here: https://github.com/pgbouncer/pgbouncer/pull/730

**Comment by eulerto** [comment]
@HalacliSeda @nicolasjulian Could you confirm that it is the same issue you are observing? Could you share your setup? Are you using SCRAM authentication?

**Comment by neteven-tld** [comment]
Hi, we can observe same behavior, when trying to connect with a user having SCRAM password on database which doesn't exist, on last 1.17.0 version.
```
Sep 21 14:40:08 dbr1 kernel: pgbouncer[3300631]: segfault at 28 ip 0000562fec879dd3 sp 00007fff7eb81a70 error 4 in pgbouncer[562fec872000+36000]
Sep 21 14:40:08 dbr1 kernel: Code: 00 00 00 31 c0 e8 0d 3e 02 00 e9 35 fb ff ff 31 f6 48 89 ef e8 6e ed ff ff e9 7c fd ff ff 48 8b 45 18 f3 0f 6f 85 e8 00 00 00 <48> 8b 40 28 0f 11 80 b8 08 00 00 f3 0f 6f 8d f8>
Sep 21 14:40:09 dbr1 systemd[1]: pgbouncer.service: Main process exited, code=killed, status=11/SEGV
Sep 21 14:40:09 dbr1 systemd[1]: pgbouncer.service: Failed with result 'signal'.
```

**Comment by ToMs77130** [comment]
Hi, we can observe same behavior, when trying to connect with a user having SCRAM password on database which doesn't exist, on last 1.17.0 version.
```
Sep 21 14:40:08 dbr1 kernel: pgbouncer[3300631]: segfault at 28 ip 0000562fec879dd3 sp 00007fff7eb81a70 error 4 in pgbouncer[562fec872000+36000]
Sep 21 14:40:08 dbr1 kernel: Code: 00 00 00 31 c0 e8 0d 3e 02 00 e9 35 fb ff ff 31 f6 48 89 ef e8 6e ed ff ff e9 7c fd ff ff 48 8b 45 18 f3 0f 6f 85 e8 00 00 00 <48> 8b 40 28 0f 11 80 b8 08 00 00 f3 0f 6f 8d f8>
Sep 21 14:40:09 dbr1 systemd[1]: pgbouncer.service: Main process exited, code=killed, status=11/SEGV
Sep 21 14:40:09 dbr1 systemd[1]: pgbouncer.service: Failed with result 'signal'.
```

**Comment by eulerto** [comment]
@ToMs77130 Could you try building from the `master` branch and check if commit #730 solved this issue? Build and install instructions are [here](https://www.pgbouncer.org/install.html).

**Comment by ToMs77130** [comment]
@eulerto it's all good.

Before
```
toms@redpill:~$ psql -h dbs1.xx.com -p 9999 -U expl         
psql: error: connection to server at "dbs1.xx.com" (xxx), port 9999 failed: SSL SYSCALL error: EOF detected
```

With rebuild version 
```
toms@redpill:~$ psql -h dbs1.xx.com -p 9999 -U expl
psql: error: connection to server at "dbs1.xx.com" (xxx), port 9999 failed: FATAL:  no such database: expl
connection to server at "dbs1.xx.com" (xxx), port 9999 failed: FATAL:  no such database: expl
```

**Comment by eulerto** [comment]
@ToMs77130 Thanks for your feedback.
