### ISSUE TITLE
ulimit is no longer observed

### ISSUE THREAD

**Issue by horriblyUnpythonic** [pgbouncer/pgbouncer#729]
Sometime between 1.12.0 and 1.17.0 (probably 1.13.0) the file `pgbouncer.service` was included, which is preferred over the previous file (`/etc/init.d/pgbouncer`). With this inclusion the `NOFILES` entry shown by `prlimit` for the pgbouncer process is set to 1024/4096 instead of what we had/have set in `/etc/default/pgbouncer`.
Is there a new place that defaults should go?
Changing `LimitNOFILES=` it in the `.service` file seems to correct the issue, but I worry that that will need to be done after each pgbouncer upgrade.
We are running on Debian 9.

**Comment by petere** [comment]
This is a packaging issue. PgBouncer only provides a sample `pgbouncer.service` file but does not install it. You should check with the packager of whatever you are using about how to set this up or whether any changes were adequately documented.
