### ISSUE TITLE
pgbouncer Not Respecting host Directive

### ISSUE THREAD

**Issue by daBee** [pgbouncer/pgbouncer#735]
I have a db server and my workstation.  `pgbouncer` is installed on my workstation already for domestic db management, and I wanted to use the same instance to reach into the db server as well.  I've used the following in the conf for `databases`:
```
mydbname = host=192.168.1.23 port=5432 dbname=dbname user=user1 password=secretpassword
```
I try entering using `psql`:
```
psql -h localhost -p 6432 -U user1 mydbname
```
Upon looking at the available viewable databases and tables, it seems I'm looking at my local databases/tables and not that of the remote db server.  I've seen this happen in another client as well.  

It somehow logs into my tables locally with a remote password for my `psql` user.  I'm not sure how to configure this any differently.

**Comment by daBee** [comment]
Never mind.  Functioning properly.  Client bug.

**Comment by daBee** [comment]
It's happening in `psql` as well as another client.  So it is changing to localhost when I use `\c dbname2`.  When I use that statement, I want to change to a database on the remote server, not jump to `localhost`.  In fact that's a security issue.

**Comment by petere** [comment]
Please provide a reproducible test case with full configuration, version numbers, exact sequence of commands, and all outputs.

**Comment by daBee** [comment]
Let me know if this is sufficient.

**pgbouncer.ini**
```
[databases]
user1 = host=localhost port=5432 dbname=user1
server_n = host=192.168.1.23 port=5432 dbname=user1 user=user1 password=mypassword

[users]
user1 = pool_mode=transaction max_user_connections=16

listen_addr = 192.168.1.4, localhost
listen_port = 6432
auth_type = md5
auth_file = /opt/homebrew/etc/userlist.txt
min_pool_size = 2
```

**userlist.txt**
```
"user1" "qugppGHmVQHU"    # workstation password
"user1" "mypassword"    # db server password
```

```
$ pgbouncer --version
PgBouncer 1.17.0
libevent 2.1.12-stable
adns: evdns2
tls: OpenSSL 1.1.1p  21 Jun 2022
```
`Mac OS Monterey 12.4`

**commands and outputs**
```
psql -h localhost -p 6432 -U user1 mydbname

psql -w -h localhost -p 6432 -U user1 mydbname
psql -h localhost -p 6432 -U user1 server_nr	# pgbouncer pointing to remote db server
<mypassword>
(2 rows)        # proper remote db server tables
\c mydbname     # this database has the same name on my workstation
(109 rows)      # showing workstation tables in the database with same name
```

**Comment by daBee** [comment]
Upon further testing, I have found the following:

- Comments interrupt and/or confuse the parsing of `userlist.txt` `user`/`password` combinations.
- The order of duplicate users is important, the system taking the last entry as the single password for that duplicate user. (i.e. fred / billabong and fred / waterfall are listed for different passwords on different postgres servers).  I moved the pertinent password to the bottom to have it remembered, and it worked.  But now I can't reach the other server with the same user.

**Comment by petere** [comment]
> Upon further testing, I have found the following:
> 
> * Comments interrupt and/or confuse the parsing of `userlist.txt` `user`/`password` combinations.
> * The order of duplicate users is important, the system taking the last entry as the single password for that duplicate user. (i.e. fred / billabong and fred / waterfall are listed for different passwords on different postgres servers).  I moved the pertinent password to the bottom to have it remembered, and it worked.  But now I can't reach the other server with the same user.

There is no such thing as one user having multiple passwords. So whatever it is you are trying to set up, this isn't the way to do it.

**Comment by daBee** [comment]
A single user on a LAN would supposedly be using their username on multiple databases using perhaps a single `pgbouncer`, which could reach into any db server.  

-h alpha.local -U user1 dbname1
-h localhost -U user1 dbname1

`psql -h localhost -p 6432 -U user1 server_nr	# pgbouncer pointing to remote db server`

Sorry, that comment is wrong.  I'm just trying to demonstrate I have different passwords for same db names on different servers.  Getting into one, then using `\c otherdbname` can get me into other tables.  Unfortunately one of my boxes is down right now so I'm not sure if I could syntax it and post at the moment.

**Comment by eulerto** [comment]
Having not received a reply, closed.
