### ISSUE TITLE
Handle URL encoded password's and db names in connection string

### ISSUE THREAD

**Issue by DanielLund** [pgbouncer/pgbouncer#737]
Currently trying to connect to pgbouncer via prisma. Currently the db password is URL encoded, for the db connection string to work. However putting this in the userlist.txt won't work as it will try to use the url encoded password to connect to the actual db which results in an auth error. 

Just wondering how to handle this or to raise it as a potential future enhancement

**Comment by petere** [comment]
What is prisma, and why is it forcing you to use URL-encoded passwords?

**Comment by petere** [comment]
Presumably, prisma would connect to pgbouncer, so you can continue to use whatever connection string format you are using. The configuration inside pgbouncer is how that connection then goes on to the real PostgreSQL server, which is separate and doesn't (necessarily) use the same password.

**Comment by DanielLund** [comment]
Yeah but I feel that's where the problem lies as in userlist.txt we have "postgres" "url encoded pw" for it to verify the prisma db connection string which also has url encoded pw `postgresql://postgres:urlencodedpw@host:6432/pgbouncerdb`

However when pgbouncer uses that password we get auth error as i assume it is using that url encoded pw

**Comment by petere** [comment]
Yes, then you need to not-url-encode that password when you put it into userlist.txt.

**Comment by DanielLund** [comment]
Okay, well I look stupid now hahaha. So that will be still match even if the one in the db url is url encoded?

**Comment by DanielLund** [comment]
Yeah I certainly do look stupid, I guess I was confused with how the userlist works and also assumed wrong about when prisma decodes the url, thanks so much for your help as it is now working @petere
