### ISSUE TITLE
peer-authentication warning due to forced admin user

### ISSUE THREAD

**Issue by scorpevans** [pgbouncer/pgbouncer#740]
It seems that when Peer authentication is made with an admin user, other than `pgbouncer`, a warning is emitted to pgbouncer log as follows:
```
WARNING C-0x564393bb07a0: pgbouncer/not-pgbouncer-user@unix(1459):1234 pooler error: unix socket login rejected
```

The reason, it seems, is that the client user is forced back to `pgbouncer` (for admin logins/pool) such that the peer authentication is broken; when the authentication is changed to Trust, the warning stops.

```
$ pgbouncer --version
PgBouncer 1.17.0
libevent 2.1.11-stable
adns: c-ares 1.17.1
tls: OpenSSL 1.1.1k  25 Mar 2021
```

**Comment by petere** [comment]
Please provide complete commands and configuration file to allow reproducing this.

**Comment by scorpevans** [comment]
Hi @petere 

This was a sloppy report; please excuse me.
I believe a rogue user is actually being reject; I've tried `log_disconnections` and `verbose=2` to get some pointers but it's not too obvious from the structure of the log, which user to blame. In any case, there no issue here.
