### ISSUE TITLE
Set role and schema on connection

### ISSUE THREAD

**Issue by mgjv** [pgbouncer/pgbouncer#75]
As part of a project to consolidate a large number of postgres database servers into a much smaller multi-tenanted set, we're looking at switching from per-tenant users and databases to a single database and user with per-tenant schemas and roles. We still want some cross-schema select protection, hence the roles per schema (with a 'super role' that can use SET role).

As part of that, we would like to leave the application alone, so it can keep authenticating the way it always did, and on connection server-side (i.e. pgbouncer) map credentials to a schema and a role, followed by a SET SCHEMA and SET ROLE and a SET SCHEMA public and RESET ROLE on disconnect.

I've been fiddling a bit with pgbouncer, and have sort of concluded that I cannot do this during the authentication step, as the return packets need to be processed, and I cannot find where that would be. I _think_ that what I need to do is put the connection in a particular (new) state, and on first query do the set role/schema.

I have some questions (@markokr)  : 
1. If a feature like this were to be implemented would it likely to be acceptable back into the main project? Or would we have to maintain a fork going forward?
2. Is my conclusion that this cannot be done during the authentication cycle correct, or am I missing something that should be obvious?
3. If I am correct in 2, is the idea of adding a state to the connection to manage this the best approach?

Thanks,
Martien

**Comment by markokr** [comment]
SET SCHEMA will not work as well as you hope, see discussion here: #73

It seems much simpler and robust setup if you give each tenant separate db user, with ALTER USER x SET SCHEMA ..;

**Comment by markokr** [comment]
Oh, you already have db roles?  Then why do you want to shuffle different roles via same connection?

**Comment by mgjv** [comment]
Thanks for the pointer to #73. It shows me that what we think we need is probably never going to be supported by pgbouncer :)

Giving each tenant a separate db user means that we cannot profit very much of connection pooling across tenants (as connections cannot be shared across authenticated users, hence the SET ROLE, and perl-role search_path is not enacted on set role, hence the SET SCHEMA), and therefore we need to maintain large numbers of connections or pay the penalty of connection setup more frequently than we want to.

I understand your objections, and the argument about the fragility of this in a general sense. We'll have to decide whether we want to take this on ourselves (in a more specific controlled environment), whether we modify our applications, whether we deal with the large number of connections, or whether we find some other compromise.

I'll have a look at the pull request in #73 anyway.

Thank you,
Martien

**Comment by markokr** [comment]
Closing.
