### ISSUE TITLE
cannot start pgbouncer and with no errors messages

### ISSUE THREAD

**Issue by solo-xwz** [pgbouncer/pgbouncer#755]
os:centos 7
install method:yum

I use : `pgbouncer -d /etc/pgbouncer/pgbouncer.ini` or `systemctl start pgbouncer` commands to start.
but when  use the `netstat -tulpn` command to check, i found port 6432 is not listening,
and no any error messages or error logs.

thanks for help

**Comment by petere** [comment]
Try starting without `-d` and read the log output when it starts.

**Comment by solo-xwz** [comment]
> Try starting without `-d` and read the log output when it starts.

thank you!got it.
it was permission issue with pgbouncer.log
