### ISSUE TITLE
PGBouncer doesn't handle SIGKILL signal

### ISSUE THREAD

**Issue by AlexBurkey** [pgbouncer/pgbouncer#763]
I'm running pgbouncer as a separate service in k8s with auto-deployments. K8s sends a SIGKILL by default to terminate containers and then a SIGTERM. 

PGBouncer apparently doesn't handle SIGKILL at all so the containers end up being killed. Ideally I could send a SIGINT to let the container shutdown gracefully but the signals sent aren't configurable. Ideally PGBouncer could handle a SIGKILL in a similar manner to how it handles SIGINT.

**Comment by petere** [comment]
There must be some confusion here. It is not possible for a process to "handle" SIGKILL.

**Comment by AlexBurkey** [comment]
oop I apologize. It's been a long on-call week and I got my signals mixed up. I'll close this issue
