### ISSUE TITLE
Make website configuration examples reflect stable not development version of pgbouncer

### ISSUE THREAD

**Issue by sammcj** [pgbouncer/pgbouncer#77]
Currently it seems the https://pgbouncer.github.io/config.html page reflects options for the development version of pgbouncer.

This causes issues when people use it as the source of documentation, which it appears to be.

I just wasted time trying to figure out why auth_type = 'hba' wasn't working then found #70

**Comment by markokr** [comment]
The problem is that stable version docs are not usable for website.  In short term it seems easier to apply "Since 1.x" tags to options.

**Comment by sammcj** [comment]
@markokr yes that could work, so for `auth_type = hba` it could state 'Available from version 1.7 and newer'

Before I submit a PR, can I confirm that the next version of pgbouncer (that will support auth_type = hba) will be version 1.7.x?

**Comment by markokr** [comment]
Yes, 1.7.
