### ISSUE TITLE
Deployment on Heroku: add options to handle SIGTERM

### ISSUE THREAD

**Issue by PetrDlouhy** [pgbouncer/pgbouncer#770]
I am using PGBouncer on Heroku in Docker container along with Gunicorn/Nginx/Supervisor.

When Heroku scales down it first sends SIGTERM to all processes in the container and after 30 seconds it sends SIGKILL. I don't think, that I can change this behavior.

The problem is, that at the time of SIGTERM being send, there are still requests being processed. I am receiving following error during scaledown event:
```
TransactionManagementError
An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```
It happens because PGBouncer gets terminated before the remaining requests finish being processed.

I wonder if there could be added (or is) any possibility to block/redirect SIGTERM (and let it wait for the SIGKILL or let me terminate it by other process) or add some waiting time before PGBouncer shutdown.

**Comment by PetrDlouhy** [comment]
Just if anyone is searching for workaround solution, I solved this by patching PGBouncer and compiling from source:
```shell
curl -L https://github.com/pgbouncer/pgbouncer/releases/download/pgbouncer_1_17_0/pgbouncer-1.17.0.tar.gz -o pgbouncer.tar.gz \                                                       
tar -xvzf pgbouncer.tar.gz \                                                                                                                                                         
cd pgbouncer-1.17.0 \                                                                                                                                                                
sed -i "s/got SIGTERM, fast exit/got SIGTERM, do nothing/" src/main.c \                                                                                                              
sed -i "s/\texit(1);$//g" src/main.c \                                                                                                                                                
./configure \                                                                                                                                                                        
make \                                                                                                                                                                               
make install
```

**Comment by petere** [comment]
You should use the `SIGINT` signal for gentle shutdown.

**Comment by PetrDlouhy** [comment]
@petere I just can't. It is not possible to change the shutdown process on Heroku.

**Comment by aaabramov** [comment]
> @petere I just can't. It is not possible to change the shutdown process on Heroku.

How about changing the root process to Dockerfile that handles SIGTERM and sends SIGINT to pgbouncer?

**Comment by PetrDlouhy** [comment]
Unfortunately Heroku sends SIGTERM to ALL processes in the Docker container.

I sent them an ticket about this, but so far they are refusing to make any change. I am trying to convince them to change this behavior, but I not giving it much change of success.

**Comment by eulerto** [comment]
As @JelteF said in [this comment](https://github.com/pgbouncer/pgbouncer/pull/806#issuecomment-1422266265), I don't think providing a PgBouncer is the right solution. The service manager has to provide an option for such cases.

**Comment by PetrDlouhy** [comment]
@eulerto I don't understand your comment entirely, but are you saying that adding an config option to PgBouncer to ignore SIGTERM is not an option for it's maintainers?

I don't think there is another solution than the desperate workaround above.
I just don't have the power to convince Heroku to change the sent signal.
