### ISSUE TITLE
pgbouncer crashes (core dump) with scram-sha-256 in user-list.txt

### ISSUE THREAD

**Issue by mrechte** [pgbouncer/pgbouncer#773]
Hello,

I set only one password in user-lists.txt for the only admin_users I have. I encoded the password in scram-sha-256.
Other users are identified by auth_query / auth_user (scram-sha-256).

I can connect OK to the pgbouncer database with the admin user, however if I use that same user trying to connect to an in-existent database, I get a pgbouncer crash.

This only happens with scram-sha-256. Using md5 does not produce this error.

$ pgbouncer --version
PgBouncer 1.17.0
libevent 2.1.8-stable
adns: evdns2
tls: OpenSSL 1.1.1k  FIPS 25 Mar 2021
systemd: yes

**Comment by goksgie** [comment]
If applicable and possible, can you create a backtrace which should help community members with the analysis.

**Comment by petere** [comment]
This looks like #730. Can you check if that fixes it?

**Comment by mrechte** [comment]
OK, I replaced pgbouncer from a fresh complied from git: the issue is gone.
