### ISSUE TITLE
Support for protocol level prepared statements

### ISSUE THREAD

**Issue by jayant07-yb** [pgbouncer/pgbouncer#777]
A prepared statement is a server-side object that can be used to optimise performance. When the PREPARE statement is executed, the specified statement is parsed, analysed, and rewritten. When an EXECUTE command is subsequently issued, the prepared statement is planned and executed.

Prepare statements can be used in two ways:-
1. statement (used in `simple Query protocol`)
2. Protocol-level prepared statements `Extended Query Protocol` 

A lot of client-side drivers use Protocol level prepared statements for enhancing performance which is blocked due to limited support for PgBouncer for Protocol Level Prepared Statements. 
Support for the ` protocol level prepared statement` can be provided. I have worked on an experimental code for the same, one can find it at https://github.com/jayant07-yb/pgbouncer/tree/prepstmt 
I was willing to discuss my approach and required further assistance in improving the design.

**Comment by eulerto** [comment]
This feature was already included at commit 60708022d5b934fa53c51849b9f02d87a7881b11.
