### ISSUE TITLE
pgbouncer forwards different SQLState code than PostgreSQL if database does not exist

### ISSUE THREAD

**Issue by sleepy-manul** [pgbouncer/pgbouncer#778]
We have a development environment where lots of PostgreSQL databases are created and dropped all day long, e.g.

```
somedb_branch_PRODUCT-5875
somedb_branch_PRODUCT-6897
somedb_branch_PRODUCT-8292
```

etc. To accommodate this, I set up pgBouncer like this:

``` 
[databases]
*=host=fqdn.of.our.postgresql.instance port=5432

[pgbouncer]
listen_port=6432
listen_addr=0.0.0.0
auth_file=/opt/bitnami/pgbouncer/conf/userlist.txt
auth_type=plain
pidfile=/opt/bitnami/pgbouncer/tmp/pgbouncer.pid
logfile=/opt/bitnami/pgbouncer/logs/pgbouncer.log
admin_users=admin@user-name-of-the-pgsql-instance
client_tls_sslmode=disable
server_tls_sslmode=verify-ca
server_tls_ca_file=/etc/ssl/certs/ca-certificates.crt
server_tls_ciphers=fast
server_tls_protocols=secure
```

The problem is that the PostgreSQL server (direct connection, without pgBouncer) returns this if the database does not exist yet:
```[3D000] FATAL: database "postgres2" does not exist.```

However, when going through pgBouncer, a different SQLState is returned:
```Npgsql.PostgresException (0x80004005): 08P01: database "postgresql2" does not exist ```
(the SQLState here is ```08P01```).

This is a problem for tools like .NET Entity Framework in connection with the npgsql driver, which relies on the SQLState to check if the database already exists. Example:
https://github.com/npgsql/efcore.pg/blob/main/src/EFCore.PG/Storage/Internal/NpgsqlDatabaseCreator.cs#L269

When ```08P01``` is returned instead of ```3D000```, the driver cannot recognise that the database does not exist yet, and thus the start of the application fails.

Due to the number of DBs and the frequency of creates/drops, it is not feasible to create the DBs manually. Also, it would require a lot of effort to change our CI/CD pipeline to create the DBs before the deployment, because our application needs several databases, and different product versions use different databases etc.

Can you change the reply that pgBouncer sends to the client so that in the case of a missing DB, SQLState ```3D000``` is sent instead of ```08P01```?

**Comment by eulerto** [comment]
PgBouncer returns [08P01](https://www.postgresql.org/docs/current/errcodes-appendix.html) that means _protocol violation_ (a connection exception). Postgres returns [3D000](https://www.postgresql.org/docs/current/errcodes-appendix.html) means _invalid catalog name_. PgBouncer uses a generic SQL state that covers all errors IMO. I don't think it is a bug but I agree that PgBouncer should mimic Postgres behavior, hence, I classify it as a feature.

**Comment by roji** [comment]
> I don't think it is a bug but I agree that PgBouncer should mimic Postgres behavior, hence, I classify it as a feature.

@eulerto can you elaborate? How is it not a bug for PgBouncer to return an incorrect SQL state which doesn't correspond to what PG returns for that same error?

**Comment by eulerto** [comment]
It has been like that for a long time and nobody complained about it. PgBouncer does not provide SQLSTATE reported by Postgres. It has been like that since day 1. That's why I said it is a new feature.
Regarding the feature, it is easy to expose the SQLSTATE, however, the function that reports an error for client will need to provide an SQLSTATE. This function (_disconnect_client_) has ~ 70 calls that need an SQLSTATE. I will post a patch when I finish it.

**Comment by sleepy-manul** [comment]
Hi @roji and @eulerto - just a quick reminder, it was not my intention to pin your two projects against each other. Both of you make great, high-quality software. I just linked the two issues to prevent a situation where the problem is fixed in 0/2 or 2/2 components.

**Comment by roji** [comment]
Thanks for the clarification @eulerto.

**Comment by eulerto** [comment]
@sleepy-manul @roji Could you verify if the proposed patch works for you? I added an additional NOISE message (to report the SQLSTATE in the log) just to help during tests that I'm planning to remove before commit.

**Comment by roji** [comment]
@eulerto I'll try to do that in the coming days, thanks.

**Comment by roji** [comment]
Apologies for not answering on this before... I did try to build pgbouncer with the patch a couple of months ago and ran into some difficulties - and I don't have enough time at the moment to look into it.

If this patch makes pgbouncer error with 3D000 instead of 08P01 when the database doesn't exist, then that fix should be perfect for the .NET provider - if anyone else can help with the confirmation that would be great...

**Comment by pirimoglu** [comment]
> Apologies for not answering on this before... I did try to build pgbouncer with the patch a couple of months ago and ran into some difficulties - and I don't have enough time at the moment to look into it.
> 
> If this patch makes pgbouncer error with 3D000 instead of 08P01 when the database doesn't exist, then that fix should be perfect for the .NET provider - if anyone else can help with the confirmation that would be great...

We encounter the same problem, we can help and test this patch

**Comment by eulerto** [comment]
@pirimoglu @Sergey-Terekhin did you try the patch referred in this issue ( #814 )?
