### ISSUE TITLE
Compilation Warnings

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [pgbouncer/pgbouncer#790]
just one warning:

src/scram.c: In function ‘build_server_final_message’:
src/scram.c:977:34: warning: ‘%s’ directive output between 0 and 2147483646 bytes may cause result to exceed ‘INT_MAX’ [-Wformat-truncation=]
  977 |         snprintf(result, len, "v=%s", server_signature);

GCC 12.x
Fedora 37 64bits

dunno where to fix the code...

**Comment by eulerto** [comment]
It is a bogus compiler warning. It is not able to detect that `server_signature` size is constrained by `len`.

https://github.com/pgbouncer/pgbouncer/blob/a84678b765f81aa17416e84c9b05fe68c6fa4849/src/scram.c#L973-L977

**Comment by ROBERT-MCDOWELL** [comment]
or maybe server_signature is not declared correctly?

**Comment by petere** [comment]
I think the problem is that the compiler thinks that `server_signature` can be very long, and that that would overflow the length of the return value of `snprintf()`, which is `int`. I can make the warning go away if I insert `assert(len < INT_MAX)`. Seems weird though.

**Comment by ROBERT-MCDOWELL** [comment]
@petere 
yeah sometimes strict mode equals obvious confirmation....
