### ISSUE TITLE
Release 1.18 not available on repositories

### ISSUE THREAD

**Issue by ToMs77130** [pgbouncer/pgbouncer#794]
Last version available on debian repositories https://apt.postgresql.org/pub/repos/apt  is 1.17.0-4, instead of 1.18.0

**Comment by eulerto** [comment]
You should direct your request to the apt team. @df7cb can provide information about it.

**Comment by df7cb** [comment]
We'll get to it. There's only 24h a day.

**Comment by ToMs77130** [comment]
OK no problem, I thought you might have forgotten as it was 9 days ago. 
Thanks.

**Comment by ToMs77130** [comment]
Hi @df7cb, sorry to ask again, do you have an approximate release date for that ?
thanks

**Comment by eulerto** [comment]
The package is already available in the repository.
