### ISSUE TITLE
creating waiting close connections

### ISSUE THREAD

**Issue by vikingUnet** [pgbouncer/pgbouncer#798]
Greetings!

When i connect from wrong user to db pgbouncer internal db it will create waiting infinity client connection.
In log file it marked with line
```
pgbouncer/(nouser)@127.0.0.1:59610 pause_client
```
How can i close automatically this paused sockets?

**Comment by eulerto** [comment]
This debug message means it does not have server connections available (small pool?) and it put this client request into a wait queue. Use `SHOW POOLS` command to understand what's going on.

**Comment by vikingUnet** [comment]
Pool is not empty, there is no queue. It is problem with only access to internal db name "pgbouncer".
Example.
```
psql -h 127.0.0.1 -p 6432 -U test_user pgbouncer
```
will produce infinity wait in console, in pool i see 
```
 database  |   user    | cl_active | cl_waiting | cl_cancel_req | sv_active | sv_idle | sv_used | sv_tested | sv_login | maxwait | maxwait_us |  pool_mode  
-----------+-----------+-----------+------------+---------------+-----------+---------+---------+-----------+----------+---------+------------+-------------
 pgbouncer | auth_user |         0 |          1 |             0 |         0 |       0 |       0 |         0 |        0 |       0 |          0 | statement
```
But if i add test_user to userlist.txt, it will change. 
Additionally I user auth_user and auth_query config parameters.

**Comment by eulerto** [comment]
[Documentation](https://www.pgbouncer.org/config.html#auth_user) says

If `auth_user` is set, then any user not specified in `auth_file` will be queried through the `auth_query` query from pg_shadow in the database, using `auth_user`. **The password of auth_user will be taken from auth_file.** (If the auth_user does not require a password then it does not need to be defined in auth_file.)
