### ISSUE TITLE
Connecting to PostgreSQL using a TLS certificate

### ISSUE THREAD

**Issue by strafer** [pgbouncer/pgbouncer#808]
Hi guys!

I am trying to set up such a connection scheme: pgbouncer (1.18.0) and postgresql (15) can accept connections with authentication using both the scram-sha-256 password and the x509 certificate, while the connection between pgbouncer and postgresql is forced over mTLS.

Postgresql has a DNS A-record like `pgsql.example.com` and the server certificate for this name, pgbouncer has a DNS A-record like `pgbouncer.example.com` and a server-client certificate for this name.

<details> 
  <summary>/etc/postgresql/postgresql.conf:</summary>

```ini
ssl = on
ssl_cert_file = '/etc/tls/pgsql.example.com/certificate.pem'
ssl_key_file  = '/etc/tls/pgsql.example.com/private.key'
ssl_ca_file   = '/etc/tls/pgsql.example.com/rootca.pem'
hba_file = '/etc/postgresql/pg_hba.conf'
```
</details>

<details> 
  <summary>/etc/postgresql/pg_hba.conf:</summary>

```ini
host       all            all                                         all          scram-sha-256
hostssl    all            all                                         all          cert
```
</details>

<details> 
  <summary>/etc/pgbouncer/pgbouncer.ini:</summary>

```ini
[databases]

* = host=pgsql.example.com port=5432 reserve_pool=5 pool_size=30


[pgbouncer]

listen_addr   = *
listen_port   = 6432
auth_type     = hba
auth_hba_file = /etc/pgbouncer/hba.conf
auth_user     = pgbouncer.example.com
auth_query    = SELECT uname, phash from pgbouncer_user_lookup($1)

client_tls_sslmode   = allow
client_tls_ciphers   = secure
client_tls_ca_file   = /etc/tls/pgbouncer.example.com/rootca.pem
client_tls_key_file  = /etc/tls/pgbouncer.example.com/private.key
client_tls_cert_file = /etc/tls/pgbouncer.example.com/cert.pem

server_tls_sslmode   = verify-full
server_tls_ciphers   = secure
server_tls_ca_file   = /etc/tls/pgbouncer.example.com/rootca.pem
server_tls_key_file  = /etc/tls/pgbouncer.example.com/private.key
server_tls_cert_file = /etc/tls/pgbouncer.example.com/cert.pem
```
</details>

<details> 
  <summary>/etc/pgbouncer/pgbouncer.ini:</summary>

```ini
hostssl    all            all                                         0.0.0.0/0          cert
host       all            all                                         0.0.0.0/0          scram-sha-256
```
</details>

As a result of this setup, password authentication works flawlessly. Connecting via certificate to postgresql directly also works fine. But if I try to connect using a certificate via pgbouncer, it behaves unexpectedly for me: after checking and accepting the user's certificate, then it connects to postgresql using the user's certificate and its **own** username to connect (i.e. `auth_user`). After that, postgresql, comparing the username and CN in the certificate, expectedly refuses to connect with the message that the names do not match.

Is this the correct behavior or is it a mistake? Is there any way I can change this so that pgbouncer uses the user name to connect?

**Comment by petere** [comment]
> Is there any way I can change this so that pgbouncer uses the user name to connect?

I think it would be helpful if your description was more precise. For example, what does "the user name" mean in that sentence?

**Comment by strafer** [comment]
> For example, what does "the user name" mean in that sentence?

This is the name of the connecting person or program, for example, it may be `some_user` with a certificate with `CN=some_user`.

Example of a connection string in this case (`verify-full` mode and the paths to the key and certificate files are set by corresponding PGSSLxxx environment variables):

```postgresql://some_user@pgbouncer.example.com:6432/some_db```

Pgbouncer checks the name with which the user `some_user` connects to it and makes sure that the name and CN match, there are no problems here, but then does not use this name to connect to postgresql, instead uses the name from its `auth_user` parameter (`pgbouncer.example.com` in my example).

A message about this in the postgresql log:

```provided user name (some_user) and authenticated user name (pgbouncer.example.com) do not match```

**Comment by JelteF** [comment]
> but then does not use this name to connect to postgresql, instead uses the name from its auth_user parameter (pgbouncer.example.com in my example).

The error message suggests something different. PgBouncer tries to connect as some_user to postgres, but it does so using its own certificate for `pgbouncer.example.com`. This makes sense, as it is the only certificate that it has access to. Postgres then does not allow pgbouncer to authenticate as this user, because the user it tries to log in as (`some_user`) and the CN of the cert (`pgbouncer.example.com`) don't match.

You'll probably want to set up `pg_ident.conf` from Postgres in such a way that `pgbouncer.example.com` can connect as every user in your database. Sadly this currently cannot be done with an `all` wildcard, and requires you to add a line to pg_ident.conf for each existing user. This will be addressed in PG16, by this patch that I submitted: https://github.com/postgres/postgres/commit/efb6f4a4f9b627b9447f5cd8e955d43a7066c30c

**Comment by strafer** [comment]
@JelteF you're right, I was conceptually wrong. I thought about it last weekend, and realized that, indeed, the pgbouncer cannot connect on behalf of the user, because it does not have the private key of the user certificate. Although it is somewhat unclear why such a scheme is even possible or does not cause a warning in the log, which immediately gave an understanding of the absurdity of the configuration.
Thank you for the proposed solution, but, as you wrote, it is not very convenient. I will probably follow the path of a secure connection between pgbouncer and postgresql (secured in another way) together with `auth_method = trust` in `pg_hba.conf` for this connection.
