### ISSUE TITLE
PgBouncer to be fips compliant

### ISSUE THREAD

**Issue by amnmtr** [pgbouncer/pgbouncer#809]
Hey guys, we are using PgBouncer 1.17.0 in our producion setup... 
Currently we are working hard to be Fedramp ready accross all of our ubuntu20 ec2 deployments.
we are transitioning our ubuntu20 images to be fedramp compliant, and we are installing pgbouncer on one of these machines.
The issue is we can't find any official documentation on pgbouncer which indicates how we can make sure it is fips compliant to align with fedramp requirements.
please help with any instructions on how we can make it so... or is that running it on a fips compliant machine is good enough ?
10x

**Comment by JelteF** [comment]
I don't know enough about FIPS compliance to know what's required for that. Sounds like you should probably hire someone with expertise in this area to advise you.

**Comment by petere** [comment]
PgBouncer uses OpenSSL, so if you have OpenSSL in FIPS mode, then it will use that. But PgBouncer also uses internal implementations of MD5, for example, which probably runs afoul of FIPS.

**Comment by amnmtr** [comment]
@petere 10x for that !!! yes we are setting up the system where pgbouncer wil with compliant fips modules (openssl as well) .... md5 is an issue but might be approved in some case .. do you know what are the use cases for this internal MD5 implemntations ? is it configurable ? and if you can point me to the part of code that does could be really helpfull as well

**Comment by petere** [comment]
It's for the "md5" authentication type.

**Comment by paulwouters** [comment]
See https://github.com/pgbouncer/pgbouncer/issues/854

Using that patch for libusual, on Fedora/RHEL/CentOS, when you put the machine into FIPS mode and set userland system wide crypto settings using "update-crypto-policies --set FIPS", pgbouncer will behave FIPS compliant

**Comment by eulerto** [comment]
Fixed by #949 .
