### ISSUE TITLE
Add systemd-tmpfiles logic for binary installation

### ISSUE THREAD

**Issue by MichaelDBA** [pgbouncer/pgbouncer#810]
systemd allows for re-creation of temp files like **/var/run/pgbouncer** upon reboot.  You just need to add a file for PGBouncer in the **/usr/lib/tmpfiles.d/** directory, **pgbouncer.conf**.  It should contain this:
`d /run/pgbouncer 0755 pgbouncer pgbouncer -`

Then when the system is rebooted, the /var/run/pgbouncer directory will automatically be restored.

**Comment by MichaelDBA** [comment]
Hmmm, didn't think of it that way. Please chime in where this kind of installation request would be the best place to state it?  Thanks in advance.

**Comment by eulerto** [comment]
Create an issue in the respective project: [Debian/Ubuntu](https://redmine.postgresql.org/projects/pgapt/issues) and [RHEL](https://redmine.postgresql.org/projects/pgrpms/issues). You need a Postgres community account. If you don't have one, [register here](https://www.postgresql.org/account/).
