### ISSUE TITLE
pgbouncer not connecting to PG 15 on AWS RDS

### ISSUE THREAD

**Issue by MichaelDBA** [pgbouncer/pgbouncer#812]
We connect fine to PG14 on AWS RDS from an EC2 instance.  We get this error when we try to do the same but with PG15:
`FATAL:  no pg_hba.conf entry for host "172.xx.xxx.xx", user "pgbouncer", database "cc_xxxx", no encryption`

**Comment by petere** [comment]
This is a an error from PostgreSQL, nothing to do with PgBouncer.

**Comment by MichaelDBA** [comment]
Well, actually it did involve PGBouncer.  Although that is a PostgreSQL error message, it pointed to the fact that SSL was turned on in the database, but turned off on PGBouncer: **server_tls_sslmode = disable**.

Anyhows, problem resolved now.  Just had to set **server_tls_sslmode = allow**.  Might want to call attention to this in the PGBouncer documentation, since the error is kinda vague in my opinion.
