### ISSUE TITLE
PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly

### ISSUE THREAD

**Issue by jrinaudo** [pgbouncer/pgbouncer#816]
Hi, I'm using the `bitnami/pgbouncer` docker image to spin up a container that sits between my Rails app and my postgres database.
Whenever I try to use the rails console to interact with my database, if I perform a database query more than 60 seconds after the last interaction with the database I get the following errors:
```
/opt/rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params': PG::ConnectionBad: PQconsumeInput() server closed the connection unexpectedly (ActiveRecord::StatementInvalid)
	This probably means the server terminated abnormally before or while processing the request.
/opt/rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params': PQconsumeInput() server closed the connection unexpectedly (PG::ConnectionBad)
	This probably means the server terminated abnormally before or while processing the request.
```

and if I try again one more time I get these:
```
/opt/rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params': PG::ConnectionBad: PQsocket() can't get socket descriptor (ActiveRecord::StatementInvalid)
/opt/rails/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params': PQsocket() can't get socket descriptor (PG::ConnectionBad)
```

These are the environment variables that I'm setting in the pgbouncer instance:
```
POSTGRESQL_USERNAME=********
POSTGRESQL_PASSWORD=********
POSTGRESQL_DATABASE=********
POSTGRESQL_HOST=********
POSTGRESQL_PORT=********
PGBOUNCER_DATABASE=db
PGBOUNCER_POOL_MODE=transaction
PGBOUNCER_EXTRA_FLAGS=--verbose
PGBOUNCER_SERVER_TLS_SSLMODE=require
PGBOUNCER_AUTH_USER=********
PGBOUNCER_AUTH_QUERY='SELECT uname, phash FROM user_lookup($1)'
PGBOUNCER_CLIENT_TLS_SSLMODE=require
PGBOUNCER_CLIENT_TLS_KEY_FILE=/opt/bitnami/pgbouncer/certs/pgbouncer.key
PGBOUNCER_CLIENT_TLS_CERT_FILE=/opt/bitnami/pgbouncer/certs/pgbouncer.crt
```

This is the configuration in my database.yml file:
```
production:
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false
  encoding: utf8
  min_messages: warning
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  reaping_frequency: 10
  timeout: 5000
  url:  <%= ENV["DATABASE_URL"] %>
```

## System configuration
Rails version: 7.0.4
Ruby version: 3.1.2
postgres version: 14
bitnami/pgbouncer tag: 1.18.0

**Comment by liveh2o** [comment]
Hey @jrinaudo, we're seeing something similar trying to get pgbouncer setup with Rails 7. Was there something specific you did to get this working? A configuration change? Code patch? Any info could help. Thanks!

**Comment by JelteF** [comment]
@liveh2o this error is very generic. It basically means that PgBouncer closed the connection or that it crashed. Could you share the  PgBouncer logs from when this error at the client side was occurring. Preferably do so by opening a new issue.

**Comment by liveh2o** [comment]
@JelteF thanks! I don't think this is an issue with PgBouncer, but with our idle timeout configs in Rails. We got this error when leaving a Rails console idle for longer than configured timeout. Everything else was working as expected. If we do find something more concrete, I'll open an issue.

Anyway, thanks for info!
