### ISSUE TITLE
No rule to make target `doc/pgbouncer.1'

### ISSUE THREAD

**Issue by doismellburning** [pgbouncer/pgbouncer#82]
Trying to build from git (6259672072c658dafdb60917d5e2e238ee210d71) based on the instructions at https://github.com/pgbouncer/pgbouncer/tree/6259672072c658dafdb60917d5e2e238ee210d71#building-from-git I hit the following:

```
$ make
make: *** No rule to make target `doc/pgbouncer.1', needed by `all'.  Stop.
```

A cheeky tweak to `Makefile` provided a short term fix:

```
 $ git diff
diff --git a/Makefile b/Makefile
index b787343..3495d1e 100644
--- a/Makefile
+++ b/Makefile
@@ -53,7 +53,7 @@ dist_doc_DATA = README.rst NEWS.rst etc/pgbouncer.ini etc/userlist.txt
 DISTCLEANFILES = config.mak config.status lib/usual/config.h config.log
 
 DIST_SUBDIRS = doc
-dist_man_MANS = doc/pgbouncer.1 doc/pgbouncer.5
+dist_man_MANS =
 
 # files in tgz
 EXTRA_DIST = AUTHORS COPYRIGHT Makefile \
```

but I'm not sure how you'd fix it "properly"

**Comment by Paxa** [comment]
I think just need to update documentation, need to add in build steps:
```
cd doc
make
cd ..
```

**Comment by markokr** [comment]
pgbouncer.1 is included in tarball.

when building from git you need rst2man tool from python-docutils

**Comment by doismellburning** [comment]
@Paxa Thanks!

Presumably there's a `Makefile` target that doesn't try to build the docs (so `rst2man` isn't a required tool); alas I'm unable to work out what it might be!

**Comment by doismellburning** [comment]
@markokr That file may be included in the tarball, but as per my link in the original description, I'm talking about building from git

**Comment by doismellburning** [comment]
Neat, cheers!
