### ISSUE TITLE
Issues with Pgbouncer v1.17 connecting to RDS Postgres Engine Version 15.XX

### ISSUE THREAD

**Issue by Avinodh** [pgbouncer/pgbouncer#843]
I have Pgbouncer v-1.17 running in my setup, which has been able to connect to RDS Postgres engine version 14 and under just fine. The pgbouncer uses the following configs:

pgbouncer.ini:

```
[databases]
db1 = port=5432 dbname=db1 pool_size=200 pool_mode=transaction host=db1.rds.amazonaws.com

[pgbouncer]
listen_addr               = 0.0.0.0
. . .
auth_type                 = md5
auth_file                 = auth_file.ini
. . .
```

auth_file.ini:

```
user1=<pwd>
```
I tried connecting to a RDS Postgres DB (engine version 15.2) using psql via the pgbouncer, but received the following error:

```
psql -h localhost -d db1 -U user1
Password for user user1:

psql: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  no pg_hba.conf entry for host "<pgbouncer_host_ip>", user "user1", database "db1", no encryption
```

However, I can directly connect to the RDS instance using psql:

```
psql -h db1.rds.amazonaws.com -d db1 -U user1
Password for user db1:

psql (14.6 (Ubuntu XXXXX), server 15.2)
WARNING: psql major version 14, server major version 15.
         Some psql features might not work.
SSL connection (protocol: TLSv1.2...)

db1=>
```

I then downloaded and deployed Pgbouncer v-1.18, and connecting to this RDS Postgres version 15.2 instance via this pgbouncer worked.

Is there a known issue with Pgbouncer v1.17 which might explain this issue? I went through the changelog of pgbouncer v1.18 as well as libpq, but could not identify anything which might explain this. Any help is appreciated!

**Comment by JelteF** [comment]
I'm pretty sure the `no encryption` part in the error is the cause. I expect RDS only allows TLS/SSL encrypted connections. Was your PgBouncer 1.17 compiled with OpenSSL support?

**Comment by whalesalad** [comment]
I am experiencing a similar issue. Went down the rabbit hole on playing with SSL but it looks like my RDS instance does not support that.

```
psql: error: connection to server at "localhost" (127.0.0.1), port 5432 failed: FATAL:  no pg_hba.conf entry for host "10.0.10.77", user "t3", database "t3", no encryption
```

I was running fine on Postgres 14.8 but recently did an upgrade to 15.2. This is also an RDS PostgreSQL instance.

**Comment by whalesalad** [comment]
Making some progress, this might actually be related to SSL.

Looking here: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.Parameters.html

Search the page for `rds.force_ssl` which is a parameter that can be modified. Looks like prior to v15 this was default of 0 or False, but going forward 15+ it is 1 or True.

After making this change (setting to 0) I am able to connect thru pgbouncer again 🎉

**Comment by JelteF** [comment]
Actually enabling TLS is definitely recommended for security reasons. You can do that by changing pgbouncer its `server_tls_sslmode` setting. The best is to also configure `server_tls_ca_file` and set it to `verify-full`.
