### ISSUE TITLE
pytest uses strict mode for asyncio without pyproject.toml in the release tarball

### ISSUE THREAD

**Issue by natrys** [pgbouncer/pgbouncer#851]
If the pyproject.toml shouldn't be in the release tarball, then I think for distro package maintainers' sake the pytest command should append `--asyncio-mode=auto` flag in the Makefile.

**Comment by JelteF** [comment]
Can you explain what exact error you get as a distro maintainer, by us putting pyproject.toml in the release tarball?

**Comment by natrys** [comment]
> Can you explain what exact error you get as a distro maintainer, by us putting pyproject.toml in the release tarball? 

I meant that the error likely happens because the pyproject.toml is *not* in the release tarball. If it's supposed to be in the release tarball, I am not seeing it in the archive (https://www.pgbouncer.org/downloads/files/1.19.0/pgbouncer-1.19.0.tar.gz)

My understanding is that without it specifying asynio-mode="auto", pytest uses its default "strict", which is causing the tests to fail (the tests do pass when I manually patch the Makefile to pass `--asyncio-mode=auto` to pytest).

**Comment by JelteF** [comment]
Ah okay, thanks for clarifying. I interpreted the other issue the exact opposite way. Indeed not including the pyproject.toml in the release tarball was an oversight. I created #852 to fix that. We plan to release 1.19.1 soonish, and we'll include it there.

**Comment by JelteF** [comment]
FYI: 1.19.1 was released yesterday and includes pyproject.toml.

**Comment by natrys** [comment]
@JelteF thanks, I was holding my PR to Void linux.
