### ISSUE TITLE
pgbouncer uses libusual with REALLY old openssl defaults from 2009

### ISSUE THREAD

**Issue by paulwouters** [pgbouncer/pgbouncer#854]
See https://github.com/libusual/libusual/pull/40

Using libusual with that PR fixes both the old settings and uses openssl modern defaults, and it adds support for system-wide crypto policies such as those that come with Fedora, RHEL, CentOS et all.

**Comment by paulwouters** [comment]
unfortunately, without the libusual PR merged in, pgbouncer is still vulnerable to using very obsolete and weak TLS parameters :(

**Comment by JelteF** [comment]
Fixed by #948
