### ISSUE TITLE
problem with logfile reopen after hup(load_config)

### ISSUE THREAD

**Issue by d-gorbachev** [pgbouncer/pgbouncer#86]
Good day,
 logfile is not reopened  after sending hup signal.
may be problem in main.c 
334  if (main_config.loaded)
335		reset_logging();
possible should use local variable loaded 
p.s.
main_config.loaded is never raised in any place of source code

**Comment by markokr** [comment]
It is set in main():
```c
        init_objects();
        load_config();
        main_config.loaded = true;
        init_caches();
        logging_prefix_cb = log_socket_prefix;
```

**Comment by d-gorbachev** [comment]
Good day,
sorry for incorrect issue
