### ISSUE TITLE
Latest version does not work after rebooting the pgbouncer server

### ISSUE THREAD

**Issue by whoistriptimahakul** [pgbouncer/pgbouncer#860]
I'm using pgbouncer with haproxy where both are installed on the same server. 
Only auth_dbname (pgbouncerdb) has the function that uses the auth_query and accessed by auth_user(details below in .ini file)

The setup works great till the pool(pgbouncer/haproxy) server is rebooted or is idle for sometime.
The only way to get it to work is to explicity make a connection using the auth_user(pgbouncer) and auth_dbname(pgbouncerdb) FIRST and then everything starts working
psql -h <pgbouncer host name> -p 6432 -U pgbouncer -Atc 'select now()' -d pgbouncerdb
otherwise , it keeps giving the error
 (nodb)/(nouser)@10.32.13.254:38062 authentication database "pgbouncerdb" is not configured.

Here is the version info
 Postgres version - 15.3
 Pgbouncer version - 1.19.0
 OS version - Red Hat Enterprise Linux release 8.7 (Ootpa)
 
 
 Pgbouncer.ini
[databases]
* = host=<haproxy hostname> port=5433 auth_user = pgbouncer auth_dbname = pgbouncerdb
[users]
[pgbouncer]
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /var/run/pgbouncer/pgbouncer.pid
listen_addr = *
listen_port = 6432
auth_type = scram-sha-256
auth_query = SELECT * FROM pgbouncer.get_auth($1)
auth_file = /etc/pgbouncer/userlist.txt
admin_users = postgres, pgbouncer
stats_users = stats, postgres, pgbouncer
pool_mode = session
server_reset_query = RESET ALL
ignore_startup_parameters = extra_float_digits
server_check_query = select 1
max_client_conn = 512
default_pool_size = 400
reserve_pool_size = 10
reserve_pool_timeout = 5
autodb_idle_timeout = 0

userlist.txt
"pgbouncer"	"SCRAM-SHA-256$4096:Ys679zksb9d64zhDAlRGLQ==$HpvJnElCWKqGQBuWfds6UruBYHbnoivauwVL/hm6fy4=:drY3imNQkmoivfS3WP61JpZcqR2W470Q/PfqLJPs0HE="

database server has two databases (fruit_dev and pgbouncerdb)

Database fruit_dev can be accessed by fruit_* users below

postgres(postgres)=> select usename,passwd from pg_shadow;
  usename  |                                                                passwd                                                                 
-----------+---------------------------------------------------------------------------------------------------------------------------------------
 postgres  | SCRAM-SHA-256$4096:awAHBLxLug2vCNGVkj91XQ==$mkzjxp2RRQMiSZS/vB45Nndvw48T5wWq+rvN+OID4vc=:N4pbALuSiVOGfn+KGNApg6DPl+29KtdSvE6sZbi4LUk=
 barman    | SCRAM-SHA-256$4096:yoVpWWzkABRCLPBno7wEUA==$Wiw0s02hnzzr+7nVBIY0NOMZ0mPXgrPCgPToVVH3HHM=:XN6bjtP2BiJqWfqKqBjnoeczVrib7LNVyTzsy16vD6I=
 pgbouncer | SCRAM-SHA-256$4096:Ys679zksb9d64zhDAlRGLQ==$HpvJnElCWKqGQBuWfds6UruBYHbnoivauwVL/hm6fy4=:drY3imNQkmoivfS3WP61JpZcqR2W470Q/PfqLJPs0HE=
 fruit_adm | SCRAM-SHA-256$4096:f48t6YV6fUeiu1UMM7XJXQ==$adqYZbIfIr9WyY6qN4Wa1jObu6qD2znC6RIJpC8BUMM=:7W3TGj47BFfs0N9lw3/1gsOaVrPjZ/4Pc0m2dQ1tijQ=
 fruit_etl | SCRAM-SHA-256$4096:66q12n2MsYR70BvGxlPzyg==$xhqAEgNfh+w++2lrRZ8JHqr/irankcZ0Dn/mohZ5ju0=:ozv7lN/TA1vwbaSkE3p9HhVCshM6K787vIpoZ1yYxqo=
 fruit_app | SCRAM-SHA-256$4096:U4B+B9E4m9nY/LYyx9UCjw==$OhsvPR32lIW6wVNWPAFFUy82NtFib/Tiu8abeji4mp0=:2g0XooR9Pe6kYtOWYoVtEn8zlJ/KzKcmwvNVK3inKac=
 fruit_ro  | SCRAM-SHA-256$4096:cq+h6Bi+tnpsPkG+hcc31A==$uUDKPi1AFvMfRrA8FqbUAARw2hCO2GtbhkCEE1bP41s=:nKxCijM2hgd143Ci0EEXPFTLqDuIQD0P8xEW2gj+aoA=
(7 rows)

connection test strings - 
1)export PGPASSWORD=<password> psql -h <pgbouncer host> -d pgbouncerdb -X -U pgbouncer  -p 6432 -c "select now();"
2)export PGPASSWORD=<password> psql -h <pgbouncer host> -d fruit_dev -X -U fruit_etl  -p 6432 -c "select * from fruit;"

**Comment by JelteF** [comment]
Can you try explicitly specifying a pgbouncerdb entry in the databases section, instead of relying on the wildcard entry `*`. That might be the issue.

**Comment by JelteF** [comment]
Also if this is a production system I would recommend rotating the passwords, because you shared the hashes in this post.

**Comment by whoistriptimahakul** [comment]
Thanks. I'm working on dev env but appreciate the comment on rotating the passwords. 
The proposed solution did not work. 
Connection test string  - export PGPASSWORD= psql -h -d fruit_dev -X -U fruit_etl -p 6432 -c "select * from fruit;" - throws this error
 6432 failed: FATAL:  SASL authentication failed

**Comment by whoistriptimahakul** [comment]
I was able to use @petere's  comment on issue#774 to resolve the issue.
https://github.com/pgbouncer/pgbouncer/issues/774#issuecomment-1305769441

The password in the userlist.txt needed to be in cleartext  for auth_user

Closing the issue
