### ISSUE TITLE
Does configure script really honour --disable-evdns?

### ISSUE THREAD

**Issue by devrimgunduz** [pgbouncer/pgbouncer#861]
Hi,

Even if I disable libevent with --disable-evdns and enable c-ares with --enable-cares, pgbouncer looks for libevent2-devel package and links with libevent :

# ldd /usr/bin/pgbouncer |grep eve
	libevent-2.1.so.7 => /lib64/libevent-2.1.so.7 (0x00007ff5e3af4000)

This is 1.19.1, but I believe this issue was there long time ago.

Here is the configure line: https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/main/common/pgbouncer/main/pgbouncer.spec;h=2b9cd6c39fc86d84638bcf51587dd9ec10e7b0e5;hb=HEAD#l66

Am I doing anything wrong?

Regards, Devrim

**Comment by JelteF** [comment]
PgBouncer still needs libevent for its eventloop, even with --disable-evdns. The only thing that --disable-evdns means is that PgBouncer won't use libevent for DNS lookups.
