### ISSUE TITLE
Incomplete instructions

### ISSUE THREAD

**Issue by davecramer** [pgbouncer/pgbouncer#862]
There are more steps than this to build pgbouncer.

https://github.com/pgbouncer/pgbouncer/blob/ff65f041660ba0551f3681965f1be25aef56b7d7/README.md?plain=1#L30

**Comment by JelteF** [comment]
If you download the release tarballs from the website or github releases those steps should be enough. If you compile from git, a little further down in the README there are steps for that too: https://github.com/pgbouncer/pgbouncer/blob/ff65f041660ba0551f3681965f1be25aef56b7d7/README.md?plain=1#L92

**Comment by davecramer** [comment]
> If you download the release tarballs from the website or github releases those steps should be enough. If you compile from git, a little further down in the README there are steps for that too:
> 
> https://github.com/pgbouncer/pgbouncer/blob/ff65f041660ba0551f3681965f1be25aef56b7d7/README.md?plain=1#L92

so it does!
