### ISSUE TITLE
Even if `bind(): Address in use`, pgbouncer will not exit normally but instead remain in an abnormal state.

### ISSUE THREAD

**Issue by cobolbaby** [pgbouncer/pgbouncer#869]
### Name and Version

1.14.0

### What do you see instead?

![2023-06-13 09-23-05屏幕截图](https://github.com/pgbouncer/pgbouncer/assets/11460848/a805c00a-ff3c-43fe-8418-ead7f2d6f730)

**Comment by JelteF** [comment]
What version of PgBouncer do you use? 1.19.1 should probably fix this issue, due to: https://github.com/pgbouncer/pgbouncer/pull/838

If not could you share your config?
