### ISSUE TITLE
pgbouncer 1.7 with SSL seems to perform worse than pgbouncer 1.6 with stunnel for SSL

### ISSUE THREAD

**Issue by diwu1989** [pgbouncer/pgbouncer#87]
is there a known performance issue with 1.7 and SSL?

**Comment by markokr** [comment]
There is known architectural issue - pgbouncer is single threaded, stunnel uses threads (afaik) so is able to use several cores for crypto load.

Does that explain it?  What kind of differences do you see?

**Comment by diwu1989** [comment]
I did some tuning and found that without stunnel, pgbouncer seems to be especially sensitive to the `sbuf_loopcnt` setting

With the default of 5, the performance was horrible, but with `sbuf_loopcnt = 0` the perf is indistinguishable from before.

When I had `stunnel`, I left this setting at default. Do you have any idea why SSL will make this setting sensitive?

**Comment by diwu1989** [comment]
jsut setting the `pkt_buf` to `4096` and leaving the sbuf_loopcnt the same also seems to inprove performance a lot

Maybe you should change the default packet buffer size to 4096?

**Comment by markokr** [comment]
I would prefer to bump pkt_buf.  sbuf_loopcnt is not a tuning parameter, rather it's there to limit extreme behaviour.

What kind of load are you using? pgbench?

**Comment by diwu1989** [comment]
I'm re-running samples of our production work load, I did try using pgbench and there wasn't any difference there. My guess would be that queries in pgbench are too synthetic.

Why is pkt_buf 2kb to begin with? Linux seems to have a 4096 default virtual memory page size, so i think it would make more sense to align to that.

**Comment by diwu1989** [comment]
I'm gonna close this issue seeing that the configuration can be changed, please do consider upping the default if it doesn't cause any issues.

Thanks
