### ISSUE TITLE
Error "client sent partial pkt in startup phase" When connecting to pgBouncer using AzureAD token

### ISSUE THREAD

**Issue by ventii** [pgbouncer/pgbouncer#874]
Hey all,

### Issue 
I am encountering an issue with Azure Postgresql Flexible server, with pgBouncer enabled.

When I try to connect using an Azure AD **user**, and access token as password, I get the following error when I try to open a connection to port 6432:

`"08P01: client sent partial pkt in startup phase"`

However everything works as expected if I provide a token of a Managed Identity, using the same connection string (username, ports etc).

It even works if I connect using a Postgresql username-password instead of authenticating using AzureAD, always using port 6432.

I only get this error when I try to connect using my personal user access token.

All combinations work if connecting to postgresql server directly on port 5432

### When using port 6432

1. AAD username 'az-sql-admins', Managed Identity token as password :white_check_mark:
2. AAD username 'az-sql-admins', Personal token as password :red_circle: - `"08P01: client sent partial pkt in startup phase"`
3. sql user, sql password :white_check_mark:

### When using port 5432

1. AAD username 'az-sql-admins', Managed Identity token as password :white_check_mark:
2. AAD username 'az-sql-admins', Personal token as password :white_check_mark:
3. sql user, sql password :white_check_mark:

it appears that the error occurs only with AAD tokens issued for my personal user. My personal user and the Managed Identity are part of the same admin group 'az-sql-admins'

### Azure Postgresql Flexible Server parameters

below are the parameters that I have currently set on the database server
![image](https://github.com/pgbouncer/pgbouncer/assets/35434284/d602acf1-aedf-4924-a1ce-16b86fefd750)

**Comment by JelteF** [comment]
I think you'll want to contact azure support for this. Because AAD integration is not part of the open source version of pgbouncer.

**Comment by ventii** [comment]
any suggestion in which repo/forum to ask this?

**Comment by JelteF** [comment]
In the azure portal you can press the question mark in the top right corner to contact support:
![image](https://github.com/pgbouncer/pgbouncer/assets/1162278/fb325efd-4a45-4dea-8a61-29caf0e56fe2)

**Comment by ventii** [comment]
Went through Microsoft QA and actually got an answer 

https://learn.microsoft.com/en-us/answers/questions/1314549/error-client-sent-partial-pkt-in-startup-phase-whe
