### ISSUE TITLE
logs: pgbouncer access from unix socket

### ISSUE THREAD

**Issue by jarojasm95** [pgbouncer/pgbouncer#883]
Hello,

I am running pgbouncer v1.19.1

This is my config file:
```
[databases]
# replaced with dummy values
xxxxxx=host=github.com port=5432 dbname=zzzzzz

[pgbouncer]
listen_port=6543
listen_addr=0.0.0.0
unix_socket_dir=/tmp/
unix_socket_mode=0777
auth_file=/opt/bitnami/pgbouncer/conf/userlist.txt
auth_type=md5
pidfile=/opt/bitnami/pgbouncer/tmp/pgbouncer.pid
logfile=/opt/bitnami/pgbouncer/logs/pgbouncer.log
admin_users=app_20210812
client_tls_sslmode=disable
server_tls_sslmode=disable
pool_mode=transaction
default_pool_size=21
min_pool_size=4
log_connections=0
log_disconnections=0
log_pooler_errors=0
log_stats=0
stats_period=60
```

I am running pgbouncer in kubernetes and using `psql` as a readiness probe, however this is causing a lot log noise such as:
```
2023-07-08 17:13:20.944 UTC [1] LOG C-0x560a9d1c05b0: (nodb)/pgbouncer@unix(992):6543 pgbouncer access from unix socket
```
even though I have configured `log_connections=0`

Is this expected? Is there an option to disable such logs?

**Comment by petere** [comment]
This message is separate from the connection logging. It appears if this situation described in the documentation is triggered:

> Admin console
> ...
> Additionally, the user name pgbouncer is allowed to log in without
> password, if the login comes via the Unix socket and the client has same
> Unix user UID as the running process.

So this is sort of a superuser override. There is currently no way to turn it off.

Do you get this message so often that it bothers you?

**Comment by JelteF** [comment]
I merged your small PR. It seemed like an oversight that this was not respecting log_connections.
