### ISSUE TITLE
not support the startup parameter search_path

### ISSUE THREAD

**Issue by wurenny** [pgbouncer/pgbouncer#89]
when i use JDBC connect to PGBOUNCER with currentSchema=...... in connection string, a exception which not support the startup parameter search_path occured
we hope the new pgbouncer can support it, thanks.

**Comment by markokr** [comment]
No, search_path is not a feature that can be emulated, for several reasons.  See #73 for some details.

You can use ignore_startup_parameters to allow such connections to pass.  Then you can use either per-role SET or several db's and connect_query to assign different path.  This is a quick&dirty fix.

Sanest way forward would be to get rid of need to play with search_path...

**Comment by spuder** [comment]
Adding this to the .ini config file fixed the issue for me

```
    ignore_startup_parameters:  search_path
```

**Comment by glosha** [comment]
And how to write two params ?
ignore_startup_parameters = extra_float_digits
ignore_startup_parameters = search_path

for skiping pooler error:   
unsupported startup parameter: extra_float_digits=2
unsupported startup parameter: search_path
