### ISSUE TITLE
what does `safe_accept(9) = Resource temporarily unavailable` mean?

### ISSUE THREAD

**Issue by alexitheodore** [pgbouncer/pgbouncer#898]
I am having performance issues ([as described here](https://stackoverflow.com/q/76717163/9819342)) that the only error-ish looking thing I have found in logs is `safe_accept(9) = Resource temporarily unavailable` and I've found no documentation on it and no answers on the internets. 

Could anyone tell me if this is something worth pursuing or if it is a meaningless notice?

**Comment by eulerto** [comment]
It is a NOISE message. We generally use it to investigate issues when you cannot run a modified version or even attach a 
debugger to PgBouncer.

Regarding `Resource temporarily unavailable`:

```
$ errno -l | grep 'Resource temp'
EAGAIN 11 Resource temporarily unavailable
EWOULDBLOCK 11 Resource temporarily unavailable
```
See `man 2 accept` and https://github.com/pgbouncer/pgbouncer/blob/27883c4f2611a275b55a789d8be1d5b53acc2487/src/pooler.c#L351-L356

I don't see evidence for a problem here. Unless you provide additional context or even better a test case to reproduce what you are observing.

BTW, it is a good practice to post a complete description here. We never know when other resources will remove the referred context (even if it duplicates information).
