### ISSUE TITLE
FATAL @src/client.c:1092 in function client_proto(): bad client state: 6

### ISSUE THREAD

**Issue by raymasson** [pgbouncer/pgbouncer#904]
Hello,

I have pgbouncer v1.19.1 in front of 10 DBs.
When I add a client that connects to one of the DBs, I start having one of the following errors and pgbouncer.service exits:
FATAL @src/client.c:1092 in function client_proto(): bad client state: 6
FATAL @src/client.c:1092 in function client_proto(): bad client state: 7

The new client (golang service)  just connects to one of the DBs through pgbouncer but does not do any queries.
The client states 6 and 7 are CL_WAITING_CANCEL and CL_ACTIVE_CANCEL. 
How can a client be in one of these states? Why could it make pgbouncer systemd service crash?
Is it just a matter of pgbouncer config (increase max_client_conn and file descriptor ulimit)?

Do you have an idea of what would cause this issue ?

Thank you very much

**Comment by raymasson** [comment]
1. It happens only on PROD unfortunately. I have the same pgbouncer config on STG and INT but it does not happen on these environments:
`[pgbouncer]
logfile = /var/log/postgresql/pgbouncer.log
pidfile = /var/run/postgresql/pgbouncer.pid
​
listen_addr = *
listen_port = 5432
​
unix_socket_dir = /var/run/postgresql
​
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt
auth_query = SELECT * FROM pgbouncer.get_auth($1)
​
admin_users = postgres
stats_users = pgbouncer
​
pool_mode = transaction
application_name_add_host = 1
​
server_reset_query = DISCARD ALL
​
max_client_conn = 500
default_pool_size = 20
min_pool_size = 0
reserve_pool_size = 5
reserve_pool_timeout = 5.0
server_idle_timeout = 30
dns_max_ttl = 15.0
dns_zone_check_period = 0
dns_nxdomain_ttl = 15.0
​
client_tls_key_file = /etc/vpcloud/certs/sa-patroni-main-eufh-fr1.prd.ops.vptech.eu_key.pem
client_tls_cert_file = /etc/vpcloud/certs/sa-patroni-main-eufh-fr1.prd.ops.vptech.eu_crt.pem
client_tls_sslmode = require
client_tls_protocols = secure
client_tls_ciphers = fast
server_tls_sslmode = verify-full
server_tls_ca_file = /etc/ssl/certs/ca-certificates.crt
server_tls_protocols = secure
server_tls_ciphers = fast
​
ignore_startup_parameters = extra_float_digits,statement_timeout
​
%include /etc/pgbouncer/pgbouncer.database.ini`

Recently a new DB has been added on all environments and an app Golang that connects to this new DB was also deployed on all envs.
Since then, pgbouncer service systemd started to crash on PROD only and only during business hours. No crash during the week-end for example. It make me think that it is related to the traffic we have on PROD because it does not crash on test envs and nor did it on PROD during the week-end. 
I have uninstalled on PROD the new app that connects to the new database and pgbouncer does not crash anymore.

2. It is kind of hard to reproduce as it happens only on PROD
3. Here are more logs:
`Jul 21 13:10:54 sa-patroni-main-eufh-fr1.prd.ops.vptech.eu pgbouncer[15255]: S-0x55a94c06df40: supplier_return/admin_sa@10.152.9.15:5431 new connection to server (from 10.152.9.15:59362)
Jul 21 13:10:54 sa-patroni-main-eufh-fr1.prd.ops.vptech.eu pgbouncer[15255]: started sending cancel request
Jul 21 13:10:54 sa-patroni-main-eufh-fr1.prd.ops.vptech.eu pgbouncer[15255]: C-0x55a94d174310: supplier_return/(nouser)@10.152.28.193:19056 closing because: client unexpected eof (age=0s)
Jul 21 13:10:54 sa-patroni-main-eufh-fr1.prd.ops.vptech.eu pgbouncer[15255]: @src/client.c:1092 in function client_proto(): bad client state: 7
Jul 21 13:10:54 sa-patroni-main-eufh-fr1.prd.ops.vptech.eu systemd[1]: pgbouncer.service: Main process exited, code=exited, status=1/FAILURE
Jul 21 13:10:54 sa-patroni-main-eufh-fr1.prd.ops.vptech.eu systemd[1]: pgbouncer.service: Failed with result 'exit-code'.
Jul 21 13:27:06 sa-patroni-main-eufh-fr1.prd.ops.vptech.eu systemd[1]: Starting connection pooler for PostgreSQL...
Jul 21 13:27:06 sa-patroni-main-eufh-fr1.prd.ops.vptech.eu pgbouncer[2293]: kernel file descriptor limit: 1024 (hard: 524288); max_client_conn: 500, max expected fd use: 712
Jul 21 13:27:06 sa-patroni-main-eufh-fr1.prd.ops.vptech.eu pgbouncer[2293]: listening on 0.0.0.0:5432
Jul 21 13:27:06 sa-patroni-main-eufh-fr1.prd.ops.vptech.eu pgbouncer[2293]: listening on [::]:5432`

`Jul 21 06:17:27 sa-patroni-main-eufh-fr1 pgbouncer[25114]: S-0x556f382cee80: importer/admin_sa@10.152.9.15:5431 new connection to server (from 10.152.9.15:32990)
Jul 21 06:17:27 sa-patroni-main-eufh-fr1 pgbouncer[25114]: S-0x556f382cee80: importer/admin_sa@10.152.9.15:5431 SSL established: TLSv1.3/TLS_AES_256_GCM_SHA384/ECDH=prime256v1
Jul 21 06:17:29 sa-patroni-main-eufh-fr1 pgbouncer[25114]: C-0x556f37231cc0: pgbouncer/pgbouncer@127.0.0.1:42144 login attempt: db=pgbouncer user=pgbouncer tls=TLSv1.3/TLS_AES_256_GCM_SHA384
Jul 21 06:17:29 sa-patroni-main-eufh-fr1 pgbouncer[25114]: C-0x556f37231cc0: pgbouncer/pgbouncer@127.0.0.1:42144 closing because: client close request (age=0s)
Jul 21 06:17:31 sa-patroni-main-eufh-fr1 pgbouncer[25114]: @src/client.c:1092 in function client_proto(): bad client state: 6
Jul 21 06:17:31 sa-patroni-main-eufh-fr1 patroni[7992]: 2023-07-21 06:17:31.487 UTC [3973] LOG:  could not receive data from client: Connection reset by peer
Jul 21 06:17:31 sa-patroni-main-eufh-fr1 systemd[1]: pgbouncer.service: Main process exited, code=exited, status=1/FAILURE
Jul 21 06:17:31 sa-patroni-main-eufh-fr1 patroni[7992]: 2023-07-21 06:17:31.487 UTC [3972] LOG:  could not receive data from client: Connection reset by peer
Jul 21 06:17:31 sa-patroni-main-eufh-fr1 systemd[1]: pgbouncer.service: Failed with result 'exit-code'.
Jul 21 06:17:31 sa-patroni-main-eufh-fr1 patroni[7992]: 2023-07-21 06:17:31.487 UTC [3971] LOG:  could not receive data from client: Connection reset by peer
Jul 21 06:17:31 sa-patroni-main-eufh-fr1 patroni[7992]: 2023-07-21 06:17:31.487 UTC [3970] LOG:  could not receive data from client: Connection reset by peer
Jul 21 06:17:31 sa-patroni-main-eufh-fr1 patroni[7992]: 2023-07-21 06:17:31.487 UTC [3876] LOG:  could not receive data from client: Connection reset by peer
Jul 21 06:17:31 sa-patroni-main-eufh-fr1 patroni[7992]: 2023-07-21 06:17:31.487 UTC [3877] LOG:  could not receive data from client: Connection reset by peer`

4. I will try simulating traffic on STAGING and see if I can reproduce the issue. Then, I will increase the logs verbosity to have more insight.

Thank you

**Comment by JelteF** [comment]
thanks for the report @tnt-dev. This is another issue than the one reported by @raymasson. I created a PR to fix it in #927. For the issue created by @raymasson I still don't know the exact cause or right fix.

**Comment by JelteF** [comment]
> For the issue created by @raymasson I still don't know the exact cause or right fix.

Actually I think I figured out what's happening and also how to correctly fix it. I'll try to reproduce tomorrow with a small Go program and confirm that the fix I have in mind works.

**Comment by JelteF** [comment]
@tnt-dev @raymasson I merged both fixes. Feel free to try out the current master branch to confirm that it resolves the issue for you.
