### ISSUE TITLE
Disable logging to syslog

### ISSUE THREAD

**Issue by lampaczcz** [pgbouncer/pgbouncer#906]
Hello,

version  1.17.0 with following config, still log to syslog.
OS is Debian 11 with systemd

;; Syslog settings
syslog = 0
;syslog_facility = daemon
;syslog_ident = pgbouncer

;; log if client connects or server connection is made
log_connections = 0

;; log if and why connection was closed
log_disconnections = 0

;; log error messages pooler sends to clients
;log_pooler_errors = 1

;; write aggregated stats into log
;log_stats = 1

;; Logging verbosity.  Same as -v switch on command line.
verbose = 0

**Comment by eulerto** [comment]
This is **not** a bug. That's a systemd configuration. Debian forwards all journal messages to `syslog` by default. Read `man 5 journald.conf`.

If you want to disable it, edit `/etc/systemd/journald.conf` and change `ForwardToSyslog` to `no`. Restart the service `systemd-journald` service.
