### ISSUE TITLE
default_pool_size per user

### ISSUE THREAD

**Issue by mfur** [pgbouncer/pgbouncer#911]
We are using pgBouncer in multitenant environment where each customer (1000+) uses dedicated DB user.
pgBouncer with transaction pooling enables such approach with tiny user pools (2-3).

However issue is that there are also system/backend DB users which should have larger pool size (~20). Currently it is impossible to configure pool size per user, so we need to run multiple pgBouncer instances to solve that.

If [users] section would support default_pool_size, just single instance would suffice.

**Comment by JelteF** [comment]
That indeed sounds useful. Instead of `default_pool_size` it would be best if we call it `pool_size` though (just like it's called in the `[databases]` section. Feel free to open a PR for this.

**Comment by rgrellmann** [comment]
While having a pool_size in [users] would be nice and straightforward, you can very simply use a database alias, you do not need a second pgbouncer instance. Like this:
`[databases]
db1 = host=... dbname=db1 pool_size=3
db2 = host=... dbname=db1 pool_size=20`
Then just connect to db2 with those users who should have a larger pool.

**Comment by mfur** [comment]
Thank you, that is excellent workaround! Not sure how I missed that. Already applied on dev systems and it works nice.

Now only if there exists similar workaround for #910  ...
