### ISSUE TITLE
pgbouncer.spec systemd problem

### ISSUE THREAD

**Issue by bilsch** [pgbouncer/pgbouncer#92]
Hi,

We have built an internal rpm spec for pgbouncer 1.7rc1 and found an issue with the logic of the rpm spec file. Not sure if this is the right audience for the issue or if we should ping the postgres guys.

lines [73-81](http://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/9.4/pgbouncer/EL-7/pgbouncer.spec;h=97629a061b64aadaaace70ec0373b94a150a076b;hb=master#l73) are configuring systemd to create [varrundir](http://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/9.4/pgbouncer/EL-7/pgbouncer.spec;h=97629a061b64aadaaace70ec0373b94a150a076b;hb=master#l80) but this is only being performed on system boot. I think this is a bit flawed in that for the package to function you have to reboot the box!

I think the right way to handle this is to either make the spec file post create the directory or somehow tell systemd service to make the directory prior to starting the service.

**Comment by markokr** [comment]
You could send mail to devrim@gunduz.org directly, but he should be reading pgbouncer-general mailing list too.
