### ISSUE TITLE
PID in /var/run/pgbouncer has disappeared

### ISSUE THREAD

**Issue by blackwidowst** [pgbouncer/pgbouncer#936]
Two weeks ago, the PID file in /var/run stopped generating when rebooting the server.  It worked fine up until then and no changes were made.  The operating system is Centos 7.

Is there a way to get the PID file to start generating again in /var/run?

Thanks.

**Comment by eulerto** [comment]
Are you rebooting the server or the PgBouncer service? Could you share your configuration file (`pgbouncer.ini`)? Did you check if the user that is running the service has write permission in the directory that contains the `pidfile`? Did you check the PgBouncer logs to see if it provides a hint?

**Comment by blackwidowst** [comment]
Are you rebooting the server or the PgBouncer service? Reboot.  
Could you share your configuration file (pgbouncer.ini)? It's quite large - were there certain parameters?
Did you check if the user that is running the service has write permission in the directory that contains the pidfile? That is the thing, it was in /var/run/pgbouncer (which is actually /run/pgbouncer) and up until 2 weeks ago, the pid file would be created there.  The permissions for that directory are root:root so the username that runs the service does not have write permission, at least now it doesn't.
Did you check the PgBouncer logs to see if it provides a hint? I didn't see anything in particular but it is due to reboot this Thursday so I'll look then.
The DBA has worked around the issue by creating a new directory to write the PID to.  I just don't know why it would stop working the previous way two weeks ago.  The items in /var/run are deleted/recreated every reboot so I am not sure how it ever worked with permissions of root:root or how those permissions got changed.

**Comment by JelteF** [comment]
Are you using systemd to run PgBouncer? Maybe the `pgbouncer.service` file changed in your OS.

**Comment by blackwidowst** [comment]
I didn't originally install the pgbouncer but when I checked there was no pgbouncer.service.  I am not sure if that is supposed to generate automatically during an install.  I wasn't able to find, so far, what the content of that file should be but I am still looking.

**Comment by JelteF** [comment]
I mean how do you start pgbouncer? `systemctl start pgbouncer`? If so, SystemD uses service files provided by the packager. They might have modified their one.

**Comment by blackwidowst** [comment]
Yes, there is a systemd file for pgbounce now but there wasn't before.  systemctl start pgbouncer does start it up but it is not starting up automatically during reboot.  Trying to troubleshoot that now - thanks!
