### ISSUE TITLE
 no such database error

### ISSUE THREAD

**Issue by akshathaerappa** [pgbouncer/pgbouncer#937]
I have deployed pgbouncer in k8s. Exposed it as a nodeport service.  When I test the pgbouncer connection using `psql -h external-pgbouncer-ip -p nodeport -U username ` this works for the default username postgres and dbname postgres . But when I try and connect to any other database say db_test and username postgres it says `psql: error: connection to server at "external-pgbouncer-ip", port nodeport failed: FATAL:  no such database: db_test`

**Comment by JelteF** [comment]
Can you share your PgBouncer config?

**Comment by akshathaerappa** [comment]
Both the pgbouncer and postgresql database are deployed as pod in the same namespace of the k8s cluster.

pgbouncer.ini: 
               [databases]
		db_test = host=<postgresql-service-name> port=5432 dbname=db_test user=<username>
		
		
		[pgbouncer]
		listen_addr = 0.0.0.0
		listen_port = 6432
		auth_type = md5
		auth_file = /etc/pgbouncer/auth/userlist.txt
		logfile = /var/log/pgbouncer/pgbouncer.log
		pidfile = /var/run/pgbouncer/pgbouncer.pid
		admin_users = <username>

**Comment by goksgie** [comment]
`no such database: db_test` suggests that PostgreSQL instance you're trying to connect does not have the database created. 

If we read your configuration, it basically says to PgBouncer that when it receives a connection attempt to database "db_test", it will use the specified host and the database name (dbname) to initiate a connection to the server. Hence, it is likely that your server doesn't have such database. Can you confirm that?

**Comment by akshathaerappa** [comment]
The database does exist.

**Comment by JelteF** [comment]
What do the logs of the pgbouncer process say?

**Comment by akshathaerappa** [comment]
[1] LOG C-0x55bb2cafc110: (nodb)/postgres@external-ip:62717 login attempt: db=db_test user=postgres tls=no
[1] LOG C-0x55bb2cafc110: (nodb)/postgres@external-ip:62717 login failed: db=db_test user=postgres
[1] LOG C-0x55bb2cafc110: (nodb)/postgres@external-ip:62717 closing because: no such database: db_test (age=0s)
[1] WARNING C-0x55bb2cafc110: (nodb)/postgres@external-ip:62717 pooler error: no such database: db_test
[1] LOG stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us, wait 0 us

**Comment by JelteF** [comment]
the `(nodb)` suggests that PgBouncer its config does not contain `db_test` in the databases section. Are you sure the config you shared is being loaded correctly?

**Comment by akshathaerappa** [comment]
command: psql -h external-ip-pgbouncer -p nodeport -U postgres
                  postgres=# \l
I get the databases in the list but not able to connect to any of them .
postgres=# \c db_test, gives the error

**Comment by JelteF** [comment]
Can you try:
```
psql -h external-ip-pgbouncer -p nodeport -d pgbouncer -U <admin_user>
pgbouncer=# SHOW DATABASSE
```

**Comment by akshathaerappa** [comment]
Yes when I try the above command I do not get the postgresql databases list. I can see pgbouncer and postgres(the default one of postgres DB). How do I fix this?

**Comment by JelteF** [comment]
Did you look at the startup logs? It sounds like the config that you shared isn't being loaded correctly. Another option is to run the RELOAD command.

**Comment by eulerto** [comment]
You have to check the initial log messages. If you start the service with:

```
$ pgbouncer -v /home/euler/pgb1201/etc/pgbouncer.ini 
2023-09-22 09:36:08.651 -03 [9129] DEBUG parse_ini_file: [databases]
2023-09-22 09:36:08.651 -03 [9129] DEBUG parse_ini_file: 'euler' = 'port=9915'
2023-09-22 09:36:08.651 -03 [9129] DEBUG pktbuf_dynamic(128): 0x55824d75b020
2023-09-22 09:36:08.651 -03 [9129] DEBUG parse_ini_file: 'euler' = 'port=9915' ok:1
2023-09-22 09:36:08.651 -03 [9129] DEBUG parse_ini_file: [users]
2023-09-22 09:36:08.651 -03 [9129] DEBUG parse_ini_file: [pgbouncer]
```

it will show you which databases it loads the configuration. As @JelteF said you can also check `SHOW DATABASES` command while connected to `pgbouncer` database.

**Comment by akshathaerappa** [comment]
Thanks for the responses the issue was fixed. I had passed the config via configmap, I tried with the evn variables, it worked!
