### ISSUE TITLE
Supported library, alternative to OpenSSL

### ISSUE THREAD

**Issue by anayrat** [pgbouncer/pgbouncer#951]
Hello,
I wonder if pgbouncer support other SSL libraries. 
I read this article about Haproxy https://github.com/haproxy/wiki/wiki/SSL-Libraries-Support-Status#openssl

They noticed Openssl v3 has *huge* performance regression : https://github.com/openssl/openssl/issues/17627#issuecomment-1060123659

Unfortunately, OpeenSSL v3 is shipped with latest Debian, Centos.... https://pkgs.org/search/?q=openssl

Thanks

**Comment by JelteF** [comment]
That Haproxy page seems to mostly talk about issues with QUIC (which is not something that applies to pgbouncer). The performance issues also seem to be addressed. But to answer your question: It should work with BorkingSSL and in the next release also with AWS-LC.

**Comment by rmrf-your-code** [comment]
Just to note OpenSSL3 performance we've seen has been outstanding with 3.x.x but it's got a few big fixes in 3.1.1 and 3.1.2

**Comment by JelteF** [comment]
Closing this, since it's related to a dependency of pgbouncer instead of pgbouncer itself
