### ISSUE TITLE
ignore_startup_options=options has no effect

### ISSUE THREAD

**Issue by torstenfohrer** [pgbouncer/pgbouncer#952]
Hi, i trying to get pgbouncer work with some software that  send following

![image](https://github.com/pgbouncer/pgbouncer/assets/88706020/0326b5e7-7290-4b41-bebf-b1131e0f750a)

And nothing set in ignore_startup_parameters=options,client_encoding,standard_conforming_strings will get around it.

Looking at code you try to find first -c option=value and then look if options is set in ignore_startup_parameters

_Originally posted by @torstenfohrer in https://github.com/pgbouncer/pgbouncer/issues/908#issuecomment-1738701265_

**Comment by JelteF** [comment]
I considered this case to be quite unlikely to actually happen on purpose in https://github.com/pgbouncer/pgbouncer/pull/908. So I thought throwing a error to indicate the user error would be better. 

Could you share what you're sending in the options startup parameter that fails?

**Comment by torstenfohrer** [comment]
See above application sends directly --client_encoding=utf and not -c client_encoding=utf8.

From source code (php app):

array('--client_encoding=utf8', '--standard_conforming_strings=on');

**Comment by JelteF** [comment]
Hmm, I didn't realise that was valid syntax. If you change it to the following that should solve your immediate problem.

array('-c client_encoding=utf8', '-c standard_conforming_strings=on');

But indeed postgres allows the syntax you're using, so PgBouncer should support that too.

**Comment by markkrj** [comment]
I was hit by this also.
The biggest problem was that we were not even aware of PgBouncer's version bump.
We use Azure Database for PostgreSQL integrated PgBouncer and in the last scheduled maintenance, PgBouncer was updated.
I was called on Saturday morning to check the outage on our Moodle platform (I think this is the app mentioned by @torstenfohrer). To fix it, we created an PgBouncer pod and pointed the applications to it.

Microsoft should notify customers about version changes like this one. The only notification I received was about certificate renewals.

Also @JelteF, you said that you considered this 'unlikely', but this is still a breaking change, and should have been explicitly noted as such in the release notes.

**Comment by JelteF** [comment]
To be clear this format wasn't the one I considered unlikely to be used, it was just one I did not know existed. The ones I intended to explicitly disallow, were things like `-e`. Which translates to `-c datestyle=euro`. And another one would be `-S 100MB` which translates to `-c work_mem=100MB`.

**Comment by JelteF** [comment]
I created #1064 to fix this issue btw. If you could confirm that that fixes your issue that would be helpful.
