### ISSUE TITLE
Question Regarding SCRAM-SHA-256 Password Hash Behavior in pgbouncer - potential security risk?

### ISSUE THREAD

**Issue by semabtariq1** [pgbouncer/pgbouncer#958]
Hello Team,

I'm unsure whether this is an issue or the expected behavior. Here's some version information that might be helpful:

- pgbouncer: 1.20.1
- Operating System: Ubuntu 22.04
- PostgreSQL: 15.4
- Authentication method: scram-sha-256

The issue I'm encountering is related to the password hash of my pgbouncer_user. When I query the pg_authid table to retrieve the hash, it looks like this:

```
select rolname, rolpassword from pg_authid where rolname='pgbouncer_user';

rolname     | rolpassword
----------------+---------------------------------------------------------------------------------------------------------------------------------------
 pgbouncer_user | SCRAM-SHA-256$4096:6RNXw06lGk4dVFkLLSCNcA==$bV+3dxq0mZ39bacn2HuNFFeeESMy2UQbomrxU44RGQg=:vR+C7tD5LRt/NFLdYaGtthcdpz87f3s39TK6+/1E/04=
```

And here is the corresponding entry inside my userlist.txt file:

```
"pgbouncer_user" "SCRAM-SHA-256$4096:6RNXw06lGk4dVFkLLSCNcA==$bV+3dxq0mZ39bacn2HuNFFeeESMy2UQbomrxU44RGQg=:vR+C7tD5LRt/NFLdYaGtthcdpz87f3s39TK6+/1E/04="
```
Initially, when I attempted to connect via psql, everything worked as expected:

```
postgres@primary:~$ psql -p 6432 pgbouncer_db -U pgbouncer_user
Password for user pgbouncer_user:
psql (15.4 (Ubuntu 15.4-2.pgdg22.04+1))
Type "help" for help.

pgbouncer_db=#
```

If i give wrong password
```
postgres@primary:~$ psql -p 6432 pgbouncer_db -U pgbouncer_user
Password for user pgbouncer_user: 
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.6432" failed: FATAL:  SASL authentication failed
postgres@primary:~$ 
```

However, when I changed the password hash inside userlist.txt by simply replacing the second last digit '4' with '5', restarted the pgbouncer server, and tried to connect again via psql, it still allowed me in. Here's the updated userlist.txt entry:

```
"pgbouncer_user" "SCRAM-SHA-256$4096:6RNXw06lGk4dVFkLLSCNcA==$bV+3dxq0mZ39bacn2HuNFFeeESMy2UQbomrxU44RGQg=:vR+C7tD5LRt/NFLdYaGtthcdpz87f3s39TK6+/1E/05="
```
My question is whether this behavior is expected or not. 
Your guidance on this matter would be greatly appreciated.

Thank you.

**Comment by petere** [comment]
Please show your `pgbouncer.ini` file. Maybe the `userlist.txt` file isn't actually used.

**Comment by JelteF** [comment]
It turns out you found a quirk of base64 its padding behaviour: multiple base64 strings can apparently decode to the same exact bytes.

```
❯ echo 'vR+C7tD5LRt/NFLdYaGtthcdpz87f3s39TK6+/1E/04=' | base64 -d |hexdump
0000000 1fbd ee82 f9d0 1b2d 347f dd52 a161 b6ad
0000010 1d17 3fa7 7f3b 377b 32f5 fbba 44fd 4eff
0000020

❯ echo 'vR+C7tD5LRt/NFLdYaGtthcdpz87f3s39TK6+/1E/05=' | base64 -d |hexdump
0000000 1fbd ee82 f9d0 1b2d 347f dd52 a161 b6ad
0000010 1d17 3fa7 7f3b 377b 32f5 fbba 44fd 4eff
0000020
```

So you didn't actually change anything about the keys stored in the encoded string by changing the 4 to the 5. If you change another character in the last section you'll see that authentication does indeed fail.
