### ISSUE TITLE
Why are BEGIN; and COMMIT; statements counted into STATS?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [pgbouncer/pgbouncer#959]
Hi, I have noticed something really odd with the STATS. Especially the `total_query_count` and `avg_query_time `.

If I connect a single psql instance to a fresh pgbouncer installation I see this behaviour, which is very unexpected to me:

`psql -U my_user -p 6432 -d my_db`:

And then run:

```sql
BEGIN; SELECT pg_sleep(10); COMMIT;
```

In pgbouncer it will result in the following:

```
pgbouncer=# show stats;
 
-[ RECORD 1 ]-----+--------------------------------
database          | my_db
total_xact_count  | 1
total_query_count | 3
total_received    | 51
total_sent        | 142
total_xact_time   | 10024367
total_query_time  | 10024033
total_wait_time   | 23827
avg_xact_count    | 0
avg_query_count   | 0
avg_recv          | 0
avg_sent          | 2
avg_xact_time     | 10024367
avg_query_time    | 3341344
avg_wait_time     | 388
```

What clearly happens is, that this one single `SELECT` query will be tracked as 3 separate queries, because the `BEGIN;` and `COMMIT;` are also counted as "queries" and hence the `total_query_count` will say `3` and the `avg_query_time` will be totally `off` from the `10 sec` I would have expected it to show, since the two super fast `BEGIN;` and `COMMIT;` statements are also counted in.

What's the good reasoning for this? To me it seems like an unexpected behaviour. It makes it really hard to compare any STATS number with e.g. numbers monitored on the client side. 

Is this on purpose and are there any way to tell pgbouncer to not include transaction declarations in the **query** metrics?

**Comment by JelteF** [comment]
That's an interesting observation. There's not much we can do about that at the PgBouncer side. PgBouncer doesn't look at the actual queries (by design, otherwise it would need to parse SQL which is slow). So it doesn't know the difference between BEGIN/SELECT/COMMIT.  When a transaction actually write something, COMMIT can actually take some non-negligible amount of time so I'm also not convinced even if we could we would want to exclude it. 

Two workarounds that I can think of:
1. use the avg_xact_time instead of the avg_query_time
2. In your example there's no writing query so there's not really a reason to use BEGIN+COMMIT. If your application does that too, you might want to send SELECT queries outside of a transaction.

**Comment by eulerto** [comment]
[Postgres glossary](https://www.postgresql.org/docs/current/glossary.html#GLOSSARY-QUERY) says

```
Query
A request sent by a client to a backend, usually to return results or to modify data on the database.
```

However, what this counter currently does is to count the `SQL commands`. It could also use `SQL statement` terminology.

The [PgBouncer documentation](https://www.pgbouncer.org/usage.html#show-commands) says

```
total_query_count
:   Total number of SQL queries pooled by **pgbouncer**.
```

However, it could replace `SQL queries` with `SQL commands`. I wouldn't like to break SHOW command to fix a terminology. IMO fix the documentation is sufficient.

**Comment by NielsKSchjoedt** [comment]
@JelteF 

> 1. use the avg_xact_time instead of the avg_query_time

Thanks for the suggestion, but I guess if the SELECT query is NOT wrapped up in a transaction, then it will not be counted in the `avg_xact_time` 🙃 so I really have no way of know what are the actual execution time of queries which are not begin/commit commands.

You say:
> There's not much we can do about that at the PgBouncer side. PgBouncer doesn't look at the actual queries (by design, otherwise it would need to parse SQL which is slow).

But how can it then know what is a transactions, and what is not? Couldn't we utilise that same differentiation to filter out the `begin/commit`s?

**Comment by NielsKSchjoedt** [comment]
Alternatively, could we add a `median_query_time` and/or `95th_percentile_worst_query_time` - that would be really helpful
