### ISSUE TITLE
requires user in auth_file even if hba auth-method is trust

### ISSUE THREAD

**Issue by mbanck** [pgbouncer/pgbouncer#96]
If I set `auth_method=hba` and put a user into the corresponding file with "trust" as method, authentication fails with `ERROR:  No such user: foo`. If I add an entry `"foo" "x"` to `/etc/pgbouncer/userlist.txt`, authentication succeeds.

In general, I think if AUTH_TRUST is the case, the user need not be in `auth_file`.

NB: Just adding "foo" to `auth_file` is not enough, I need a bogus password as second field.

**Comment by mbanck** [comment]
Hrm, if I add ```"foo" "x"``` to userlist.txt, reload, then remove it, it no longer sends the error. So this seems to be a cached then.

**Comment by petere** [comment]
This appears to be behaving as intended. Just like in PostgreSQL proper, you need to create a user in addition to setting up `pg_hba.conf`. In PgBouncer, `auth_file` (or `auth_query`) "create" a user.

An alternative is to use `auth_type=any`, but that has other requirements.
