### ISSUE TITLE
Getting "server conn crashed?" after query runs for 1800s

### ISSUE THREAD

**Issue by udit47** [pgbouncer/pgbouncer#966]
I am getting "server conn crashed" exactly once the query run time hits 1800s. Query is continuously running during this time and in active state (checked from pg_stat_activity). Query is related to archival and uses dblink to execute a function in another database on the same server. So, there are two queries in pg_stat_activity one which is caller function and another is the function that is being executed in remote database. However, with when direct connection to postgresql is made, query runs successfully.

Pgbouncer config:

> listen_addr = ip
listen_port = 7432
auth_type = scram-sha-256
max_client_conn = 8000
default_pool_size = 300
ignore_startup_parameters = extra_float_digits
>

Pgbouncer Logs during this:

> 2023-10-18 21:14:49.387 IST [856] LOG C-0x564b64890540: dbname/uname@172.22.1.253:58718 closing because: server conn crashed? (age=1800s)
2023-10-18 21:14:49.387 IST [856] WARNING C-0x564b64890540: dbname/uname@172.22.1.253:58718 pooler error: server conn crashed?
> 

I have not set any timeouts explicitly at PG or PgBouncer level.
Are there any default timeouts which could cause this?

**Comment by eulerto** [comment]
No, there isn't. Check your firewall and the TCP keepalive settings.

**Comment by JelteF** [comment]
1800 is the default Keepalive Interval on Linux, so it seems like a likely culprit.

**Comment by udit47** [comment]
@eulerto , @JelteF Thanks for guidance. Will check after changing keep alive settings and update.

**Comment by eulerto** [comment]
Having not received a reply, closed.
