### ISSUE TITLE
Features page in the website still says "Protocol-level prepared plans" are not supported in transaction pooling mode

### ISSUE THREAD

**Issue by iarenaza** [pgbouncer/pgbouncer#977]
https://www.pgbouncer.org/features.html still says they are not supported. But support for them was included in 1.21.0. The features page should be updated to reflect that.

**Comment by eulerto** [comment]
It was fixed yesterday. See pgbouncer/pgbouncer.github.io@5e8aa1dfe33f2c022dcb0c55ebc7f6f44ab0e255.

**Comment by JelteF** [comment]
Ah yeah thanks for the report, I forgot to close the issue after fixing it.
