### ISSUE TITLE
Discrepancy between pg_namespace and information_schema.schemata when connected via PgBouncer

### ISSUE THREAD

**Issue by StanleyP** [pgbouncer/pgbouncer#978]
Hello,

I have been experimenting with utilization of PgBouncer 1.21 in my current project and encountered very strange behaviour regarding data in information_schema.schemata system table.

In my case queries

`SELECT nspname FROM pg_namespace`

and

`SELECT schema_name FROM information_schema.schemata`

return very different results (many schemata are missing from results of second query).

I haven't found any configuration option regarding caching of schema information in PgBouncer documentation so either this must be some kind of strange bug or really unfortunate feature.

When I connect to the target database directly I see usual expected results, so the issue is definitely in PgBouncer mediation of SQL connection.

Any hints welcome.

Kind regards,
Stanislav Pavlicek

**Comment by JelteF** [comment]
That sounds very weird. Can you share some logs? And your pgbouncer config?

**Comment by StanleyP** [comment]
Sorry for late response, here are the details.

My pgbouncer configuration template

```
[pgbouncer]
listen_addr = *
listen_port = 6432
unix_socket_dir =
pool_mode = transaction
max_client_conn = 10000
default_pool_size = 8
min_pool_size = 4
max_prepared_statements = 3000
auth_type = trust
auth_file = userlist.txt
client_tls_sslmode = disable
server_tls_sslmode = verify-full
server_tls_ca_file = /etc/ssl/certs/ca-certificates.crt
ignore_startup_parameters = options,extra_float_digits
log_stats = 0
verbose = 2
[databases]
dihflexi = host={{ .Values.variables.pgsqlf.db.hostname }} port={{ .Values.variables.pgsqlf.db.port }} dbname={{ .Values.variables.pgsqlf.db.name }} user={{ .Values.variables.migrationflexi.admin }}  password=$DB_DIH_CORE_SVC_DIH_DEPLOY_PASSWORD
```
here is output from the queries

```
dihflexi=> SELECT nspname FROM pg_namespace;
      nspname       
--------------------
 pg_toast
 pg_catalog
 information_schema
 public
 mds
 dih
 replication
 billing_calculator
 migrations
 utils
 nav4
 billing_document
 document_service
 nav16
 fds
 ods
 sap_document
 nav4~
 nav16~
(19 rows)
```
and

```
dihflexi=> SELECT schema_name FROM information_schema.schemata;
    schema_name     
--------------------
 information_schema
 pg_catalog
 utils
 replication
(4 rows)
```
logs from pgbouncer are in the attachments (verbose 2).
[pgbouncer-nsp.log](https://github.com/pgbouncer/pgbouncer/files/13247915/pgbouncer-nsp.log)
[pgbouncer-schemata.log](https://github.com/pgbouncer/pgbouncer/files/13247916/pgbouncer-schemata.log)

**Comment by StanleyP** [comment]
After restart of pgbouncer the query `SELECT schema_name FROM information_schema.schemata` returns correct results for a while, but after couple of minutes it starts to return only some schemata as you can see above.

**Comment by StanleyP** [comment]
I had big plans for pgbouncer utilization, but this weird issue is currently absolute show stopper. Any hints and suggestions will be greatly appreciated.

**Comment by JelteF** [comment]
From the postgres docs:

> The view schemata contains all schemas in the current database that the current user has access to (by way of being the owner or having some privilege).

Do you ever run `SET ROLE` or `SET SESSION AUTHORIZATION` in your application that talks to PgBouncer? Because these change the role for the length of the session, in transaction pooling these commands will "leak" to the next transaction on the same server connection. This can usually solved fairly easily by using `SET LOCAL ROLE` or `SET LOCAL SESSION AUTHORIZATION`, which only change the role until the end of the current transaction.

**Comment by StanleyP** [comment]
That could be it! Our components definitely use SET ROLE, thank you very much for the hint! I will try to modify the code to use SET LOCAL ROLE and report my findings here.

**Comment by StanleyP** [comment]
Closing the issue, the problem was in the SET ROLE statements as suggested by @JelteF
Thank you very much for prompt resolution!
