### ISSUE TITLE
Queries can hang indefinitely with default sbuf_loopcnt

### ISSUE THREAD

**Issue by tdavis** [pgbouncer/pgbouncer#98]
I found that after adding pgbouncer to my setup that certain larger insert queries were simply never completing. I checked ``pg_stat_activity`` and ``pg_lock`` and it wasn't because anything obvious was preventing them from doing so (and similar queries had worked fine pre-pgbouncer). I eventually started playing around with some of the network settings in ``pgbouncer.ini`` and discovered that changing ``sbuf_loopcnt`` to 50 fixed the issue.

My uneducated guess as to the fundamental problem is that no other connections had things to process, so skipping that one connection after 5 loops meant it effectively was stuck in limbo until another connection became active (there were other client connections, but none were actually issuing queries). Since the connection in question handles the majority of queries to that particular database, it was unlikely that it would naturally show up in the processing loop again.

Maybe I'm wrong about the cause, but in any case I'm curious what your recommendation would be. Is there a setting that provides a timeout (say a few ms) to give another connection priority before packets are processed again for the "greedy" one? Should I modify ``pkt_buf`` instead?

**Comment by markokr** [comment]
What version of pgbouncer are you using.

I spotted one version on "connection in limbo" problem and fixed it in 1.7.  Does that work for you?

**Comment by tdavis** [comment]
I am on 1.7rc1. It looks as if changes to ``pkt_buf`` and/or fixing bugs with TLS (which I am using) since that RC might resolve the issue. I'll check next time I have cause to restart pgbouncer.

**Comment by markokr** [comment]
Yeah, the change was made post-rc1 - "sbuf: improved sbuf_loopcnt logic"

**Comment by tdavis** [comment]
Can confirm this was fixed by upgrading to 1.7 and removing previous ``sbuf_loopcnt`` customization.
