### ISSUE TITLE
When connecting to a new non-existing database pgbouncer doesn't report it

### ISSUE THREAD

**Issue by khanova** [pgbouncer/pgbouncer#989]
How to reproduce:

I have the latest version of the pgbouncer repo. And I build pgbouncer from sources on Ubuntu 22.

<details>
<summary>test.ini (I just replaced `[databases]` with the autodb: `* = port=6666 host=127.0.0.1 auth_user=postgres password=password`):</summary>

```
[databases]
* = port=6666 host=127.0.0.1 auth_user=postgres password=password

[users]
maxedout = max_user_connections=3
maxedout2 = max_user_connections=2

[pgbouncer]
logfile = test.log
pidfile = test.pid

listen_addr = 127.0.0.1
listen_port = 6667
unix_socket_dir = /tmp

auth_type = trust
auth_file = userlist.txt

pool_mode = statement

server_check_delay = 10
max_client_conn = 10
default_pool_size = 5

server_lifetime = 120
server_idle_timeout = 60

tcp_defer_accept = 0
tcp_keepalive = 0

; use a small tcp_socket_buffer so that we trigger EAGAIN more often in tests.
; Otherwise bugs caused by EAGAIN are hard to debug.
tcp_socket_buffer = 4096

;track_extra_parameters is case sensitive.
;bgbouncer will only track the parameters with GUC_REPORT flag set in Postgres
track_extra_parameters = search_path, intervalstyle
ignore_startup_parameters = extra_float_digits

```
</details>

test:
```py
def test_pgbouncer_stuck(bouncer):
    bouncer.admin(f"set verbose=6")
    utils.run(["psql", f"port={bouncer.port} host={bouncer.host} dbname=fake"], shell=False, capture_output=True)
```

Expected behaviour: immediately return error to the client.

Actual behaviour: falls in the `launching new connection` loop until `query_wait_timeout`.

I suspect that the issue is with [this line ](https://github.com/pgbouncer/pgbouncer/blame/master/src/server.c#L76).

A bit of debugging showed me that the client has `wait_for_welcome` equal to false, however `wait_for_user_conn` is true.
I think that replacing it with:
```c
if (!client->wait_for_welcome && !client->wait_for_user_conn)
	continue;
```
Added suggested fix with the corresponding test in this PR: https://github.com/pgbouncer/pgbouncer/pull/985.

However I am not sure whether the described problem could be a symptom of larger bug.

**Comment by JelteF** [comment]
> However I am not sure whether the described problem could be a symptom of larger bug.

Looking into this more closely, I do think that the problem is the symptom of a larger bug. I created #998 to improve the failfast logic.
